# Install packages|

In [3]:
import torch
import numpy as np
from torch import nn
from torch import optim
import pandas as pd
import matplotlib.pyplot as plt

print(f"Torch version: {torch.__version__}")

# Tensors are just like Numpy ndarrays matrices, but with capability to run much faster on GPUs, TPUs and CPUs

Torch version: 2.5.1

In [4]:
cuda_available = torch.cuda.is_available()
print(f"Cude is available: {cuda_available}")

#If false, then PyTorch is running on the CPU. If true, then running on GPU, but we installed it without CUDA NVIDIA drivers

Cude is available: False

In [8]:
mps_available = torch.backends.mps.is_available()
mps_built = torch.backends.mps.is_built() # currently installed pytorch supports mps 
print(mps_available, mps_built)

True True

In [4]:
# Creating a simple tensor

x = torch.randn(4,7) # random but follows normal distribution
y = torch.rand(3,2) # random within 0 - 1 range continuous values
print(x, "\nTensor stored in:", x.device, "\nTensor shape:", x.shape, "\nTensor datatype:", x.dtype, type(x), "\n")

# By default the dtype is float32
type(y)
display(y)
print(f"Tensor stored in: {y.device}\nTensor shape: {y.shape}\nTensor datatype: {y.dtype} {type(y)}")

tensor([[ 0.1975,  2.3857,  2.0725,  0.2292,  1.4295,  0.2413,  1.5068],
        [ 0.8240, -0.3320,  0.6636,  1.4492,  0.9831, -0.5983, -1.3798],
        [ 2.1171, -0.6836,  0.9505,  1.0101, -0.0826,  1.4257,  0.1901],
        [-1.0944,  0.0055,  0.3359,  0.3584,  1.1735,  0.3462, -1.5338]])
Tensor stored in: cpu
Tensor shape: torch.Size([4, 7])
Tensor datatype: torch.float32 <class 'torch.Tensor'>

tensor([[0.8075, 0.5019],
        [0.4307, 0.6033],
        [0.4977, 0.8694]])

Tensor stored in: cpu
Tensor shape: torch.Size([3, 2])
Tensor datatype: torch.float32 <class 'torch.Tensor'>

In [146]:
# Creating tensors from python list

data_list = [[1,2], [3,4],[7,8]]
tensfor_from_list = torch.tensor(data_list, dtype = torch.float32)
display(tensfor_from_list)
print(f"Tensor info: {tensfor_from_list.dtype}, {tensfor_from_list.shape}, {tensfor_from_list.device}, {type(tensfor_from_list)}")

tensor([[1., 2.],
        [3., 4.],
        [7., 8.]])

Tensor info: torch.float32, torch.Size([3, 2]), cpu, <class 'torch.Tensor'>

# Working with Tensors

In [203]:
# [] - a scalar number, 0D array/tensor. rank-0
# [[]] - a vector, 1D array/tensor. rank-1
# [[],[],[]...] - a matrix, 2D array/tensor. rank-n

# [[1,2,3]] - row vector, shape(1,3), one row & three columns. rank-1
# [[1], [2], [3]] - column vector, shape three rows & one column. rank-1
# [[1,2,3], [3,4,5]] - matrix of shape(2,3), two rows and 3 columns. rank-2


data_list = [[1,2,3,4,5]] 
tensor_from_list = torch.tensor(data_list, dtype=torch.float32) # dtype explicitly can be changed
display(type(tensor_from_list))

print(tensor_from_list.T, tensor_from_list.T.shape, tensor_from_list.device, tensor_from_list.dtype, type(tensor_from_list))

torch.Tensor

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]]) torch.Size([5, 1]) cpu torch.float32 <class 'torch.Tensor'>

In [200]:
data_list = [[1,2,3], [3,4,5], [7,8,9], [11, 12, 13], [14, 15, 16]]
tensor_from_list = torch.tensor(data_list)

print(f"{tensor_from_list.T}, \n{tensor_from_list.dtype}, {tensor_from_list.device}, {tensor_from_list.T.shape}, {type(tensor_from_list)}")

tensor([[ 1,  3,  7, 11, 14],
        [ 2,  4,  8, 12, 15],
        [ 3,  5,  9, 13, 16]]),
torch.int64, cpu, torch.Size([3, 5]), <class 'torch.Tensor'>

In [215]:
# Tensors from numpy

data_numpy = np.array([1, 2, 3, 4]) # a single [] represents a scalar number
tensor_from_np = torch.from_numpy(data_numpy)

display(tensor_from_np)
print(tensor_from_np.dtype, tensor_from_np.device, tensor_from_np.shape, type(tensor_from_np))

tensor([1, 2, 3, 4])

torch.int64 cpu torch.Size([4]) <class 'torch.Tensor'>

In [261]:
data_numpy = np.array([[1, 2, 3, 4]], dtype=np.float32) # [[]] represents row vector as of now
print("Numpy dtype:", data_numpy.dtype)
tensor_from_np = torch.from_numpy(data_numpy)

display(tensor_from_np.T) # after transposing, now it is column vector
print(f"Tensor shape: {tensor_from_np.T.shape}\nTensor datatype: {tensor_from_np.dtype, type(tensor_from_np)}\n \
Tensor stored in: {tensor_from_np.device}\n")

Numpy dtype: float32

tensor([[1.],
        [2.],
        [3.],
        [4.]])

Tensor shape: torch.Size([4, 1])
Tensor datatype: (torch.float32, <class 'torch.Tensor'>)
 Tensor stored in: cpu

In [293]:
data_numpy = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13],[15,16,17]])
tensor_from_np = torch.from_numpy(data_numpy)

display(tensor_from_np)
print(f"Tensor shape: {tensor_from_np.shape}\nTensor datatype: {tensor_from_np.dtype, type(tensor_from_np)}\n \
Tensor stored in: {tensor_from_np.device}")

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13],
        [15, 16, 17]])

Tensor shape: torch.Size([5, 3])
Tensor datatype: (torch.int64, <class 'torch.Tensor'>)
 Tensor stored in: cpu

In [290]:
data_numpy = np.array([[[1,2,3], [3,4,5], [6,7,8]],
                      [[11,12,13], [14,15,16], [17,18,19]],
                      [[21,22,23], [23,24,25], [26,27,28]]])
tensor_from_np = torch.from_numpy(data_numpy)

display(tensor_from_np)

print(tensor_from_np.shape, tensor_from_np.dtype, tensor_from_np.device, type(tensor_from_np))

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [23, 24, 25],
         [26, 27, 28]]])

torch.Size([3, 3, 3]) torch.int64 cpu <class 'torch.Tensor'>

In [13]:
# the range is between 0 and 1, continuous values
data_rand = torch.rand(3,6,5,5,6)
display(data_rand)

print(type(data_rand), data_rand.device, data_rand.shape, data_rand.dtype)

tensor([[[[[0.5690, 0.0818, 0.7334, 0.7479, 0.7470, 0.7807],
           [0.3080, 0.5642, 0.0268, 0.6542, 0.9962, 0.1948],
           [0.8360, 0.5335, 0.7966, 0.2066, 0.3203, 0.6581],
           [0.0686, 0.6480, 0.4794, 0.2984, 0.3671, 0.0635],
           [0.5211, 0.2838, 0.5029, 0.7513, 0.0535, 0.7766]],

          [[0.1584, 0.7182, 0.8947, 0.7645, 0.1467, 0.5904],
           [0.3381, 0.3275, 0.8389, 0.6606, 0.8481, 0.7248],
           [0.1729, 0.2273, 0.8817, 0.0909, 0.9683, 0.8622],
           [0.2807, 0.7360, 0.4525, 0.0498, 0.7388, 0.5148],
           [0.7674, 0.5755, 0.8463, 0.8062, 0.0062, 0.4510]],

          [[0.8714, 0.3873, 0.7940, 0.5704, 0.6458, 0.0063],
           [0.2315, 0.4958, 0.8788, 0.1932, 0.2610, 0.6501],
           [0.2683, 0.1105, 0.7179, 0.8703, 0.5799, 0.4031],
           [0.3507, 0.7391, 0.1129, 0.3320, 0.5486, 0.8110],
           [0.1462, 0.1957, 0.6390, 0.2085, 0.7570, 0.1197]],

          [[0.5360, 0.2915, 0.2596, 0.4052, 0.4653, 0.5107],
           [0.4753, 0.2606, 0.0169, 0.3406, 0.9332, 0.3487],
           [0.3182, 0.4114, 0.9092, 0.5990, 0.7239, 0.1777],
           [0.2233, 0.8022, 0.6494, 0.7127, 0.5085, 0.5390],
           [0.0321, 0.5123, 0.6207, 0.7074, 0.9923, 0.5711]],

          [[0.1151, 0.1589, 0.6328, 0.2897, 0.3956, 0.6714],
           [0.5631, 0.7193, 0.1173, 0.8521, 0.6831, 0.0255],
           [0.2249, 0.7645, 0.5405, 0.4956, 0.8240, 0.9725],
           [0.4877, 0.3196, 0.7030, 0.5901, 0.2159, 0.9467],
           [0.1094, 0.8947, 0.3039, 0.7418, 0.6376, 0.4769]]],


         [[[0.7620, 0.5780, 0.5923, 0.2693, 0.4445, 0.1172],
           [0.0072, 0.2625, 0.6865, 0.3940, 0.5773, 0.9040],
           [0.2159, 0.4749, 0.3459, 0.5870, 0.9145, 0.9537],
           [0.0074, 0.9831, 0.1544, 0.4351, 0.8100, 0.4146],
           [0.8459, 0.0296, 0.9911, 0.7101, 0.9478, 0.1313]],

          [[0.4194, 0.6168, 0.4422, 0.0818, 0.6151, 0.2729],
           [0.1708, 0.8131, 0.5210, 0.9367, 0.6314, 0.8646],
           [0.0769, 0.9932, 0.9064, 0.2458, 0.2795, 0.7844],
           [0.2738, 0.9029, 0.6704, 0.5688, 0.4230, 0.0974],
           [0.8497, 0.4932, 0.0820, 0.7535, 0.5640, 0.3216]],

          [[0.1595, 0.2929, 0.1355, 0.6633, 0.8658, 0.3298],
           [0.7610, 0.9301, 0.3377, 0.6525, 0.2693, 0.4205],
           [0.2017, 0.1527, 0.7875, 0.1935, 0.0603, 0.2100],
           [0.9525, 0.7197, 0.0064, 0.6737, 0.0190, 0.2430],
           [0.3812, 0.7376, 0.6708, 0.5810, 0.9251, 0.6159]],

          [[0.6209, 0.7409, 0.3853, 0.2817, 0.4338, 0.3074],
           [0.9430, 0.4277, 0.8283, 0.5079, 0.9923, 0.6240],
           [0.4728, 0.7408, 0.6756, 0.1341, 0.2738, 0.5398],
           [0.0733, 0.7631, 0.2829, 0.1392, 0.9762, 0.5258],
           [0.0463, 0.8203, 0.1467, 0.5401, 0.1906, 0.6720]],

          [[0.3144, 0.6038, 0.0913, 0.7897, 0.7737, 0.1120],
           [0.2468, 0.1786, 0.3816, 0.9656, 0.0394, 0.6034],
           [0.7585, 0.1583, 0.6215, 0.8246, 0.8537, 0.5356],
           [0.5297, 0.4934, 0.1610, 0.0481, 0.1927, 0.4575],
           [0.9943, 0.2196, 0.0778, 0.0457, 0.8030, 0.5395]]],


         [[[0.2351, 0.3475, 0.1979, 0.4863, 0.8171, 0.9457],
           [0.2328, 0.1149, 0.9319, 0.1839, 0.6950, 0.5457],
           [0.6863, 0.8637, 0.6924, 0.5335, 0.5910, 0.0442],
           [0.8044, 0.7754, 0.7807, 0.2773, 0.1944, 0.1107],
           [0.1255, 0.2262, 0.8963, 0.9104, 0.0758, 0.6419]],

          [[0.2862, 0.8198, 0.9081, 0.7025, 0.3676, 0.0933],
           [0.1452, 0.4689, 0.5730, 0.1897, 0.3914, 0.2227],
           [0.7436, 0.1827, 0.7952, 0.8107, 0.4611, 0.0667],
           [0.3031, 0.0379, 0.8846, 0.7999, 0.9021, 0.1224],
           [0.9061, 0.5505, 0.4430, 0.3552, 0.8414, 0.2101]],

          [[0.7902, 0.4496, 0.2165, 0.5224, 0.0750, 0.4903],
           [0.4701, 0.0314, 0.0216, 0.2941, 0.3868, 0.8590],
           [0.4929, 0.2024, 0.3167, 0.6420, 0.5110, 0.6051],
           [0.5365, 0.9722, 0.2717, 0.0691, 0.6148, 0.7131],
           [0.0496, 0.9551, 0.3977, 0.8924, 0.1283, 0.2129]],

          [[0.3257, 0.5385, 0.0185, 0.1130, 0.4171, 0.7757],
           [0.3855, 0.3367, 0.4247, 0.9121, 0.6132, 0.7952],
           [0.5345, 0.2594, 0.0156, 0.3323, 0.6320, 0.9120],
           [0.2865, 0.2976, 0.6089, 0.5211, 0.0354, 0.0054],
           [0.0834, 0.3771, 0.4513, 0.9599, 0.8100, 0.6825]],

          [[0.4355, 0.7452, 0.5151, 0.9068, 0.1685, 0.2876],
           [0.4072, 0.1000, 0.6223, 0.1481, 0.5194, 0.7450],
           [0.3203, 0.3383, 0.6303, 0.3334, 0.3579, 0.5783],
           [0.3078, 0.5749, 0.3272, 0.4734, 0.6428, 0.5639],
           [0.3809, 0.5775, 0.4267, 0.3730, 0.2306, 0.6900]]],


         [[[0.4435, 0.7273, 0.9978, 0.5624, 0.6455, 0.7977],
           [0.2039, 0.2662, 0.3527, 0.3332, 0.4281, 0.6700],
           [0.2563, 0.1378, 0.3496, 0.0021, 0.9357, 0.0085],
           [0.2698, 0.8956, 0.8696, 0.3177, 0.9271, 0.5878],
           [0.1093, 0.9963, 0.4021, 0.2079, 0.8145, 0.4354]],

          [[0.5467, 0.3264, 0.4389, 0.8007, 0.7872, 0.7538],
           [0.4466, 0.3183, 0.3809, 0.7538, 0.0511, 0.8141],
           [0.9675, 0.2374, 0.6108, 0.6346, 0.2733, 0.9002],
           [0.5782, 0.7213, 0.5490, 0.2686, 0.8594, 0.8176],
           [0.6667, 0.8956, 0.7661, 0.7222, 0.5599, 0.3288]],

          [[0.1727, 0.1175, 0.2740, 0.5631, 0.5024, 0.0152],
           [0.5858, 0.1613, 0.1141, 0.8733, 0.3127, 0.8979],
           [0.3356, 0.8419, 0.9340, 0.7165, 0.3161, 0.8258],
           [0.7683, 0.1880, 0.5016, 0.8495, 0.0347, 0.5900],
           [0.5613, 0.8060, 0.0090, 0.3577, 0.3578, 0.8233]],

          [[0.1721, 0.6099, 0.6340, 0.8570, 0.5290, 0.7142],
           [0.8101, 0.5060, 0.6111, 0.6143, 0.7970, 0.6504],
           [0.8791, 0.3703, 0.0147, 0.0463, 0.4912, 0.7744],
           [0.5908, 0.1187, 0.6703, 0.9682, 0.0733, 0.9634],
           [0.1844, 0.7810, 0.3504, 0.8297, 0.3767, 0.0577]],

          [[0.4871, 0.8573, 0.4967, 0.5330, 0.4015, 0.4307],
           [0.8497, 0.0849, 0.0490, 0.7890, 0.9273, 0.5077],
           [0.9272, 0.8657, 0.5616, 0.1833, 0.1335, 0.6807],
           [0.3011, 0.3671, 0.3116, 0.2501, 0.6404, 0.9899],
           [0.1718, 0.9104, 0.1689, 0.0568, 0.3139, 0.7755]]],


         [[[0.4388, 0.8003, 0.2868, 0.6856, 0.0066, 0.9214],
           [0.0271, 0.5904, 0.9005, 0.7069, 0.5843, 0.8414],
           [0.9279, 0.8728, 0.7647, 0.1624, 0.7691, 0.2994],
           [0.9560, 0.6508, 0.4822, 0.8511, 0.8914, 0.9182],
           [0.7272, 0.4529, 0.4574, 0.0938, 0.2953, 0.2638]],

          [[0.8194, 0.0612, 0.7294, 0.7751, 0.7340, 0.9783],
           [0.6819, 0.7310, 0.2631, 0.8986, 0.9552, 0.0520],
           [0.1591, 0.1627, 0.8979, 0.5033, 0.6288, 0.6003],
           [0.0517, 0.8572, 0.3523, 0.8932, 0.6971, 0.0093],
           [0.0913, 0.7515, 0.5635, 0.0215, 0.2292, 0.4333]],

          [[0.4650, 0.5643, 0.7392, 0.5785, 0.9746, 0.0134],
           [0.9034, 0.1352, 0.0516, 0.9440, 0.1498, 0.8642],
           [0.7673, 0.4653, 0.6351, 0.5943, 0.7106, 0.4584],
           [0.6181, 0.5252, 0.1373, 0.5253, 0.9965, 0.7211],
           [0.5094, 0.4422, 0.3236, 0.5825, 0.9391, 0.9403]],

          [[0.2891, 0.1037, 0.8763, 0.3902, 0.0420, 0.7157],
           [0.0756, 0.0795, 0.1350, 0.3163, 0.2712, 0.2429],
           [0.6149, 0.0011, 0.4567, 0.1563, 0.5973, 0.2504],
           [0.9211, 0.6140, 0.4578, 0.5899, 0.7853, 0.2340],
           [0.2220, 0.5499, 0.1630, 0.8209, 0.5037, 0.7810]],

          [[0.2485, 0.4541, 0.1068, 0.9340, 0.0363, 0.9055],
           [0.3677, 0.0860, 0.1095, 0.2002, 0.3394, 0.8312],
           [0.1912, 0.4807, 0.0074, 0.4196, 0.7399, 0.1777],
           [0.4682, 0.3092, 0.0466, 0.2372, 0.5867, 0.3027],
           [0.5398, 0.6570, 0.8806, 0.7410, 0.3248, 0.5158]]],


         [[[0.8892, 0.6570, 0.7784, 0.2498, 0.5738, 0.4847],
           [0.9246, 0.0238, 0.8940, 0.4734, 0.1791, 0.7805],
           [0.8795, 0.0751, 0.4291, 0.4245, 0.2953, 0.1560],
           [0.1372, 0.6877, 0.8125, 0.1494, 0.7496, 0.1635],
           [0.2722, 0.6535, 0.4612, 0.8715, 0.2118, 0.0843]],

          [[0.5409, 0.7315, 0.1831, 0.8215, 0.6669, 0.0298],
           [0.2945, 0.7691, 0.7909, 0.9539, 0.6454, 0.2186],
           [0.5495, 0.7090, 0.8663, 0.4206, 0.6943, 0.8035],
           [0.4815, 0.4111, 0.2921, 0.6388, 0.4745, 0.3522],
           [0.4860, 0.7162, 0.5604, 0.0922, 0.3388, 0.2248]],

          [[0.4350, 0.5993, 0.1916, 0.3494, 0.7080, 0.1207],
           [0.6576, 0.7364, 0.1046, 0.9635, 0.1209, 0.1550],
           [0.0623, 0.8418, 0.0987, 0.9185, 0.8811, 0.5407],
           [0.4427, 0.1961, 0.5750, 0.6605, 0.4655, 0.2166],
           [0.2252, 0.7944, 0.5558, 0.1338, 0.3838, 0.2398]],

          [[0.5128, 0.7718, 0.5745, 0.5513, 0.0112, 0.5457],
           [0.5728, 0.2919, 0.7052, 0.0075, 0.7326, 0.0256],
           [0.3543, 0.2801, 0.2761, 0.8756, 0.7311, 0.1438],
           [0.9795, 0.1842, 0.2610, 0.5882, 0.1565, 0.4504],
           [0.6312, 0.4300, 0.6291, 0.8355, 0.3627, 0.1587]],

          [[0.5446, 0.9638, 0.3879, 0.7772, 0.4551, 0.5091],
           [0.0090, 0.6431, 0.5022, 0.3375, 0.6231, 0.3708],
           [0.4474, 0.6371, 0.0903, 0.1247, 0.4951, 0.0972],
           [0.1358, 0.3352, 0.8956, 0.3635, 0.3982, 0.1838],
           [0.9931, 0.2352, 0.8180, 0.6780, 0.5362, 0.9422]]]],



        [[[[0.7191, 0.4796, 0.2721, 0.8848, 0.9559, 0.7572],
           [0.6507, 0.7630, 0.1108, 0.5739, 0.4951, 0.8781],
           [0.8331, 0.1473, 0.3743, 0.1834, 0.6351, 0.1359],
           [0.4169, 0.0750, 0.9886, 0.6532, 0.7808, 0.1827],
           [0.6596, 0.2739, 0.4048, 0.7928, 0.2556, 0.2076]],

          [[0.8381, 0.1755, 0.9127, 0.9183, 0.4800, 0.0595],
           [0.7642, 0.6440, 0.9117, 0.6893, 0.5089, 0.6010],
           [0.7945, 0.6757, 0.7348, 0.2613, 0.2642, 0.9259],
           [0.2651, 0.5088, 0.0014, 0.5330, 0.4084, 0.1380],
           [0.0993, 0.4438, 0.6250, 0.1335, 0.8941, 0.0228]],

          [[0.8311, 0.8096, 0.3021, 0.5007, 0.6415, 0.5259],
           [0.1715, 0.1897, 0.2038, 0.9889, 0.0468, 0.1517],
           [0.1480, 0.2778, 0.5598, 0.6118, 0.7231, 0.8837],
           [0.3888, 0.5782, 0.2019, 0.2887, 0.1755, 0.0070],
           [0.7272, 0.2393, 0.0231, 0.5511, 0.7107, 0.4345]],

          [[0.3919, 0.1330, 0.5156, 0.8392, 0.5069, 0.3196],
           [0.5687, 0.3187, 0.9620, 0.2222, 0.0660, 0.3098],
           [0.5364, 0.6889, 0.5598, 0.0724, 0.7468, 0.2262],
           [0.4487, 0.7683, 0.2000, 0.2318, 0.1539, 0.6769],
           [0.0629, 0.8724, 0.9041, 0.9902, 0.0498, 0.5952]],

          [[0.0953, 0.4835, 0.3938, 0.3206, 0.6918, 0.7241],
           [0.4560, 0.2686, 0.4636, 0.3254, 0.8750, 0.6581],
           [0.8122, 0.5222, 0.4628, 0.6769, 0.5197, 0.3185],
           [0.8099, 0.9918, 0.6491, 0.9308, 0.5180, 0.5539],
           [0.6894, 0.0096, 0.4531, 0.1921, 0.6162, 0.1408]]],


         [[[0.0487, 0.6399, 0.0726, 0.4303, 0.2076, 0.3343],
           [0.9816, 0.9838, 0.9238, 0.0467, 0.2690, 0.2445],
           [0.3769, 0.4270, 0.0694, 0.9295, 0.7054, 0.5159],
           [0.9586, 0.6390, 0.2637, 0.0452, 0.6476, 0.8761],
           [0.6534, 0.0560, 0.4968, 0.6236, 0.6253, 0.9542]],

          [[0.1858, 0.0520, 0.0258, 0.5622, 0.2846, 0.5988],
           [0.3671, 0.6700, 0.1235, 0.4111, 0.8027, 0.6621],
           [0.3116, 0.1867, 0.7738, 0.8981, 0.8592, 0.1808],
           [0.2494, 0.9347, 0.3423, 0.8975, 0.6619, 0.9350],
           [0.6855, 0.9569, 0.6345, 0.1787, 0.9522, 0.1907]],

          [[0.2657, 0.7446, 0.9376, 0.8880, 0.2660, 0.7121],
           [0.1744, 0.9407, 0.9152, 0.2636, 0.1923, 0.9024],
           [0.0917, 0.4234, 0.1603, 0.8480, 0.5009, 0.6294],
           [0.9656, 0.1488, 0.3762, 0.6982, 0.8334, 0.1162],
           [0.7757, 0.2444, 0.3134, 0.4668, 0.6196, 0.7281]],

          [[0.1965, 0.2901, 0.4418, 0.5949, 0.6800, 0.4373],
           [0.5558, 0.1339, 0.5834, 0.9565, 0.3273, 0.9487],
           [0.4907, 0.1639, 0.2448, 0.0739, 0.5725, 0.4727],
           [0.5041, 0.5873, 0.0633, 0.2172, 0.2536, 0.9607],
           [0.8920, 0.8349, 0.4904, 0.6354, 0.1816, 0.8063]],

          [[0.0757, 0.8989, 0.5919, 0.7825, 0.4028, 0.1486],
           [0.4176, 0.6727, 0.7437, 0.8399, 0.6671, 0.6090],
           [0.8801, 0.8825, 0.4865, 0.3121, 0.8531, 0.1632],
           [0.5835, 0.1178, 0.1104, 0.4385, 0.6574, 0.1880],
           [0.1438, 0.6922, 0.6661, 0.7819, 0.1565, 0.6885]]],


         [[[0.3698, 0.0418, 0.5793, 0.3761, 0.9860, 0.4248],
           [0.8212, 0.9171, 0.0107, 0.1548, 0.2871, 0.7246],
           [0.5501, 0.0589, 0.4700, 0.3034, 0.1832, 0.7628],
           [0.9715, 0.2277, 0.7161, 0.8554, 0.5019, 0.6778],
           [0.9899, 0.3006, 0.3817, 0.3437, 0.2047, 0.5865]],

          [[0.9256, 0.7709, 0.7508, 0.6066, 0.5522, 0.5632],
           [0.4126, 0.4703, 0.2411, 0.2650, 0.2913, 0.4868],
           [0.7210, 0.4097, 0.4272, 0.7616, 0.1554, 0.2600],
           [0.0274, 0.4704, 0.5325, 0.1805, 0.6926, 0.0957],
           [0.6441, 0.4501, 0.3781, 0.8265, 0.0390, 0.2149]],

          [[0.8397, 0.4089, 0.0779, 0.4032, 0.2089, 0.4866],
           [0.7553, 0.9937, 0.4457, 0.1644, 0.3082, 0.9743],
           [0.3404, 0.0421, 0.0523, 0.0698, 0.5983, 0.1142],
           [0.0206, 0.0720, 0.9325, 0.3626, 0.3660, 0.1463],
           [0.5198, 0.5071, 0.4142, 0.7328, 0.1593, 0.1599]],

          [[0.5641, 0.6066, 0.0197, 0.4579, 0.5120, 0.4904],
           [0.5196, 0.2682, 0.8214, 0.8334, 0.3704, 0.8150],
           [0.4859, 0.7511, 0.2075, 0.4611, 0.8313, 0.5542],
           [0.2227, 0.5620, 0.9763, 0.2762, 0.7741, 0.7352],
           [0.1188, 0.8072, 0.2322, 0.4902, 0.3439, 0.2282]],

          [[0.6875, 0.6995, 0.7014, 0.5448, 0.9393, 0.1062],
           [0.6009, 0.3031, 0.3568, 0.4246, 0.5616, 0.0392],
           [0.6126, 0.2724, 0.2235, 0.5432, 0.1789, 0.3260],
           [0.4889, 0.1309, 0.3529, 0.0037, 0.2794, 0.8627],
           [0.5228, 0.4130, 0.0782, 0.2624, 0.7110, 0.8151]]],


         [[[0.3057, 0.5820, 0.8377, 0.2943, 0.4636, 0.4022],
           [0.6821, 0.6178, 0.2572, 0.0924, 0.3016, 0.3835],
           [0.5585, 0.7386, 0.7527, 0.3801, 0.8046, 0.6253],
           [0.6900, 0.5548, 0.5266, 0.2348, 0.1854, 0.2068],
           [0.4713, 0.7723, 0.8469, 0.2965, 0.4810, 0.3773]],

          [[0.4004, 0.1525, 0.6871, 0.0184, 0.7726, 0.5593],
           [0.6594, 0.8212, 0.1167, 0.8635, 0.4463, 0.4325],
           [0.0678, 0.0804, 0.1730, 0.5385, 0.3678, 0.3733],
           [0.8228, 0.3626, 0.7993, 0.2592, 0.5625, 0.6535],
           [0.2452, 0.4540, 0.1007, 0.7887, 0.1322, 0.4160]],

          [[0.2654, 0.3153, 0.7183, 0.1535, 0.4898, 0.5818],
           [0.4718, 0.2203, 0.5107, 0.9962, 0.1766, 0.4040],
           [0.3868, 0.5481, 0.9058, 0.7464, 0.8202, 0.0023],
           [0.0843, 0.4769, 0.7556, 0.5884, 0.8421, 0.0766],
           [0.7262, 0.7653, 0.6531, 0.7481, 0.0186, 0.0185]],

          [[0.0669, 0.5907, 0.8628, 0.6957, 0.6120, 0.0950],
           [0.6626, 0.0163, 0.1672, 0.1473, 0.6300, 0.7587],
           [0.2254, 0.4221, 0.7200, 0.6335, 0.1835, 0.2833],
           [0.3641, 0.2067, 0.0394, 0.1846, 0.5030, 0.1928],
           [0.3209, 0.6986, 0.7065, 0.1143, 0.7749, 0.9711]],

          [[0.1870, 0.7661, 0.7769, 0.5197, 0.6287, 0.7092],
           [0.9509, 0.7474, 0.8059, 0.4306, 0.1559, 0.8281],
           [0.5555, 0.7581, 0.0273, 0.2461, 0.9020, 0.7146],
           [0.9104, 0.9101, 0.8699, 0.1581, 0.5436, 0.5511],
           [0.8827, 0.7985, 0.9601, 0.7451, 0.8751, 0.8869]]],


         [[[0.4551, 0.9605, 0.6101, 0.2072, 0.9408, 0.0479],
           [0.4609, 0.3407, 0.6339, 0.6223, 0.8063, 0.0998],
           [0.5884, 0.1068, 0.1222, 0.7639, 0.1121, 0.1822],
           [0.9879, 0.8887, 0.2282, 0.0538, 0.1739, 0.4391],
           [0.8962, 0.3749, 0.0927, 0.4628, 0.4862, 0.8100]],

          [[0.0253, 0.2627, 0.8038, 0.8570, 0.8255, 0.2050],
           [0.0535, 0.1967, 0.6747, 0.4623, 0.4984, 0.1611],
           [0.6592, 0.8254, 0.2960, 0.6754, 0.2876, 0.0271],
           [0.3807, 0.0824, 0.3452, 0.6297, 0.3267, 0.2058],
           [0.1056, 0.1242, 0.4625, 0.1698, 0.1332, 0.3924]],

          [[0.5466, 0.0490, 0.5249, 0.7984, 0.6552, 0.4552],
           [0.9323, 0.0960, 0.8491, 0.3713, 0.2011, 0.0705],
           [0.1507, 0.6460, 0.1171, 0.3891, 0.5665, 0.8844],
           [0.0313, 0.4702, 0.6359, 0.6645, 0.8284, 0.2634],
           [0.5944, 0.5080, 0.6621, 0.2602, 0.5909, 0.2140]],

          [[0.1008, 0.5950, 0.5198, 0.4129, 0.3041, 0.4267],
           [0.4748, 0.9851, 0.2367, 0.0795, 0.2211, 0.4041],
           [0.5647, 0.7317, 0.7528, 0.3141, 0.1693, 0.2746],
           [0.7844, 0.5123, 0.5795, 0.1473, 0.7790, 0.9386],
           [0.9425, 0.6945, 0.7552, 0.0961, 0.8143, 0.8213]],

          [[0.4883, 0.4059, 0.9199, 0.2873, 0.2051, 0.4942],
           [0.2119, 0.6400, 0.9887, 0.9119, 0.5058, 0.4107],
           [0.5374, 0.8364, 0.4496, 0.7353, 0.1149, 0.1758],
           [0.6121, 0.1178, 0.0686, 0.5512, 0.5433, 0.7681],
           [0.4543, 0.4162, 0.4382, 0.8564, 0.9396, 0.7544]]],


         [[[0.6283, 0.7395, 0.3545, 0.6903, 0.3989, 0.2715],
           [0.2824, 0.0015, 0.9286, 0.6046, 0.7750, 0.7707],
           [0.6848, 0.4199, 0.1440, 0.1011, 0.6997, 0.1313],
           [0.0086, 0.7698, 0.6560, 0.3358, 0.3740, 0.5036],
           [0.1488, 0.8261, 0.3145, 0.8701, 0.3519, 0.5573]],

          [[0.2969, 0.2725, 0.7884, 0.6310, 0.3132, 0.3192],
           [0.3598, 0.8454, 0.7506, 0.8739, 0.8568, 0.6310],
           [0.5028, 0.8892, 0.0698, 0.3698, 0.0081, 0.9625],
           [0.8118, 0.0260, 0.4225, 0.4220, 0.2149, 0.8875],
           [0.4098, 0.2811, 0.5574, 0.6960, 0.2931, 0.1837]],

          [[0.0083, 0.4756, 0.3788, 0.2216, 0.2519, 0.5149],
           [0.4544, 0.7194, 0.4885, 0.1907, 0.8136, 0.3734],
           [0.8397, 0.3967, 0.2560, 0.5219, 0.4719, 0.2161],
           [0.1507, 0.2580, 0.5492, 0.5813, 0.4263, 0.8889],
           [0.9262, 0.1740, 0.3901, 0.9525, 0.2037, 0.3048]],

          [[0.3481, 0.9352, 0.7245, 0.8260, 0.3949, 0.9520],
           [0.0786, 0.3191, 0.5372, 0.9029, 0.0119, 0.4068],
           [0.9542, 0.9445, 0.3225, 0.0406, 0.4883, 0.6319],
           [0.1210, 0.9777, 0.1768, 0.6584, 0.0919, 0.3745],
           [0.5422, 0.8360, 0.1467, 0.4189, 0.7362, 0.7729]],

          [[0.1124, 0.2892, 0.1527, 0.9768, 0.6344, 0.7471],
           [0.2405, 0.6639, 0.8646, 0.2531, 0.4883, 0.8449],
           [0.6439, 0.9561, 0.9018, 0.8868, 0.7388, 0.1969],
           [0.6730, 0.3934, 0.3750, 0.3097, 0.6989, 0.0998],
           [0.9292, 0.4519, 0.0522, 0.4267, 0.9323, 0.5989]]]],



        [[[[0.9218, 0.7899, 0.7021, 0.9580, 0.2737, 0.4610],
           [0.8974, 0.7396, 0.0020, 0.4295, 0.0455, 0.5852],
           [0.4772, 0.8580, 0.1985, 0.8946, 0.6173, 0.5783],
           [0.4042, 0.3604, 0.3730, 0.0207, 0.5469, 0.8501],
           [0.3175, 0.1947, 0.2755, 0.9370, 0.4767, 0.1810]],

          [[0.2588, 0.3479, 0.2714, 0.8123, 0.9081, 0.7231],
           [0.7933, 0.1994, 0.6066, 0.9767, 0.6946, 0.0626],
           [0.9453, 0.7418, 0.6572, 0.4926, 0.0781, 0.6531],
           [0.2692, 0.8362, 0.7528, 0.7426, 0.7981, 0.1160],
           [0.5018, 0.7963, 0.3711, 0.1748, 0.3760, 0.4654]],

          [[0.8396, 0.4184, 0.4496, 0.1545, 0.5633, 0.1890],
           [0.2717, 0.0186, 0.7323, 0.8098, 0.8797, 0.8478],
           [0.7200, 0.6189, 0.2406, 0.9733, 0.9840, 0.7869],
           [0.7113, 0.2772, 0.3893, 0.2393, 0.8880, 0.5407],
           [0.1009, 0.4246, 0.5284, 0.5026, 0.4571, 0.7767]],

          [[0.4254, 0.7717, 0.0983, 0.9092, 0.2342, 0.4910],
           [0.8423, 0.0497, 0.0204, 0.3566, 0.9187, 0.1859],
           [0.4579, 0.2851, 0.4370, 0.6482, 0.2663, 0.1360],
           [0.9888, 0.6975, 0.8637, 0.8177, 0.1020, 0.3684],
           [0.9355, 0.3961, 0.0432, 0.7443, 0.7879, 0.3175]],

          [[0.1574, 0.8020, 0.3839, 0.0256, 0.4886, 0.7285],
           [0.8678, 0.9690, 0.9536, 0.9629, 0.9920, 0.3868],
           [0.5118, 0.7462, 0.6360, 0.2448, 0.1688, 0.8648],
           [0.6457, 0.5816, 0.7877, 0.0587, 0.3201, 0.2203],
           [0.4380, 0.7237, 0.7372, 0.5160, 0.2512, 0.0939]]],



<class 'torch.Tensor'> cpu torch.Size([3, 6, 5, 5, 6]) torch.float32

In [139]:
# values follow a normal distribution
data_randn = torch.randn(2,3,2,2)
print("g:", data_randn)

g: tensor([[[[-1.1143, -0.2329],
          [-0.6670,  0.7410]],

         [[ 0.7010,  0.1869],
          [ 0.2297, -0.0074]],

         [[-0.3161,  0.0057],
          [ 1.3207, -0.9103]]],


        [[[ 0.0486, -0.4034],
          [ 0.3652,  0.5020]],

         [[ 0.9283,  1.0278],
          [ 0.7446, -0.0997]],

         [[ 0.7095,  1.4607],
          [-0.2492,  0.2420]]]])

In [142]:
data_random_zero_to_one = torch.rand(3,5)
data_random_normal = torch.randn(4,7)

display(data_random_zero_to_one, data_random_normal)
display(data_random_zero_to_one.T, data_random_normal.T)

tensor([[0.4904, 0.1041, 0.7446, 0.8541, 0.0787],
        [0.1401, 0.7797, 0.1442, 0.9158, 0.2678],
        [0.9923, 0.2882, 0.3806, 0.5698, 0.6849]])

tensor([[-0.6434,  1.4317, -0.4912,  1.7764,  1.0498, -0.3891, -0.6872],
        [ 0.4841,  2.1635,  0.7083, -0.2999, -0.1306,  1.3264,  0.1005],
        [ 0.4051,  0.8345,  0.2810, -0.6223,  0.8083,  0.0234, -0.2112],
        [ 0.1314, -0.8676, -0.5983, -1.3256,  0.4899, -0.1967, -1.0668]])

tensor([[0.4904, 0.1401, 0.9923],
        [0.1041, 0.7797, 0.2882],
        [0.7446, 0.1442, 0.3806],
        [0.8541, 0.9158, 0.5698],
        [0.0787, 0.2678, 0.6849]])

tensor([[-0.6434,  0.4841,  0.4051,  0.1314],
        [ 1.4317,  2.1635,  0.8345, -0.8676],
        [-0.4912,  0.7083,  0.2810, -0.5983],
        [ 1.7764, -0.2999, -0.6223, -1.3256],
        [ 1.0498, -0.1306,  0.8083,  0.4899],
        [-0.3891,  1.3264,  0.0234, -0.1967],
        [-0.6872,  0.1005, -0.2112, -1.0668]])

In [172]:
# shape(2,3) - 2 rows and 3 columns: or shortly called a matrix of 2 by 3
# shape(1,2,3) - a single matrix of 2 by 3 
# shape(2,2,3) - two matrixes of shape 2 by 3
# shape(3,2,3) - three matrixes of shape 2 by 3
# shape(5,2,4) - five matrixes of shape 2 by 4
# shape(1,5,2,4) - a single matrix that contains 5 sub-matrices with shape of 2 by 4
# shape(2,5,2,4) - two matrixes, each containing 5 sub-matrices of shape 2 by 4
# shape(4,3,4,4) - four matrices, each containing 3 sub-matrices of square shape 4 by 4
""" 
shape(n_1,n_2,n_3,...,n_k,row,column) - in high dimensional ndarrays/tensors the last two numbers represent the actual 
#s of rows and columns, while the numbers before/preceding them represent how many sub-matrices each matrix has but at its core
the last two numbers representing the actual shape of the base matrix, for which, its shape is being used multiple times

"""
# shape(1,1,1,1,3,4) - at its core it is 3 by 4 matrix, the output will just display many []s around [3,4], like [[[[[[3,4]]]]]]


data_zero = torch.zeros(2,3,4)
display(data_zero)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [175]:
data_ones = torch.ones(2,3,3)
display(data_ones)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [227]:
data_zeros = torch.zeros(4,9)
data_ones = torch.ones(3,11)

display(data_zeros, data_ones)
print(f"data_zeros info: {data_zeros.shape}, {data_zeros.dtype}, {data_zeros.device}, {type(data_zeros)}\
\ndata_ones info: {data_ones.shape}, {data_ones.dtype}, {data_ones.device}, {type(data_ones)}\n\nTransposed:")

display(data_zeros.T, data_ones.T)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

data_zeros info: torch.Size([4, 9]), torch.float32, cpu, <class 'torch.Tensor'>
data_ones info: torch.Size([3, 11]), torch.float32, cpu, <class 'torch.Tensor'>

Transposed:

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [226]:
# to run cli scripts prefix it with "!", exclamation mark so that jupyter knows the specfied code is sli and not a python code
!jupyter kernelspec list --help-all

List installed kernel specifications.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--json
    output spec name and location as machine-readable json.
    Equivalent to: [--ListKernelSpecs.json_output=True]
--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]

Class options
=============
The command-line option below sets the respective configurable class-parameter:
    --Class.parameter=value
This line is evaluated in Python, so simple expressions are allowed.
For instance, to set `C.a=[0,1,2]`, you may type this:
    --C.a='range(3)'

Application(SingletonConfigurable) options
------------------------------------------
--Application.log_datefmt=<Unicode>
    The date format used by logging formatters for %(asctime)s
    Default: '%Y-%m-%d %H:%M:%S'
--Application.log_format=<Unicode>
    The Logging format template
    Default: '[%(name)s]%(highlevel)s %(message)s'
--Application.log_level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
--Application.logging_config=<key-1>=<value-1>...
    Configure additional log handlers.
    The default stderr logs handler is configured by the log_level, log_datefmt
    and log_format settings.
    This configuration can be used to configure additional handlers (e.g. to
    output the log to a file) or for finer control over the default handlers.
    If provided this should be a logging configuration dictionary, for more
    information see:
    https://docs.python.org/3/library/logging.config.html#logging-config-
    dictschema
    This dictionary is merged with the base logging configuration which defines
    the following:
    * A logging formatter intended for interactive use called
      ``console``.
    * A logging handler that writes to stderr called
      ``console`` which uses the formatter ``console``.
    * A logger with the name of this application set to ``DEBUG``
      level.
    This example adds a new handler that writes to a file:
    .. code-block:: python
       c.Application.logging_config = {
           "handlers": {
               "file": {
                   "class": "logging.FileHandler",
                   "level": "DEBUG",
                   "filename": "<path/to/file>",
               }
           },
           "loggers": {
               "<application-name>": {
                   "level": "DEBUG",
                   # NOTE: if you don't list the default "console"
                   # handler here then it will be disabled
                   "handlers": ["console", "file"],
               },
           },
       }
    Default: {}
--Application.show_config=<Bool>
    Instead of starting the Application, dump configuration to stdout
    Default: False
--Application.show_config_json=<Bool>
    Instead of starting the Application, dump configuration to stdout (as JSON)
    Default: False

JupyterApp(Application) options
-------------------------------
--JupyterApp.answer_yes=<Bool>
    Answer yes to any prompts.
    Default: False
--JupyterApp.config_file=<Unicode>
    Full path of a config file.
    Default: ''
--JupyterApp.config_file_name=<Unicode>
    Specify a config file to load.
    Default: ''
--JupyterApp.generate_config=<Bool>
    Generate default config file.
    Default: False
--JupyterApp.log_datefmt=<Unicode>
    The date format used by logging formatters for %(asctime)s
    Default: '%Y-%m-%d %H:%M:%S'
--JupyterApp.log_format=<Unicode>
    The Logging format template
    Default: '[%(name)s]%(highlevel)s %(message)s'
--JupyterApp.log_level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
--JupyterApp.logging_config=<key-1>=<value-1>...
    Configure additional log handlers.
    The default stderr logs handler is configured by the log_level, log_datefmt
    and log_format settings.
    This configuration can be used to configure additional handlers (e.g. to
    output the log to a file) or for finer control over the default handlers.
    If provided this should be a logging configuration dictionary, for more
    information see:
    https://docs.python.org/3/library/logging.config.html#logging-config-
    dictschema
    This dictionary is merged with the base logging configuration which defines
    the following:
    * A logging formatter intended for interactive use called
      ``console``.
    * A logging handler that writes to stderr called
      ``console`` which uses the formatter ``console``.
    * A logger with the name of this application set to ``DEBUG``
      level.
    This example adds a new handler that writes to a file:
    .. code-block:: python
       c.Application.logging_config = {
           "handlers": {
               "file": {
                   "class": "logging.FileHandler",
                   "level": "DEBUG",
                   "filename": "<path/to/file>",
               }
           },
           "loggers": {
               "<application-name>": {
                   "level": "DEBUG",
                   # NOTE: if you don't list the default "console"
                   # handler here then it will be disabled
                   "handlers": ["console", "file"],
               },
           },
       }
    Default: {}
--JupyterApp.show_config=<Bool>
    Instead of starting the Application, dump configuration to stdout
    Default: False
--JupyterApp.show_config_json=<Bool>
    Instead of starting the Application, dump configuration to stdout (as JSON)
    Default: False

ListKernelSpecs(JupyterApp) options
-----------------------------------
--ListKernelSpecs.answer_yes=<Bool>
    Answer yes to any prompts.
    Default: False
--ListKernelSpecs.config_file=<Unicode>
    Full path of a config file.
    Default: ''
--ListKernelSpecs.config_file_name=<Unicode>
    Specify a config file to load.
    Default: ''
--ListKernelSpecs.generate_config=<Bool>
    Generate default config file.
    Default: False
--ListKernelSpecs.json_output=<Bool>
    output spec name and location as machine-readable json.
    Default: False
--ListKernelSpecs.log_datefmt=<Unicode>
    The date format used by logging formatters for %(asctime)s
    Default: '%Y-%m-%d %H:%M:%S'
--ListKernelSpecs.log_format=<Unicode>
    The Logging format template
    Default: '[%(name)s]%(highlevel)s %(message)s'
--ListKernelSpecs.log_level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
--ListKernelSpecs.logging_config=<key-1>=<value-1>...
    Configure additional log handlers.
    The default stderr logs handler is configured by the log_level, log_datefmt
    and log_format settings.
    This configuration can be used to configure additional handlers (e.g. to
    output the log to a file) or for finer control over the default handlers.
    If provided this should be a logging configuration dictionary, for more
    information see:
    https://docs.python.org/3/library/logging.config.html#logging-config-
    dictschema
    This dictionary is merged with the base logging configuration which defines
    the following:
    * A logging formatter intended for interactive use called
      ``console``.
    * A logging handler that writes to stderr called
      ``console`` which uses the formatter ``console``.
    * A logger with the name of this application set to ``DEBUG``
      level.
    This example adds a new handler that writes to a file:
    .. code-block:: python
       c.Application.logging_config = {
           "handlers": {
               "file": {
                   "class": "logging.FileHandler",
                   "level": "DEBUG",
                   "filename": "<path/to/file>",
               }
           },
           "loggers": {
               "<application-name>": {
                   "level": "DEBUG",
                   # NOTE: if you don't list the default "console"
                   # handler here then it will be disabled
                   "handlers": ["console", "file"],
               },
           },
       }
    Default: {}
--ListKernelSpecs.show_config=<Bool>
    Instead of starting the Application, dump configuration to stdout
    Default: False
--ListKernelSpecs.show_config_json=<Bool>
    Instead of starting the Application, dump configuration to stdout (as JSON)
    Default: False

# Indexing and Slicing

In [270]:
data = torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
display(data)
print("Extract first row:",data[0])
print("Extract first column:", data[:,0])
print("Extract second row:", data[1])
print("Extract second column:", data[:,1])
print("Extract third row:", data[2])
print("Extract third column:", data[:,2],"\n")
print("Extract the first first row:", data[0,0])
print("Extract the first two rows:", data[0:2,0])
print("Extract the last last row:", data[2,0])
print("Extract the last two rows:", data[1:,0],"\n")
print("Extract the first second column:", data[0,1])
print("Extract the first two rows of the second column:", data[0:2,1])
print("Extract the last row of second column:", data[2,1])
print("Extract the last two rows of second column:", data[1:,1], "\n")
print("Extract the first first row of third column:", data[0,2])
print("Extract the first two rows of third column:", data[0:2,2])
print("Extract the last row of third column:", data[2,2])
print("Extract the last two rows of third column:", data[1:,2])

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

Extract first row: tensor([1, 2, 3])
Extract first column: tensor([1, 3, 5])
Extract second row: tensor([3, 4, 5])
Extract second column: tensor([2, 4, 6])
Extract third row: tensor([5, 6, 7])
Extract third column: tensor([3, 5, 7])

Extract the first first row: tensor(1)
Extract the first two rows: tensor([1, 3])
Extract the last last row: tensor(5)
Extract the last two rows: tensor([3, 5])

Extract the first second column: tensor(2)
Extract the first two rows of the second column: tensor([2, 4])
Extract the last row of second column: tensor(6)
Extract the last two rows of second column: tensor([4, 6])

Extract the first first row of third column: tensor(3)
Extract the first two rows of third column: tensor([3, 5])
Extract the last row of third column: tensor(7)
Extract the last two rows of third column: tensor([5, 7])

In [276]:
data = torch.tensor([range(20)])
display(data.T)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])

In [284]:
data = torch.tensor([range(15)])
display(data)
display(data.T)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]])

In [399]:
data = torch.tensor([[2,3,4],[5,6,7],[8,9,0],[11,14,16],[67,78,99], [44,33,22]])
display(data, data.shape)

print("Extract the middle two rows of first column:", data[2:4,0])
print("Extract the middle two rows:", data[2:4])
print("Extract the sub-matrix of 2 by 2:",data[3:5,1:], data[4:,0:2], data[0:2,1:]\
     , data[1:3,0:2], data[2:4,1:], data[2:4,0:2])
print("Extract the sub-matrix of 3 by 3:", data[0:3,:], data[3:,:])
print("Extract the sub-matrix of 3 by 2:", data[0:3,0:2], data[0:3, 1:], data[2:5,1:]\
     , data[3:,1:], data[2:5,0:2], data[3:,0:2], data[1:4,0:2], data[1:4,1:])
print("Extract the sub-matrix of 2 by 3:", data[0:2,:], data[2:4,:], data[3:5,:]\
     , data[4:,:])
print("Extract the column vector of 4 by 1:", data[0:4,0:1], data[2:,0:1]\
     , data[0:4,1:2], data[2:,1:2], data[0:4,2:], data[2:,2:])
print("Extract the row vector of 1 by 2:", data[0:1,0:2], data[0:1,1:]\
     , data[1:2,0:2], data[1:2,1:], data[2:3,0:2], data[2:3,1:], data[3:4,0:2]\
     , data[3:4,1:], data[4:5,:2], data[4:5,1:], data[5:,:2], data[5:,1:])
print("Extract column vector 2 by 1:", data[3:5,2:], data[3:5,1:2], data[1:3,2:])
print("Extract columns only:", data[:,0:1], data[:,1:2], data[:,2:])
print("Extract rows only:", data[0:1], data[1:2], data[2:3], data[3:4]\
     , data[4:5], data[5:])
print("Extract scalar/single numers:", data[0,0], data[3,2:], data[4:5,1], data[5,2])

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9,  0],
        [11, 14, 16],
        [67, 78, 99],
        [44, 33, 22]])

torch.Size([6, 3])

Extract the middle two rows of first column: tensor([ 8, 11])
Extract the middle two rows: tensor([[ 8,  9,  0],
        [11, 14, 16]])
Extract the sub-matrix of 2 by 2: tensor([[14, 16],
        [78, 99]]) tensor([[67, 78],
        [44, 33]]) tensor([[3, 4],
        [6, 7]]) tensor([[5, 6],
        [8, 9]]) tensor([[ 9,  0],
        [14, 16]]) tensor([[ 8,  9],
        [11, 14]])
Extract the sub-matrix of 3 by 3: tensor([[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]]) tensor([[11, 14, 16],
        [67, 78, 99],
        [44, 33, 22]])
Extract the sub-matrix of 3 by 2: tensor([[2, 3],
        [5, 6],
        [8, 9]]) tensor([[3, 4],
        [6, 7],
        [9, 0]]) tensor([[ 9,  0],
        [14, 16],
        [78, 99]]) tensor([[14, 16],
        [78, 99],
        [33, 22]]) tensor([[ 8,  9],
        [11, 14],
        [67, 78]]) tensor([[11, 14],
        [67, 78],
        [44, 33]]) tensor([[ 5,  6],
        [ 8,  9],
        [11, 14]]) tensor([[ 6,  7],
        [ 9,  0],
        [14, 16]])
Extract the sub-matrix of 2 by 3: tensor([[2, 3, 4],
        [5, 6, 7]]) tensor([[ 8,  9,  0],
        [11, 14, 16]]) tensor([[11, 14, 16],
        [67, 78, 99]]) tensor([[67, 78, 99],
        [44, 33, 22]])
Extract the column vector of 4 by 1: tensor([[ 2],
        [ 5],
        [ 8],
        [11]]) tensor([[ 8],
        [11],
        [67],
        [44]]) tensor([[ 3],
        [ 6],
        [ 9],
        [14]]) tensor([[ 9],
        [14],
        [78],
        [33]]) tensor([[ 4],
        [ 7],
        [ 0],
        [16]]) tensor([[ 0],
        [16],
        [99],
        [22]])
Extract the row vector of 1 by 2: tensor([[2, 3]]) tensor([[3, 4]]) tensor([[5, 6]]) tensor([[6, 7]]) tensor([[8, 9]]) tensor([[9, 0]]) tensor([[11, 14]]) tensor([[14, 16]]) tensor([[67, 78]]) tensor([[78, 99]]) tensor([[44, 33]]) tensor([[33, 22]])
Extract column vector 2 by 1: tensor([[16],
        [99]]) tensor([[14],
        [78]]) tensor([[7],
        [0]])
Extract columns only: tensor([[ 2],
        [ 5],
        [ 8],
        [11],
        [67],
        [44]]) tensor([[ 3],
        [ 6],
        [ 9],
        [14],
        [78],
        [33]]) tensor([[ 4],
        [ 7],
        [ 0],
        [16],
        [99],
        [22]])
Extract rows only: tensor([[2, 3, 4]]) tensor([[5, 6, 7]]) tensor([[8, 9, 0]]) tensor([[11, 14, 16]]) tensor([[67, 78, 99]]) tensor([[44, 33, 22]])
Extract scalar/single numers: tensor(2) tensor([16]) tensor([78]) tensor(22)

# Creating Tensors based on other Tensors

In [435]:
# zeros_like(input_tensor)
# ones_like(input_tensor)
# rand_like(input_tensor)
# randn_like(input_tensor)


base_foundation = torch.tensor([[1,2,3,10,11,12],[4,5,6,13,14,15],[7,8,9,16,17,18]], dtype=torch.float64)
display(base_foundation)
print(f"Base tensor shape: {base_foundation.shape}, and datatype {base_foundation.dtype}")

zero_like_base = torch.zeros_like(base_foundation)
one_like_base = torch.ones_like(base_foundation)
rand_like_base = torch.rand_like(base_foundation) # since rand & randn, can only have floating values, integer tensors will prompt error
randn_like_base = torch.randn_like(base_foundation)

display(zero_like_base)
print(f"Zero like base info: {zero_like_base.shape}, {zero_like_base.dtype}\n")

display(one_like_base)
print(f"One like base info: {one_like_base.shape}, {one_like_base.dtype}\n")

display(rand_like_base)
print(f"Rand like base info: {rand_like_base.shape}, {rand_like_base.dtype}\n")

display(randn_like_base)
print(f"Randn like base info: {randn_like_base.shape}, {randn_like_base.dtype}")

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]], dtype=torch.float64)

Base tensor shape: torch.Size([3, 6]), and datatype torch.float64

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

Zero like base info: torch.Size([3, 6]), torch.float64

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

One like base info: torch.Size([3, 6]), torch.float64

tensor([[0.9731, 0.5757, 0.1599, 0.4065, 0.4899, 0.7840],
        [0.7871, 0.7655, 0.9428, 0.5875, 0.7318, 0.5175],
        [0.1560, 0.5264, 0.3200, 0.4035, 0.2370, 0.8763]], dtype=torch.float64)

Rand like base info: torch.Size([3, 6]), torch.float64

tensor([[-0.3289,  0.8927,  0.5578,  0.1772,  0.2331,  1.9367],
        [ 2.1001,  1.0563,  1.1401, -0.0840, -0.1294,  0.5280],
        [ 0.0841, -0.3956, -0.0523,  0.3307,  1.7072, -1.6295]],
       dtype=torch.float64)

Randn like base info: torch.Size([3, 6]), torch.float64

In [450]:
fnd = torch.rand(2,3,4, dtype=torch.float64)
display(fnd, fnd.shape, fnd.dtype, fnd.device)

subzero = torch.zeros_like(fnd)
oneone = torch.ones_like(fnd)
rand_zero_to_one = torch.rand_like(fnd)
randn_normal = torch.randn_like(fnd)

print(f"Zeros like: {subzero}, {subzero.shape, subzero.dtype}\n")
print(f"Ones like: {oneone}, {oneone.shape, oneone.dtype}\n")
print(f"Rand (0-1) like: {rand_zero_to_one}, {rand_zero_to_one.shape, rand_zero_to_one.dtype}\n")
print(f"Randn (-3-3) like: {randn_normal}, {randn_normal.shape, randn_normal.dtype}")

tensor([[[0.3841, 0.3180, 0.3793, 0.4173],
         [0.3500, 0.8248, 0.2829, 0.8171],
         [0.1338, 0.8299, 0.7436, 0.3687]],

        [[0.1049, 0.7300, 0.9700, 0.5374],
         [0.9372, 0.6310, 0.0248, 0.9433],
         [0.7177, 0.9117, 0.5864, 0.3479]]], dtype=torch.float64)

torch.Size([2, 3, 4])

torch.float64

device(type='cpu')

Zeros like: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=torch.float64), (torch.Size([2, 3, 4]), torch.float64)

Ones like: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64), (torch.Size([2, 3, 4]), torch.float64)

Rand (0-1) like: tensor([[[0.1044, 0.4622, 0.6890, 0.5514],
         [0.1013, 0.1911, 0.5922, 0.5115],
         [0.4042, 0.8815, 0.0344, 0.7364]],

        [[0.7062, 0.3122, 0.3774, 0.6398],
         [0.2664, 0.9501, 0.8376, 0.2279],
         [0.1950, 0.4914, 0.4397, 0.2307]]], dtype=torch.float64), (torch.Size([2, 3, 4]), torch.float64)

Randn (-3-3) like: tensor([[[ 2.0311, -0.2349,  0.7264, -0.9681],
         [ 0.9670, -0.3477, -0.4224, -0.5017],
         [-2.5053, -1.9490,  1.3155,  0.3068]],

        [[ 0.1734, -0.2983, -1.2166,  0.7827],
         [-0.3191,  0.0249, -0.4239,  0.9706],
         [ 0.1131, -0.3955,  1.4270, -0.8431]]], dtype=torch.float64), (torch.Size([2, 3, 4]), torch.float64)

# Basic operations with Tensors

In [392]:
# Addition torch.add()
# Subtraction torch.sub()
# Multiplication torch.mul()
# Division torch.div()
# Exponentiation torch.pow()

"""
    All these operations are done element-wise only, and tensors must have compatible shapes
    (m, n) * (m, n) - all entries must be the same number, basically only square and rectangular matrices can 
    perform element-wise operations!
    
    NOTE: that there it is not a matrix multiplication torch.matmul(), which is completely different from 
    element-wise multiplication torch.mul()
"""
a_1 = torch.tensor([[1,2],[3,4]])
b_1 = torch.tensor([[11,12],[13,14]])
display(a_1, b_1)
sum_a_b = a_1 + b_1
print("\nSum of tensors (a_1 + b_1):\n", sum_a_b)
print("\nSum of tensors torch.add(a,b):\n", torch.add(a_1, b_1))
diff_a_b = a_1 - b_1
print("\nSubtraction of tensors (a_1 - b_1):\n", diff_a_b)
print("\nSubtraction of tensors torch.sub(a_1,b_1):\n", torch.sub(a_1,b_1))
div_a_b = a_1/b_1
print("\nDivision of tensors (a_1/b_1):\n", div_a_b)
print("\nDivision of tensors torch.div(a_1,b_1):\n", torch.div(a_1,b_1))
mul_a_b = a_1*b_1
print("\nMultiplication of tensors (a_1*b_1):\n", mul_a_b)
print("\nMultiplication of tensors torch.mul(a_1,b_1):\n", torch.mul(a_1,b_1))
raise_a_to_pow_of_b = a_1 ** b_1
print("\nExponentiation of tensors (a_1**b_1):\n", raise_a_to_pow_of_b)
print("\nExponentiation of tensors torch.pow(a_1,b_1):\n", torch.pow(a_1,b_1))

tensor([[1, 2],
        [3, 4]])

tensor([[11, 12],
        [13, 14]])

Sum of tensors (a_1 + b_1):
 tensor([[12, 14],
        [16, 18]])

Sum of tensors torch.add(a,b):
 tensor([[12, 14],
        [16, 18]])

Subtraction of tensors (a_1 - b_1):
 tensor([[-10, -10],
        [-10, -10]])

Subtraction of tensors torch.sub(a_1,b_1):
 tensor([[-10, -10],
        [-10, -10]])

Division of tensors (a_1/b_1):
 tensor([[0.0909, 0.1667],
        [0.2308, 0.2857]])

Division of tensors torch.div(a_1,b_1):
 tensor([[0.0909, 0.1667],
        [0.2308, 0.2857]])

Multiplication of tensors (a_1*b_1):
 tensor([[11, 24],
        [39, 56]])

Multiplication of tensors torch.mul(a_1,b_1):
 tensor([[11, 24],
        [39, 56]])

Exponentiation of tensors (a_1**b_1):
 tensor([[        1,      4096],
        [  1594323, 268435456]])

Exponentiation of tensors torch.pow(a_1,b_1):
 tensor([[        1,      4096],
        [  1594323, 268435456]])

In [393]:
# For element-wise operations shapes, both rows and columns of two or more tensors must be the same
a_2 = torch.rand(4,4)
b_2 = torch.rand(4,4)

# Element-wise operations where shapes of both must be square and equal
print(torch.add(a_2,b_2))
print(torch.sub(a_2,b_2))
print(torch.sub(b_2,a_2))
print(torch.mul(a_2,b_2))
print(torch.div(a_2,b_2))
print(torch.div(b_2,a_2))
print(torch.pow(a_2,b_2))
print(torch.pow(b_2,a_2))

tensor([[1.0532, 0.8718, 1.6102, 1.5640],
        [1.6450, 1.4353, 0.5954, 0.9011],
        [1.5734, 1.4784, 0.8115, 1.0972],
        [0.7050, 0.6156, 1.5870, 1.1890]])
tensor([[ 0.2096, -0.3296, -0.2742,  0.0789],
        [ 0.3094,  0.3300,  0.0230,  0.7940],
        [ 0.2722, -0.1056,  0.1342,  0.1017],
        [-0.3155,  0.5696, -0.1861,  0.7369]])
tensor([[-0.2096,  0.3296,  0.2742, -0.0789],
        [-0.3094, -0.3300, -0.0230, -0.7940],
        [-0.2722,  0.1056, -0.1342, -0.1017],
        [ 0.3155, -0.5696,  0.1861, -0.7369]])
tensor([[0.2663, 0.1628, 0.6294, 0.6100],
        [0.6526, 0.4878, 0.0885, 0.0454],
        [0.6004, 0.5437, 0.1601, 0.2984],
        [0.0994, 0.0136, 0.6210, 0.2176]])
tensor([[ 1.4970,  0.4513,  0.7090,  1.1063],
        [ 1.4633,  1.5971,  1.0805, 15.8363],
        [ 1.4183,  0.8667,  1.3961,  1.2044],
        [ 0.3817, 25.7728,  0.7901,  4.2605]])
tensor([[0.6680, 2.2158, 1.4104, 0.9039],
        [0.6834, 0.6261, 0.9255, 0.0631],
        [0.7051, 1.1538, 0.7163, 0.8303],
        [2.6201, 0.0388, 1.2657, 0.2347]])
tensor([[0.8237, 0.4565, 0.6838, 0.8641],
        [0.9847, 0.9333, 0.7147, 0.9912],
        [0.9491, 0.7423, 0.7759, 0.7752],
        [0.4340, 0.9880, 0.7293, 0.9915]])
tensor([[0.5798, 0.8709, 0.9610, 0.7831],
        [0.6740, 0.5925, 0.6792, 0.0836],
        [0.6726, 0.8521, 0.5993, 0.6582],
        [0.8772, 0.1069, 0.9191, 0.2388]])

In [394]:
# Above given example creates a new tensor, say by a + b or torch.add(a,b)
# However the original tensors "a" and "b" remain unchanged
# We can do in-place operations where either a or b will be changed without creating a new tensor, thus saving memory

a_3 = torch.tensor([[3,4],[6,7]])
b_3 = torch.tensor([[5,1],[8,0]])
display(a_3, b_3)
print(torch.add(a_3, b_3), "\nTensor a_3 after basic operation:",a_3)
print("\nTensor a_3 after in-place operation:", a_3.add_(b_3), a_3, b_3)
print("\nTensor b_3 after in-place operation:", b_3.add_(a_3), b_3)

tensor([[3, 4],
        [6, 7]])

tensor([[5, 1],
        [8, 0]])

tensor([[ 8,  5],
        [14,  7]])
Tensor a_3 after basic operation: tensor([[3, 4],
        [6, 7]])

Tensor a_3 after in-place operation: tensor([[ 8,  5],
        [14,  7]]) tensor([[ 8,  5],
        [14,  7]]) tensor([[5, 1],
        [8, 0]])

Tensor b_3 after in-place operation: tensor([[13,  6],
        [22,  7]]) tensor([[13,  6],
        [22,  7]])

In [395]:
print(a_3.mul_(b_3))
print(b_3.sub_(a_3))
print(a_3.pow_(b_3))
print(a_3.add_(b_3))
#print(a_3.div_(b_3))

# In-place operations change the original tensors, thus saving memory, while basic operations create new tensors,
# therefore original tensors intact

tensor([[104,  30],
        [308,  49]])
tensor([[ -91,  -24],
        [-286,  -42]])
tensor([[0, 0],
        [0, 0]])
tensor([[ -91,  -24],
        [-286,  -42]])

In [396]:
# Element-wise operations with scalar(single) numbers

x = torch.ones(4,3, dtype=torch.int32)
y = torch.tensor([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])

scalar = 10

print("\nTensor + Scalar:\n", scalar+x,"\n",scalar+y)
print("\nTensor - Scalar:\n", scalar-x,"\n", scalar-y)
print("\nTensor * Scalar:\n", scalar * x,"\n", scalar * y)
print("\nPower:\n", y.pow_(scalar), y) #Inplace operations
print("\nMultiplication:\n", y.mul_(scalar), y)

# Again Inplace operations change the original tensors, thus saving memory without creating a new object/variable to store the result
# Be cautious to use it, in cases where original value of tensors are important

Tensor + Scalar:
 tensor([[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]], dtype=torch.int32)
 tensor([[11, 11, 11],
        [12, 12, 12],
        [13, 13, 13],
        [14, 14, 14],
        [15, 15, 15]])

Tensor - Scalar:
 tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]], dtype=torch.int32)
 tensor([[9, 9, 9],
        [8, 8, 8],
        [7, 7, 7],
        [6, 6, 6],
        [5, 5, 5]])

Tensor * Scalar:
 tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]], dtype=torch.int32)
 tensor([[10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50]])

Power:
 tensor([[      1,       1,       1],
        [   1024,    1024,    1024],
        [  59049,   59049,   59049],
        [1048576, 1048576, 1048576],
        [9765625, 9765625, 9765625]]) tensor([[      1,       1,       1],
        [   1024,    1024,    1024],
        [  59049,   59049,   59049],
        [1048576, 1048576, 1048576],
        [9765625, 9765625, 9765625]])

Multiplication:
 tensor([[      10,       10,       10],
        [   10240,    10240,    10240],
        [  590490,   590490,   590490],
        [10485760, 10485760, 10485760],
        [97656250, 97656250, 97656250]]) tensor([[      10,       10,       10],
        [   10240,    10240,    10240],
        [  590490,   590490,   590490],
        [10485760, 10485760, 10485760],
        [97656250, 97656250, 97656250]])

In [397]:
# PyTorch also includes operations such as sqrt, log, abs, exp just like in Numpy

x = torch.rand(3,4)
y = torch.tensor([[100, 100], [25,25],[9,9]])
print("Square root:\n", torch.sqrt(x), "\n",torch.sqrt(y))

x_1 = torch.randn(3,5)
x_1_2 = torch.randn(2,3,3)
print("\nAbsolute value:\n", torch.abs(x_1), "\nBefore taking absolute:\n", x_1)
print("\nAbsolute value:\n", torch.abs(x_1_2), "\nBefore taking absolute:\n", x_1_2)


y_1 = torch.ones(2,3)
y_1_2 = torch.tensor([[2,2,2],[2,2,2],[2,2,2]])
y_1_3 = torch.zeros(3,2)
y_1_4 = torch.rand(2,2)
print("\nExponentiation e^(input_value):\n", torch.exp(y_1), "\n", torch.exp(y_1_2)\
     , "\n", torch.exp(y_1_3), "\n", torch.exp(y_1_4))

Square root:
 tensor([[0.7279, 0.9160, 0.3552, 0.5117],
        [0.9645, 0.9171, 0.7372, 0.4763],
        [0.4625, 0.6453, 0.6363, 0.6052]])
 tensor([[10., 10.],
        [ 5.,  5.],
        [ 3.,  3.]])

Absolute value:
 tensor([[0.3186, 0.3233, 0.2157, 0.0171, 0.1623],
        [0.8317, 0.9261, 0.0188, 1.0016, 0.3461],
        [0.0326, 0.8280, 1.1600, 0.4430, 0.5705]])
Before taking absolute:
 tensor([[ 0.3186,  0.3233,  0.2157, -0.0171,  0.1623],
        [-0.8317,  0.9261, -0.0188, -1.0016, -0.3461],
        [ 0.0326, -0.8280,  1.1600, -0.4430,  0.5705]])

Absolute value:
 tensor([[[0.4411, 0.9329, 0.4732],
         [0.3270, 2.2166, 0.4721],
         [1.3215, 0.3173, 0.8030]],

        [[1.2395, 0.0512, 1.4917],
         [0.4787, 0.3557, 0.5708],
         [0.9547, 1.5155, 0.7965]]])
Before taking absolute:
 tensor([[[-0.4411, -0.9329, -0.4732],
         [-0.3270,  2.2166,  0.4721],
         [-1.3215, -0.3173,  0.8030]],

        [[-1.2395, -0.0512,  1.4917],
         [-0.4787,  0.3557,  0.5708],
         [ 0.9547, -1.5155, -0.7965]]])

Exponentiation e^(input_value):
 tensor([[2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183]])
 tensor([[7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891]])
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
 tensor([[1.3966, 1.6265],
        [2.4481, 1.4089]])

In [398]:
# For natural logarithm with the base of e = 2.718~, we must provide only positive numbers as input
# negative numbers will not work for any logarithms
# ln(e^x) = y(input_value), basically it will calculate such "x" so that e^x equals to "y" an input value
# Natural log is simple an inverse of e^x, in torch.exp(input_value), we are raising Eulers' number to given input_value, e^input_value
# Natural log, is log with base of e=2.718~, in torch.log(input_value), it will calculate an exponent for e such that
# the e^x = input_value, basically it is does the exact opposite of torch.exp()

x = torch.tensor([3,3,3])
e = torch.exp(x)
print("\n e^input_value:\n", e)

x = torch.abs(x)
print("\n Find such exponent so that e^x will equal to input_value:\n", torch.log(e))

# torch.exp() and torch.log() are inverses of each other

 e^input_value:
 tensor([20.0855, 20.0855, 20.0855])

 Find such exponent so that e^x will equal to input_value:
 tensor([3., 3., 3.])

In [399]:
x = torch.randn(2,3)
display(x)
e = torch.exp(x)
display(e) # raises Euler's number to the power of input_value
y = torch.log(e)
display(y)

tensor([[ 2.5460, -0.5250,  0.1986],
        [-1.7966, -2.4358, -0.0138]])

tensor([[12.7557,  0.5915,  1.2198],
        [ 0.1659,  0.0875,  0.9863]])

tensor([[ 2.5460, -0.5250,  0.1986],
        [-1.7966, -2.4358, -0.0138]])

In [400]:
x = torch.rand(2,3)
display(x)
y = torch.log(x) # remember it outputs the exponential values "x" such that e^x=input_value
display(y)
e = torch.exp(y) # if we e^torch.exp(x), then we will get back the original value of x
display(e)
# Natural log does not take negative values, because e^x = the output is never negative even if exponent "x" is negative
# negative exponents, will simply make the value smaller but never become negative
# ln(e^x) = y, basically it finds such exponent "x" so that the output is "y"

tensor([[0.5093, 0.2118, 0.2989],
        [0.8138, 0.8431, 0.9175]])

tensor([[-0.6748, -1.5523, -1.2076],
        [-0.2060, -0.1707, -0.0861]])

tensor([[0.5093, 0.2118, 0.2989],
        [0.8138, 0.8431, 0.9175]])

In [401]:
x = torch.randn(4,5)
x = torch.abs(x)
x_1 = torch.ones(3,5) * 2 # Scalar
e = torch.exp(x_1)
print(torch.sqrt(e))

tensor([[2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183, 2.7183]])

In [402]:
# Reduction operations help to summarize vast amount of data within a single number, such as sum, mean, min, max
# Instead of looking at all the data, it is much easier to analyze the only few numbers which are representitives of the whole data
a = torch.rand(4,9)
display(a)

print("\nMean:\n", torch.mean(a))
print("\nSum:\n", torch.sum(a))
print("\nMin:\n", torch.min(a))
print("\nMax:\n", torch.max(a))

# Notice that the mean value stays more or less the same with few changes, which means that most of the data points
# are centered around that value of approximate 0.5, only when we are using rand with range (0,1) and not randn with normal distribution

tensor([[0.5340, 0.2789, 0.6121, 0.8012, 0.1938, 0.1412, 0.3877, 0.0363, 0.7764],
        [0.8699, 0.7946, 0.5591, 0.9067, 0.6184, 0.7033, 0.6262, 0.0195, 0.8188],
        [0.5028, 0.1628, 0.5443, 0.7226, 0.8835, 0.9063, 0.8497, 0.7745, 0.9600],
        [0.5109, 0.3464, 0.4243, 0.1182, 0.5919, 0.3182, 0.8460, 0.6174, 0.9228]])

Mean:
 tensor(0.5745)

Sum:
 tensor(20.6808)

Min:
 tensor(0.0195)

Max:
 tensor(0.9600)

In [403]:
a = torch.tensor([range(5)])
b = torch.randn(2,3)
display(a.float().T)
display(torch.abs(b.int()))

# The reason why we can keep adding methods in objects, because at its core they are torch.tensor() 
# which allows adding more methods to their assigned objects, if we are doing a.abs().int()
# effectively we are doing torch.tensor().abs().int(), because torch.tensor() is assigned to object "a"

display(torch.max(a))
display(a.max()) # the output is the same
display(torch.sum(a))
display(a.sum())
display(torch.mean(a.float()))
display(a.float().mean()) # remember that the mean requires input to be of floating type and not integer

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

tensor([[1, 0, 0],
        [2, 0, 0]], dtype=torch.int32)

tensor(4)

tensor(4)

tensor(10)

tensor(10)

tensor(2.)

tensor(2.)

In [404]:
# We can use reduction operations along particular dimensions (rows and columns)
# if not dimension is specified the reduction will be made along all the dimensions by producing a single output for the entire tensor
# dim=0 represents rows, while dim=1 represents columns, dim=3,4...k represents sub-matrices any number preceding those
# standard (row, column) shape

a = torch.tensor([[1,1,1],[2,2,2],[4,4,4],[7,7,7]])
display(a.device, a.dtype, a.shape)
print("\nSumming Rows:\n", torch.sum(a, dim=0))
print("\nSumming columns:\n", torch.sum(a, dim=1))
print("\nMean rows:\n", torch.mean(a.float(), dim=0))
print("\nMean columns:\n", torch.mean(a.float(), dim=1))

device(type='cpu')

torch.int64

torch.Size([4, 3])

Summing Rows:
 tensor([14, 14, 14])

Summing columns:
 tensor([ 3,  6, 12, 21])

Mean rows:
 tensor([3.5000, 3.5000, 3.5000])

Mean columns:
 tensor([1., 2., 4., 7.])

In [405]:
a = torch.ones(2,5)
display(a, type(a))
display(torch.sum(a, dim=0))
display(torch.sum(a, dim=1))
display(torch.mean(a, dim=0))
display(torch.mean(a, dim=1))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

torch.Tensor

tensor([2., 2., 2., 2., 2.])

tensor([5., 5.])

tensor([1., 1., 1., 1., 1.])

tensor([1., 1.])

In [406]:
# Comparison operations, shapes of both tensors must match, although does not have to be a square matrices like for element-wise operations
# <
# >
# <=
# >=
# == 
# !=
# the dtype of output is torch.bool, but it is still a torch.tensor at its core
# it is doing element-wise comparison, that is why shapes of both tensors must be equal, but not necessarily be square, can be rectangle

a = torch.rand(3,5)
b = torch.randn(3,5)
display(a,b)
c = a == b
print("\na == b:\n", a == b, type(c), c.dtype) # False if not equal
print("\na > b:\n", a > b)
print("\na < b:\n", a < b)
print("\na >= b:\n", a >= b)
print("\na <= b:\n", a <= b)
print("\na != b:\n", a != b) # True if not equal

tensor([[0.3696, 0.3075, 0.7802, 0.3711, 0.7749],
        [0.1043, 0.5252, 0.5201, 0.3494, 0.4971],
        [0.3683, 0.2233, 0.5532, 0.7388, 0.5115]])

tensor([[-0.9742,  1.3534,  0.4010,  1.7942, -0.1868],
        [ 0.1541,  1.2404, -1.8009,  0.3063, -0.1182],
        [ 0.9977,  1.9513, -0.2250, -1.2190, -1.1815]])

a == b:
 tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]) <class 'torch.Tensor'> torch.bool

a > b:
 tensor([[ True, False,  True, False,  True],
        [False, False,  True,  True,  True],
        [False, False,  True,  True,  True]])

a < b:
 tensor([[False,  True, False,  True, False],
        [ True,  True, False, False, False],
        [ True,  True, False, False, False]])

a >= b:
 tensor([[ True, False,  True, False,  True],
        [False, False,  True,  True,  True],
        [False, False,  True,  True,  True]])

a <= b:
 tensor([[False,  True, False,  True, False],
        [ True,  True, False, False, False],
        [ True,  True, False, False, False]])

a != b:
 tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [436]:
# Updated info, element-wise operations can be performed by only square and rectangular matrices
# the shapes of both tensors must be the same, (mxn) for both A and B tensors

a = torch.rand(2,3)
b = torch.rand(2,3)

display(torch.mul(a, b))

x = torch.ones(2,3)
k = torch.ones(2,3)
display(x.add_(k), x, k)
display(k.add_(x), k)
display(k.pow_(x), k)
display(k.div_(x), k)
display(x.sub_(k), x, k)
display(k.add_(x), k)
k = k.int()
display(k)

tensor([[0.0556, 0.1531, 0.3779],
        [0.0325, 0.0393, 0.4640]])

tensor([[2., 2., 2.],
        [2., 2., 2.]])

tensor([[2., 2., 2.],
        [2., 2., 2.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[3., 3., 3.],
        [3., 3., 3.]])

tensor([[3., 3., 3.],
        [3., 3., 3.]])

tensor([[9., 9., 9.],
        [9., 9., 9.]])

tensor([[9., 9., 9.],
        [9., 9., 9.]])

tensor([[4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000]])

tensor([[4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000]])

tensor([[-2.5000, -2.5000, -2.5000],
        [-2.5000, -2.5000, -2.5000]])

tensor([[-2.5000, -2.5000, -2.5000],
        [-2.5000, -2.5000, -2.5000]])

tensor([[4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000]])

tensor([[2., 2., 2.],
        [2., 2., 2.]])

tensor([[2., 2., 2.],
        [2., 2., 2.]])

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

In [82]:
# .ipynb jupyter notebook is a simple JSON file containing text, source code, rich media output, and metadata

!cat PyTorch.ipynb

{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "2a7eff3e-a048-4829-8425-841989f1e275",
   "metadata": {},
   "source": [
    "# Install packages|"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "766ecba1-aed8-45f0-8c22-338731c752ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Torch version: 2.5.1\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import numpy as np\n",
    "\n",
    "print(f\"Torch version: {torch.__version__}\")\n",
    "\n",
    "# Tensors are just like Numpy ndarrays matrices, but with capability to run much faster on GPUs, TPUs and CPUs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7c69fb56-74fe-4af5-9c35-550e150afd6d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cude is available: False\n"
     ]
    }
   ],
   "source": [
    "cuda_available = torch.cuda.is_available()\n",
    "print(f\"Cude is available: {cuda_available}\")\n",
    "\n",
    "#If false, then PyTorch is running on the CPU. If true, then running on GPU, but we installed it without CUDA NVIDIA drivers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "29986fa8-a502-455b-9a4f-d44f4824fa44",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tensor([[ 0.1975,  2.3857,  2.0725,  0.2292,  1.4295,  0.2413,  1.5068],\n",
      "        [ 0.8240, -0.3320,  0.6636,  1.4492,  0.9831, -0.5983, -1.3798],\n",
      "        [ 2.1171, -0.6836,  0.9505,  1.0101, -0.0826,  1.4257,  0.1901],\n",
      "        [-1.0944,  0.0055,  0.3359,  0.3584,  1.1735,  0.3462, -1.5338]]) \n",
      "Tensor stored in: cpu \n",
      "Tensor shape: torch.Size([4, 7]) \n",
      "Tensor datatype: torch.float32 <class 'torch.Tensor'> \n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "tensor([[0.8075, 0.5019],\n",
       "        [0.4307, 0.6033],\n",
       "        [0.4977, 0.8694]])"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tensor stored in: cpu\n",
      "Tensor shape: torch.Size([3, 2])\n",
      "Tensor datatype: torch.float32 <class 'torch.Tensor'>\n"
     ]
    }
   ],
   "source": [
    "# Creating a simple tensor\n",
    "\n",
    "x = torch.randn(4,7) # random but follows normal distribution\n",
    "y = torch.rand(3,2) # random within 0 - 1 range continuous values\n",
    "print(x, \"\\nTensor stored in:\", x.device, \"\\nTensor shape:\", x.shape, \"\\nTensor datatype:\", x.dtype, type(x), \"\\n\")\n",
    "\n",
    "# By default the dtype is float32\n",
    "type(y)\n",
    "display(y)\n",
    "print(f\"Tensor stored in: {y.device}\\nTensor shape: {y.shape}\\nTensor datatype: {y.dtype} {type(y)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 146,
   "id": "f6f7665c-eec5-4c20-bae2-8c5fd9711606",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[1., 2.],\n",
       "        [3., 4.],\n",
       "        [7., 8.]])"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tensor info: torch.float32, torch.Size([3, 2]), cpu, <class 'torch.Tensor'>\n"
     ]
    }
   ],
   "source": [
    "# Creating tensors from python list\n",
    "\n",
    "data_list = [[1,2], [3,4],[7,8]]\n",
    "tensfor_from_list = torch.tensor(data_list, dtype = torch.float32)\n",
    "display(tensfor_from_list)\n",
    "print(f\"Tensor info: {tensfor_from_list.dtype}, {tensfor_from_list.shape}, {tensfor_from_list.device}, {type(tensfor_from_list)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "368ce542-f07a-45bc-af1f-21a0fccd2b2f",
   "metadata": {
    "jp-MarkdownHeadingCollapsed": true
   },
   "source": [
    "# Working with Tensors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 203,
   "id": "4cb8b592-7352-4927-8503-1e659065cdfe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "torch.Tensor"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tensor([[1.],\n",
      "        [2.],\n",
      "        [3.],\n",
      "        [4.],\n",
      "        [5.]]) torch.Size([5, 1]) cpu torch.float32 <class 'torch.Tensor'>\n"
     ]
    }
   ],
   "source": [
    "# [] - a scalar number, 0D array/tensor. rank-0\n",
    "# [[]] - a vector, 1D array/tensor. rank-1\n",
    "# [[],[],[]...] - a matrix, 2D array/tensor. rank-n\n",
    "\n",
    "# [[1,2,3]] - row vector, shape(1,3), one row & three columns. rank-1\n",
    "# [[1], [2], [3]] - column vector, shape three rows & one column. rank-1\n",
    "# [[1,2,3], [3,4,5]] - matrix of shape(2,3), two rows and 3 columns. rank-2\n",
    "\n",
    "\n",
    "data_list = [[1,2,3,4,5]] \n",
    "tensor_from_list = torch.tensor(data_list, dtype=torch.float32) # dtype explicitly can be changed\n",
    "display(type(tensor_from_list))\n",
    "\n",
    "print(tensor_from_list.T, tensor_from_list.T.shape, tensor_from_list.device, tensor_from_list.dtype, type(tensor_from_list))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 200,
   "id": "7fa841b0-a61a-4056-b041-25a47a880112",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tensor([[ 1,  3,  7, 11, 14],\n",
      "        [ 2,  4,  8, 12, 15],\n",
      "        [ 3,  5,  9, 13, 16]]), \n",
      "torch.int64, cpu, torch.Size([3, 5]), <class 'torch.Tensor'>\n"
     ]
    }
   ],
   "source": [
    "data_list = [[1,2,3], [3,4,5], [7,8,9], [11, 12, 13], [14, 15, 16]]\n",
    "tensor_from_list = torch.tensor(data_list)\n",
    "\n",
    "print(f\"{tensor_from_list.T}, \\n{tensor_from_list.dtype}, {tensor_from_list.device}, {tensor_from_list.T.shape}, {type(tensor_from_list)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 215,
   "id": "f69ab210-66f2-4024-890a-779093d98c3b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([1, 2, 3, 4])"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "torch.int64 cpu torch.Size([4]) <class 'torch.Tensor'>\n"
     ]
    }
   ],
   "source": [
    "# Tensors from numpy\n",
    "\n",
    "data_numpy = np.array([1, 2, 3, 4]) # a single [] represents a scalar number\n",
    "tensor_from_np = torch.from_numpy(data_numpy)\n",
    "\n",
    "display(tensor_from_np)\n",
    "print(tensor_from_np.dtype, tensor_from_np.device, tensor_from_np.shape, type(tensor_from_np))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 261,
   "id": "5bee36a2-8e58-4be8-9af4-f51aa45ea4bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Numpy dtype: float32\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "tensor([[1.],\n",
       "        [2.],\n",
       "        [3.],\n",
       "        [4.]])"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tensor shape: torch.Size([4, 1])\n",
      "Tensor datatype: (torch.float32, <class 'torch.Tensor'>)\n",
      " Tensor stored in: cpu\n",
      "\n"
     ]
    }
   ],
   "source": [
    "data_numpy = np.array([[1, 2, 3, 4]], dtype=np.float32) # [[]] represents row vector as of now\n",
    "print(\"Numpy dtype:\", data_numpy.dtype)\n",
    "tensor_from_np = torch.from_numpy(data_numpy)\n",
    "\n",
    "display(tensor_from_np.T) # after transposing, now it is column vector\n",
    "print(f\"Tensor shape: {tensor_from_np.T.shape}\\nTensor datatype: {tensor_from_np.dtype, type(tensor_from_np)}\\n \\\n",
    "Tensor stored in: {tensor_from_np.device}\\n\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 293,
   "id": "feaea925-f93d-4375-8ff9-1a35efb33a7b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[ 1,  2,  3],\n",
       "        [ 4,  5,  6],\n",
       "        [ 7,  8,  9],\n",
       "        [11, 12, 13],\n",
       "        [15, 16, 17]])"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tensor shape: torch.Size([5, 3])\n",
      "Tensor datatype: (torch.int64, <class 'torch.Tensor'>)\n",
      " Tensor stored in: cpu\n"
     ]
    }
   ],
   "source": [
    "data_numpy = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13],[15,16,17]])\n",
    "tensor_from_np = torch.from_numpy(data_numpy)\n",
    "\n",
    "display(tensor_from_np)\n",
    "print(f\"Tensor shape: {tensor_from_np.shape}\\nTensor datatype: {tensor_from_np.dtype, type(tensor_from_np)}\\n \\\n",
    "Tensor stored in: {tensor_from_np.device}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 290,
   "id": "0b49ec41-4fc7-497b-9ef8-9c003d2ad7cd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[[ 1,  2,  3],\n",
       "         [ 3,  4,  5],\n",
       "         [ 6,  7,  8]],\n",
       "\n",
       "        [[11, 12, 13],\n",
       "         [14, 15, 16],\n",
       "         [17, 18, 19]],\n",
       "\n",
       "        [[21, 22, 23],\n",
       "         [23, 24, 25],\n",
       "         [26, 27, 28]]])"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "torch.Size([3, 3, 3]) torch.int64 cpu <class 'torch.Tensor'>\n"
     ]
    }
   ],
   "source": [
    "data_numpy = np.array([[[1,2,3], [3,4,5], [6,7,8]],\n",
    "                      [[11,12,13], [14,15,16], [17,18,19]],\n",
    "                      [[21,22,23], [23,24,25], [26,27,28]]])\n",
    "tensor_from_np = torch.from_numpy(data_numpy)\n",
    "\n",
    "display(tensor_from_np)\n",
    "\n",
    "print(tensor_from_np.shape, tensor_from_np.dtype, tensor_from_np.device, type(tensor_from_np))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "0b366d24-2ae8-4fe6-a20b-c3d362b75e8b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[[[[0.5690, 0.0818, 0.7334, 0.7479, 0.7470, 0.7807],\n",
       "           [0.3080, 0.5642, 0.0268, 0.6542, 0.9962, 0.1948],\n",
       "           [0.8360, 0.5335, 0.7966, 0.2066, 0.3203, 0.6581],\n",
       "           [0.0686, 0.6480, 0.4794, 0.2984, 0.3671, 0.0635],\n",
       "           [0.5211, 0.2838, 0.5029, 0.7513, 0.0535, 0.7766]],\n",
       "\n",
       "          [[0.1584, 0.7182, 0.8947, 0.7645, 0.1467, 0.5904],\n",
       "           [0.3381, 0.3275, 0.8389, 0.6606, 0.8481, 0.7248],\n",
       "           [0.1729, 0.2273, 0.8817, 0.0909, 0.9683, 0.8622],\n",
       "           [0.2807, 0.7360, 0.4525, 0.0498, 0.7388, 0.5148],\n",
       "           [0.7674, 0.5755, 0.8463, 0.8062, 0.0062, 0.4510]],\n",
       "\n",
       "          [[0.8714, 0.3873, 0.7940, 0.5704, 0.6458, 0.0063],\n",
       "           [0.2315, 0.4958, 0.8788, 0.1932, 0.2610, 0.6501],\n",
       "           [0.2683, 0.1105, 0.7179, 0.8703, 0.5799, 0.4031],\n",
       "           [0.3507, 0.7391, 0.1129, 0.3320, 0.5486, 0.8110],\n",
       "           [0.1462, 0.1957, 0.6390, 0.2085, 0.7570, 0.1197]],\n",
       "\n",
       "          [[0.5360, 0.2915, 0.2596, 0.4052, 0.4653, 0.5107],\n",
       "           [0.4753, 0.2606, 0.0169, 0.3406, 0.9332, 0.3487],\n",
       "           [0.3182, 0.4114, 0.9092, 0.5990, 0.7239, 0.1777],\n",
       "           [0.2233, 0.8022, 0.6494, 0.7127, 0.5085, 0.5390],\n",
       "           [0.0321, 0.5123, 0.6207, 0.7074, 0.9923, 0.5711]],\n",
       "\n",
       "          [[0.1151, 0.1589, 0.6328, 0.2897, 0.3956, 0.6714],\n",
       "           [0.5631, 0.7193, 0.1173, 0.8521, 0.6831, 0.0255],\n",
       "           [0.2249, 0.7645, 0.5405, 0.4956, 0.8240, 0.9725],\n",
       "           [0.4877, 0.3196, 0.7030, 0.5901, 0.2159, 0.9467],\n",
       "           [0.1094, 0.8947, 0.3039, 0.7418, 0.6376, 0.4769]]],\n",
       "\n",
       "\n",
       "         [[[0.7620, 0.5780, 0.5923, 0.2693, 0.4445, 0.1172],\n",
       "           [0.0072, 0.2625, 0.6865, 0.3940, 0.5773, 0.9040],\n",
       "           [0.2159, 0.4749, 0.3459, 0.5870, 0.9145, 0.9537],\n",
       "           [0.0074, 0.9831, 0.1544, 0.4351, 0.8100, 0.4146],\n",
       "           [0.8459, 0.0296, 0.9911, 0.7101, 0.9478, 0.1313]],\n",
       "\n",
       "          [[0.4194, 0.6168, 0.4422, 0.0818, 0.6151, 0.2729],\n",
       "           [0.1708, 0.8131, 0.5210, 0.9367, 0.6314, 0.8646],\n",
       "           [0.0769, 0.9932, 0.9064, 0.2458, 0.2795, 0.7844],\n",
       "           [0.2738, 0.9029, 0.6704, 0.5688, 0.4230, 0.0974],\n",
       "           [0.8497, 0.4932, 0.0820, 0.7535, 0.5640, 0.3216]],\n",
       "\n",
       "          [[0.1595, 0.2929, 0.1355, 0.6633, 0.8658, 0.3298],\n",
       "           [0.7610, 0.9301, 0.3377, 0.6525, 0.2693, 0.4205],\n",
       "           [0.2017, 0.1527, 0.7875, 0.1935, 0.0603, 0.2100],\n",
       "           [0.9525, 0.7197, 0.0064, 0.6737, 0.0190, 0.2430],\n",
       "           [0.3812, 0.7376, 0.6708, 0.5810, 0.9251, 0.6159]],\n",
       "\n",
       "          [[0.6209, 0.7409, 0.3853, 0.2817, 0.4338, 0.3074],\n",
       "           [0.9430, 0.4277, 0.8283, 0.5079, 0.9923, 0.6240],\n",
       "           [0.4728, 0.7408, 0.6756, 0.1341, 0.2738, 0.5398],\n",
       "           [0.0733, 0.7631, 0.2829, 0.1392, 0.9762, 0.5258],\n",
       "           [0.0463, 0.8203, 0.1467, 0.5401, 0.1906, 0.6720]],\n",
       "\n",
       "          [[0.3144, 0.6038, 0.0913, 0.7897, 0.7737, 0.1120],\n",
       "           [0.2468, 0.1786, 0.3816, 0.9656, 0.0394, 0.6034],\n",
       "           [0.7585, 0.1583, 0.6215, 0.8246, 0.8537, 0.5356],\n",
       "           [0.5297, 0.4934, 0.1610, 0.0481, 0.1927, 0.4575],\n",
       "           [0.9943, 0.2196, 0.0778, 0.0457, 0.8030, 0.5395]]],\n",
       "\n",
       "\n",
       "         [[[0.2351, 0.3475, 0.1979, 0.4863, 0.8171, 0.9457],\n",
       "           [0.2328, 0.1149, 0.9319, 0.1839, 0.6950, 0.5457],\n",
       "           [0.6863, 0.8637, 0.6924, 0.5335, 0.5910, 0.0442],\n",
       "           [0.8044, 0.7754, 0.7807, 0.2773, 0.1944, 0.1107],\n",
       "           [0.1255, 0.2262, 0.8963, 0.9104, 0.0758, 0.6419]],\n",
       "\n",
       "          [[0.2862, 0.8198, 0.9081, 0.7025, 0.3676, 0.0933],\n",
       "           [0.1452, 0.4689, 0.5730, 0.1897, 0.3914, 0.2227],\n",
       "           [0.7436, 0.1827, 0.7952, 0.8107, 0.4611, 0.0667],\n",
       "           [0.3031, 0.0379, 0.8846, 0.7999, 0.9021, 0.1224],\n",
       "           [0.9061, 0.5505, 0.4430, 0.3552, 0.8414, 0.2101]],\n",
       "\n",
       "          [[0.7902, 0.4496, 0.2165, 0.5224, 0.0750, 0.4903],\n",
       "           [0.4701, 0.0314, 0.0216, 0.2941, 0.3868, 0.8590],\n",
       "           [0.4929, 0.2024, 0.3167, 0.6420, 0.5110, 0.6051],\n",
       "           [0.5365, 0.9722, 0.2717, 0.0691, 0.6148, 0.7131],\n",
       "           [0.0496, 0.9551, 0.3977, 0.8924, 0.1283, 0.2129]],\n",
       "\n",
       "          [[0.3257, 0.5385, 0.0185, 0.1130, 0.4171, 0.7757],\n",
       "           [0.3855, 0.3367, 0.4247, 0.9121, 0.6132, 0.7952],\n",
       "           [0.5345, 0.2594, 0.0156, 0.3323, 0.6320, 0.9120],\n",
       "           [0.2865, 0.2976, 0.6089, 0.5211, 0.0354, 0.0054],\n",
       "           [0.0834, 0.3771, 0.4513, 0.9599, 0.8100, 0.6825]],\n",
       "\n",
       "          [[0.4355, 0.7452, 0.5151, 0.9068, 0.1685, 0.2876],\n",
       "           [0.4072, 0.1000, 0.6223, 0.1481, 0.5194, 0.7450],\n",
       "           [0.3203, 0.3383, 0.6303, 0.3334, 0.3579, 0.5783],\n",
       "           [0.3078, 0.5749, 0.3272, 0.4734, 0.6428, 0.5639],\n",
       "           [0.3809, 0.5775, 0.4267, 0.3730, 0.2306, 0.6900]]],\n",
       "\n",
       "\n",
       "         [[[0.4435, 0.7273, 0.9978, 0.5624, 0.6455, 0.7977],\n",
       "           [0.2039, 0.2662, 0.3527, 0.3332, 0.4281, 0.6700],\n",
       "           [0.2563, 0.1378, 0.3496, 0.0021, 0.9357, 0.0085],\n",
       "           [0.2698, 0.8956, 0.8696, 0.3177, 0.9271, 0.5878],\n",
       "           [0.1093, 0.9963, 0.4021, 0.2079, 0.8145, 0.4354]],\n",
       "\n",
       "          [[0.5467, 0.3264, 0.4389, 0.8007, 0.7872, 0.7538],\n",
       "           [0.4466, 0.3183, 0.3809, 0.7538, 0.0511, 0.8141],\n",
       "           [0.9675, 0.2374, 0.6108, 0.6346, 0.2733, 0.9002],\n",
       "           [0.5782, 0.7213, 0.5490, 0.2686, 0.8594, 0.8176],\n",
       "           [0.6667, 0.8956, 0.7661, 0.7222, 0.5599, 0.3288]],\n",
       "\n",
       "          [[0.1727, 0.1175, 0.2740, 0.5631, 0.5024, 0.0152],\n",
       "           [0.5858, 0.1613, 0.1141, 0.8733, 0.3127, 0.8979],\n",
       "           [0.3356, 0.8419, 0.9340, 0.7165, 0.3161, 0.8258],\n",
       "           [0.7683, 0.1880, 0.5016, 0.8495, 0.0347, 0.5900],\n",
       "           [0.5613, 0.8060, 0.0090, 0.3577, 0.3578, 0.8233]],\n",
       "\n",
       "          [[0.1721, 0.6099, 0.6340, 0.8570, 0.5290, 0.7142],\n",
       "           [0.8101, 0.5060, 0.6111, 0.6143, 0.7970, 0.6504],\n",
       "           [0.8791, 0.3703, 0.0147, 0.0463, 0.4912, 0.7744],\n",
       "           [0.5908, 0.1187, 0.6703, 0.9682, 0.0733, 0.9634],\n",
       "           [0.1844, 0.7810, 0.3504, 0.8297, 0.3767, 0.0577]],\n",
       "\n",
       "          [[0.4871, 0.8573, 0.4967, 0.5330, 0.4015, 0.4307],\n",
       "           [0.8497, 0.0849, 0.0490, 0.7890, 0.9273, 0.5077],\n",
       "           [0.9272, 0.8657, 0.5616, 0.1833, 0.1335, 0.6807],\n",
       "           [0.3011, 0.3671, 0.3116, 0.2501, 0.6404, 0.9899],\n",
       "           [0.1718, 0.9104, 0.1689, 0.0568, 0.3139, 0.7755]]],\n",
       "\n",
       "\n",
       "         [[[0.4388, 0.8003, 0.2868, 0.6856, 0.0066, 0.9214],\n",
       "           [0.0271, 0.5904, 0.9005, 0.7069, 0.5843, 0.8414],\n",
       "           [0.9279, 0.8728, 0.7647, 0.1624, 0.7691, 0.2994],\n",
       "           [0.9560, 0.6508, 0.4822, 0.8511, 0.8914, 0.9182],\n",
       "           [0.7272, 0.4529, 0.4574, 0.0938, 0.2953, 0.2638]],\n",
       "\n",
       "          [[0.8194, 0.0612, 0.7294, 0.7751, 0.7340, 0.9783],\n",
       "           [0.6819, 0.7310, 0.2631, 0.8986, 0.9552, 0.0520],\n",
       "           [0.1591, 0.1627, 0.8979, 0.5033, 0.6288, 0.6003],\n",
       "           [0.0517, 0.8572, 0.3523, 0.8932, 0.6971, 0.0093],\n",
       "           [0.0913, 0.7515, 0.5635, 0.0215, 0.2292, 0.4333]],\n",
       "\n",
       "          [[0.4650, 0.5643, 0.7392, 0.5785, 0.9746, 0.0134],\n",
       "           [0.9034, 0.1352, 0.0516, 0.9440, 0.1498, 0.8642],\n",
       "           [0.7673, 0.4653, 0.6351, 0.5943, 0.7106, 0.4584],\n",
       "           [0.6181, 0.5252, 0.1373, 0.5253, 0.9965, 0.7211],\n",
       "           [0.5094, 0.4422, 0.3236, 0.5825, 0.9391, 0.9403]],\n",
       "\n",
       "          [[0.2891, 0.1037, 0.8763, 0.3902, 0.0420, 0.7157],\n",
       "           [0.0756, 0.0795, 0.1350, 0.3163, 0.2712, 0.2429],\n",
       "           [0.6149, 0.0011, 0.4567, 0.1563, 0.5973, 0.2504],\n",
       "           [0.9211, 0.6140, 0.4578, 0.5899, 0.7853, 0.2340],\n",
       "           [0.2220, 0.5499, 0.1630, 0.8209, 0.5037, 0.7810]],\n",
       "\n",
       "          [[0.2485, 0.4541, 0.1068, 0.9340, 0.0363, 0.9055],\n",
       "           [0.3677, 0.0860, 0.1095, 0.2002, 0.3394, 0.8312],\n",

In [546]:
# Logical operations, are effectively element-wise boolean operations on boolean tensors containing only "True" or "False"
# torch.logical_and(a,b) - it will output True only if both "a" AND "b" are the same, either True or False. 
# if at least one of them is different, then it will output False.
# torch.logical_or(a,b) - will output True of either of one boolean tensors have value True, and will output False only if
# both of the values of tensors are False.
# torch.logical_not(a) - takes only one tensor, and will output the exact opposite of the input_values, for instance,
# if input of given element is True, then it becomes False, and vice versa
# torch.logical_xor(a,b) - will output True only if both element values are not the same, otherwise if both values are the same
# it will output False, it is the reverse of what AND logical operation does which for statement to be True both must be equal and if not
# then will show False

x_1 = torch.ones(3,4)
x_2 = torch.zeros(3,4)
a = x_1 != x_2
b = x_1 == x_2
display(a,b)
print("\nLogical AND operation:\n", torch.logical_and(a, b))
print("\nLogical OR operation:\n", torch.logical_or(a, b))
print("\nLogical NOT operation of tensor A:\n", torch.logical_not(a))
print("\nLogical NOT operation of tensor B:\n", torch.logical_not(b))

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Logical AND operation:
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Logical OR operation:
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Logical NOT operation of tensor A:
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Logical NOT operation of tensor B:
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [547]:
import copy

#commented since the intention for boolean tensors not to change but rather stay the same with the help of copy.deepcopy()
#x_1 = torch.rand(3,4)
#x_2 = torch.rand(3,4)

x_1_1 = copy.deepcopy(x_1)
x_2_2 = copy.deepcopy(x_2)

a = x_1_1 >= x_2_2
b = x_1_1 <= x_2_2
display(a,b)

print("\nLogical AND operation:\n", torch.logical_and(a,b))
print("\nLogical OR operation:\n", torch.logical_or(a,b))
print("\nLogical NOT operation for tensor A:\n", torch.logical_not(a))
print(f"\nLogical NOT operation for tensor B:\n{torch.logical_not(b)}")
print(f"\nLogical XOR operation:\n{torch.logical_xor(a,b)}")

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Logical AND operation:
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Logical OR operation:
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Logical NOT operation for tensor A:
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Logical NOT operation for tensor B:
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Logical XOR operation:
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [585]:
import copy

#x_1 = torch.randn(4,7)
#x_2 = torch.randn(4,7)
x_1 = copy.deepcopy(x_1)
x_2 = copy.deepcopy(x_2)
a = x_1 > x_2
b = x_1 < x_2
c = x_1 == x_2
d = x_1 != x_2
f = copy.deepcopy(a)
display(a,b,c,d)
print("\nLogical AND operator:\n", torch.logical_and(b,d))
print("\nLogical OR operator:\n", torch.logical_or(b,c))
print("\nLogical NOT operator:\n", torch.logical_not(torch.logical_or(b,c)))
print("\nLogical XOR operator:\n", torch.logical_xor(d,b))
display(a.dtype, b.dtype, c.dtype, d.dtype, type(a), type(b), type(c), type(d))
print(f, f.dtype)
display(f.int(), f.dtype)

tensor([[ True,  True,  True,  True,  True, False,  True],
        [False, False, False, False,  True,  True, False],
        [False,  True, False,  True,  True,  True, False],
        [False,  True,  True, False,  True,  True,  True]])

tensor([[False, False, False, False, False,  True, False],
        [ True,  True,  True,  True, False, False,  True],
        [ True, False,  True, False, False, False,  True],
        [ True, False, False,  True, False, False, False]])

tensor([[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False]])

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])

Logical AND operator:
 tensor([[False, False, False, False, False,  True, False],
        [ True,  True,  True,  True, False, False,  True],
        [ True, False,  True, False, False, False,  True],
        [ True, False, False,  True, False, False, False]])

Logical OR operator:
 tensor([[False, False, False, False, False,  True, False],
        [ True,  True,  True,  True, False, False,  True],
        [ True, False,  True, False, False, False,  True],
        [ True, False, False,  True, False, False, False]])

Logical NOT operator:
 tensor([[ True,  True,  True,  True,  True, False,  True],
        [False, False, False, False,  True,  True, False],
        [False,  True, False,  True,  True,  True, False],
        [False,  True,  True, False,  True,  True,  True]])

Logical XOR operator:
 tensor([[ True,  True,  True,  True,  True, False,  True],
        [False, False, False, False,  True,  True, False],
        [False,  True, False,  True,  True,  True, False],
        [False,  True,  True, False,  True,  True,  True]])

torch.bool

torch.bool

torch.bool

torch.bool

torch.Tensor

torch.Tensor

torch.Tensor

torch.Tensor

tensor([[ True,  True,  True,  True,  True, False,  True],
        [False, False, False, False,  True,  True, False],
        [False,  True, False,  True,  True,  True, False],
        [False,  True,  True, False,  True,  True,  True]]) torch.bool

tensor([[1, 1, 1, 1, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 1, 1, 0],
        [0, 1, 1, 0, 1, 1, 1]], dtype=torch.int32)

torch.bool

In [62]:
# Again for element-wise operations the shape or order which represents the number of rows and columns 
# must be the same for both tensors if tensor A is of shape(4,9), then tensor B -which is being used
# for element-wise operations with tensor A - must also be of shape(4,9). shape can be both square and rectangular
import copy

a = torch.ones(3,4)
b = torch.randn(3,4)
x = a >= b
f = copy.deepcopy(x.int())
display(x, x.dtype)
display(x.int())
display(x.float())
display(f.bool())

# torch.logical_and(a,b) - True if both elements are the same 
# torch.logical_or(a,b) - True if at least one of the elements is True
# torch.logical_not(a) - returns the exact opposite, if it was True, then it turns to False
# torch.logical_xor(a,b) - True if both are not the same

tensor([[ True,  True,  True,  True],
        [ True,  True,  True, False],
        [ True, False, False,  True]])

torch.bool

tensor([[1, 1, 1, 1],
        [1, 1, 1, 0],
        [1, 0, 0, 1]], dtype=torch.int32)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 0.],
        [1., 0., 0., 1.]])

tensor([[ True,  True,  True,  True],
        [ True,  True,  True, False],
        [ True, False, False,  True]])

# Relationship with Numpy

In [135]:
import numpy as np

data_np = np.array([[1,2,3],[4,5,6]], dtype=np.float32) # numpy.ndarray object type
data_tn = torch.from_numpy(data_np) # torch.Tensor object type

display(data_np, type(data_np), data_np.dtype, data_np.device)
display(data_tn, type(data_tn), data_tn.dtype, data_tn.device)

# One thing to note, if changes made to ndarray, it will reflect in tensor as well
# Because, in this case, since tensor is created from ndarray, they are both stored in the same CPU location
# If you do not want to create duplicates of ndarray from tensor, then do not use torch.from_numpy(), 
# but instead use simple torch.tensor(), because change in one will not reflect in another

a_np = np.array([[1,2,3],[4,5,6]])
a_tn_from_np = torch.from_numpy(a_np)
a_tn = torch.tensor(a_np)

display(a_np, a_tn_from_np)
a_np[1,2] = 99
display(a_np,a_tn_from_np)
a_tn_from_np[0,1] = 226
display(a_np, a_tn_from_np)
# Notice that change in ndarray, causes the same change in tensor
# However, when using simple torch.tensor() instead of torch.from_numpy(), does cause the tensor to change if ndarray is changed
# because now, they are stored in different CPU locations, but with from_numpy(), they are stored in the same CPU location

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

numpy.ndarray

dtype('float32')

'cpu'

tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.Tensor

torch.float32

device(type='cpu')

array([[1, 2, 3],
       [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

array([[ 1,  2,  3],
       [ 4,  5, 99]])

tensor([[ 1,  2,  3],
        [ 4,  5, 99]])

array([[  1, 226,   3],
       [  4,   5,  99]])

tensor([[  1, 226,   3],
        [  4,   5,  99]])

In [141]:
# If you do not want a change to reflect if either of one is modified, then do not use torch.from_numpy()
# use a simple torch.tensor() instead
# We can also convert PyTorch tensors into Numpy ndarrays using .numpy() method, but again in this way
# they both will point to the same memory location, cause change in one to be reflected in the other

cpu_tensor = torch.tensor([[4,5,6],[11,12,13]])
np_from_tn = cpu_tensor.numpy()
print(f"{cpu_tensor}\n{type(cpu_tensor)}\n")
print(f"{np_from_tn}\n{type(np_from_tn)}\n")

cpu_tensor[1,1] = 144
display(cpu_tensor, np_from_tn)
np_from_tn[1,2] = 169
display(cpu_tensor, np_from_tn)
# See, if ndarray is modified, so does tensor, and vice versa
# If you do not want this behaviour, then consider in this case using copy.deepcopy()

tensor([[ 4,  5,  6],
        [11, 12, 13]])
<class 'torch.Tensor'>

[[ 4  5  6]
 [11 12 13]]
<class 'numpy.ndarray'>

tensor([[  4,   5,   6],
        [ 11, 144,  13]])

array([[  4,   5,   6],
       [ 11, 144,  13]])

tensor([[  4,   5,   6],
        [ 11, 144, 169]])

array([[  4,   5,   6],
       [ 11, 144, 169]])

In [155]:
# .numpy() method only works for tensors stored on CPU, meaning torch.tensor().device must show CPU for
# conversion from tensor to numpy to actually work, if tensor is on GPU, then first move it to CPU
# by using method .cpu() and then use .numpy()

if torch.cuda.is_available():
    gpu_tensor_1 = torch.tensor([[4,5,6],[8,9,0]], device='cuda')
    gpu_tensor_2 = torch.randn(4,8)
    print(f"Tensors stored on GPU:\n{gpu_tensor_1}\n{gpu_tensor_2}")

    # Change the tensor memory location from GPU to CPU, in order for numpy conversion to work
    # because numpy ndarrays can only be stored and used on CPU only
    from_gpu_to_cpu_tensor_1 = gpu_tensor_1.cpu()
    from_gpu_to_cpu_tensor_2 = gpu_tensor_2.cpu()
    print(f"Tensors moved to CPU from GPU:\n{from_gpu_to_cpu_tensor_1}\n{from_gpu_to_cpu_tensor_2}")

    tn_to_np_1 = from_gpu_to_cpu_tensor_1.numpy()
    tn_to_np_2 = from_gpu_to_cpu_tensor_2.numpy()
    print(f"Successfuly conversion from tensor to numpy:\n{tn_to_np_1}\n{tn_to_np_2}")
else:
    print("\nCuda not available, conversion failed.")

Cuda not available, conversion failed.

In [158]:
# MPS GPU acceleration on Mac M-series is alternative for CUDA GPU acceleration
# MPS - Metal Performance Shaders
display(torch.backends.mps.is_available())
display(torch.backends.mps.is_built())

True

True

In [159]:
display(torch.cuda.is_available())

False

In [196]:
if torch.backends.mps.is_available():
    data_tn = torch.randn((4,6), device="mps")
    print(f"\nTensor stored in {data_tn.device} :\n{data_tn}\n")

    # Conversion to CPU from GPU
    tn_to_cpu = data_tn.cpu()
    print(f"Tensor stored in {tn_to_cpu.device} :\n{tn_to_cpu}")

    # From Tensor to Numpy ndarray
    tn_to_np = tn_to_cpu.numpy()
    print(f"From tensor to {type(tn_to_np)}:\n{tn_to_np}")
else:
    print("MPS is not available, because current PyTorch was not built with MPS enabled")

# Attempting to convert Tensors (stored on GPU) to Numpy ndarrays, will result in error

Tensor stored in mps:0 :
tensor([[ 0.0811,  0.1007, -1.5628,  0.8233,  2.2584,  1.0718],
        [ 0.1500,  0.8188, -1.5844,  0.8607,  0.5774,  0.9538],
        [-0.6257,  1.2679, -0.4052, -0.7668, -1.0988,  0.1977],
        [ 1.0082,  0.8887, -0.6935, -1.2598, -0.7664,  0.3295]],
       device='mps:0')

Tensor stored in cpu :
tensor([[ 0.0811,  0.1007, -1.5628,  0.8233,  2.2584,  1.0718],
        [ 0.1500,  0.8188, -1.5844,  0.8607,  0.5774,  0.9538],
        [-0.6257,  1.2679, -0.4052, -0.7668, -1.0988,  0.1977],
        [ 1.0082,  0.8887, -0.6935, -1.2598, -0.7664,  0.3295]])
From tensor to <class 'numpy.ndarray'>:
[[ 0.08106023  0.10071743 -1.5628318   0.8232865   2.2583804   1.071765  ]
 [ 0.15002526  0.81876004 -1.5844166   0.8607232   0.5773765   0.9538122 ]
 [-0.62565416  1.2679352  -0.40515414 -0.76682585 -1.0988053   0.19771942]
 [ 1.0082097   0.8886786  -0.69345546 -1.2597829  -0.7663796   0.32948285]]

In [186]:
print(torch.backends.mps.is_available()) # checks if MPS acceleration is available, since it can have limited memory size
print(torch.backends.mps.is_built()) # checks if current PyTorch install was built with MPS enabled 
# As of my knowledge, MPS may not be available if Mac is intel-based, or due to old MacOS version 
# or simply MPS is not enabled, hence need to enable it or install corresponding PyTorch with MPS-enabled

True
True

In [188]:
x = torch.rand(4,5)
display(x.device)
# Looks like as of now, by default configurations, variables are stored on CPU

device(type='cpu')

In [213]:
"""
    The ability to convert tensors to numpy and vice versa is critical, since at the initial step
    I might want to work with NumPy ndarrays for data loading and processing and leveraging libraries
    built using NumPy ndarrays. Then when it is time for building or training the neural networks
    I will need to convert NumPy ndarrays to PyTorch tensors in order to access GPU/MPS acceleration.
    Likewise, the outputs of the model (which are tensors), can be converted back to NumPy ndarrays for
    data analysis and visualization using matplotlib or seaborn.
    
"""

# Remember that torch.from_numpy(ndarray_as_input), results in both tensor and ndarray having the same CPU location in memory
# hence changing one, will modify the other as well. Likewise, converting torch.tensor(..., device="cpu") given that it is in CPU,
# converting tensor to numpy using torch.tensor().numpy() by using .numpy() will result in changes being reflected for both.
# Make sure that tensor's location is changed from GPU/MPS to CPU, before using .numpy() since ndarrays can be used on CPU only,
# otherwise the error will show up.

import copy

if torch.backends.mps.is_available():
    a = torch.randn((4,5), device="mps")
    b = torch.rand((3,4), device="mps")
    c = torch.ones((6,7), device="mps")
    d = torch.zeros((2,8), device="mps")
    print(f"\nTensors are stored in a: {a.device}, b: {b.device}, c: {c.device}, d: {d.device}\nObject type is {type(a)}")

    # with .cpu command which is effectively being used for torch.tensor().cpu()
    # changes the memory location of objects from GPU/MPS to CPU
    a_cpu = a.cpu()
    b_cpu = b.cpu()
    c_cpu = c.cpu()
    d_cpu = d.cpu()
    print(f"Tensors are stored in a: {a.device}, b: {b.device}, c: {c.device}, d: {d.device}")

    # If we want both ndarray and tensors be in the same CPU location, hence changes being reflect then do the following:
    a_np_ref = a_cpu.numpy()
    b_np_ref = b_cpu.numpy()
    c_np_ref = c_cpu.numpy()
    d_np_ref = d_cpu.numpy()
    print(f"Tensors are converted to {type(a_np_ref)}")

    c_cpu[2,3] = 789
    display(c_cpu, c_np_ref) # changes are reflect in both
    
    # If we do not want ndarray and tensors have the same CPU location and want to avoid change in one, cause change in another
    # , then do the following:
    a_np = copy.deepcopy(a_np_ref)
    b_np = copy.deepcopy(b_np_ref)
    c_np = copy.deepcopy(c_np_ref)
    d_np = copy.deepcopy(d_np_ref)

    d_cpu[1,4] = 567 # changing tensor
    display(d_cpu,d_np)
    d_np[1, 3] = 888 # changing ndarray
    display(d_cpu,d_np)

else:
    print("\nMPS is not available because the current PyTorch install was not built with MPS enabled or the MacOS version is old\
    or this Mac is intel-based.")

Tensors are stored in a: mps:0, b: mps:0, c: mps:0, d: mps:0
Object type is <class 'torch.Tensor'>
Tensors are stored in a: mps:0, b: mps:0, c: mps:0, d: mps:0
Tensors are converted to <class 'numpy.ndarray'>

tensor([[  1.,   1.,   1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1., 789.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.,   1.,   1.]])

array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1., 789.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.]], dtype=float32)

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0., 567.,   0.,   0.,   0.]])

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0., 567.,   0.,   0.,   0.]])

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 888.,   0.,   0.,   0.,   0.]], dtype=float32)

In [253]:
x = torch.randn(3,4)
display(x.device)

# use .to() method in order to move the variables/models from CPU to GPU and vice versa
device_cuda = torch.device("cuda" if torch.cuda.is_available() else "cpu") # since no cuda then replace it with mps
device_mps = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
x = x.to(device_mps)
display(x.device)

# Likewise we can also move models from CPU to GPU/MPS model.to(torch.device("cuda"))

x_1 = torch.rand(5,8)
display(x_1.device)

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
x_1 = x_1.to(device)
display(x_1.device)

x_1 = x_1.cpu()
display(x_1.device)
x_np = x_1.numpy()
display(type(x_np))

device(type='cpu')

device(type='mps', index=0)

device(type='cpu')

device(type='mps', index=0)

device(type='cpu')

numpy.ndarray

In [260]:
a = torch.rand(5,6)
display(a.device)
device_cuda = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device_mps = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
a_cuda = a.to(device_cuda)
a_mps = a.to(device_mps)
display(a_cuda.device, a_mps.device)

device(type='cpu')

device(type='cpu')

device(type='mps', index=0)

In [299]:
[torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]

x = torch.randn(4,4)
print(x.device)
print(x.is_cpu)
print(x.is_cuda)

cpu
True
False

In [386]:
# list comprehension
a = [i**2 for i in range(5)]
b = [i+10 for i in range(9)]
c = [i+1e-10 for i in range(1,4,1)]
print(a, b, c)

display(1e-3)
display(9e-3)

[torch.cuda.get_device_name(k) for k in range(torch.cuda.device_count())]
device = torch.device("cuda" if torch.backends.mps.is_available() and torch.cuda.is_available() else "cpu")
display(device)

[0, 1, 4, 9, 16] [10, 11, 12, 13, 14, 15, 16, 17, 18] [1.0000000001, 2.0000000001, 3.0000000001]

0.001

0.009

device(type='cpu')

In [4]:
import timeit

timeit.default_timer() # shows in seconds the current time

x = torch.ones((4,5), dtype=torch.int32)
display(x, x.dtype)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

torch.int32

# Practice

In [14]:
# Below are various ways to check GPU availability, with list comprehension method being the shortets code-wise

import torch 
import numpy as np

print(f"PyTorch version: {torch.__version__}")

if torch.cuda.is_available():
    print(f"Device name: {torch.cuda.get_device_name(0)}")
    print(f"Devices name: {[torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]}")

    device = torch.device("cuda")
else:
    print("GPU is not available")
    device = torch.device("cpu")

device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(device)

PyTorch version: 2.5.1
GPU is not available
mps

In [10]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.mps.is_available():
    device = torch.device("mps")
else:
    print("CUDA/MPS is not available because it is either not enabled with PyTorch install or this machine does not have CUDA/MPS \
    compatible GPU. Therefore switching to CPU.")
    device = torch.device("cpu")

print(device)

PyTorch version: 2.5.1
mps

In [20]:
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(device)

mps

In [32]:
# Some tensors operations

data_list = [[3,4,5],[0,2,6]]
x = torch.tensor(data_list, device="mps:0")
display(x, x.dtype, x.device, x.shape)
x_1 = torch.tensor(data_list, dtype=torch.float32)
display(x_1, x_1.dtype, x_1.device, x_1.shape)
display(x_1.int(),x_1.bool(),x_1.float())

tensor([[3, 4, 5],
        [0, 2, 6]], device='mps:0')

torch.int64

device(type='mps', index=0)

torch.Size([2, 3])

tensor([[3., 4., 5.],
        [0., 2., 6.]])

torch.float32

device(type='cpu')

torch.Size([2, 3])

tensor([[3, 4, 5],
        [0, 2, 6]], dtype=torch.int32)

tensor([[ True,  True,  True],
        [False,  True,  True]])

tensor([[3., 4., 5.],
        [0., 2., 6.]])

In [76]:
a = torch.zeros(3,4)
b = torch.ones(3,5)
c = torch.rand(5,3)
d = torch.randn(3,4)
e = torch.arange(9)
display(a.T,b.T,c.T,d.T,e.T)

a_1 = torch.tensor([range(9)])
a_2 = torch.arange(8)
a_3 = torch.arange(0,8,2)
a_4 = torch.arange(-10,-20,-1)
display(a_1, a_2, a_3, a_4)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[0.2732, 0.6586, 0.2809, 0.8131, 0.4121],
        [0.2538, 0.6386, 0.6992, 0.0259, 0.0512],
        [0.8165, 0.8876, 0.3466, 0.1153, 0.2816]])

tensor([[-0.5081,  0.7981, -0.3126],
        [-1.6333, -0.1380,  0.9548],
        [ 0.2522, -0.6939, -0.1397],
        [-2.1123,  1.0102,  0.6103]])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

tensor([0, 1, 2, 3, 4, 5, 6, 7])

tensor([0, 2, 4, 6])

tensor([-10, -11, -12, -13, -14, -15, -16, -17, -18, -19])

In [111]:
# For matrix multiplication we can use either A @ B or torch.matmul(A,B)
# althoug note that (x, m) @ (m, y) that the column of first matrix must match row of second matrix
a = torch.ones(3,4)
b = torch.rand(3,4)
#y = a @ b
print(y)
#print(torch.matmul(a,b))
print(torch.add(a,b), a+b)
print(torch.sub(a,b), a-b)
print(torch.div(a,b), a/b)
print(torch.mul(a,b), a*b)
print(torch.pow(a,b), a**b)
print(torch.mean(a.float()))
print(torch.mean(b.float()))
print(torch.sum(a))
print(torch.sum(b))
print(torch.min(a))
print(torch.min(b))
print(torch.max(a))
print(torch.max(b))
print(torch.sqrt(a))
print(torch.sqrt(b))
print(torch.abs(b))
print(torch.abs(a))
print(torch.exp(a))
print(torch.exp(b))
print(torch.log(a.abs()))
print(torch.log(b.abs()))
print(a.add_(b))
print(a.sub_(b))
print(a.div_(b))
print(a.mul_(b))
print(a.pow_(b))

tensor([[2.0890, 1.0459, 1.6776, 1.7605, 2.3827, 2.4006, 2.8182],
        [2.0890, 1.0459, 1.6776, 1.7605, 2.3827, 2.4006, 2.8182],
        [2.0890, 1.0459, 1.6776, 1.7605, 2.3827, 2.4006, 2.8182]])
tensor([[1.3166, 1.0175, 1.1785, 1.6299],
        [1.5109, 1.0669, 1.3003, 1.8897],
        [1.5190, 1.7838, 1.4329, 1.6846]]) tensor([[1.3166, 1.0175, 1.1785, 1.6299],
        [1.5109, 1.0669, 1.3003, 1.8897],
        [1.5190, 1.7838, 1.4329, 1.6846]])
tensor([[0.6834, 0.9825, 0.8215, 0.3701],
        [0.4891, 0.9331, 0.6997, 0.1103],
        [0.4810, 0.2162, 0.5671, 0.3154]]) tensor([[0.6834, 0.9825, 0.8215, 0.3701],
        [0.4891, 0.9331, 0.6997, 0.1103],
        [0.4810, 0.2162, 0.5671, 0.3154]])
tensor([[ 3.1585, 57.2129,  5.6023,  1.5875],
        [ 1.9574, 14.9368,  3.3298,  1.1240],
        [ 1.9269,  1.2759,  2.3102,  1.4608]]) tensor([[ 3.1585, 57.2129,  5.6023,  1.5875],
        [ 1.9574, 14.9368,  3.3298,  1.1240],
        [ 1.9269,  1.2759,  2.3102,  1.4608]])
tensor([[0.3166, 0.0175, 0.1785, 0.6299],
        [0.5109, 0.0669, 0.3003, 0.8897],
        [0.5190, 0.7838, 0.4329, 0.6846]]) tensor([[0.3166, 0.0175, 0.1785, 0.6299],
        [0.5109, 0.0669, 0.3003, 0.8897],
        [0.5190, 0.7838, 0.4329, 0.6846]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor(1.)
tensor(0.4442)
tensor(12.)
tensor(5.3305)
tensor(1.)
tensor(0.0175)
tensor(1.)
tensor(0.8897)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.5627, 0.1322, 0.4225, 0.7937],
        [0.7148, 0.2587, 0.5480, 0.9432],
        [0.7204, 0.8853, 0.6579, 0.8274]])
tensor([[0.3166, 0.0175, 0.1785, 0.6299],
        [0.5109, 0.0669, 0.3003, 0.8897],
        [0.5190, 0.7838, 0.4329, 0.6846]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183, 2.7183]])
tensor([[1.3725, 1.0176, 1.1954, 1.8775],
        [1.6667, 1.0692, 1.3503, 2.4343],
        [1.6803, 2.1897, 1.5417, 1.9829]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[-1.1501, -4.0468, -1.7232, -0.4621],
        [-0.6716, -2.7038, -1.2029, -0.1169],
        [-0.6559, -0.2436, -0.8373, -0.3790]])
tensor([[1.3166, 1.0175, 1.1785, 1.6299],
        [1.5109, 1.0669, 1.3003, 1.8897],
        [1.5190, 1.7838, 1.4329, 1.6846]])
tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])
tensor([[ 3.1585, 57.2129,  5.6023,  1.5875],
        [ 1.9574, 14.9368,  3.3298,  1.1240],
        [ 1.9269,  1.2759,  2.3102,  1.4608]])
tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])
tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])

In [125]:
# matrix multiplication
a = torch.randn(4,5)
b = torch.rand(5,3)
print(a @ b)
#print(b @ a) # matrix multiplication is not commutative
print(torch.matmul(a,b))
#print(torch.matmul(b,a))

a_1 = torch.rand(2,9)
b_1 = torch.randn(9,5)
print(a_1 @ b_1)
print(torch.matmul(a_1, b_1))
display(a_1 * 3)
print(b_1 + 1)
display(b_1 - 10)
display(b_1 / 4)
display(b_1 ** 2)
print(id(a))
print(id(b))

tensor([[-2.2348, -2.1300, -2.0124],
        [-0.8307, -0.6297, -0.5578],
        [ 1.0247,  0.6327,  0.4816],
        [ 2.6537,  2.9586,  1.0045]])
tensor([[-2.2348, -2.1300, -2.0124],
        [-0.8307, -0.6297, -0.5578],
        [ 1.0247,  0.6327,  0.4816],
        [ 2.6537,  2.9586,  1.0045]])
tensor([[-2.0059, -1.9786,  1.9418,  0.6486, -1.0208],
        [-0.7881, -0.6209,  1.2929,  1.9759, -1.2086]])
tensor([[-2.0059, -1.9786,  1.9418,  0.6486, -1.0208],
        [-0.7881, -0.6209,  1.2929,  1.9759, -1.2086]])

tensor([[1.1166, 1.0423, 1.8062, 1.7092, 2.0117, 1.3892, 0.4268, 0.7326, 1.8988],
        [2.8019, 2.1994, 1.0522, 0.6768, 2.5155, 2.3751, 2.3687, 0.5885, 0.2601]])

tensor([[ 2.5791,  2.2930,  0.0651,  1.4913,  0.4913],
        [ 0.1671, -0.4124,  0.2346,  1.3057,  1.3856],
        [ 0.6891,  2.0036,  1.6641, -0.4641,  0.8951],
        [ 0.6300, -0.7139,  1.3866,  1.5974,  0.3811],
        [-0.6538,  0.7905,  3.0068,  1.9610,  0.6015],
        [ 1.5509,  0.7372,  2.2493,  2.2552,  0.3759],
        [ 0.8132,  0.8284,  0.9675,  0.8721,  1.1839],
        [-0.3596,  0.6334, -0.4825,  1.0931,  0.0532],
        [-0.0962, -0.9288,  1.5972,  0.4794,  1.3342]])

tensor([[ -8.4209,  -8.7070, -10.9349,  -9.5087, -10.5087],
        [-10.8329, -11.4124, -10.7654,  -9.6943,  -9.6144],
        [-10.3109,  -8.9964,  -9.3359, -11.4641, -10.1049],
        [-10.3700, -11.7139,  -9.6134,  -9.4026, -10.6189],
        [-11.6538, -10.2095,  -7.9932,  -9.0390, -10.3985],
        [ -9.4491, -10.2628,  -8.7507,  -8.7448, -10.6241],
        [-10.1868, -10.1716, -10.0325, -10.1279,  -9.8161],
        [-11.3596, -10.3666, -11.4825,  -9.9069, -10.9468],
        [-11.0962, -11.9288,  -9.4028, -10.5206,  -9.6658]])

tensor([[ 0.3948,  0.3232, -0.2337,  0.1228, -0.1272],
        [-0.2082, -0.3531, -0.1914,  0.0764,  0.0964],
        [-0.0777,  0.2509,  0.1660, -0.3660, -0.0262],
        [-0.0925, -0.4285,  0.0967,  0.1493, -0.1547],
        [-0.4134, -0.0524,  0.5017,  0.2402, -0.0996],
        [ 0.1377, -0.0657,  0.3123,  0.3138, -0.1560],
        [-0.0467, -0.0429, -0.0081, -0.0320,  0.0460],
        [-0.3399, -0.0917, -0.3706,  0.0233, -0.2367],
        [-0.2741, -0.4822,  0.1493, -0.1302,  0.0835]])

tensor([[2.4935e+00, 1.6718e+00, 8.7412e-01, 2.4140e-01, 2.5880e-01],
        [6.9371e-01, 1.9947e+00, 5.8590e-01, 9.3476e-02, 1.4871e-01],
        [9.6665e-02, 1.0072e+00, 4.4102e-01, 2.1435e+00, 1.0995e-02],
        [1.3690e-01, 2.9375e+00, 1.4946e-01, 3.5683e-01, 3.8298e-01],
        [2.7349e+00, 4.3877e-02, 4.0272e+00, 9.2347e-01, 1.5878e-01],
        [3.0349e-01, 6.9080e-02, 1.5608e+00, 1.5755e+00, 3.8949e-01],
        [3.4878e-02, 2.9460e-02, 1.0565e-03, 1.6359e-02, 3.3828e-02],
        [1.8485e+00, 1.3440e-01, 2.1978e+00, 8.6640e-03, 8.9646e-01],
        [1.2017e+00, 3.7201e+00, 3.5668e-01, 2.7107e-01, 1.1168e-01]])

6356706384
6356649120

In [131]:
a = torch.rand(3,4)
b = torch.rand(3,4)
print(f"Memory address ID before in-place operation: {id(a)}")
print(a.add_(b))
print(f"After in-place operation: {id(a)}")
display(id(a) == id(a))

data_np = np.array([[1,2,3],[5,6,7]])
data_tn_np = torch.from_numpy(data_np)
data_tn = torch.tensor(data_np)
display(id(data_np))
display(id(data_tn_np))
display(id(data_tn))

print(f"Tensors from Numpy using torch.from_numpy(), have_same_memory_location: {id(data_np) == id(data_tn_np)}")
print(f"Tensors from Numpy using torch.tensor(), have_same_memory_location: {id(data_np) == id(data_tn)}")

Memory address ID before in-place operation: 6356530256
tensor([[0.7734, 1.9098, 1.1382, 0.9781],
        [0.7951, 0.9700, 1.2751, 0.8907],
        [0.7296, 0.6490, 0.6124, 0.9672]])
After in-place operation: 6356530256

True

6356641520

6356531456

6359090816

Tensors from Numpy using torch.from_numpy(), have_same_memory_location: False
Tensors from Numpy using torch.tensor(), have_same_memory_location: False

In [159]:
import numpy as np

data_np = np.array([[3,4,5],[1,2,3]])
data_tn_np = torch.from_numpy(data_np)
data_tn_np = data_tn_np.clone() 
# this helps to create a distinct copy of the tensor, so that any changes made to numpy will not reflect tensor
data_np[0,2] = 45

display(data_np, data_tn_np)

array([[ 3,  4, 45],
       [ 1,  2,  3]])

tensor([[3, 4, 5],
        [1, 2, 3]])

In [202]:
import copy

if torch.cuda.is_available() or torch.backends.mps.is_available():
    device = torch.device("cuda" if torch.cuda.is_available() else "mps")
    data_tn = torch.ones((3,4), device=device)
    display(data_tn.device, data_tn.is_cuda, data_tn.is_mps)

    data_tn = data_tn.cpu()
    display(data_tn.device)
    data_tn = data_tn.clone() # .clone() is available for tensors only, use copy.deepcopy() for numpy
    data_tn_np = data_tn.numpy()
    data_tn_np = copy.deepcopy(data_tn_np)
    data_tn[2,2] = 888
    display(data_tn, data_tn_np)
else:
    print("GPU/MPS acceleration is not available.")

device(type='mps', index=0)

False

True

device(type='cpu')

tensor([[  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.],
        [  1.,   1., 888.,   1.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [201]:
import numpy as np

ndarray_np = np.array([[4,5,6],[3,4,5]])
tn = torch.from_numpy(ndarray_np)
tn = tn.clone()
ndarray_np[1,2] = 999
tn[1,2] = 123
display(ndarray_np, tn)

tns = torch.tensor(ndarray_np)
tns[0,0] = 48
ndarray_np[0,0] = 56
display(tns, ndarray_np)

array([[  4,   5,   6],
       [  3,   4, 999]])

tensor([[  4,   5,   6],
        [  3,   4, 123]])

tensor([[ 48,   5,   6],
        [  3,   4, 999]])

array([[ 56,   5,   6],
       [  3,   4, 999]])

# Tensor indexing and slicing

In [21]:
import torch

a = torch.tensor([12,3,4,5,98,56])
a_ = a[0].item() # If we use .item() then it will return a strandard Python dtype
print(a_, type(a_)) # Even though it returns a single value scalar, 0-dimensional, it still shows as torch.Tenso
a_1 = a[-1]
a[2] = 457
display(a_1, a)
b = torch.arange(2,13,3)
display(b[-1])

12 <class 'int'>

tensor(56)

tensor([ 12,   3, 457,   5,  98,  56])

tensor(11)

In [42]:
a = torch.arange(0,100,3)
a_last = a[-1]
a_mid = a[15]
a[4] = 144
display(a_last, a_mid, a)
a_1 = a[5]
a_2 = a[6].item()
display(type(a_1), type(a_2))

tensor(99)

tensor(45)

tensor([  0,   3,   6,   9, 144,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87,  90,  93,  96,  99])

torch.Tensor

int

In [41]:
a = torch.rand(4,5)
col_1 = a[:,0]
row_1 = a[0]
col_2 = a[:,1]
row_3 = a[2]
scalar = a[0,0].item() #.item works for 0-dimensional tensors/scalars

display(a, col_1, row_1, col_2, row_3)
display(type(row_3), type(scalar))

tensor([[0.4805, 0.3837, 0.9928, 0.0972, 0.7391],
        [0.9631, 0.6443, 0.5999, 0.4072, 0.7218],
        [0.4677, 0.3635, 0.2099, 0.8057, 0.3101],
        [0.4876, 0.5296, 0.4929, 0.5418, 0.2990]])

tensor([0.4805, 0.9631, 0.4677, 0.4876])

tensor([0.4805, 0.3837, 0.9928, 0.0972, 0.7391])

tensor([0.3837, 0.6443, 0.3635, 0.5296])

tensor([0.4677, 0.3635, 0.2099, 0.8057, 0.3101])

torch.Tensor

float

In [100]:
a = torch.arange(10.0)
slice_1 = a[2:8]
slice_2 = a[::2]
slice_3 = a[:5]
slice_4 = a[5::2]
slice_5 = a[5:]
slice_6 = a[::]
s_slice = a[6].item()
display(slice_1, slice_2, slice_3, slice_4, slice_5, slice_6)
display(type(s_slice))

tensor([2., 3., 4., 5., 6., 7.])

tensor([0., 2., 4., 6., 8.])

tensor([0., 1., 2., 3., 4.])

tensor([5., 7., 9.])

tensor([5., 6., 7., 8., 9.])

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

float

In [103]:
# We can perform indexing with boolean tensors, where only values correspondin to True will be returned
# This is called boolean masking where instead of integer values acting as index for capturing specific values within the tensor
# We are using boolean tensor containing only True and False, based on a given condition
# Boolean tensor can be derived from the original tensor, thus their shapes will be equal and must be equal for boolean masking to work
# Boolean masking/indexing, does not preserve the shape when values are returned unlike slicing which does preserve the shape
# of original tensor, Boolean masking/indexing will also make a distinct copy of original tensor, therefore no changes will be reflected

a = torch.tensor([[3,4,5],[6,7,8],[1,2,9]])
b = torch.ones(3,3)
c = a > b
display(c)
y = a[c]
display(y)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False,  True,  True]])

tensor([3, 4, 5, 6, 7, 8, 2, 9])

In [107]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
mask = a > 4
print(mask.dtype)
output = a[mask] # Boolean tensor is provided as an index, and only values corresponding to True in index positions will be returned
print(output)

mask_2 = a < 5
print(mask_2) # Boolean Tensor
print(a[mask_2])

torch.bool
tensor([5, 6, 7, 8, 9])
tensor([[ True,  True,  True],
        [ True, False, False],
        [False, False, False]])
tensor([1, 2, 3, 4])

In [109]:
# We can also modify the values based on condition
a[a <= 4] = 0 # all the values below 4 are now 0, similar how ReLu works
print(a)

tensor([[0, 0, 0],
        [0, 5, 6],
        [7, 8, 9]])

In [230]:
x = torch.randn(5,7)
mask = x > 1
y = x[mask]
x[x >= 1] = 1
display(y)
display(x)

tensor([1.6515, 1.2300, 1.3310, 1.7905, 1.6108])

tensor([[-9.7886e-02, -8.6619e-01, -6.4920e-01,  4.9512e-01,  3.4835e-01,
          7.6029e-01,  1.0000e+00],
        [ 1.0000e+00, -1.0876e+00,  9.3101e-01, -2.0407e-01, -4.8372e-01,
          4.8101e-01,  6.9200e-01],
        [-1.4987e-01,  2.8305e-01, -3.4163e-01,  9.8276e-01,  1.0000e+00,
          6.2071e-01,  1.0000e+00],
        [-1.3958e+00, -1.2621e+00, -6.7389e-01,  5.3808e-01, -1.4386e+00,
          5.9616e-01, -6.5851e-01],
        [ 1.0000e+00, -1.8491e+00,  9.1861e-02, -1.9241e-01, -1.6943e-03,
          6.2034e-01,  6.4031e-01]])

In [278]:
x = torch.rand(3,7)
mask = x > 0.5
print(mask)
print(x[mask])
x[x <= 0.5 ] = 0
print(x)

tensor([[False, False, False,  True,  True, False,  True],
        [False, False,  True, False, False, False, False],
        [False,  True, False,  True,  True, False,  True]])
tensor([0.7758, 0.8148, 0.5171, 0.8012, 0.7501, 0.6935, 0.9376, 0.7177])
tensor([[0.0000, 0.0000, 0.0000, 0.7758, 0.8148, 0.0000, 0.5171],
        [0.0000, 0.0000, 0.8012, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.7501, 0.0000, 0.6935, 0.9376, 0.0000, 0.7177]])

In [290]:
x = torch.rand(8,5)
mask_1 = x < 0.2
#k = [i for i in x if i < 0.4]
mask_2 = x < 0.4
display(mask_2)

y_1 = x[mask_2]
y_2 = x[mask_1]
display(y_1, y_2)

tensor([[False, False, False,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False, False],
        [False,  True, False,  True,  True],
        [ True, False, False, False,  True],
        [ True,  True, False, False, False],
        [ True, False, False,  True,  True],
        [False, False,  True, False, False]])

tensor([0.1836, 0.3841, 0.2054, 0.3287, 0.0135, 0.2012, 0.0368, 0.2202, 0.0154,
        0.1289, 0.2149, 0.3630, 0.2507, 0.3311, 0.0946])

tensor([0.1836, 0.0135, 0.0368, 0.0154, 0.1289, 0.0946])

In [301]:
a = torch.arange(12).reshape(3,4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [309]:
# Just like boolean indexing, we can provide integer tensors for selecting an arbitrary order of elements from tensors
# Those integer tensors acting as indexes, must be 0-dimensional acting as a scalar, or simply a list of integers
a = torch.arange(20).reshape(5,4)
display(a)
print(a[[0,4],[3,0]])

ind = [0,1,3]
print(a[ind])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

tensor([ 3, 16])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [328]:
# See the tensor acting as an index, allows more flexibility to choose any values in arbitrary order
a = torch.arange(100, 200, 15)
ind = torch.tensor([0,4,5,2,2])
print(f"Indexes {ind} and corresponding values:\n{a[ind]}\n")

# row index
b = torch.arange(20).reshape(4,5)
display(b)
row_index = torch.tensor([1,3]) 
row_index_1 = torch.tensor([0,2])
print(f"Indexes {row_index} {row_index_1} and corresponding rows:\n{b[row_index]}\n{b[row_index_1]}")
# Since the first value corresponds to the # of rows, only given rows of 1 and 3 are sliced
# Also, just like for boolean masking, tensor indexing also create a new distinct copy of original tensor, without any reference
# Hence no updates in one will reflect the other

# column index
col_index_1 = torch.tensor([1,3])
col_index_2 = torch.tensor([0,2,4])
print(f"Column indexes {col_index_1} {col_index_2} and corresponding columns:\n{b[:,col_index_1]}\n{b[:,col_index_2]}")


# row and column index to select [3,17,12] and [7,14,16]
crow_index_1 = torch.tensor([0,3,2])
rcol_index_1 = torch.tensor([3,2,2])
crow_index_2 = torch.tensor([1,2,3])
rcol_index_2 = torch.tensor([2,4,1])

print(f"Row index {crow_index_1} column index {rcol_index_1}:\n{b[crow_index_1, rcol_index_1]}\n")
print(f"Row index {crow_index_2} column index {rcol_index_2}:\n{b[crow_index_2, rcol_index_2]}\n")

Indexes tensor([0, 4, 5, 2, 2]) and corresponding values:
tensor([100, 160, 175, 130, 130])

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

Indexes tensor([1, 3]) tensor([0, 2]) and corresponding rows:
tensor([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]])
Column indexes tensor([1, 3]) tensor([0, 2, 4]) and corresponding columns:
tensor([[ 1,  3],
        [ 6,  8],
        [11, 13],
        [16, 18]])
tensor([[ 0,  2,  4],
        [ 5,  7,  9],
        [10, 12, 14],
        [15, 17, 19]])
Row index tensor([0, 3, 2]) column index tensor([3, 2, 2]):
tensor([ 3, 17, 12])

Row index tensor([1, 2, 3]) column index tensor([2, 4, 1]):
tensor([ 7, 14, 16])

In [346]:
x = torch.arange(0,1,1e-6).reshape(1000, 1000)
display(x.shape)

torch.Size([1000, 1000])

In [388]:
# reshape(a,b) must so that a*b equal to given input of arange(c) a*b = c, 10*10=100
a = torch.arange(100).reshape(10, 10)
print(a)
row_index = [2,6,2,7,-1, -3]
col_index = [2,3,6,8,-1, -2]
out = a[row_index, col_index]
out_1 = a[:,col_index]
out_2 = a[row_index,:]
print(out, out.shape, out_1, out_1.shape, out_2, out_2.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
tensor([22, 63, 26, 78, 99, 78]) torch.Size([6]) tensor([[ 2,  3,  6,  8,  9,  8],
        [12, 13, 16, 18, 19, 18],
        [22, 23, 26, 28, 29, 28],
        [32, 33, 36, 38, 39, 38],
        [42, 43, 46, 48, 49, 48],
        [52, 53, 56, 58, 59, 58],
        [62, 63, 66, 68, 69, 68],
        [72, 73, 76, 78, 79, 78],
        [82, 83, 86, 88, 89, 88],
        [92, 93, 96, 98, 99, 98]]) torch.Size([10, 6]) tensor([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]) torch.Size([6, 10])

In [367]:
a = torch.arange(250).reshape(5,5,10)
print(a, a.dtype, type(a))
a[a > 125] = 125
a[a < 125] = 0
print(a)

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

        [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
         [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
         [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
         [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]],

        [[200, 201, 202, 203, 204, 205, 206, 207, 208, 209],
         [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
         [220, 221, 222, 223, 224, 225, 226, 227, 228, 229],
         [230, 231, 232, 233, 234, 235, 236, 237, 238, 239],
         [240, 241, 242, 243, 244, 245, 246, 247, 248, 249]]]) torch.int64 <class 'torch.Tensor'>
tensor([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],

        [[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],

        [[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125]],

        [[125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125]],

        [[125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125],
         [125, 125, 125, 125, 125, 125, 125, 125, 125, 125]]])

In [387]:
a = torch.randn(5,5,10)
a[a <= 0] = 0
print(a)
k = a.bool()
print(k)
a = a[k]
print(a)
a = a.cpu()
a = a.to("cpu").numpy()
print(type(a))

tensor([[[1.0452, 2.1169, 0.0000, 0.0000, 0.0000, 0.0000, 0.1204, 0.2706,
          0.5941, 0.1667],
         [0.0000, 0.3531, 0.0000, 0.0000, 0.3922, 0.7303, 0.0000, 0.0000,
          0.0000, 0.0000],
         [0.0000, 1.7069, 0.0000, 0.0000, 0.9918, 0.0000, 1.5400, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.4139, 0.7814, 0.0000, 0.1294, 0.0000, 1.9712,
          0.0000, 0.0000],
         [0.0713, 0.0000, 0.6040, 0.0000, 0.9000, 0.9442, 0.0000, 0.0000,
          1.3106, 1.4688]],

        [[0.9692, 0.9037, 0.0000, 1.3800, 2.4983, 1.9402, 0.0000, 1.2193,
          0.7208, 0.6699],
         [0.0000, 0.9197, 1.2402, 0.1188, 0.0000, 0.0000, 1.3453, 0.8899,
          0.0000, 0.0000],
         [1.5770, 0.0000, 0.6776, 0.0000, 0.0000, 0.8369, 0.5640, 0.4449,
          0.0000, 0.8447],
         [0.3091, 1.5039, 0.0000, 1.6581, 0.0000, 0.4514, 0.0000, 0.3266,
          0.0000, 0.0766],
         [0.0000, 0.9519, 0.0000, 0.6262, 0.2252, 0.5458, 0.0000, 0.0000,
          0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.9471, 0.0000, 0.0146, 0.0000, 0.1440,
          0.3735, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.4368, 0.0000, 1.0104, 0.6224, 0.6016,
          0.5469, 0.6164],
         [0.0000, 0.0000, 1.3095, 0.0000, 0.0000, 0.0000, 0.0000, 0.5929,
          0.0000, 0.8325],
         [0.7173, 0.0000, 0.5807, 0.0000, 0.0000, 2.2207, 0.0421, 0.0000,
          0.0000, 0.0000],
         [0.9413, 0.0000, 0.2020, 0.5606, 1.5194, 0.3858, 0.0000, 0.1027,
          0.1170, 1.1666]],

        [[0.0041, 0.5713, 0.0000, 0.0000, 1.1948, 0.5761, 0.3189, 0.0000,
          0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 1.1749, 0.0000, 0.0000, 0.4690,
          0.0000, 0.2164],
         [1.3612, 0.5121, 1.0968, 0.1234, 0.0000, 0.0000, 0.6317, 0.0000,
          0.8754, 0.0000],
         [2.1273, 0.0556, 0.0207, 0.9670, 0.0000, 0.0000, 0.0000, 0.9922,
          0.0000, 1.1061],
         [0.9001, 0.0000, 0.2206, 0.1171, 0.0000, 0.0000, 0.0000, 0.5359,
          0.0000, 0.0000]],

        [[0.3552, 0.0000, 0.0000, 0.9309, 0.0000, 0.3500, 0.0000, 0.0000,
          0.0507, 0.0000],
         [0.0000, 0.0000, 1.5334, 1.2525, 0.7064, 0.0000, 0.7574, 0.5895,
          0.5640, 0.6948],
         [0.0000, 0.1061, 0.3256, 2.5773, 0.3204, 1.2049, 2.2000, 0.0000,
          0.6102, 0.9829],
         [0.5353, 1.3596, 0.0000, 1.7043, 0.0000, 1.3254, 0.0000, 0.0000,
          0.0000, 2.8679],
         [0.0000, 1.0361, 0.0000, 0.0000, 0.2446, 0.0000, 0.2622, 0.0879,
          0.9513, 0.5793]]])
tensor([[[ True,  True, False, False, False, False,  True,  True,  True,  True],
         [False,  True, False, False,  True,  True, False, False, False, False],
         [False,  True, False, False,  True, False,  True, False, False, False],
         [False, False,  True,  True, False,  True, False,  True, False, False],
         [ True, False,  True, False,  True,  True, False, False,  True,  True]],

        [[ True,  True, False,  True,  True,  True, False,  True,  True,  True],
         [False,  True,  True,  True, False, False,  True,  True, False, False],
         [ True, False,  True, False, False,  True,  True,  True, False,  True],
         [ True,  True, False,  True, False,  True, False,  True, False,  True],
         [False,  True, False,  True,  True,  True, False, False, False, False]],

        [[False, False, False,  True, False,  True, False,  True,  True, False],
         [False, False, False,  True, False,  True,  True,  True,  True,  True],
         [False, False,  True, False, False, False, False,  True, False,  True],
         [ True, False,  True, False, False,  True,  True, False, False, False],
         [ True, False,  True,  True,  True,  True, False,  True,  True,  True]],

        [[ True,  True, False, False,  True,  True,  True, False, False, False],
         [False, False, False, False,  True, False, False,  True, False,  True],
         [ True,  True,  True,  True, False, False,  True, False,  True, False],
         [ True,  True,  True,  True, False, False, False,  True, False,  True],
         [ True, False,  True,  True, False, False, False,  True, False, False]],

        [[ True, False, False,  True, False,  True, False, False,  True, False],
         [False, False,  True,  True,  True, False,  True,  True,  True,  True],
         [False,  True,  True,  True,  True,  True,  True, False,  True,  True],
         [ True,  True, False,  True, False,  True, False, False, False,  True],
         [False,  True, False, False,  True, False,  True,  True,  True,  True]]])
tensor([1.0452, 2.1169, 0.1204, 0.2706, 0.5941, 0.1667, 0.3531, 0.3922, 0.7303,
        1.7069, 0.9918, 1.5400, 0.4139, 0.7814, 0.1294, 1.9712, 0.0713, 0.6040,
        0.9000, 0.9442, 1.3106, 1.4688, 0.9692, 0.9037, 1.3800, 2.4983, 1.9402,
        1.2193, 0.7208, 0.6699, 0.9197, 1.2402, 0.1188, 1.3453, 0.8899, 1.5770,
        0.6776, 0.8369, 0.5640, 0.4449, 0.8447, 0.3091, 1.5039, 1.6581, 0.4514,
        0.3266, 0.0766, 0.9519, 0.6262, 0.2252, 0.5458, 0.9471, 0.0146, 0.1440,
        0.3735, 0.4368, 1.0104, 0.6224, 0.6016, 0.5469, 0.6164, 1.3095, 0.5929,
        0.8325, 0.7173, 0.5807, 2.2207, 0.0421, 0.9413, 0.2020, 0.5606, 1.5194,
        0.3858, 0.1027, 0.1170, 1.1666, 0.0041, 0.5713, 1.1948, 0.5761, 0.3189,
        1.1749, 0.4690, 0.2164, 1.3612, 0.5121, 1.0968, 0.1234, 0.6317, 0.8754,
        2.1273, 0.0556, 0.0207, 0.9670, 0.9922, 1.1061, 0.9001, 0.2206, 0.1171,
        0.5359, 0.3552, 0.9309, 0.3500, 0.0507, 1.5334, 1.2525, 0.7064, 0.7574,
        0.5895, 0.5640, 0.6948, 0.1061, 0.3256, 2.5773, 0.3204, 1.2049, 2.2000,
        0.6102, 0.9829, 0.5353, 1.3596, 1.7043, 1.3254, 2.8679, 1.0361, 0.2446,
        0.2622, 0.0879, 0.9513, 0.5793])
<class 'numpy.ndarray'>

In [436]:
data = torch.randn(5,9,6)
print(data)
data_ = data.clone()
mask = data_ >= 2.5
out = data_[mask]
print(out)

tensor([[[ 0.1541, -0.7640,  1.4316,  0.4440, -0.1638,  0.5339],
         [-1.3795,  1.6910, -0.2075,  0.0386, -0.4740,  1.4058],
         [-0.2388,  1.9894, -2.6206,  0.5318,  0.8574,  0.2210],
         [-0.9408, -0.2698,  2.3347,  0.1570,  1.0208,  1.9685],
         [ 1.9682, -0.7210, -0.5699, -0.3891, -0.6902, -0.1473],
         [ 1.0022, -1.1553, -0.6832, -0.7163,  1.1684, -1.0898],
         [-0.7565, -1.8426,  0.8631,  1.3623, -0.2753, -0.9114],
         [ 2.0284,  0.8553, -1.2546, -1.6465,  0.0274, -1.7507],
         [-1.9344, -0.6700, -1.3205,  0.2744,  0.0488, -0.7669]],

        [[ 0.2334, -0.3849, -0.0371, -2.1344, -1.5492, -1.4440],
         [ 0.0851, -0.4351,  0.5415,  1.0551, -0.5707, -0.7926],
         [ 0.4770, -1.0899,  0.3575, -1.0402,  1.0323,  0.5071],
         [ 0.8206,  0.1172,  0.7503, -0.8246,  0.1645,  2.7949],
         [-1.0634, -0.5220, -0.2783,  0.2780, -1.0693,  0.1411],
         [-0.0453,  0.1379, -1.2321,  0.1092, -0.7607, -0.9166],
         [-0.4697, -1.2646, -0.4846,  0.0394,  0.0795, -0.1589],
         [-0.2544,  1.1033, -0.6096,  0.2306, -0.2493,  1.1039],
         [-1.3576,  0.0458, -0.0235, -1.2875,  0.0291, -0.5967]],

        [[-1.8746,  0.1580,  0.7409,  1.3334, -1.0044, -0.4460],
         [ 1.2855, -0.5434,  0.2314,  1.3300, -0.9923,  0.8374],
         [ 1.5023,  0.1938, -0.3940, -0.6242,  0.7418, -1.1036],
         [ 0.8489,  1.0290, -0.3931, -2.0093,  0.4991, -1.4513],
         [-1.3856,  0.4138, -0.3842,  1.5035, -1.2356,  0.4493],
         [ 0.7562, -0.1255,  1.1362, -1.5525,  0.9317,  0.1677],
         [-0.2053,  1.0421, -0.3234,  0.4898, -0.6966, -0.0031],
         [ 0.2167, -0.9249, -2.4712,  0.1479,  1.0366,  1.5920],
         [-1.3036, -0.6513,  0.0317,  0.1120, -0.3032,  2.7813]],

        [[ 1.0116,  0.0748, -0.5415, -0.0706,  0.1513,  0.3421],
         [-0.1354,  1.4665,  1.3693, -0.4056,  0.7635,  0.2231],
         [-0.7511,  0.7512, -0.4571,  0.3288, -0.5804,  0.8353],
         [-0.7543, -0.6982,  0.4553,  0.8830,  1.0521, -0.7005],
         [-0.3901, -1.2903,  1.6037, -0.8750, -1.5090, -1.2801],
         [ 0.1032, -0.3258, -0.4811,  1.2917, -0.0840, -1.0601],
         [-1.0486,  0.9222, -1.2571, -0.3042, -0.2870, -0.2326],
         [ 0.9683, -0.0658, -0.3149,  0.7630, -0.9302, -0.2224],
         [ 1.8595,  0.8985,  0.5951, -0.6412,  0.1535,  0.3890]],

        [[-1.3856, -0.9692, -0.8573,  0.2130,  1.5655, -0.3240],
         [ 1.1518,  0.4012,  0.2460, -0.0844,  0.0455, -0.6878],
         [-1.0096,  0.6971,  0.1884,  0.2780,  1.7120, -0.7850],
         [-0.3575,  1.7292,  0.5305,  0.8780,  0.0428, -0.3336],
         [-0.5618, -1.1575,  0.9262,  0.9536, -0.4559, -0.5927],
         [ 0.2107, -0.2102,  1.0000,  0.8206,  0.3407,  1.1434],
         [-0.7965, -0.1799,  0.5652, -0.9415,  0.1055,  0.0486],
         [ 0.5319, -1.8150, -1.5669, -0.0105, -1.2539, -0.2704],
         [ 1.6249, -1.5608, -0.9098,  1.8411,  0.3258, -1.0488]]])
tensor([2.7949, 2.7813])

In [440]:
a = torch.rand(8,4,3)
print(a)
a = a.clone()
a[a <= 0.5] = 0
k = a.bool()
print(a)
print(a[k])

tensor([[[0.3295, 0.6129, 0.3455],
         [0.6025, 0.8643, 0.7655],
         [0.4261, 0.2768, 0.4233],
         [0.5592, 0.3922, 0.9427]],

        [[0.2687, 0.2633, 0.6238],
         [0.2583, 0.6621, 0.2675],
         [0.7784, 0.1841, 0.7578],
         [0.7109, 0.6096, 0.8750]],

        [[0.4524, 0.3265, 0.3561],
         [0.7671, 0.0372, 0.0468],
         [0.1766, 0.5985, 0.9410],
         [0.2882, 0.3704, 0.6663]],

        [[0.0797, 0.4322, 0.9529],
         [0.3096, 0.4884, 0.8075],
         [0.9607, 0.0531, 0.9894],
         [0.6854, 0.7408, 0.5432]],

        [[0.6648, 0.7839, 0.0036],
         [0.7835, 0.7145, 0.4826],
         [0.0291, 0.9633, 0.6656],
         [0.1704, 0.7170, 0.2273]],

        [[0.9336, 0.6461, 0.4245],
         [0.3716, 0.8536, 0.0368],
         [0.6886, 0.4181, 0.7093],
         [0.1621, 0.3817, 0.1797]],

        [[0.7348, 0.9000, 0.9823],
         [0.3002, 0.8980, 0.7955],
         [0.7578, 0.0923, 0.4431],
         [0.4791, 0.0858, 0.4528]],

        [[0.6568, 0.1919, 0.3835],
         [0.0708, 0.0987, 0.1469],
         [0.8986, 0.2346, 0.5674],
         [0.5202, 0.2840, 0.8847]]])
tensor([[[0.0000, 0.6129, 0.0000],
         [0.6025, 0.8643, 0.7655],
         [0.0000, 0.0000, 0.0000],
         [0.5592, 0.0000, 0.9427]],

        [[0.0000, 0.0000, 0.6238],
         [0.0000, 0.6621, 0.0000],
         [0.7784, 0.0000, 0.7578],
         [0.7109, 0.6096, 0.8750]],

        [[0.0000, 0.0000, 0.0000],
         [0.7671, 0.0000, 0.0000],
         [0.0000, 0.5985, 0.9410],
         [0.0000, 0.0000, 0.6663]],

        [[0.0000, 0.0000, 0.9529],
         [0.0000, 0.0000, 0.8075],
         [0.9607, 0.0000, 0.9894],
         [0.6854, 0.7408, 0.5432]],

        [[0.6648, 0.7839, 0.0000],
         [0.7835, 0.7145, 0.0000],
         [0.0000, 0.9633, 0.6656],
         [0.0000, 0.7170, 0.0000]],

        [[0.9336, 0.6461, 0.0000],
         [0.0000, 0.8536, 0.0000],
         [0.6886, 0.0000, 0.7093],
         [0.0000, 0.0000, 0.0000]],

        [[0.7348, 0.9000, 0.9823],
         [0.0000, 0.8980, 0.7955],
         [0.7578, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.6568, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.8986, 0.0000, 0.5674],
         [0.5202, 0.0000, 0.8847]]])
tensor([0.6129, 0.6025, 0.8643, 0.7655, 0.5592, 0.9427, 0.6238, 0.6621, 0.7784,
        0.7578, 0.7109, 0.6096, 0.8750, 0.7671, 0.5985, 0.9410, 0.6663, 0.9529,
        0.8075, 0.9607, 0.9894, 0.6854, 0.7408, 0.5432, 0.6648, 0.7839, 0.7835,
        0.7145, 0.9633, 0.6656, 0.7170, 0.9336, 0.6461, 0.8536, 0.6886, 0.7093,
        0.7348, 0.9000, 0.9823, 0.8980, 0.7955, 0.7578, 0.6568, 0.8986, 0.5674,
        0.5202, 0.8847])

# Reshaping and Rearranging Tensors

In [496]:
# Contiguous tensors are the ones which did not go through slicing or transposing, basically nothing is changed about them
# regarding their position of rows and columns or taking slices of the given tensor.

a = torch.arange(10).reshape(2,5) 
print(a.is_contiguous())
# since after that we did not make any changes to its shape by slicing or transposing, thus it is contiguous tensor
a = a.T
print(a[[1,3]])
# now it is no longer contiguous tensor, since it has been either sliced and transposed
print(a.is_contiguous())
x = a.reshape(5,2)
display(x, a)

True
tensor([[1, 6],
        [3, 8]])
False

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [497]:
a = torch.arange(18)
print(f"Tensor:\n{a}\nTensor shape: {a.shape}\nIs tensor contiguous?: {a.is_contiguous()}\n")

# both view and reshape seem to produce the same results
x = a.view(3,6)
print(f"Tensor:\n{x}\nTensor shape: {x.shape}\nIs tensor contiguous?: {x.is_contiguous()}")
print(f"Are both tensors stored in the same memory location?: {a.storage().data_ptr() == x.storage().data_ptr()}\n")

z = x.view(9,2)
print(f"Tensor:\n{z}\nTensor shape:\n{z.shape}\nIs tensor contiguous?: {z.is_contiguous()}")
print(f"Are both tensors are stored in the same memory location?: {x.storage().data_ptr() == z.storage().data_ptr()}\n")
print(f"Are all three tensors of different sizes created with .view() share the same memory location?:\
 {a.storage().data_ptr() == x.storage().data_ptr() == z.storage().data_ptr()}\n")

Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])
Tensor shape: torch.Size([18])
Is tensor contiguous?: True

Tensor:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]])
Tensor shape: torch.Size([3, 6])
Is tensor contiguous?: True
Are both tensors stored in the same memory location?: True

Tensor:
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17]])
Tensor shape:
torch.Size([9, 2])
Is tensor contiguous?: True
Are both tensors are stored in the same memory location?: True

Are all three tensors of different sizes created with .view() share the same memory location?: True

In [530]:
# .view() method works for contiguous tensors, so before reshaping check whether a given tensor is_contiguous()
# or otherwise reshaping will not work

a = torch.arange(12)
x = a.view(3,-1,2)
print(x)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [535]:
# With .view() we can infer only one dimension based on other dimensions
# if the total number of elements are 12, then we can use "-1" for PyTorch to infer the dimension of that last 
# element by itselfs so that the product of shape elements equal to the total number of elements, here being 12
a = torch.arange(12)
x_1 = a.view(2,2,-1) # "-1" here inferring, so that 2*2*x = 12, hence x=3
x_2 = a.view(-1,3,2) # "-1" here inferring, so that x*3*2 = 12, hence x=2
x_3 = a.view(3, -1, 4) # "-1" here inferring, so that 3*x*4 = 12, hence x=1
display(x_1, x_1.shape, x_2, x_2.shape, x_3, x_3.shape)
# Again only one dimension can be inferred, and only one.

print(f"\nAre these tensors share the same memory location?: \
{a.storage().data_ptr() == x_1.storage().data_ptr() == x_2.storage().data_ptr() == x_3.storage().data_ptr()}")

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

torch.Size([2, 2, 3])

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

torch.Size([2, 3, 2])

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

torch.Size([3, 1, 4])

Are these tensors share the same memory location?: True

In [555]:
# If we try to reshape with .view() for non-contiguous tensors then nothing will change and error may pop up
a = torch.arange(15).view(3,5)
b = a.t()
print(b.is_contiguous())

try:
    x = b.view(15)
    display(x, x.shape)
except RuntimeError as e:
    print(f"\nTensor is non-congtiguous {e}")

False

Tensor is non-congtiguous view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [568]:
# .reshape() behaves similarly to .view() but .reshape() is more flexible and versatile since it does not require
# tensors to be contiguous, because if the tensors are non-contiguous then .reshape() simply makes copies of original
# tensor and reshapes them as needed, potentially creating several copies of the original tensor, which is 
# unlike .view() the resulting tensors shares the same memory location hence any changes will reflect other tensors

a = torch.arange(12).reshape(3,4)
a = a.t()
print(f"\nIs contiguous?: {a.is_contiguous()}\nShape: {a.shape}\n")
x = a.reshape(2,6)
print(f"Is contiguous?: {x.is_contiguous()}\nShape: {x.shape}\n")
z = x.reshape(4,-1) # "-1" will be inferred as 3 since 4*3=12
print(f"Is contiguous?: {z.is_contiguous()}\nShape:{z.shape}\n")
flat = z.view(-1) # flattens the matrix into a list of scalar/singular values in 0-dimensions

# Now check whether reshape() has created a copy of original tensor, or simply took its view
# reshape() will create a copy of original tensor if only it is non-contiguous, otherwise no copy is created
print(f"Are these tensors share the same memory location?: {a.storage().data_ptr() == x.storage().data_ptr()}")
display(id(a), id(x)) # IDs do not represent memory location
display(flat, flat.shape)

Is contiguous?: False
Shape: torch.Size([4, 3])

Is contiguous?: True
Shape: torch.Size([2, 6])

Is contiguous?: True
Shape:torch.Size([4, 3])

Are these tensors share the same memory location?: False

5376074432

5389109344

tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

torch.Size([12])

In [582]:
image_tensor = torch.rand(3, 128, 128) # C, H, W
print(image_tensor.shape)
permutated_tensor = image_tensor.permute(1,2,0)
print(permutated_tensor.shape)
original_again = permutated_tensor.permute(2,0,1)
print(original_again.shape)
print(f"Are permutated tensors are contiguous: {permutated_tensor.is_contiguous()} {original_again.is_contiguous()}\n\
Does original tensor and permutated back to original tensor share the same memory location?: \
{image_tensor.storage().data_ptr() == original_again.storage().data_ptr()}")

# permute() just like view() does not create a copy of original tensor, but rather changes the original tensor
# thus any reference to them, will cause change in other tensors as well
# permute() however, returns non-contiguous tensors, in order to fix that use .contiguous() method

print(f"\nIs permutated tensor contiguous?: {permutated_tensor.is_contiguous()}")
permutated_tensor_to_contiguous = permutated_tensor.contiguous()
print(f"\nIs permutated tensor after using .contiguous() method caused it to become contiguous?:\
 {permutated_tensor_to_contiguous.is_contiguous()}")

torch.Size([3, 128, 128])
torch.Size([128, 128, 3])
torch.Size([3, 128, 128])
Are permutated tensors are contiguous: False True
Does original tensor and permutated back to original tensor share the same memory location?: True

Is permutated tensor contiguous?: False

Is permutated tensor after using .contiguous() method caused it to become contiguous?: True

In [600]:
# .view() does the reshaping faster than .reshape(), because it does not copy
# but it assumges contiguity in order to work without RuntimeError while .reshape() is more flexible and can handle
# non-contiguous tensors by making copies, though taking time for this operation
# .permute() simply changes the order of given input shapes by using their indexes

big_data = torch.rand(3, 3, 64, 64)
display(big_data.shape)
permute_data = big_data.permute(2, 0, 3, 1)
display(permute_data.shape)
permute_data_2 = permute_data.permute(0, 2, 1, 3)
display(permute_data_2.shape)
permute_back_to_original = permute_data_2.permute(2,3,0,1)
display(permute_back_to_original.shape)

print(f"Are those tensors contiguous?: {permute_data.is_contiguous()}, {permute_data_2.is_contiguous()}, \
{permute_back_to_original.is_contiguous()}")
permute_data = permute_data.contiguous()
permute_data_2 = permute_data_2.contiguous()
print(f"Are those tensors contiguous after using .contiguous() method?: \
{permute_data.is_contiguous()}, {permute_data_2.is_contiguous()}, \
{permute_back_to_original.is_contiguous()}")

# .permute() simply changes the order of dimensions/shapes of the tensor by taking indexes of those dimensions as input

torch.Size([3, 3, 64, 64])

torch.Size([64, 3, 64, 3])

torch.Size([64, 64, 3, 3])

torch.Size([3, 3, 64, 64])

Are those tensors contiguous?: False, False, True
Are those tensors contiguous after using .contiguous() method?: True, True, True

In [643]:
# We can also flatten the matrix into a list of scalar/singular values
# by flatenning we can see how man elements are there in the tensor

x = torch.rand(64, 64, 3)
print(x.shape)
z = x.reshape(-1)
z = x.view(-1)
print(z.shape)

a = torch.rand(4,4,3,2)
full = a.reshape(-1)
print(f"Total number of elements: {full.shape}")
mask_1 =  a >= 0.5
mask_2 = a < 0.5
output_1 = a[mask_1]
output_2 = a[mask_2]
print(f"Total number of element above or equal to 0.5: {output_1.shape}")
print(f"Total number of element below 0.5: {output_2.shape}")

# Below approach uses conditions, while the above approach uses boolean masking which requires less code to implement
copy = a.clone()
copy[copy < 0.5] = 0
msk = copy.bool()
copy = a[msk]
print(copy.shape)

torch.Size([64, 64, 3])
torch.Size([12288])
Total number of elements: torch.Size([96])
Total number of element above or equal to 0.5: torch.Size([47])
Total number of element below 0.5: torch.Size([49])
torch.Size([47])

In [655]:
x = torch.randn(3,224,224)
per = x.permute(1,2,0)
display(per.shape)
print(x.storage().data_ptr() == per.storage().data_ptr())
display(x.shape)
x = x.view(-1)
x = x.reshape(-1)
print(x.shape)

torch.Size([224, 224, 3])

True

torch.Size([3, 224, 224])

torch.Size([150528])

In [657]:
x.is_same_size(z)
display(x.shape, z.shape)

torch.Size([150528])

torch.Size([12288])

In [666]:
a = torch.ones(3,4,2)
b = torch.zeros(3,4,2)
display(b.is_same_size(a))
display(a.is_same_size(b))

True

True

# Joining and Splitting Tensors

In [680]:
# we can join sequence of tensors as long as their shapes are equal (except the one we are trying to concatenate) or be empty

a = torch.rand(3,4)
b = torch.rand(3,4)
cat_dim0 = torch.cat((a,b), dim=0) # (3+3,4) = (6,4) 
# dim=#, the # is the index of the first value of the shape, hence not always rows when it comes to multidimensional tensors
print(f"Initial shape of tensors: {a.shape}, {b.shape}")
print(f"Joining/Concatenating tensors along dim=0, rows: {cat_dim0.shape}")
cat_dim1 = torch.cat((a,b), dim=1) # (3, 4+4) = (3, 8)
print(f"Joining/Concatenating tensors along dim=1, columns: {cat_dim1.shape}")

Initial shape of tensors: torch.Size([3, 4]), torch.Size([3, 4])
Joining/Concatenating tensors along dim=0, rows: torch.Size([6, 4])
Joining/Concatenating tensors along dim=1, columns: torch.Size([3, 8])

In [715]:
# Now we will concatenate tensors but the shape will be equal, except the one we are trying to concatenate

a = torch.rand(5, 12)
b = torch.rand(7, 12)
cat_dim0 = torch.cat((a,b), dim=0) # dim=0, refers to the first index in the shape order
display(cat_dim0.shape) # (5+7, 12) = (12,12)

c = torch.rand(3,12,45)
d = torch.rand(3,12,32)
cat_dim2 = torch.cat((c,d), dim=2) # dim=2, looks into the 2-index position of the shape, which is 45 and 32 in C and D
display(cat_dim2.shape) # (3,12,45+32) = (3,12,77)

e = torch.arange(3584).view(4, 56, 8, -1)
f = torch.arange(2048).view(4,32,8,-1)
display(e.shape, f.shape)
cat_dim1 = torch.cat((e,f), dim=1)
display(cat_dim1.shape) # (4, 56+32, 8, 2) = (4, 88, 8, 2)
print(cat_dim1)

torch.Size([12, 12])

torch.Size([3, 12, 77])

torch.Size([4, 56, 8, 2])

torch.Size([4, 32, 8, 2])

torch.Size([4, 88, 8, 2])

tensor([[[[   0,    1],
          [   2,    3],
          [   4,    5],
          ...,
          [  10,   11],
          [  12,   13],
          [  14,   15]],

         [[  16,   17],
          [  18,   19],
          [  20,   21],
          ...,
          [  26,   27],
          [  28,   29],
          [  30,   31]],

         [[  32,   33],
          [  34,   35],
          [  36,   37],
          ...,
          [  42,   43],
          [  44,   45],
          [  46,   47]],

         ...,

         [[ 464,  465],
          [ 466,  467],
          [ 468,  469],
          ...,
          [ 474,  475],
          [ 476,  477],
          [ 478,  479]],

         [[ 480,  481],
          [ 482,  483],
          [ 484,  485],
          ...,
          [ 490,  491],
          [ 492,  493],
          [ 494,  495]],

         [[ 496,  497],
          [ 498,  499],
          [ 500,  501],
          ...,
          [ 506,  507],
          [ 508,  509],
          [ 510,  511]]],


        [[[ 896,  897],
          [ 898,  899],
          [ 900,  901],
          ...,
          [ 906,  907],
          [ 908,  909],
          [ 910,  911]],

         [[ 912,  913],
          [ 914,  915],
          [ 916,  917],
          ...,
          [ 922,  923],
          [ 924,  925],
          [ 926,  927]],

         [[ 928,  929],
          [ 930,  931],
          [ 932,  933],
          ...,
          [ 938,  939],
          [ 940,  941],
          [ 942,  943]],

         ...,

         [[ 976,  977],
          [ 978,  979],
          [ 980,  981],
          ...,
          [ 986,  987],
          [ 988,  989],
          [ 990,  991]],

         [[ 992,  993],
          [ 994,  995],
          [ 996,  997],
          ...,
          [1002, 1003],
          [1004, 1005],
          [1006, 1007]],

         [[1008, 1009],
          [1010, 1011],
          [1012, 1013],
          ...,
          [1018, 1019],
          [1020, 1021],
          [1022, 1023]]],


        [[[1792, 1793],
          [1794, 1795],
          [1796, 1797],
          ...,
          [1802, 1803],
          [1804, 1805],
          [1806, 1807]],

         [[1808, 1809],
          [1810, 1811],
          [1812, 1813],
          ...,
          [1818, 1819],
          [1820, 1821],
          [1822, 1823]],

         [[1824, 1825],
          [1826, 1827],
          [1828, 1829],
          ...,
          [1834, 1835],
          [1836, 1837],
          [1838, 1839]],

         ...,

         [[1488, 1489],
          [1490, 1491],
          [1492, 1493],
          ...,
          [1498, 1499],
          [1500, 1501],
          [1502, 1503]],

         [[1504, 1505],
          [1506, 1507],
          [1508, 1509],
          ...,
          [1514, 1515],
          [1516, 1517],
          [1518, 1519]],

         [[1520, 1521],
          [1522, 1523],
          [1524, 1525],
          ...,
          [1530, 1531],
          [1532, 1533],
          [1534, 1535]]],


        [[[2688, 2689],
          [2690, 2691],
          [2692, 2693],
          ...,
          [2698, 2699],
          [2700, 2701],
          [2702, 2703]],

         [[2704, 2705],
          [2706, 2707],
          [2708, 2709],
          ...,
          [2714, 2715],
          [2716, 2717],
          [2718, 2719]],

         [[2720, 2721],
          [2722, 2723],
          [2724, 2725],
          ...,
          [2730, 2731],
          [2732, 2733],
          [2734, 2735]],

         ...,

         [[2000, 2001],
          [2002, 2003],
          [2004, 2005],
          ...,
          [2010, 2011],
          [2012, 2013],
          [2014, 2015]],

         [[2016, 2017],
          [2018, 2019],
          [2020, 2021],
          ...,
          [2026, 2027],
          [2028, 2029],
          [2030, 2031]],

         [[2032, 2033],
          [2034, 2035],
          [2036, 2037],
          ...,
          [2042, 2043],
          [2044, 2045],
          [2046, 2047]]]])

In [712]:
# For joining/concatenation to work, all the shapes/dimensions must be equal, except the one which we are concatenating
# or be empty such as torch.tensor([]) nothing inside
a = torch.rand(4,7,10)
b = torch.tensor([])
cat_dim2 = torch.cat((a,b), dim=2)
display(cat_dim2.shape)

torch.Size([4, 7, 10])

In [717]:
a = torch.rand(3, 32, 64)
b = torch.rand(5, 32, 64)
c = torch.rand(7, 32, 64)
d = torch.rand(2, 32, 64)
res = torch.cat((a,b,c,d), dim=0)
print(res.shape)
# .cat() does not create a new dimension, but adds tensors along the existing dimension

torch.Size([17, 32, 64])

In [752]:
# torch.stack() adds tensors along a new dimension, the one preceding the existing one
# if two tensors have shape(2,3), then torch.stack() will add them along a new dimension preceding them, resulting in (2,2,3)
# shapes of all tensors must the equal, unlike for torch.cat() for which the concatenating one need not be the same for both tensors

a = torch.rand(2,3)
b = torch.rand(2,3)
output = torch.stack((a,b), dim=0) # it stacks these 2by3 submatrcies next to each other.
display(output.shape)
print(output)

torch.Size([2, 2, 3])

tensor([[[0.0667, 0.0571, 0.7986],
         [0.0580, 0.3755, 0.8325]],

        [[0.5012, 0.1691, 0.9647],
         [0.2593, 0.5427, 0.3676]]])

In [768]:
a = torch.rand(4,7)
b = torch.rand(4,7)
c = torch.rand(4,7)
# Since here, are three individual tensors, a new dimension along 0-D will be 3
output_0 = torch.stack((a,b,c), dim=0)
output_1 = torch.stack((a,b,c), dim=1)
output_2 = torch.stack((a,b,c), dim=2)
# for torch.stack() the dim=#, will be equal to the total sequence/number of tensors being stacked
# so for each dim=#, the resulting dimension for that particular shape/dim index is the total number of tensors being stacked

print(a.shape)
print(output_0.shape)
print(output_1.shape)
print(output_2.shape)

torch.Size([4, 7])
torch.Size([3, 4, 7])
torch.Size([4, 3, 7])
torch.Size([4, 7, 3])

In [776]:
# for torch.stack(), the order of shape/dimensions and their number must be the same or otherwise error will popo up
# torch.stack() adds tensors along a new dimension preceding the existing dimension, for instance
# shape(4,3) for tensors becomes shape(2,4,3)
a = torch.rand(3,32,64)
b = torch.rand(3,32,64)
c = torch.rand(3,32,64)
d = torch.rand(3,32,64)


output_0 = torch.stack((a,b,c,d), dim=0)
output_1 = torch.stack((a,b,c,d), dim=1)
output_2 = torch.stack((a,b,c,d), dim=2)
output_3 = torch.stack((a,b,c,d), dim=3)

out_0 = torch.cat((a,b,c,d),dim=0)
out_1 = torch.cat((a,b,c,d),dim=1)
out_2 = torch.cat((a,b,c,d),dim=2)


print(f"Original shape of all three tensors: {a.shape}")
print("\nBelow are dimensions of torch.stack():")
display(output_0.shape, output_1.shape, output_2.shape, output_3.shape)
print("\nBelow are dimensions of torch.cat():")
display(out_0.shape, out_1.shape, out_2.shape)

Original shape of all three tensors: torch.Size([3, 32, 64])

Below are dimensions of torch.stack():

torch.Size([4, 3, 32, 64])

torch.Size([3, 4, 32, 64])

torch.Size([3, 32, 4, 64])

torch.Size([3, 32, 64, 4])

Below are dimensions of torch.cat():

torch.Size([12, 32, 64])

torch.Size([3, 128, 64])

torch.Size([3, 32, 256])

In [790]:
data = torch.arange(18).reshape(6,3)
data = torch.arange(18).view(6,3)
print(f"Original data:\n{data}\n")
equal_split_1 = torch.split(data, 2, dim=0) # dim=0 referring to the rows or the first index in the dim order of shapes
equal_split_2 = torch.split(data, 3, dim=0)
col_split = torch.split(data, 1, dim=1) # dim=1 referring to the columns or the second index inthe dim order of shapes

for i, chunk in enumerate(equal_split):
    print(f"Chunk #{i+1}, Shape {chunk.shape}:\n{chunk}\n")
# Since there are 6 rows, splitting it into 3 chunks with each one having two rows

for i, chunk in enumerate(equal_split_2):
    print(f"Chunk #{i+1}, Shape {chunk.shape}:\n{chunk}\n")

for i, cup in enumerate(col_split):
    print(f"Chunk #{i}, Shape {cup.shape}:\n{cup}\n")


# in torch.split(tensor, chunk_size, dim=#), you can specify the size of each chunk or provide a list of various sizes for each chunk
# but the total number of chunks must equal to the dimension we are splitting the tensor

Original data:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

Chunk #1, Shape torch.Size([2, 3]):
tensor([[0, 1, 2],
        [3, 4, 5]])

Chunk #2, Shape torch.Size([2, 3]):
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

Chunk #3, Shape torch.Size([2, 3]):
tensor([[12, 13, 14],
        [15, 16, 17]])

Chunk #1, Shape torch.Size([3, 3]):
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Chunk #2, Shape torch.Size([3, 3]):
tensor([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

Chunk #0, Shape torch.Size([6, 1]):
tensor([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]])

Chunk #1, Shape torch.Size([6, 1]):
tensor([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]])

Chunk #2, Shape torch.Size([6, 1]):
tensor([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])

In [791]:
data = torch.rand(10,25)
row_split_1 = torch.split(data, 2, dim=0)
row_split_2 = torch.split(data, [1,2,3,4], dim=0)
row_split_3 = torch.split(data, [3,7], dim=0)
row_split_4 = torch.split(data, 5, dim=0)

col_split_1 = torch.split(data, 5, dim=1)
col_split_2 = torch.split(data, [10,12,3], dim=1)
col_split_3 = torch.split(data, [14,11], dim=1)
col_split_4 = torch.split(data, [9,16], dim=1)

for i, cup in enumerate(row_split_1):
    print(f"Chunk #{i} Shape {cup.shape}:\n{cup}\n")

Chunk #0 Shape torch.Size([2, 25]):
tensor([[0.4032, 0.2665, 0.5689, 0.9558, 0.7335, 0.7716, 0.5554, 0.3178, 0.9897,
         0.5315, 0.0098, 0.2412, 0.0468, 0.8986, 0.6931, 0.8588, 0.5396, 0.2338,
         0.6108, 0.5326, 0.2469, 0.4281, 0.3185, 0.0626, 0.1491],
        [0.2311, 0.8909, 0.6141, 0.2340, 0.3224, 0.8999, 0.0766, 0.6744, 0.8163,
         0.0356, 0.6372, 0.3902, 0.7307, 0.6787, 0.0254, 0.8702, 0.3233, 0.8955,
         0.7436, 0.3276, 0.5380, 0.6280, 0.7185, 0.5924, 0.6137]])

Chunk #1 Shape torch.Size([2, 25]):
tensor([[0.8391, 0.8178, 0.6335, 0.4885, 0.2518, 0.1025, 0.8629, 0.9401, 0.0244,
         0.4913, 0.6978, 0.5261, 0.4289, 0.5088, 0.0057, 0.7855, 0.6461, 0.4029,
         0.9442, 0.4653, 0.4173, 0.3630, 0.7301, 0.1023, 0.8310],
        [0.0269, 0.1513, 0.8446, 0.8116, 0.1698, 0.6665, 0.3376, 0.8438, 0.6839,
         0.4616, 0.3571, 0.1008, 0.2831, 0.6438, 0.2404, 0.8769, 0.2470, 0.1786,
         0.6707, 0.2115, 0.4791, 0.6347, 0.0774, 0.6267, 0.7447]])

Chunk #2 Shape torch.Size([2, 25]):
tensor([[0.8740, 0.5422, 0.0165, 0.8561, 0.7294, 0.3002, 0.8806, 0.4817, 0.6837,
         0.2224, 0.4994, 0.4722, 0.3805, 0.8495, 0.4144, 0.3544, 0.1469, 0.1613,
         0.4677, 0.5428, 0.6903, 0.6059, 0.3213, 0.9013, 0.0455],
        [0.9116, 0.1909, 0.5668, 0.0351, 0.1990, 0.2575, 0.3091, 0.9088, 0.8170,
         0.0043, 0.5571, 0.0108, 0.8758, 0.1824, 0.0495, 0.2206, 0.7634, 0.6089,
         0.6091, 0.7605, 0.0304, 0.9115, 0.4810, 0.0161, 0.9152]])

Chunk #3 Shape torch.Size([2, 25]):
tensor([[0.2753, 0.0154, 0.6505, 0.4634, 0.1127, 0.4970, 0.3040, 0.3445, 0.8309,
         0.1767, 0.6247, 0.7780, 0.6746, 0.5937, 0.9582, 0.4665, 0.1535, 0.3081,
         0.5820, 0.3078, 0.5672, 0.5641, 0.7055, 0.2708, 0.6210],
        [0.4482, 0.4008, 0.1151, 0.1501, 0.7122, 0.2017, 0.7427, 0.7841, 0.4604,
         0.8754, 0.7092, 0.3173, 0.3148, 0.2232, 0.8313, 0.3866, 0.4686, 0.6559,
         0.5608, 0.6785, 0.7752, 0.5868, 0.5288, 0.9620, 0.6349]])

Chunk #4 Shape torch.Size([2, 25]):
tensor([[0.1428, 0.4605, 0.8928, 0.5830, 0.9445, 0.6096, 0.0723, 0.9198, 0.3845,
         0.9378, 0.4988, 0.0383, 0.4058, 0.8235, 0.0457, 0.5461, 0.8810, 0.8300,
         0.8974, 0.4875, 0.1180, 0.0536, 0.6728, 0.0289, 0.7024],
        [0.8379, 0.5845, 0.3492, 0.4667, 0.0021, 0.7452, 0.9432, 0.5371, 0.2272,
         0.4878, 0.1132, 0.7781, 0.3727, 0.0455, 0.3466, 0.0797, 0.6039, 0.8110,
         0.1953, 0.8152, 0.0224, 0.1172, 0.4016, 0.7553, 0.5207]])

In [792]:
for i, cup in enumerate(row_split_2):
    print(f"Chunk #{i} Shape {cup.shape}:\n{cup}\n")

Chunk #0 Shape torch.Size([1, 25]):
tensor([[0.4032, 0.2665, 0.5689, 0.9558, 0.7335, 0.7716, 0.5554, 0.3178, 0.9897,
         0.5315, 0.0098, 0.2412, 0.0468, 0.8986, 0.6931, 0.8588, 0.5396, 0.2338,
         0.6108, 0.5326, 0.2469, 0.4281, 0.3185, 0.0626, 0.1491]])

Chunk #1 Shape torch.Size([2, 25]):
tensor([[0.2311, 0.8909, 0.6141, 0.2340, 0.3224, 0.8999, 0.0766, 0.6744, 0.8163,
         0.0356, 0.6372, 0.3902, 0.7307, 0.6787, 0.0254, 0.8702, 0.3233, 0.8955,
         0.7436, 0.3276, 0.5380, 0.6280, 0.7185, 0.5924, 0.6137],
        [0.8391, 0.8178, 0.6335, 0.4885, 0.2518, 0.1025, 0.8629, 0.9401, 0.0244,
         0.4913, 0.6978, 0.5261, 0.4289, 0.5088, 0.0057, 0.7855, 0.6461, 0.4029,
         0.9442, 0.4653, 0.4173, 0.3630, 0.7301, 0.1023, 0.8310]])

Chunk #2 Shape torch.Size([3, 25]):
tensor([[0.0269, 0.1513, 0.8446, 0.8116, 0.1698, 0.6665, 0.3376, 0.8438, 0.6839,
         0.4616, 0.3571, 0.1008, 0.2831, 0.6438, 0.2404, 0.8769, 0.2470, 0.1786,
         0.6707, 0.2115, 0.4791, 0.6347, 0.0774, 0.6267, 0.7447],
        [0.8740, 0.5422, 0.0165, 0.8561, 0.7294, 0.3002, 0.8806, 0.4817, 0.6837,
         0.2224, 0.4994, 0.4722, 0.3805, 0.8495, 0.4144, 0.3544, 0.1469, 0.1613,
         0.4677, 0.5428, 0.6903, 0.6059, 0.3213, 0.9013, 0.0455],
        [0.9116, 0.1909, 0.5668, 0.0351, 0.1990, 0.2575, 0.3091, 0.9088, 0.8170,
         0.0043, 0.5571, 0.0108, 0.8758, 0.1824, 0.0495, 0.2206, 0.7634, 0.6089,
         0.6091, 0.7605, 0.0304, 0.9115, 0.4810, 0.0161, 0.9152]])

Chunk #3 Shape torch.Size([4, 25]):
tensor([[0.2753, 0.0154, 0.6505, 0.4634, 0.1127, 0.4970, 0.3040, 0.3445, 0.8309,
         0.1767, 0.6247, 0.7780, 0.6746, 0.5937, 0.9582, 0.4665, 0.1535, 0.3081,
         0.5820, 0.3078, 0.5672, 0.5641, 0.7055, 0.2708, 0.6210],
        [0.4482, 0.4008, 0.1151, 0.1501, 0.7122, 0.2017, 0.7427, 0.7841, 0.4604,
         0.8754, 0.7092, 0.3173, 0.3148, 0.2232, 0.8313, 0.3866, 0.4686, 0.6559,
         0.5608, 0.6785, 0.7752, 0.5868, 0.5288, 0.9620, 0.6349],
        [0.1428, 0.4605, 0.8928, 0.5830, 0.9445, 0.6096, 0.0723, 0.9198, 0.3845,
         0.9378, 0.4988, 0.0383, 0.4058, 0.8235, 0.0457, 0.5461, 0.8810, 0.8300,
         0.8974, 0.4875, 0.1180, 0.0536, 0.6728, 0.0289, 0.7024],
        [0.8379, 0.5845, 0.3492, 0.4667, 0.0021, 0.7452, 0.9432, 0.5371, 0.2272,
         0.4878, 0.1132, 0.7781, 0.3727, 0.0455, 0.3466, 0.0797, 0.6039, 0.8110,
         0.1953, 0.8152, 0.0224, 0.1172, 0.4016, 0.7553, 0.5207]])

In [812]:
for i, cup in enumerate(col_split_1):
    print(f"Chunk #{i} Shape {cup.shape}:\n{cup}\n")

Chunk #0 Shape torch.Size([10, 5]):
tensor([[0.4032, 0.2665, 0.5689, 0.9558, 0.7335],
        [0.2311, 0.8909, 0.6141, 0.2340, 0.3224],
        [0.8391, 0.8178, 0.6335, 0.4885, 0.2518],
        [0.0269, 0.1513, 0.8446, 0.8116, 0.1698],
        [0.8740, 0.5422, 0.0165, 0.8561, 0.7294],
        [0.9116, 0.1909, 0.5668, 0.0351, 0.1990],
        [0.2753, 0.0154, 0.6505, 0.4634, 0.1127],
        [0.4482, 0.4008, 0.1151, 0.1501, 0.7122],
        [0.1428, 0.4605, 0.8928, 0.5830, 0.9445],
        [0.8379, 0.5845, 0.3492, 0.4667, 0.0021]])

Chunk #1 Shape torch.Size([10, 5]):
tensor([[0.7716, 0.5554, 0.3178, 0.9897, 0.5315],
        [0.8999, 0.0766, 0.6744, 0.8163, 0.0356],
        [0.1025, 0.8629, 0.9401, 0.0244, 0.4913],
        [0.6665, 0.3376, 0.8438, 0.6839, 0.4616],
        [0.3002, 0.8806, 0.4817, 0.6837, 0.2224],
        [0.2575, 0.3091, 0.9088, 0.8170, 0.0043],
        [0.4970, 0.3040, 0.3445, 0.8309, 0.1767],
        [0.2017, 0.7427, 0.7841, 0.4604, 0.8754],
        [0.6096, 0.0723, 0.9198, 0.3845, 0.9378],
        [0.7452, 0.9432, 0.5371, 0.2272, 0.4878]])

Chunk #2 Shape torch.Size([10, 5]):
tensor([[0.0098, 0.2412, 0.0468, 0.8986, 0.6931],
        [0.6372, 0.3902, 0.7307, 0.6787, 0.0254],
        [0.6978, 0.5261, 0.4289, 0.5088, 0.0057],
        [0.3571, 0.1008, 0.2831, 0.6438, 0.2404],
        [0.4994, 0.4722, 0.3805, 0.8495, 0.4144],
        [0.5571, 0.0108, 0.8758, 0.1824, 0.0495],
        [0.6247, 0.7780, 0.6746, 0.5937, 0.9582],
        [0.7092, 0.3173, 0.3148, 0.2232, 0.8313],
        [0.4988, 0.0383, 0.4058, 0.8235, 0.0457],
        [0.1132, 0.7781, 0.3727, 0.0455, 0.3466]])

Chunk #3 Shape torch.Size([10, 5]):
tensor([[0.8588, 0.5396, 0.2338, 0.6108, 0.5326],
        [0.8702, 0.3233, 0.8955, 0.7436, 0.3276],
        [0.7855, 0.6461, 0.4029, 0.9442, 0.4653],
        [0.8769, 0.2470, 0.1786, 0.6707, 0.2115],
        [0.3544, 0.1469, 0.1613, 0.4677, 0.5428],
        [0.2206, 0.7634, 0.6089, 0.6091, 0.7605],
        [0.4665, 0.1535, 0.3081, 0.5820, 0.3078],
        [0.3866, 0.4686, 0.6559, 0.5608, 0.6785],
        [0.5461, 0.8810, 0.8300, 0.8974, 0.4875],
        [0.0797, 0.6039, 0.8110, 0.1953, 0.8152]])

Chunk #4 Shape torch.Size([10, 5]):
tensor([[0.2469, 0.4281, 0.3185, 0.0626, 0.1491],
        [0.5380, 0.6280, 0.7185, 0.5924, 0.6137],
        [0.4173, 0.3630, 0.7301, 0.1023, 0.8310],
        [0.4791, 0.6347, 0.0774, 0.6267, 0.7447],
        [0.6903, 0.6059, 0.3213, 0.9013, 0.0455],
        [0.0304, 0.9115, 0.4810, 0.0161, 0.9152],
        [0.5672, 0.5641, 0.7055, 0.2708, 0.6210],
        [0.7752, 0.5868, 0.5288, 0.9620, 0.6349],
        [0.1180, 0.0536, 0.6728, 0.0289, 0.7024],
        [0.0224, 0.1172, 0.4016, 0.7553, 0.5207]])

In [796]:
for i, cup in enumerate(col_split_2):
    print(f"Chunk #{i} Shape {cup.shape}:\n{cup}\n")

Chunk #0 Shape torch.Size([10, 10]):
tensor([[0.4032, 0.2665, 0.5689, 0.9558, 0.7335, 0.7716, 0.5554, 0.3178, 0.9897,
         0.5315],
        [0.2311, 0.8909, 0.6141, 0.2340, 0.3224, 0.8999, 0.0766, 0.6744, 0.8163,
         0.0356],
        [0.8391, 0.8178, 0.6335, 0.4885, 0.2518, 0.1025, 0.8629, 0.9401, 0.0244,
         0.4913],
        [0.0269, 0.1513, 0.8446, 0.8116, 0.1698, 0.6665, 0.3376, 0.8438, 0.6839,
         0.4616],
        [0.8740, 0.5422, 0.0165, 0.8561, 0.7294, 0.3002, 0.8806, 0.4817, 0.6837,
         0.2224],
        [0.9116, 0.1909, 0.5668, 0.0351, 0.1990, 0.2575, 0.3091, 0.9088, 0.8170,
         0.0043],
        [0.2753, 0.0154, 0.6505, 0.4634, 0.1127, 0.4970, 0.3040, 0.3445, 0.8309,
         0.1767],
        [0.4482, 0.4008, 0.1151, 0.1501, 0.7122, 0.2017, 0.7427, 0.7841, 0.4604,
         0.8754],
        [0.1428, 0.4605, 0.8928, 0.5830, 0.9445, 0.6096, 0.0723, 0.9198, 0.3845,
         0.9378],
        [0.8379, 0.5845, 0.3492, 0.4667, 0.0021, 0.7452, 0.9432, 0.5371, 0.2272,
         0.4878]])

Chunk #1 Shape torch.Size([10, 12]):
tensor([[0.0098, 0.2412, 0.0468, 0.8986, 0.6931, 0.8588, 0.5396, 0.2338, 0.6108,
         0.5326, 0.2469, 0.4281],
        [0.6372, 0.3902, 0.7307, 0.6787, 0.0254, 0.8702, 0.3233, 0.8955, 0.7436,
         0.3276, 0.5380, 0.6280],
        [0.6978, 0.5261, 0.4289, 0.5088, 0.0057, 0.7855, 0.6461, 0.4029, 0.9442,
         0.4653, 0.4173, 0.3630],
        [0.3571, 0.1008, 0.2831, 0.6438, 0.2404, 0.8769, 0.2470, 0.1786, 0.6707,
         0.2115, 0.4791, 0.6347],
        [0.4994, 0.4722, 0.3805, 0.8495, 0.4144, 0.3544, 0.1469, 0.1613, 0.4677,
         0.5428, 0.6903, 0.6059],
        [0.5571, 0.0108, 0.8758, 0.1824, 0.0495, 0.2206, 0.7634, 0.6089, 0.6091,
         0.7605, 0.0304, 0.9115],
        [0.6247, 0.7780, 0.6746, 0.5937, 0.9582, 0.4665, 0.1535, 0.3081, 0.5820,
         0.3078, 0.5672, 0.5641],
        [0.7092, 0.3173, 0.3148, 0.2232, 0.8313, 0.3866, 0.4686, 0.6559, 0.5608,
         0.6785, 0.7752, 0.5868],
        [0.4988, 0.0383, 0.4058, 0.8235, 0.0457, 0.5461, 0.8810, 0.8300, 0.8974,
         0.4875, 0.1180, 0.0536],
        [0.1132, 0.7781, 0.3727, 0.0455, 0.3466, 0.0797, 0.6039, 0.8110, 0.1953,
         0.8152, 0.0224, 0.1172]])

Chunk #2 Shape torch.Size([10, 3]):
tensor([[0.3185, 0.0626, 0.1491],
        [0.7185, 0.5924, 0.6137],
        [0.7301, 0.1023, 0.8310],
        [0.0774, 0.6267, 0.7447],
        [0.3213, 0.9013, 0.0455],
        [0.4810, 0.0161, 0.9152],
        [0.7055, 0.2708, 0.6210],
        [0.5288, 0.9620, 0.6349],
        [0.6728, 0.0289, 0.7024],
        [0.4016, 0.7553, 0.5207]])

In [799]:
display(col_split_2, type(col_split_2))

(tensor([[0.4032, 0.2665, 0.5689, 0.9558, 0.7335, 0.7716, 0.5554, 0.3178, 0.9897,
          0.5315],
         [0.2311, 0.8909, 0.6141, 0.2340, 0.3224, 0.8999, 0.0766, 0.6744, 0.8163,
          0.0356],
         [0.8391, 0.8178, 0.6335, 0.4885, 0.2518, 0.1025, 0.8629, 0.9401, 0.0244,
          0.4913],
         [0.0269, 0.1513, 0.8446, 0.8116, 0.1698, 0.6665, 0.3376, 0.8438, 0.6839,
          0.4616],
         [0.8740, 0.5422, 0.0165, 0.8561, 0.7294, 0.3002, 0.8806, 0.4817, 0.6837,
          0.2224],
         [0.9116, 0.1909, 0.5668, 0.0351, 0.1990, 0.2575, 0.3091, 0.9088, 0.8170,
          0.0043],
         [0.2753, 0.0154, 0.6505, 0.4634, 0.1127, 0.4970, 0.3040, 0.3445, 0.8309,
          0.1767],
         [0.4482, 0.4008, 0.1151, 0.1501, 0.7122, 0.2017, 0.7427, 0.7841, 0.4604,
          0.8754],
         [0.1428, 0.4605, 0.8928, 0.5830, 0.9445, 0.6096, 0.0723, 0.9198, 0.3845,
          0.9378],
         [0.8379, 0.5845, 0.3492, 0.4667, 0.0021, 0.7452, 0.9432, 0.5371, 0.2272,
          0.4878]]),
 tensor([[0.0098, 0.2412, 0.0468, 0.8986, 0.6931, 0.8588, 0.5396, 0.2338, 0.6108,
          0.5326, 0.2469, 0.4281],
         [0.6372, 0.3902, 0.7307, 0.6787, 0.0254, 0.8702, 0.3233, 0.8955, 0.7436,
          0.3276, 0.5380, 0.6280],
         [0.6978, 0.5261, 0.4289, 0.5088, 0.0057, 0.7855, 0.6461, 0.4029, 0.9442,
          0.4653, 0.4173, 0.3630],
         [0.3571, 0.1008, 0.2831, 0.6438, 0.2404, 0.8769, 0.2470, 0.1786, 0.6707,
          0.2115, 0.4791, 0.6347],
         [0.4994, 0.4722, 0.3805, 0.8495, 0.4144, 0.3544, 0.1469, 0.1613, 0.4677,
          0.5428, 0.6903, 0.6059],
         [0.5571, 0.0108, 0.8758, 0.1824, 0.0495, 0.2206, 0.7634, 0.6089, 0.6091,
          0.7605, 0.0304, 0.9115],
         [0.6247, 0.7780, 0.6746, 0.5937, 0.9582, 0.4665, 0.1535, 0.3081, 0.5820,
          0.3078, 0.5672, 0.5641],
         [0.7092, 0.3173, 0.3148, 0.2232, 0.8313, 0.3866, 0.4686, 0.6559, 0.5608,
          0.6785, 0.7752, 0.5868],
         [0.4988, 0.0383, 0.4058, 0.8235, 0.0457, 0.5461, 0.8810, 0.8300, 0.8974,
          0.4875, 0.1180, 0.0536],
         [0.1132, 0.7781, 0.3727, 0.0455, 0.3466, 0.0797, 0.6039, 0.8110, 0.1953,
          0.8152, 0.0224, 0.1172]]),
 tensor([[0.3185, 0.0626, 0.1491],
         [0.7185, 0.5924, 0.6137],
         [0.7301, 0.1023, 0.8310],
         [0.0774, 0.6267, 0.7447],
         [0.3213, 0.9013, 0.0455],
         [0.4810, 0.0161, 0.9152],
         [0.7055, 0.2708, 0.6210],
         [0.5288, 0.9620, 0.6349],
         [0.6728, 0.0289, 0.7024],
         [0.4016, 0.7553, 0.5207]]))

tuple

In [800]:
display(row_split_2, type(row_split_2))

(tensor([[0.4032, 0.2665, 0.5689, 0.9558, 0.7335, 0.7716, 0.5554, 0.3178, 0.9897,
          0.5315, 0.0098, 0.2412, 0.0468, 0.8986, 0.6931, 0.8588, 0.5396, 0.2338,
          0.6108, 0.5326, 0.2469, 0.4281, 0.3185, 0.0626, 0.1491]]),
 tensor([[0.2311, 0.8909, 0.6141, 0.2340, 0.3224, 0.8999, 0.0766, 0.6744, 0.8163,
          0.0356, 0.6372, 0.3902, 0.7307, 0.6787, 0.0254, 0.8702, 0.3233, 0.8955,
          0.7436, 0.3276, 0.5380, 0.6280, 0.7185, 0.5924, 0.6137],
         [0.8391, 0.8178, 0.6335, 0.4885, 0.2518, 0.1025, 0.8629, 0.9401, 0.0244,
          0.4913, 0.6978, 0.5261, 0.4289, 0.5088, 0.0057, 0.7855, 0.6461, 0.4029,
          0.9442, 0.4653, 0.4173, 0.3630, 0.7301, 0.1023, 0.8310]]),
 tensor([[0.0269, 0.1513, 0.8446, 0.8116, 0.1698, 0.6665, 0.3376, 0.8438, 0.6839,
          0.4616, 0.3571, 0.1008, 0.2831, 0.6438, 0.2404, 0.8769, 0.2470, 0.1786,
          0.6707, 0.2115, 0.4791, 0.6347, 0.0774, 0.6267, 0.7447],
         [0.8740, 0.5422, 0.0165, 0.8561, 0.7294, 0.3002, 0.8806, 0.4817, 0.6837,
          0.2224, 0.4994, 0.4722, 0.3805, 0.8495, 0.4144, 0.3544, 0.1469, 0.1613,
          0.4677, 0.5428, 0.6903, 0.6059, 0.3213, 0.9013, 0.0455],
         [0.9116, 0.1909, 0.5668, 0.0351, 0.1990, 0.2575, 0.3091, 0.9088, 0.8170,
          0.0043, 0.5571, 0.0108, 0.8758, 0.1824, 0.0495, 0.2206, 0.7634, 0.6089,
          0.6091, 0.7605, 0.0304, 0.9115, 0.4810, 0.0161, 0.9152]]),
 tensor([[0.2753, 0.0154, 0.6505, 0.4634, 0.1127, 0.4970, 0.3040, 0.3445, 0.8309,
          0.1767, 0.6247, 0.7780, 0.6746, 0.5937, 0.9582, 0.4665, 0.1535, 0.3081,
          0.5820, 0.3078, 0.5672, 0.5641, 0.7055, 0.2708, 0.6210],
         [0.4482, 0.4008, 0.1151, 0.1501, 0.7122, 0.2017, 0.7427, 0.7841, 0.4604,
          0.8754, 0.7092, 0.3173, 0.3148, 0.2232, 0.8313, 0.3866, 0.4686, 0.6559,
          0.5608, 0.6785, 0.7752, 0.5868, 0.5288, 0.9620, 0.6349],
         [0.1428, 0.4605, 0.8928, 0.5830, 0.9445, 0.6096, 0.0723, 0.9198, 0.3845,
          0.9378, 0.4988, 0.0383, 0.4058, 0.8235, 0.0457, 0.5461, 0.8810, 0.8300,
          0.8974, 0.4875, 0.1180, 0.0536, 0.6728, 0.0289, 0.7024],
         [0.8379, 0.5845, 0.3492, 0.4667, 0.0021, 0.7452, 0.9432, 0.5371, 0.2272,
          0.4878, 0.1132, 0.7781, 0.3727, 0.0455, 0.3466, 0.0797, 0.6039, 0.8110,
          0.1953, 0.8152, 0.0224, 0.1172, 0.4016, 0.7553, 0.5207]]))

tuple

In [839]:
# Since the splitted tensors along row or column dimensions are stored in tuples, they do not change
# even if the original tensor initializes randomly each time updated
# torch.split() requires chunk size as input while torch.chunk() requires the number of total chunks to be taken from the tensor
# and torch.chunk() specifies the size of each chunk depending on the total number of chunks the tensor must be splitted

data = torch.rand(6,7)
row_chunk = torch.chunk(data, 3, dim=0) # dim=0 along rows and in total there must be 3 chunks
print(f"Original tensor:\n{data}\n{data.shape}\n")
print("Tensor rows are splitted into 3 chunks:", end=" ")
for i, cup in enumerate(row_chunk):
    print(f"\nChunk shape{cup.shape}\n{cup}\n")

print("Tensor columns are splitted into 5 chunks:", end=" ")
col_chunk = torch.chunk(data, 5, dim=1)
for i, cup in enumerate(col_chunk):
    print(f"\nChunk shape{cup.shape}\n{cup}\n")

Original tensor:
tensor([[0.1045, 0.0863, 0.5751, 0.6409, 0.5114, 0.5787, 0.5644],
        [0.2856, 0.3925, 0.4852, 0.9777, 0.7159, 0.5573, 0.3067],
        [0.4334, 0.6696, 0.5189, 0.1549, 0.9224, 0.5600, 0.3944],
        [0.7698, 0.1562, 0.2757, 0.0176, 0.8966, 0.5232, 0.4803],
        [0.0809, 0.6718, 0.1052, 0.0651, 0.3589, 0.1446, 0.9719],
        [0.3556, 0.3636, 0.2126, 0.8544, 0.0205, 0.8106, 0.7103]])
torch.Size([6, 7])

Tensor rows are splitted into 3 chunks:
Chunk shapetorch.Size([2, 7])
tensor([[0.1045, 0.0863, 0.5751, 0.6409, 0.5114, 0.5787, 0.5644],
        [0.2856, 0.3925, 0.4852, 0.9777, 0.7159, 0.5573, 0.3067]])


Chunk shapetorch.Size([2, 7])
tensor([[0.4334, 0.6696, 0.5189, 0.1549, 0.9224, 0.5600, 0.3944],
        [0.7698, 0.1562, 0.2757, 0.0176, 0.8966, 0.5232, 0.4803]])


Chunk shapetorch.Size([2, 7])
tensor([[0.0809, 0.6718, 0.1052, 0.0651, 0.3589, 0.1446, 0.9719],
        [0.3556, 0.3636, 0.2126, 0.8544, 0.0205, 0.8106, 0.7103]])

Tensor columns are splitted into 5 chunks:
Chunk shapetorch.Size([6, 2])
tensor([[0.1045, 0.0863],
        [0.2856, 0.3925],
        [0.4334, 0.6696],
        [0.7698, 0.1562],
        [0.0809, 0.6718],
        [0.3556, 0.3636]])


Chunk shapetorch.Size([6, 2])
tensor([[0.5751, 0.6409],
        [0.4852, 0.9777],
        [0.5189, 0.1549],
        [0.2757, 0.0176],
        [0.1052, 0.0651],
        [0.2126, 0.8544]])


Chunk shapetorch.Size([6, 2])
tensor([[0.5114, 0.5787],
        [0.7159, 0.5573],
        [0.9224, 0.5600],
        [0.8966, 0.5232],
        [0.3589, 0.1446],
        [0.0205, 0.8106]])


Chunk shapetorch.Size([6, 1])
tensor([[0.5644],
        [0.3067],
        [0.3944],
        [0.4803],
        [0.9719],
        [0.7103]])

In [4]:
# While torch.split() takes chunk-size as input or list of chunk-sizes as input, the torch.chunk()
# takes the total number of desired chunks, and if it the number of chunks is not perfectly divisible by the given dimension
# then the last chunk's size will be smaller, overall we are not defining the chunk-size as it is being done for us.
# but rather we are defining the number of chunks we want to split the original tensor.
# for torch.chunk() we care about the number of chunks, their size is of low importance
# for torch.split() we care about the size of individual chunk, the total number of individual chunks is of low importance

# Broadcasting

In [20]:
# In order for two tensors be broadcastable, element-wise dimensions from right to left, must follow at least one of 3 rules
# 1. Each dimension must be equal
# 2. At least one dimension must be 1
# 3. Or one dimension should be empty
# In order to avoid manual change of each tensors, these statements must be met for tensors to be broadcastable

a = torch.arange(15).view(5,3)
b = torch.tensor(4)
c = a + b
c_ = torch.add(a,b)

print(f"Tensor A info: {a.shape, a.device, a.is_cpu, a.is_mps, a.dtype, type(a)}")
print(f"Scanar B info: {b.shape, b.device, b.is_cpu, b.is_mps, b.dtype, type(b)}")
print(f"Tensor C info: {c.shape, c.device, c.is_cpu, c.is_mps, c.dtype, type(c)}")

# In this case, the scalar/singular value is a tensor of empty dimension since it is 0-dimensional
# and because as it is stated above, scalar has empty dimension or 0-dimension, it is broadcastable
# and this singular value is expanded to match the shape of the tensor and element-wise opeation is performed for each
# element of the tensor

Tensor A info: (torch.Size([5, 3]), device(type='cpu'), True, False, torch.int64, <class 'torch.Tensor'>)
Scanar B info: (torch.Size([]), device(type='cpu'), True, False, torch.int64, <class 'torch.Tensor'>)
Tensor C info: (torch.Size([5, 3]), device(type='cpu'), True, False, torch.int64, <class 'torch.Tensor'>)

In [33]:
s = torch.tensor(5)
f = torch.tensor([5])

print(f"Tensor/Scalar dimension of torch.tensor(5), without []: {s.shape}")
print(f"Tensor/Scalar dimension of torch.tensor([5]), by using []: {f.shape}")

# Look, when no square brackets are used [], the dimension of tensor/scalar is zero
# while, by using square brackets [], the dimension is one
# In both cases these scalar/tensor values are broadcastable since they meet 2 of 3 at least needed requirements
# which are one of two tensors, either must have dimension of 1 or be empty(the same as having zero dimension)

# Therefore these scalar/tensor values are broadcastable to any tensors they are being used for element-wise operations
a = torch.rand(5,6)
print(torch.add(a,s,f))
print(torch.mul(a,s))
print(torch.sub(a,s,f))

Tensor/Scalar dimension of torch.tensor(5), without []: torch.Size([])
Tensor/Scalar dimension of torch.tensor([5]), by using []: torch.Size([1])
tensor([[25.9251, 25.1830, 25.6939, 25.0616, 25.7822, 25.4442],
        [25.2247, 25.8715, 25.1613, 25.6851, 25.8000, 25.2355],
        [25.1913, 25.9505, 25.8545, 25.3986, 25.5565, 25.5515],
        [25.5750, 25.2453, 25.2338, 25.6556, 25.9781, 25.5161],
        [25.2935, 25.6953, 25.1240, 25.8574, 25.9913, 25.9949]])
tensor([[4.6253, 0.9150, 3.4697, 0.3079, 3.9109, 2.2208],
        [1.1234, 4.3577, 0.8067, 3.4256, 3.9998, 1.1776],
        [0.9563, 4.7525, 4.2723, 1.9929, 2.7824, 2.7576],
        [2.8751, 1.2263, 1.1688, 3.2782, 4.8907, 2.5804],
        [1.4675, 3.4764, 0.6200, 4.2871, 4.9565, 4.9743]])
tensor([[-24.0749, -24.8170, -24.3061, -24.9384, -24.2178, -24.5558],
        [-24.7753, -24.1285, -24.8387, -24.3149, -24.2000, -24.7645],
        [-24.8087, -24.0495, -24.1455, -24.6014, -24.4435, -24.4485],
        [-24.4250, -24.7547, -24.7662, -24.3444, -24.0219, -24.4839],
        [-24.7065, -24.3047, -24.8760, -24.1426, -24.0087, -24.0051]])

In [8]:
# If dimension of one tensor is fewer than the other, in that case, the missing dimension of first tensor
# will be treated as having dimension of one, such as [2,3,3] and [3,3], here since [3,3] has fewer dimensions
# than [2,3,3], then [3,3] is treated as [1,3,3], as having one dimension in the place of missing dimension

# Always remember that for broadcasting the dimensions are compared against from the right to left
# starting comparison from the rightmost dimension to the left.

# If one of the dimension of the tensor is 1, then the dimension of the other(larger) tensor's dimension replaces that 1-d
# For instance for tensors of shapes [2,3] and [1,3], look we start comparing from the rigth to the left
# since 3 and 3 are equal we compare the next left dimension, and look just like mentioned above, one of the dimension
# of these two tensors is 1, and it is not possible to do element-wise operations without changing that 1
# therefore that 1 is changed to the dimension of the other(larger) tensor, which is 2 in this case
# hence automatically 1 becomes 2, since it meets one of three requirements, this tensor is broadcastable

# ROW VECTOR has dimension of [1, n] but in terms of tensors it is written as [n]
# COLUMN VECTOR has dimension of [n, 1], and shown as it is for tensors as well

a = torch.arange(8).reshape(2,4)
b = torch.tensor([3,5,7,1])

print(f"Shapes of matrix/tensor A: {a.shape}, and shape of row vector/tensor B: {b.shape}\
\n row vector/tensor of B dimensions is shown as [4], but in reality it is [1,4], we get the one since \n\
 tensor B has fewer dimension compared to tensor A, and in place of empty/missing dimension is filled with one.")

# These tensors meet the broadcastable requirements hence, we can perform element-wise operations with them
c = a + b
c = torch.add(a,b)
c_mul = torch.mul(a,b)
c_div = torch.div(a,b)
print(f"\nInitial values of tensors:\n{a}\n{b}\n")
print(f"Tensor C shape {c.shape}, \n{c}")

Shapes of matrix/tensor A: torch.Size([2, 4]), and shape of row vector/tensor B: torch.Size([4])
 row vector/tensor of B dimensions is shown as [4], but in reality it is [1,4], we get the one since
 tensor B has fewer dimension compared to tensor A, and in place of empty/missing dimension is filled with one.

Initial values of tensors:
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([3, 5, 7, 1])

Tensor C shape torch.Size([2, 4]),
tensor([[ 3,  6,  9,  4],
        [ 7, 10, 13,  8]])

In [19]:
a = torch.arange(20).reshape(2,2,5)
b = torch.arange(5).view(1,1,5) # [1,1,5], all the ones become twos 
print(f"Initial tensors A and B: \n{a}\n{b}\n")
print(f"Shape of A: {a.shape} of B: {b.shape}")

# Look two elements dimension of tensor is equal to 1, while others are equal
# Basically 1, changes to the value of other(larger) tensor for that particular dimension element

c_plus = torch.add(a,b)
print(f"{c_plus}\nShape of C: {c_plus.shape}") # [2,2,5]
c_diff = torch.sub(a,b)
c_pow = torch.pow(a,b)
c_mul = torch.mul(a,b)
c_div = torch.div(b,a)
display(c_diff, c_pow, c_mul, c_div)

Initial tensors A and B:
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])
tensor([[[0, 1, 2, 3, 4]]])

Shape of A: torch.Size([2, 2, 5]) of B: torch.Size([1, 1, 5])
tensor([[[ 0,  2,  4,  6,  8],
         [ 5,  7,  9, 11, 13]],

        [[10, 12, 14, 16, 18],
         [15, 17, 19, 21, 23]]])
Shape of C: torch.Size([2, 2, 5])

tensor([[[ 0,  0,  0,  0,  0],
         [ 5,  5,  5,  5,  5]],

        [[10, 10, 10, 10, 10],
         [15, 15, 15, 15, 15]]])

tensor([[[     1,      1,      4,     27,    256],
         [     1,      6,     49,    512,   6561]],

        [[     1,     11,    144,   2197,  38416],
         [     1,     16,    289,   5832, 130321]]])

tensor([[[ 0,  1,  4,  9, 16],
         [ 0,  6, 14, 24, 36]],

        [[ 0, 11, 24, 39, 56],
         [ 0, 16, 34, 54, 76]]])

tensor([[[   nan, 1.0000, 1.0000, 1.0000, 1.0000],
         [0.0000, 0.1667, 0.2857, 0.3750, 0.4444]],

        [[0.0000, 0.0909, 0.1667, 0.2308, 0.2857],
         [0.0000, 0.0625, 0.1176, 0.1667, 0.2105]]])

In [26]:
# Row Vector

a = torch.arange(24).view(4,6)
b = torch.tensor([2,3,4,5,6,1]) # torch.Size[4], a row vector, but it reality it is [1,4]
# broadcastable
c_plus = torch.add(a,b)
c_diff = torch.sub(a,b)
c_mul = torch.mul(a,b)
c_pow = torch.pow(b,a)
c_div = torch.div(a,b)

print(f"Initial Tensors:\n{a}\n{b}\n")
display(c_plus, c_diff, c_mul, c_pow, c_div)

Initial Tensors:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([2, 3, 4, 5, 6, 1])

tensor([[ 2,  4,  6,  8, 10,  6],
        [ 8, 10, 12, 14, 16, 12],
        [14, 16, 18, 20, 22, 18],
        [20, 22, 24, 26, 28, 24]])

tensor([[-2, -2, -2, -2, -2,  4],
        [ 4,  4,  4,  4,  4, 10],
        [10, 10, 10, 10, 10, 16],
        [16, 16, 16, 16, 16, 22]])

tensor([[  0,   3,   8,  15,  24,   5],
        [ 12,  21,  32,  45,  60,  11],
        [ 24,  39,  56,  75,  96,  17],
        [ 36,  57,  80, 105, 132,  23]])

tensor([[                 1,                  3,                 16,
                        125,               1296,                  1],
        [                64,               2187,              65536,
                    1953125,           60466176,                  1],
        [              4096,            1594323,          268435456,
                30517578125,      2821109907456,                  1],
        [            262144,         1162261467,      1099511627776,
            476837158203125, 131621703842267136,                  1]])

tensor([[ 0.0000,  0.3333,  0.5000,  0.6000,  0.6667,  5.0000],
        [ 3.0000,  2.3333,  2.0000,  1.8000,  1.6667, 11.0000],
        [ 6.0000,  4.3333,  3.5000,  3.0000,  2.6667, 17.0000],
        [ 9.0000,  6.3333,  5.0000,  4.2000,  3.6667, 23.0000]])

In [31]:
# Column vector

a = torch.arange(20,44).view(4,6)
b = torch.tensor([[1],[2],[3],[4]]) # column vector of shape 4 by 1
# We could also create a row vector and transpose it, to get a column vector, which is much easier and accurate than manually doing it
print(f"Initial tensors A and B: \n{a}\n{b}\nTheir shapes: {a.shape}, {b.shape}")
# Since 4 and 4 match, and one of them has 1, [4,1] will become [4,6] taking the value of the other(larger) dimension of tensor

c_plus = torch.add(a,b)
c_diff = torch.sub(a,b)
c_div = torch.div(a,b)
c_pow = torch.pow(a,b)
c_mul = torch.mul(a,b)
display(c_plus, c_diff, c_div, c_pow, c_mul)

Initial tensors A and B:
tensor([[20, 21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37],
        [38, 39, 40, 41, 42, 43]])
tensor([[1],
        [2],
        [3],
        [4]])
Their shapes: torch.Size([4, 6]), torch.Size([4, 1])

tensor([[21, 22, 23, 24, 25, 26],
        [28, 29, 30, 31, 32, 33],
        [35, 36, 37, 38, 39, 40],
        [42, 43, 44, 45, 46, 47]])

tensor([[19, 20, 21, 22, 23, 24],
        [24, 25, 26, 27, 28, 29],
        [29, 30, 31, 32, 33, 34],
        [34, 35, 36, 37, 38, 39]])

tensor([[20.0000, 21.0000, 22.0000, 23.0000, 24.0000, 25.0000],
        [13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000],
        [10.6667, 11.0000, 11.3333, 11.6667, 12.0000, 12.3333],
        [ 9.5000,  9.7500, 10.0000, 10.2500, 10.5000, 10.7500]])

tensor([[     20,      21,      22,      23,      24,      25],
        [    676,     729,     784,     841,     900,     961],
        [  32768,   35937,   39304,   42875,   46656,   50653],
        [2085136, 2313441, 2560000, 2825761, 3111696, 3418801]])

tensor([[ 20,  21,  22,  23,  24,  25],
        [ 52,  54,  56,  58,  60,  62],
        [ 96,  99, 102, 105, 108, 111],
        [152, 156, 160, 164, 168, 172]])

In [47]:
# row vector and column vector

r = torch.tensor([4,5,6,7])
c = torch.tensor([[4],[5],[6],[7]])
print(f"Shape of Row Vector {r.shape}\nShow of Column Vector{c.shape}")
# Even though for row vector it shows [4] it is actually [1,4] since it has a single row and 4 columns
# For column vector it shows fully

print(f"Row Vector before {r} {r.shape}")
print(f"Row Vector after transposing:\n{r.T} {r.T.shape}")

print(f"Column Vector before:\n{c} {c.T.shape}")
print(f"Column Vector after transposing: {c.t()} {c.T.shape}")

Shape of Row Vector torch.Size([4])
Show of Column Vectortorch.Size([4, 1])
Row Vector before tensor([4, 5, 6, 7]) torch.Size([4])
Row Vector after transposing:
tensor([4, 5, 6, 7]) torch.Size([4])
Column Vector before:
tensor([[4],
        [5],
        [6],
        [7]]) torch.Size([1, 4])
Column Vector after transposing: tensor([[4, 5, 6, 7]]) torch.Size([1, 4])

# Type Casting

In [56]:
a = torch.arange(20, dtype=torch.float32).reshape(4,5)
print(f"Data Type: {a.dtype}\n{a}")
a_ = a.to(torch.int32)
print(f"Data type after type casting: {a_.dtype}\n{a_}")

# Just like we can use .to() for changing the location of tensors from CPU to GPU and vice versa
# We can use to convert its data type, type casting

Data Type: torch.float32
tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])
Data type after type casting: torch.int32
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]], dtype=torch.int32)

In [73]:
a = torch.randn(4,5)
display(a, a.shape)
a_ = a.to(dtype=torch.int8)
display(a_)

# Likewise we can use .float() and long() and bool()
a_long = a.long() # is the same as int64
a_fl = a.float() # is the same as float32
a_bool = a.bool() # acting as boolean masking, 0=False, else True
display(a_long.dtype, a_fl.dtype, a_bool.dtype)

display(a_long, a_fl, a_bool)

tensor([[-0.2596, -1.1229,  1.8660,  1.1105,  1.0734],
        [ 0.6009, -0.2864, -1.2107, -1.3312, -0.1966],
        [ 1.0371, -0.0436, -0.9606, -0.0787,  0.3518],
        [-0.4379,  0.1628, -1.5787,  0.4633,  0.2021]])

torch.Size([4, 5])

tensor([[ 0, -1,  1,  1,  1],
        [ 0,  0, -1, -1,  0],
        [ 1,  0,  0,  0,  0],
        [ 0,  0, -1,  0,  0]], dtype=torch.int8)

torch.int64

torch.float32

torch.bool

tensor([[ 0, -1,  1,  1,  1],
        [ 0,  0, -1, -1,  0],
        [ 1,  0,  0,  0,  0],
        [ 0,  0, -1,  0,  0]])

tensor([[-0.2596, -1.1229,  1.8660,  1.1105,  1.0734],
        [ 0.6009, -0.2864, -1.2107, -1.3312, -0.1966],
        [ 1.0371, -0.0436, -0.9606, -0.0787,  0.3518],
        [-0.4379,  0.1628, -1.5787,  0.4633,  0.2021]])

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [77]:
# .long() is the same as int64
# .float() is the same as float32
# .bool() acts as boolean masking, if 0=False else True
# Data conversion creates a new copy of the original tensor, and will not have reference to original tensor

a = torch.randn(3,5)
a_ = a.to(dtype=torch.int32)
_a_ = a.long() # the same as int64
display(a.dtype, a_.dtype, _a_.dtype)
print(f"Do these tensors share the same memory: {a.storage().data_ptr() == a_.storage().data_ptr()}")
print(f"Do these tensors share the same memory: {a_.storage().data_ptr() == _a_.storage().data_ptr()}")
# Their location in the memory is different, so they do not have reference to each other

torch.float32

torch.int32

torch.int64

Do these tensors share the same memory: False
Do these tensors share the same memory: False

In [80]:
torch.get_default_device()

device(type='cpu')

In [88]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "mps:0" if torch.backends.mps.is_available() else "cpu")
a = torch.rand(4,5, device=device)
display(a.device)

ls = [torch.cuda.get_device_name(k) for k in range(torch.cuda.device_count())]
print(ls)

device(type='mps', index=0)

[]

In [93]:
try:
    a = torch.rand((3,4), device="cuda")
except RuntimeError as e:
    print(f"Could not create tensor directly on CUDA GPU: {e}")
except AssertionError as ae:
    print(f"CUDA is not enabled on this device: {ae}")

CUDA is not enabled on this device: Torch not compiled with CUDA enabled

In [101]:
if a.is_cpu:
    a.to("mps")
a.device
a = a.cpu()
a.device

device(type='cpu')

In [107]:
device.type

'mps'

In [109]:
# We will face a RuntimeError if we try to make computations on tensors stored in two different devices

a = torch.rand(4,5, device = "mps")
b = torch.rand(4,5, device = "cpu") # by default tensors are stored on the CPU

try:
    c = a + b
    print(f"Operations performed successfully, even if they are on the different devices\n{c}")
except RuntimeError as e:
    print(f"Operations of two or more tensors stored in different devices cannot be performed, you need to convert them\
    back to a single device\n{e}")

Operations of two or more tensors stored in different devices cannot be performed, you need to convert them    back to a single device
Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [114]:
x = torch.ones(4,3)
a = torch.tensor([2,3,4])
b = torch.tensor([[2,3,4]])
display(x.shape, a.shape, b.shape)
c = x + a
c_ = x + b
print(f"Shapes after addition: {c.shape} {c_.shape}")

torch.Size([4, 3])

torch.Size([3])

torch.Size([1, 3])

Shapes after addition: torch.Size([4, 3]) torch.Size([4, 3])

# AutoGrad

In [2]:
torch.get_default_device()

device(type='cpu')

In [3]:
torch.get_default_dtype()

torch.float32

In [15]:
img = torch.rand(16,32,64,128,3)
display(img.shape[1])
display(img.shape)
c = img.permute(4,0,1,2,3).contiguous().view(img.shape[0], -1)
print(c.shape)
f = img.reshape(-1)
print(f.shape)

32

torch.Size([16, 32, 64, 128, 3])

torch.Size([16, 786432])
torch.Size([12582912])

In [48]:
a = torch.rand(3,4,5,10)
extract = a[0,0,3:,4]


b = torch.rand(4,5,10)
et = a[0,:,-2:]
display(et.shape)

torch.Size([4, 2, 10])

In [56]:
import torch

w = torch.tensor(5.0, requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

y = w * x # or torch.mul(w, x)
z = y + b # or torch.add(y, b)
print(f"Result z: {z}")

Result z: 16.0

In [69]:
w = torch.rand(3,4, requires_grad=True)
x = torch.rand(3,4, requires_grad=True)
b = torch.arange(3.0, requires_grad=True).view(3,1)

y = torch.mul(w,x)
z = torch.add(y,b)
print(f"Result z:\n{z}\n{z.shape, z.device}")

Result z:
tensor([[0.0909, 0.1682, 0.1878, 0.3820],
        [1.1382, 1.4012, 1.3964, 1.1866],
        [2.0526, 2.0295, 2.1878, 2.0068]], grad_fn=<AddBackward0>)
(torch.Size([3, 4]), device(type='cpu'))

In [78]:
# So any tensors that have requires_grad=True, will be recorded by PyTorch in grad_fn
# and any operations performed on them and associated in the variable, which are called intermediate tensors
# and therefore any other tensors without requires_grad=True or an intermediate variable without those grad tensor operations
# will not be recorded or included in the comptionational graph on the PyTorch

w = torch.rand(5,6, requires_grad=True)
x = torch.rand(6,5, requires_grad=True)
b = torch.rand(5,1, requires_grad=True)

y = torch.matmul(w,x)
z = torch.add(y,b)
print(f"Result z:\n{z}\n{z.shape}")

# grad_fn=<AddBackward0> has a reference to a sequential order of all the operations/functions performed on tensors
# that have requires_grad=True enabled, even including intermediate variables which did not have that enabled
# but did have tensors which have it enabled and operations were performed on them
display(z.grad_fn)

Result z:
tensor([[2.5217, 2.6221, 2.4600, 2.6091, 1.4784],
        [1.5324, 1.9483, 1.7585, 1.9915, 1.1791],
        [2.2603, 2.3784, 2.3125, 2.4800, 1.3092],
        [1.1756, 1.3836, 1.3794, 1.4984, 0.6779],
        [2.5021, 2.7108, 2.4398, 2.4713, 1.7434]], grad_fn=<AddBackward0>)
torch.Size([5, 5])

In [80]:
# we use .backward() for the final output (final a single loss value) and it uses
# grad_fn=<AddBackward0> in order to use chain rule to traverse back to the initial input value
# by following all the operations/functions on tensors in the reverse-mode order in order to calculate 
# how much the final loss is affected by a single change in input and intermediate tensors

# All the PyTorch tensors have boolean attribute of requires_grad, which is set to False by default
# it is used in order for PyTorch know which tensors should be recorded for the potential computations of gradients
# since not all tensors require gradients, makes sence by default to be as False or otherwise it would consume
# extra memory and computation

a = torch.rand(3,5).view(5,3)
print(f"Does this tensor have requires_grad enabled by default: {a.requires_grad}")
b = torch.rand(6,7, requires_grad=False) # it is False by default anyways 
print(f"Does this tensor have requires_grad enabled by default: {b.requires_grad}")

# ONLY those tensors that have requires_grad, will be recorded by AutoGrad for 
# computing the gradient, including the intermediate variables that simply store and provide reference
# to the results of operations performed on grad enabled tensors

Does this tensor have requires_grad enabled by default: False
Does this tensor have requires_grad enabled by default: False

In [82]:
# There are two ways to have tell the AutoGrad of PyTorch to track the tensors for potential gradient computation

# enable at creation time, by passing as an argument
a = torch.rand(4,5, requires_grad=True)
print(f"Is grad is enabled: {a.requires_grad}")

# or enable it after tensor creation
b = torch.rand(5,6)
print(f"Before: {b.requires_grad}")
b.requires_grad_(True) # This function enabled the requires_grad after creation of the tensor
print(f"After: {b.requires_grad}")

Is grad is enabled: True
Before: False
After: True

In [85]:
a = torch.rand(9,4).view(3,3,2,2)
print(f"Before: {a.requires_grad}")
a.requires_grad_(True)
print(f"After: {a.requires_grad}")

Before: False
After: True

In [88]:
a = torch.arange(10,100, 0.1, requires_grad=True).view(10,90)
display(a.requires_grad) # check if it is being tracked by AutoGrad for computations of gradients

True

In [100]:
# since gradients involve continuous values, trying to have requires_grad=True on integer values will show RuntimeError
# because gradients represented by discrete numbers will produce a huge round-off errors
# mathematically gradients will be inaccurate

a = torch.rand(6,7,8)
a = a.permute(2,1,0)
display(a.is_contiguous())
display(a.shape)
display(a.requires_grad)
a.requires_grad_(False)
display(a.requires_grad)
a.requires_grad_(True)
display(a.requires_grad)

False

torch.Size([8, 7, 6])

False

False

True

In [103]:
try:
    a = torch.arange(50).view(5,5,2)
    a.requires_grad_(True)
    display(a.requires_grad)
except RuntimeError as e:
    print(f"Integer dtype tensors cannot have requires_grad enabled, since gradients by nature are continuous values: \n{e}")
    print(a.requires_grad)

Integer dtype tensors cannot have requires_grad enabled, since gradients by nature are continuous values:
only Tensors of floating point dtype can require gradients
False

In [106]:
# If any tensor, if at least one tensor has gradients enabled, then the resulting output will also have
# requires_grad=True enabled, because not all input tensors will requires operations such as 
# feature tensor which stores independent variables, but we do not need gradients for them, since we do not aim to change them

x = torch.arange(10,20,0.1).view(4,5,5) # requires_grad=False is not enabled
w = torch.rand(5,5, requires_grad=True)
b = torch.randn(4,5,1)
b.requires_grad_(True)

print(f"x: {x.requires_grad}, w: {w.requires_grad}, b: {b.requires_grad}\n")

intermediate = w * x # or torch.mul(w,x)
print(f"Does Intermediate variable's output has requires_grad=True when at least one tensors has it enabled for operations: \
{intermediate.requires_grad}")

y = intermediate + b # or torch.add(intermediate, b)
print(f"Does the final output has requires_grad=True enabled if at least one of its tensors has it enabled for operation:\
{y.requires_grad}")

x: False, w: True, b: True

Does Intermediate variable's output has requires_grad=True when at least one tensors has it enabled for operations: True
Does the final output has requires_grad=True enabled if at least one of its tensors has it enabled for operation:True

In [125]:
a = torch.rand(5,6, requires_grad=True)
b = torch.arange(30).view(1,5,6)
c = torch.randn(4,5,6)
d = torch.rand(6)
e = torch.ones(1,5,1)
f = torch.zeros(4,1,6)
output = a + b + c + d + e + f + 4 * torch.tensor(6) + torch.tensor([456])
print(f"Does output have requires_grad=True, even if only one of its tensor had it enabled for operations: \
{output.requires_grad}\nNotice all these tensors are broadcastable and their resulting shape is: {output.shape}") # 4,5,6

Does output have requires_grad=True, even if only one of its tensor had it enabled for operations: True
Notice all these tensors are broadcastable and their resulting shape is: torch.Size([4, 5, 6])

In [150]:
# grad_fn attribute is attached to all tensors that have gradients required enabled, or resulting output tensors
# grad_fn will be None for manually created tensors which did not result from any operations of grad tensors
# grad_fn will have the name of the function for the tensors that were resulted from the operation of grad tensors

x = torch.rand(4,5)
w = torch.randn(5,4, requires_grad=True)
b = torch.ones(5,1, requires_grad=True) # or b.requires_grad_(True)
display(x.requires_grad, w.requires_grad, b.requires_grad)
print(f"grad_fn of leaf tensors, x: {x.grad_fn}, w: {w.grad_fn}, b: {b.grad_fn}\n")
intermediate = torch.matmul(w,x) 
print(f"Intermediate requires_grad={intermediate.requires_grad}\nIntermediate variable grand_fn: {intermediate.grad_fn}")
output = intermediate + b
print(f"Output requires_grad={output.requires_grad}\nOutput variable grand_fn: {output.grad_fn}")

False

True

True

grad_fn of leaf tensors, x: None, w: None, b: None

Intermediate requires_grad=True
Intermediate variable grand_fn: <MmBackward0 object at 0x11f894580>
Output requires_grad=True
Output variable grand_fn: <AddBackward0 object at 0x11f894580>

In [5]:
# grad_fn is basically a reference to what function was applied for the tensors with gradients required
# then .backward() will use grad_fn references for computing the gradients from output to input by following
# what functions were used in the reverse-mode order

# AGAIN for leaf tensors, leaf meaning they are outside, manually created have grad_fn=None
# since they were not created through operations or passing through a function.
# non-leaf tensors represent tensors which are created through operations or passing through function
# the tensors with gradients required, non-leaf meaning they did not come from outside but rather created
# from the those that came outside with gradients enabled

a = torch.rand(4,5)
b = torch.rand(4,5)
print(a.grad_fn, b.grad_fn, a.requires_grad, b.requires_grad)
a.requires_grad_(True)
b.requires_grad_(True)
print(a.grad_fn, b.grad_fn, a.requires_grad, b.requires_grad)
c_plus = torch.add(a,b)
c_div = torch.div(a,b)
c_sub = torch.sub(a,b)
c_pow = torch.pow(a,b)
c_mul = torch.mul(a,b)
c_exp = torch.exp(a)
c_log = torch.log(b)
c_sqrt = torch.sqrt(a)
c_abs = torch.abs(b)
c_matmul = a @ b.T # or torch.matmul(a,b)

print(f"grad_fn list:\nc_plus: {c_plus.grad_fn}\nc_div: {c_div.grad_fn}\nc_sub: {c_sub.grad_fn}\nc_pow: {c_pow.grad_fn}\n\
c_mul: {c_mul.grad_fn}\nc_exp: {c_exp.grad_fn}\nc_log: {c_log.grad_fn}\nc_sqrt: {c_sqrt.grad_fn}\nc_abs: {c_abs.grad_fn}\n\
c_matmul: {c_matmul.grad_fn}")

None None False False
None None True True
grad_fn list:
c_plus: <AddBackward0 object at 0x105e58b20>
c_div: <DivBackward0 object at 0x105e58b20>
c_sub: <SubBackward0 object at 0x105e58b20>
c_pow: <PowBackward1 object at 0x105e58b20>
c_mul: <MulBackward0 object at 0x105e58b20>
c_exp: <ExpBackward0 object at 0x105e58b20>
c_log: <LogBackward0 object at 0x105e58b20>
c_sqrt: <SqrtBackward0 object at 0x105e58b20>
c_abs: <AbsBackward0 object at 0x105e58b20>
c_matmul: <MmBackward0 object at 0x105e58b20>

In [60]:
a = torch.rand(4,9)
b = torch.rand(4)
a.requires_grad_(True)

c = torch.matmul(b,a) # b is treated as shape[1,4] row vector
display(c.requires_grad, c.grad_fn, c)
# in this case we used inner matmul which effectively Squeezed the original two grad tensors into a flattened tensor

True

tensor([1.3965, 0.7085, 1.4566, 0.6300, 0.3112, 0.8569, 1.5620, 1.1497, 1.3617],
       grad_fn=<SqueezeBackward4>)

In [70]:
a = torch.randn(3,98,6, requires_grad=True)
b = torch.randn(3,6,12)
c = torch.matmul(a,b)
display(c.requires_grad, c.grad_fn)

True

In [66]:
a = torch.rand(4,9)
b = torch.rand(4)
b.requires_grad_(True)
display(a.requires_grad, b.requires_grad)
c_sq = b @ a
display(c.grad_fn)

False

True

In [106]:
x = torch.rand(34,7)
w = torch.rand(3,34,1, requires_grad=True)
b = torch.rand(34,1, requires_grad=True)
print(f"Requires_grad status x: {x.requires_grad}, w: {w.requires_grad}, b: {b.requires_grad}")

intermediate = x * w
print(f"Intermediate(non-leaf) tensor: is grad enabled even if \"x\" does not have grad enabled: {intermediate.requires_grad}\n\
Gradient function of intermediate(non-leaf) tensor {intermediate.grad_fn}")

output = intermediate + b
print(f"Output(final loss) tensor: is grad enabled: {output.requires_grad}\n\
Gradient function of output(final loss) tensor: {output.grad_fn}")

a = torch.rand(2,5,6)
b = torch.ones(2,6,5)
c = a @ b # torch.matmul(a,b)
display(c.grad_fn) 
# It will show non, because tensors used for operations, none of them, or at least one of them, do not have
# gradients required so PyTorch is not recording it for potential gradient computation
a.requires_grad_(True)
display(c.requires_grad, c.grad_fn) # so it will still show False and None because
# even though A was enabled with gradients requiring, it was done after all the operations were completed
# that is why, always set the requires_grad=True before doing any operations
e = a @ b
display(e.requires_grad, e.grad_fn) # now it works because gradient required was enabled before doing any operations
# hence creating a new non-leaf/intermediate tensor
display(e.grad)

Requires_grad status x: False, w: True, b: True
Intermediate(non-leaf) tensor: is grad enabled even if "x" does not have grad enabled: True
Gradient function of intermediate(non-leaf) tensor <MulBackward0 object at 0x13d6c61c0>
Output(final loss) tensor: is grad enabled: True
Gradient function of output(final loss) tensor: <AddBackward0 object at 0x13d6c61c0>

None

False

None

True

/var/folders/1x/9lpkf83945l_89078l86mxm80000gn/T/ipykernel_7435/3273315041.py:27: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_951ooclnw1/croot/libtorch_1746637517770/work/build/aten/src/ATen/core/TensorBody.h:494.)
  display(e.grad)

None

In [108]:
a = torch.tensor(5)
b = torch.tensor([5])
c = torch.tensor([[5]])
e = torch.tensor([[[5]]])
display(a.shape,b.shape,c.shape,e.shape)

torch.Size([])

torch.Size([1])

torch.Size([1, 1])

torch.Size([1, 1, 1])

In [116]:
# the real work or engine of AutoGrad starts when we use .backward() on the scalar tensor
# which is usually final output or loss function value

x = torch.tensor(4.0, requires_grad=True)
w = torch.tensor(4.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

y = w * x + b # or torch.add(torch.mul(w,x),b)
loss = y * y

# Gradients of tensors before backward pass
print(f"Gradients of X before backward pass: {x.grad}")
print(f"Gradients of W before backward pass: {w.grad}")
print(f"Gradients of B before backward pass: {b.grad}\n")

loss.backward() 
# now the real work begins with .backward()
# now AutoGrad goes backwards, by tracking the tensors which have gradients required and any non-leaf tensors
# and corresponding functions performed on them in the sequential reverse order


print(f"Gradients of X after backward pass: {x.grad}")
print(f"Gradients of W before backward pass: {w.grad}")
print(f"Gradients of B before backward pass: {b.grad}\n")

Gradients of X before backward pass: None
Gradients of W before backward pass: None
Gradients of B before backward pass: None

Gradients of X after backward pass: 136.0
Gradients of W before backward pass: 136.0
Gradients of B before backward pass: 34.0

In [141]:
x = torch.tensor(43, dtype=torch.float64, requires_grad=True)
w = torch.tensor(67, dtype=torch.float32, requires_grad=True)
b = torch.tensor(18)
b = b.to(dtype=torch.float64)
b.requires_grad_(True)

y = w * x + b
loss = torch.mul(y,y)
display(loss.requires_grad)
display(y.grad_fn)
display(loss.grad_fn)
print(f"Gradients before backward pass: {x.grad, w.grad, b.grad}\n")
loss.backward()
print(f"Gradients after backward pass: {x.grad, w.grad, b.grad}")
print(f"Gradients after backward pass: {x.grad}, {w.grad}, {b.grad}")

True

Gradients before backward pass: (None, None, None)

Gradients after backward pass: (tensor(388466., dtype=torch.float64), tensor(249314.), tensor(5798., dtype=torch.float64))
Gradients after backward pass: 388466.0, 249314.0, 5798.0

In [30]:
x = torch.rand(4,5, requires_grad=True)
w = torch.randn(4,5, requires_grad=True)
b = torch.rand(4,1, requires_grad=True)

y = w * x + b
loss = torch.mul(y,y)
display(y.requires_grad, y.grad_fn)

grad_like = torch.ones_like(loss)
loss.backward(gradient=grad_like)
print(f"Gradients after backward pass: {x.grad}, {w.grad}, {b.grad}")
display(grad_like.shape, loss.shape)

True

Gradients after backward pass: tensor([[ 4.6386e+00,  1.4188e-01,  1.7259e+00,  1.6847e+00, -1.1178e+00],
        [ 3.2277e-01, -2.0231e-01,  5.1504e+00, -1.3771e-01,  1.3713e+00],
        [-1.0984e+00,  2.3315e-01, -4.0364e-01, -4.7043e-01,  1.8674e+00],
        [ 1.7413e+00,  3.9444e+00,  5.6293e+00,  6.9434e-01, -2.9229e-03]]), tensor([[ 3.8198,  1.2594,  0.4467,  1.7931,  0.0947],
        [ 0.0274,  0.2519,  1.5673,  0.4631,  0.0220],
        [ 0.2447,  1.4471,  0.7935,  0.3999,  0.3566],
        [ 0.6189, -1.6583,  2.0312,  0.1783,  0.0046]]), tensor([[12.1273],
        [ 6.0584],
        [ 7.6945],
        [ 3.9756]])

torch.Size([4, 5])

torch.Size([4, 5])

In [51]:
x = torch.tensor(5.0, requires_grad=True)
w = torch.tensor(6.4, requires_grad=True)
b = torch.tensor(3.2, requires_grad=True)

print(f"Gradients before backward pass: {x.grad}, {w.grad}, {b.grad}")
y = w * x + b
y.backward()
print(f"Gradients after backward pass: {x.grad}, {w.grad}, {b.grad}") # these are the derivates
# basically these corresponding derivates, represent how does a unit change in those parameters effect
# and influence the value fo the range/dependent value Y

loss = torch.pow(x,b)
print(f"Leaf tensor: X: {x.is_leaf}, W: {w.is_leaf}, B: {b.is_leaf}")
print(f"Non-leaf tensor: Y: {y.is_leaf}, LOSS: {loss.is_leaf}")
# Leaf tensors are tensors which were not created through operations with gradient tensors
# but they were created by explicitly requires_grad=True, and manually created or taken from outside
# while the non-leaf tensors are the ones which were neither created manually or taken from outside
# and did not have requires_grad=True enabled explicitly, so what are non-leaf tensors then?
# non-leaf tensors are tensors which were created through the operations or functions where
# at least of the tensors used in that operation or function is gradient tensor,
# even if there are 1000 tensors and only one gradient tensor, the resulting output
# will be automatically become or so to speak implicitly become requires_grad=True

Gradients before backward pass: None, None, None
Gradients after backward pass: 6.400000095367432, 5.0, 1.0
Leaf tensor: X: True, W: True, B: True
Non-leaf tensor: Y: False, LOSS: False

In [68]:
a = torch.rand(6,7,13, requires_grad=True)
b = torch.rand(13)
c = torch.rand(4,1,1,13)
e = torch.ones(1,13)
f = torch.ones(6,7,1)
g = torch.zeros(1,7,1)
k = torch.zeros(1,1,7,1)
l = torch.randn(4,6,7,13)
h = torch.randn(3,1,6,1,13)
a1 = torch.rand_like(a) # produces tensors with the same shape and dtype of input tensor
b1 = torch.rand_like(b)
c1 = torch.rand_like(c)
e1 = torch.ones_like(e)
f1 = torch.ones_like(f)
g1 = torch.zeros_like(g)
k1 = torch.zeros_like(k)
l1 = torch.randn_like(l)
h1 = torch.randn_like(h)
# even though the dimensions are different, and from linear algebra perspective element-wise operations
# cannot be performed, but thanks to broadcasting, the element-wise operations are possible
# for two tensors to be broadcastable, the # of dimensions must be equal, or one must have 1 or 0 dimension
# and in case of 0 or 1, the other(larger) tensors dimension will change to that, but not stay as 0 and 1.

print(f"Addition: {(a + b + c + e + f + g + k + l + h + a1 + b1 + c1 + e1 + f1 + g1 + k1 + l1 + h1).shape}")
print(f"Addition: {(a * b * c * e * f * g * k * l * h * a1 * b1 * c1 * e1 * f1 * g1 * k1 * l1 * h1).shape}")
print(f"Addition: {(a - b - c - e - f - g - k - l - h - a1 - b1 - c1 - e1 - f1 - g1 - k1 - l1 - h1).shape}")
print(f"Addition: {(a - b * c + e - f * g - k + l - h * a1 + b1 - c1 * e1 * f1 + g1 + k1 - l1 ** h1).shape}")
print(f"Addition: {(a - b * c + e - f * g - k + l - h * a1 + b1 - c1 * e1 * f1 + g1 + k1 - l1 ** h1).requires_grad}")
print(f"Addition: {(a - b * c + e - f * g - k + l - h * a1 + b1 - c1 * e1 * f1 + g1 + k1 - l1 ** h1).is_leaf}")
print(f"Leaf tensor: {a.is_leaf}")
print(f"Non Leaf tensor: {a1.is_leaf}")

Addition: torch.Size([3, 4, 6, 7, 13])
Addition: torch.Size([3, 4, 6, 7, 13])
Addition: torch.Size([3, 4, 6, 7, 13])
Addition: torch.Size([3, 4, 6, 7, 13])
Addition: True
Addition: False
Leaf tensor: True
Non Leaf tensor: True

In [76]:
import copy

a = torch.rand(56,78)
a.requires_grad_(True)
b = a + 2
f = torch.tensor(5)
b1 = torch.ones_like(b)
a1 = torch.ones_like(a1)
a2 = a.clone()
print(f"Is leaf tensor: a:{a.is_leaf}, a1:{a1.is_leaf}, a2:{a2.is_leaf}, b:{b.is_leaf}, b1:{b1.is_leaf}, f:{f.is_leaf}")
# So new tensors created with _like from leaf tensors, the resulting new _like tensor with the same shape and dtype of leaf tensor
# will also be a leaf tensor
# looks like any tensors manually created or taken from outside are considered leaf tensors

Is leaf tensor: a:True, a1:True, a2:False, b:False, b1:True, f:True

In [117]:
# When we use .backward() the gradients start the computations,
# but this method does not return the gradients
# but rather this gradients are stored in the individual tensors themselves, 
# in the tensors' attribute called .grad, and to access gradients
# we use .grad on the desired tensor, to get their corresponding gradient/derivate
# this .grad attribute even though it does exist for any gradient tensors
# PyTorch by default only stores the gradients to .grad attribute of only Leaf Tensors
# meaning, Non-Leaf/Intermediate tensors gradients are not stored in their .grad attribute
# if we want to explicitly store the gradients of non-leaf tensors, then we use retain_graph=True to the .backward() method as argument

x = torch.tensor([[[4.0]]], requires_grad=True)
w = torch.tensor([[[3.0]]], requires_grad=True)
b = torch.tensor([[[2.0]]], requires_grad=True)
print(f"Gradient attributes before backward pass: {x.grad}, {w.grad}, {b.grad}")
y = w * x + b
y.backward() # important to note that each time we call .backward() the gradients are accumulated
# meaning with each run of .backward(), the gradient values will be added to the previous ones and so forth
# it is useful for gradient accumulation across mini-batches
# but if we do not need this gradient accumulation, then we need to empty the gradients attribute values
# before calling .backward() with the optimizer.zero_grad()

print(f"Gradient of Y with respect to X: dy/dx: {x.grad}")
print(f"Gradient of Y with respect to W: dy/dw: {w.grad}")
print(f"Gradient of Y with respect to B: dy/db: {b.grad}")
print("These values represent how much the value of Y is changed/influenced/effected for every unit change in {x,w,b} respectively")
# These values represent how much the value of Y is changed/influenced/effected for every unit change in {x,w,b}

# fi we run this .backward() several times, the value of gradients will add up

Gradient attributes before backward pass: None, None, None
Gradient of Y with respect to X: dy/dx: tensor([[[3.]]])
Gradient of Y with respect to W: dy/dw: tensor([[[4.]]])
Gradient of Y with respect to B: dy/db: tensor([[[1.]]])
These values represent how much the value of Y is changed/influenced/effected for every unit change in {x,w,b} respectively

In [100]:
y.backward(retain_graph=True) # important to note that each time we call .backward() the gradients are accumulated
# meaning with each run of .backward(), the gradient values will be added to the previous ones and so forth
# it is useful for gradient accumulation across mini-batches
# but if we do not need this gradient accumulation, then we need to empty the gradients attribute values
# before calling .backward() with the optimizer.zero_grad()

print(f"Gradient of Y with respect to X: dy/dx: {x.grad}")
print(f"Gradient of Y with respect to W: dy/dw: {w.grad}")
print(f"Gradient of Y with respect to B: dy/db: {b.grad}")
print("These values represent how much the value of Y is changed/influenced/effected for every unit change in {x,w,b} respectively")
# These values represent how much the value of Y is changed/influenced/effected for every unit change in {x,w,b}

# fi we run this .backward() several times, the value of gradients will add up

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [135]:
# requires_grad=True or requires_grad_(True), makes sure that given (leaf)tensors and intermediate(non-leaf) tensors
# which performed operations with gradient tensors, will be recorded by PyTorch for potential gradient calculation
# grad_fn is attribute is attached for every gradient tensor, and they tell us which what operations
# a given intermediate(non-leaf) tensors was created, for leaf tensors that were manually created or taken from outside
# will show None since there was no operation involved in order to create these tensors in the first place
# .grad attribute stores the calculated gradients of the leaf tensors only by default
# .backward() does the gradient computation and draws the computational graph, it does not return gradients
# to access those gradients, we need to call .grad attribute for the desired tensor
# also, .backward() can be used only for the scalar tensors, meaning 
# it does not matter how many dimensions it has, as long as those tensors have a single/singular/scalar value
# then .backward() will work without RuntimeError
# also important note, is that when we call .backward() several times, within each time
# gradients are accumulated, meaning the new calculated gradient is added to the previous ones that used .backward() before it
# if we want to empty gradients value attribute, as to avoid gradient accumulation, the use optimizer.zero_grad()
# if we want to store the gradients for non-leaf tensors, then we have to explicitly call 
# retain_graph=True as an argument for the .backward() method

a = torch.rand(5,6, requires_grad=True)
b = torch.rand(3,6,9)
b.requires_grad_(True)
c = a @ b
e = c + 129
display(c.shape)
print(f"Is leaf: a:{a.is_leaf}, b:{b.is_leaf}, c:{c.is_leaf}, e:{e.is_leaf}")
print(f"Grad_fn: a:{a.grad_fn}, b:{b.grad_fn}, c:{c.grad_fn}, e:{e.grad_fn}")

torch.Size([3, 5, 9])

Is leaf: a:True, b:True, c:False, e:False
Grad_fn: a:None, b:None, c:<CloneBackward0 object at 0x156743be0>, e:<AddBackward0 object at 0x156743be0>

In [187]:
x = torch.rand(1,5, requires_grad=True)
w = torch.randn(5,1, requires_grad=True)
b = torch.ones(5,1, requires_grad=True)
y = w * x + b
y_ones = torch.ones_like(y)
y.backward(gradient=y_ones)
print(f"Gradient of Y with respect to X: {x.grad}")
print(f"Gradient of Y with respect to W: {w.grad}")
print(f"Gradient of Y with respect to B: {b.grad}")

Gradient of Y with respect to X: tensor([[-0.2350, -0.2350, -0.2350, -0.2350, -0.2350]])
Gradient of Y with respect to W: tensor([[2.2113],
        [2.2113],
        [2.2113],
        [2.2113],
        [2.2113]])
Gradient of Y with respect to B: tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.]])

In [206]:
x = torch.rand(1,5, requires_grad=True)
w = torch.randn(5,1, requires_grad=True)
b = torch.ones(5,1, requires_grad=True)
y = w * x + b
y = torch.mean(y)
y.backward() # has to scalar tensor, does not matter if it is N-dimensional, as long as it has a singular/single/scalar tensor
print(f"Gradient of Y with respect to X: {x.grad}")
print(f"Gradient of Y with respect to W: {w.grad}")
print(f"Gradient of Y with respect to B: {b.grad}")

Gradient of Y with respect to X: tensor([[-0.0686, -0.0686, -0.0686, -0.0686, -0.0686]])
Gradient of Y with respect to W: tensor([[0.1441],
        [0.1441],
        [0.1441],
        [0.1441],
        [0.1441]])
Gradient of Y with respect to B: tensor([[0.2000],
        [0.2000],
        [0.2000],
        [0.2000],
        [0.2000]])

In [234]:
x = torch.tensor(4.0, requires_grad=True)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.3, requires_grad=True)
y = torch.add(torch.mul(w,x),b)
f = 2**y
f.retain_grad()
y.backward(gradient=torch.tensor(1.0)) # it needs to take a gradient of the same shape as the final output, here Y
display(x.grad,w.grad,b.grad, f.grad)
# so by default, .backward() works for scalar tensors with gradient=torch.tensor(1.0), 
# but for matrices or vectors, we need to explicitly specify the gradient, and it has to have the same shape
# as the final output tensor, Y

tensor(3.)

tensor(4.)

tensor(1.)

None

In [261]:
x = torch.rand(3,4,18, requires_grad=True)
w = torch.randn(4,18, requires_grad=True)
b = torch.rand(3,4,1, requires_grad=True)
y = w * x + b
y.retain_grad()
loss = y*y

loss_ones = torch.ones_like(loss)
loss.backward(gradient=torch.ones_like(loss))
print(x.is_leaf,w.is_leaf,b.is_leaf,y.is_leaf,loss.is_leaf, loss.shape)
print(f"Gradient of Loss with respect to X:\n{x.grad}")
print(f"Gradient of Loss with respect to W:\n{w.grad}")
print(f"Gradient of Loss with respect to B:\n{b.grad}")
print(f"Gradient of Loss with respect to Y:\n{y.grad}") # since Y is non-leaf, gradients ARE NOT stored in .grad attribute
# in order for this non-leaf/intermediate tensor to explicitly store the gradients in their .grad attribute
# use tensor.retain_grad() method

True True True False False torch.Size([3, 4, 18])
Gradient of Loss with respect to X:
tensor([[[ 7.6566e-03,  4.6448e+00,  8.7880e-02,  9.9911e-01,  1.2427e-02,
           5.0039e+00,  3.7647e-01,  3.6018e-02,  1.7974e+00,  2.5786e-02,
           1.1600e+00,  2.4531e-03,  8.9086e-03, -2.7080e-02,  4.0341e-01,
           1.5871e+00, -3.4288e-03,  1.3255e+00],
         [ 5.6679e-02,  8.3234e-01,  2.8144e-01,  1.1311e+00,  7.6381e-01,
           5.6489e+00, -1.3147e-01,  2.2801e+00,  1.3443e+00, -2.0175e-01,
          -3.2055e-02, -3.9420e-02,  1.0131e+00,  9.4108e-01,  6.1843e-01,
           7.7810e-01,  1.0663e+00,  4.8585e-01],
         [-2.3978e-02,  2.6324e+00,  1.7885e+00,  1.4892e-01,  1.0352e-02,
           2.5893e-01,  2.2468e+00,  2.3662e-02,  4.9263e-02, -3.4814e-03,
          -5.5805e-02, -6.5501e-03, -1.0111e-02, -2.7019e-01, -6.9381e-02,
           3.8361e-01,  1.1225e+00, -5.1395e-01],
         [-8.2629e-01,  1.3847e+00, -1.3318e+00, -3.6174e-01, -2.2580e+00,
          -2.0930e-02,  3.9499e-01, -1.4208e+00,  3.4813e-01,  3.8956e+00,
           7.3888e-02, -2.1070e+00,  2.1192e+00, -4.6776e-01,  1.8977e+00,
          -3.1115e-01, -5.6892e-01,  6.3173e+00]],

        [[ 8.1369e-03,  5.0862e+00,  5.3909e-02,  1.1502e+00, -1.9161e-02,
           4.0208e+00,  4.5023e-01,  3.2825e-02,  2.2731e-01,  1.2616e-01,
           7.9370e-01, -1.8934e-02,  1.0671e-01,  7.0120e-02, -5.9610e-03,
           4.5562e-01, -9.9218e-03, -1.9519e-01],
         [-1.5510e-01,  1.3202e+00,  2.5298e-01,  2.3276e+00,  2.6511e+00,
           7.0052e+00, -3.0169e-01,  1.9111e+00,  1.7074e+00, -1.5991e-01,
          -5.7658e-02, -5.7805e-02,  9.2813e-01,  7.5957e-01, -2.4567e-01,
           2.3616e+00,  1.6473e+00,  3.6170e-01],
         [ 2.2844e-02,  3.0671e+00,  2.2614e+00,  1.2839e-01,  9.3095e-03,
           4.1941e-01,  1.6636e+00,  2.0878e-02,  3.7924e-02, -3.1888e-03,
          -5.4173e-02, -5.9527e-03, -9.3128e-03, -4.9925e-02, -5.7578e-02,
           5.6639e-01,  8.2088e-01,  1.2410e+00],
         [-7.9905e-01,  1.2333e+00, -1.1796e+00, -3.4807e-01,  9.6961e-03,
           1.1396e+00,  3.9259e-01, -1.5645e+00,  3.1867e-01,  3.4235e+00,
           7.3619e-02, -3.1002e+00,  2.4350e+00, -4.4222e-01,  1.7364e+00,
          -3.6895e-01, -7.6442e-01,  1.0651e-01]],

        [[ 4.3407e-02,  5.1438e+00,  3.0963e-01,  5.1636e-01, -2.2567e-01,
           5.9549e+00,  1.6834e+00,  1.3523e-01,  1.3878e+00, -2.9995e-01,
           2.3469e+00, -1.0301e-01, -2.2012e-01, -1.6688e-01, -1.9630e-01,
           1.7809e+00, -7.2747e-02, -2.0366e-01],
         [-5.6251e-01,  1.6854e+00,  6.1081e-01,  1.6327e+00,  1.9456e+00,
           8.3075e+00,  6.3198e-02,  4.2217e+00, -3.1248e-01, -5.7776e-01,
          -1.1916e-01, -1.5153e-01,  1.2463e+00,  1.7699e+00, -1.1115e-02,
           2.9236e+00,  1.4420e+00,  6.4742e-01],
         [-2.5713e-01,  5.0330e-01,  7.2458e+00,  1.7593e-01,  1.3033e-02,
           2.8359e-01,  2.4509e+00,  3.0315e-02, -3.1329e-01, -4.3481e-03,
          -8.3977e-02, -8.1890e-03, -1.2850e-02, -1.7837e-01, -1.2891e-01,
           8.2032e-01,  8.0878e-01,  7.1541e-01],
         [-4.4125e-01,  1.1126e+00,  9.8892e-04, -2.3209e-01, -8.5338e-01,
           1.4805e-01,  3.1019e-01, -3.2279e-01,  2.5301e-01,  2.8426e+00,
           4.7510e-02,  2.8626e+00,  1.8607e+00, -2.2476e-01,  8.3732e-01,
          -2.4525e-01, -6.9334e-01,  3.4186e+00]]])
Gradient of Loss with respect to W:
tensor([[ 0.5008,  4.7541,  1.2138, -1.2336,  0.3705,  8.0598,  1.1396,  1.0696,
          2.0776, -0.0799,  1.7069,  0.7281,  0.2288,  0.3071, -0.2141,  1.5441,
          0.6265, -0.1748],
        [ 0.0747,  3.4947,  1.5081,  3.4089,  1.6979,  8.1197,  0.0284,  4.4302,
         -1.2006,  0.5470,  1.0800,  0.8650,  1.9012,  4.0222, -0.3284,  4.0034,
          1.6642,  1.5219],
        [ 0.1735, -4.0380,  4.1282,  1.8919,  1.4866, -0.5016,  1.2127,  1.2797,
         -0.0702,  1.1577,  1.1584,  0.2174,  0.4923,  0.3400,  0.8945,  2.7225,
          1.0792, -1.1436],
        [ 1.1544,  1.3410,  0.6902,  2.4830,  0.2806, -0.5924,  1.1351,  0.5218,
          3.5870,  5.1059,  2.9668, -0.8929,  6.7302,  2.5533,  3.6130,  2.0694,
          1.4030, -3.5610]])
Gradient of Loss with respect to B:
tensor([[[ 9.2071],
         [14.1975],
         [ 9.0126],
         [27.6176]],

        [[ 6.5158],
         [21.4182],
         [ 5.7808],
         [28.1147]],

        [[22.5378],
         [31.5266],
         [16.1189],
         [15.2182]]])
Gradient of Loss with respect to Y:
tensor([[[ 1.9751e-01,  2.5063e+00,  3.9759e-01, -8.7883e-01, -4.8705e-02,
           3.1598e+00,  4.3628e-01,  3.2457e-01,  1.9071e+00, -7.8060e-02,
           1.0701e+00, -2.1906e-02, -2.2224e-02,  1.1444e-01, -6.4743e-01,
           1.5193e+00,  4.8210e-02, -7.7688e-01],
         [-1.4843e-01,  1.1683e+00,  8.4670e-01,  1.2447e+00,  6.5695e-01,
           2.9697e+00,  9.3033e-02,  1.8701e+00, -9.4793e-01,  3.2660e-01,
           3.7717e-01,  3.7671e-01,  1.4381e+00,  1.4417e+00, -6.7011e-01,
           7.7113e-01,  1.1806e+00,  1.2025e+00],
         [ 6.2973e-02, -1.8697e+00,  1.0166e+00,  9.3219e-01,  7.1576e-01,
          -2.5727e-01,  1.5760e+00,  7.2859e-01, -1.1610e-01,  6.9260e-01,
           5.0393e-01,  6.9683e-01,  6.8485e-01,  5.9936e-01,  3.2391e-01,
           8.3672e-01,  1.4408e+00,  4.4457e-01],
         [ 1.7127e+00,  2.2157e+00,  1.0023e+00,  1.6906e+00,  1.7019e+00,
           1.2827e-02,  1.9431e+00,  1.6762e+00,  2.1678e+00,  3.4316e+00,
           1.9782e+00,  1.1611e+00,  2.8396e+00,  1.6115e+00,  2.8915e+00,
           1.5366e+00,  7.5279e-01, -2.7086e+00]],

        [[ 2.0990e-01,  2.7444e+00,  2.4389e-01, -1.0117e+00,  7.5098e-02,
           2.5390e+00,  5.2176e-01,  2.9580e-01,  2.4120e-01, -3.8191e-01,
           7.3218e-01,  1.6908e-01, -2.6622e-01, -2.9633e-01,  9.5668e-03,
           4.3614e-01,  1.3951e-01,  1.1441e-01],
         [ 4.0619e-01,  1.8532e+00,  7.6108e-01,  2.5614e+00,  2.2801e+00,
           3.6827e+00,  2.1349e-01,  1.5675e+00, -1.2040e+00,  2.5886e-01,
           6.7843e-01,  5.5240e-01,  1.3175e+00,  1.1636e+00,  2.6621e-01,
           2.3404e+00,  1.8239e+00,  8.9518e-01],
         [-5.9996e-02, -2.1785e+00,  1.2854e+00,  8.0367e-01,  6.4368e-01,
          -4.1672e-01,  1.1669e+00,  6.4287e-01, -8.9376e-02,  6.3438e-01,
           4.8919e-01,  6.3329e-01,  6.3080e-01,  1.1075e-01,  2.6880e-01,
           1.2354e+00,  1.0536e+00, -1.0735e+00],
         [ 1.6563e+00,  1.9734e+00,  8.8772e-01,  1.6267e+00, -7.3082e-03,
          -6.9842e-01,  1.9313e+00,  1.8458e+00,  1.9844e+00,  3.0158e+00,
           1.9710e+00,  1.7084e+00,  3.2627e+00,  1.5234e+00,  2.6458e+00,
           1.8220e+00,  1.0115e+00, -4.5668e-02]],

        [[ 1.1197e+00,  2.7755e+00,  1.4008e+00, -4.5420e-01,  8.8446e-01,
           3.7603e+00,  1.9508e+00,  1.2186e+00,  1.4725e+00,  9.0801e-01,
           2.1650e+00,  9.1981e-01,  5.4914e-01,  7.0523e-01,  3.1505e-01,
           1.7047e+00,  1.0229e+00,  1.1937e-01],
         [ 1.4731e+00,  2.3657e+00,  1.8376e+00,  1.7967e+00,  1.6734e+00,
           4.3673e+00, -4.4721e-02,  3.4626e+00,  2.2034e-01,  9.3528e-01,
           1.4021e+00,  1.4481e+00,  1.7692e+00,  2.7115e+00,  1.2044e-02,
           2.8974e+00,  1.5967e+00,  1.6023e+00],
         [ 6.7530e-01, -3.5748e-01,  4.1186e+00,  1.1013e+00,  9.0111e-01,
          -2.8178e-01,  1.7192e+00,  9.3345e-01,  7.3834e-01,  8.6502e-01,
           7.5834e-01,  8.7119e-01,  8.7038e-01,  3.9566e-01,  6.0181e-01,
           1.7893e+00,  1.0381e+00, -6.1883e-01],
         [ 9.1463e-01,  1.7803e+00, -7.4422e-04,  1.0846e+00,  6.4322e-01,
          -9.0738e-02,  1.5259e+00,  3.8083e-01,  1.5755e+00,  2.5040e+00,
           1.2720e+00, -1.5775e+00,  2.4932e+00,  7.7431e-01,  1.2758e+00,
           1.2111e+00,  9.1742e-01, -1.4657e+00]]])

In [264]:
"""
    There are cases when computing gradients is pointless. 
    
    First: for model evaluation, all we do here is simply forward pass the data and provide predictions
    at this evaluation point we do not make any changes/updates to parameters, hence computing gradients
    for those parameters is useless, and makes the evaluation process much slower, without any benefit

    Second: for fine-tuning, we may need to update only certain parameters of the model, mostly pre-trained models
    and fine-tune them to our needs. With transfer learning, we do not need to train the model from scratch,
    but rather fine-tune some of its parameters to our needs, by freezing other parameters as to not change them
    and rather keep them.

    Third: In both above two cases, calculations of gradients unnecessarily takes memory for drawing computational graph,
    operations of chain rule, and storing those gradients in .grad attribute, causes the model take more time and memory
    without any benefit. 
"""

'\n    There are cases when computing gradients is pointless. \n    \n    First: for model evaluation, all we do here is simply forward pass the data and provide predictions\n    at this evaluation point we do not make any changes/updates to parameters, hence computing gradients\n    for those parameters is useless, and makes the evaluation process much slower, without any benefit\n\n    Second: for fine-tuning, we may need to update only certain parameters of the model, mostly pre-trained models\n    and fine-tune them to our needs. With transfer learning, we do not need to train the model from scratch,\n    but rather fine-tune some of its parameters to our needs, by freezing other parameters as to not change them\n    and rather keep them.\n\n    Third: In both above two cases, calculations of gradients unnecessarily takes memory for drawing computational graph,\n    operations of chain rule, and storing those gradients in .grad attribute, causes the model take more time and memory\n    without any benefit. \n'

In [279]:
# by using "with torch.no_grad():" any tensors that are used inside of this statement
# will not have gradients required, even if they were explicitly set as requires_grad=True
x = torch.rand(4,5, requires_grad=True)
w = torch.rand(2,5,4, requires_grad=True)
b = torch.rand(2,1,5, requires_grad=True)
y = w @ x + b
print(f"Is gradient required: y:{y.requires_grad}")
print(f"Is leaf: y:{y.is_leaf}, x:{x.is_leaf}, w:{w.is_leaf}, b:{b.is_leaf}")
print(f"Grad_fn: y:{y.grad_fn}, x:{x.grad_fn}, w:{w.grad_fn}, b:{b.grad_fn}")
print("\nFollowing is written inside of torch.no_grad()")
with torch.no_grad():
    z = w @ x + b
    print(f"Is gradient required: z:{z.requires_grad}, x:{x.requires_grad}, w:{w.requires_grad}, b:{b.requires_grad}")
    print(f"Grad_fn: z:{z.grad_fn}")
    # Look it does acknowledge that the gradient tensors have grad required, but operations performed with them
    # will not have gradients required because it is inside of with torch.no_grad()
    e = x @ w * 56
    print(f"Is gradient required e: {e.requires_grad}")
print("\nOutside the torch.no_grad()")
h = w @ x + b
print(f"Is gradient enabled: h:{h.requires_grad}\nGrad_fn h:{h.grad_fn}")

Is gradient required: y:True
Is leaf: y:False, x:True, w:True, b:True
Grad_fn: y:<AddBackward0 object at 0x155b621f0>, x:None, w:None, b:None

Following is written inside of torch.no_grad()
Is gradient required: z:False, x:True, w:True, b:True
Grad_fn: z:None
Is gradient required e: False

Outside the torch.no_grad()
Is gradient enabled: h:True
Grad_fn h:<AddBackward0 object at 0x15663dd90>

In [340]:
# Another method is by using .detach() which creates a new tensor that has reference to original gradient tensor
# meaning if change is done for either detached or gradient tensor, the changes will be reflected in both
a = torch.rand(4,5, requires_grad=True)
b = a**2
print(f"Tensor B: b.requires_grad: {b.requires_grad}, b.grad_fn: {b.grad_fn}")

# C is detached from being tracked for gradient computation, but keeps the reference to original gradient tensor
c = b.detach()
print(f"Detached Tensor C: c.requires_grad: {c.requires_grad}")
c.contiguous()
c = c.view(5,2,2)
# so any operations done with C will not be tracked
f = c**5
print(f.requires_grad, f.grad_fn)
display(c.shape,b.shape)

Tensor B: b.requires_grad: True, b.grad_fn: <PowBackward0 object at 0x148181e50>
Detached Tensor C: c.requires_grad: False
False None

torch.Size([5, 2, 2])

torch.Size([4, 5])

In [366]:
# torch.no_grad() is standar practice for evaluation and inferencing code block
# while .detach() offer more control as to which gradient tensor to disregard from being tracked for gradient computation

w = torch.ones(3,4,8, requires_grad=True)
x = torch.arange(32, dtype=torch.float32).view(8,-1) # -1 for inferencing the other dimension so that the resulting dimensions are 32
x.requires_grad_(True)
b = torch.arange(12, dtype=torch.float64).reshape(3,4,1)
b.requires_grad_(True)

Y = torch.matmul(w,x) + b
mask = Y > 132.0
loss = Y[mask]
loss.backward(gradient=torch.ones_like(loss))
# gradients of Loss with respect to each parameter is now stored in the leaf-tensors .grad attribute


with torch.no_grad():
    # we can either permute order of dimensions
    x_ = x.clone()
    x_ = x_.permute(1,0)
    
    # or use .view() or .reshape(), for .view() make sure that tensors are contiguous
    print(x.is_contiguous())
    x.view(4,8)
    
    y_ = w * x_ + b
    print(x.shape, w.shape, b.shape)
    
    loss_ = y_[y_> 15.0]
    #eg = torch.sum(loss_) 
    #eg.backward() # will show error since gradients are not required inside of torch.no_grad()

    # any operations performed with gradient tensors inside of torch.no_grad() will not have gradients required
    # hence grad_fn=None and no computations will be done for them, usually used on code block
    # performing evaluation and inference 


_x = x.clone()
print("_x CLONE",_x.grad_fn) # so cloning is also tracked into grad_fn as CloneBackward0
_x = _x.detach()
# now _x is no longer being tracked 

print(f"Initial tensors Y: {Y.requires_grad}, {Y.grad_fn}")
print(f"Gradients of Loss with respect to parameters:\nw:{w.grad}\nx:{x.grad}\nb:{b.grad}")
print(f"\nTensors with torch.no_grad(): x_:{x_.requires_grad}, loss_:{loss_.requires_grad}, loss_.grad_fn:{loss_.grad_fn}")
print(f"\nDetached tensor with .detach(): _x:{_x.requires_grad}, _x.grad_fn:{_x.grad_fn}")

True
torch.Size([8, 4]) torch.Size([3, 4, 8]) torch.Size([3, 4, 1])
_x CLONE <CloneBackward0 object at 0x156a37340>
Initial tensors Y: True, <AddBackward0 object at 0x156a37340>
Gradients of Loss with respect to parameters:
w:tensor([[[ 3.,  7., 11., 15., 19., 23., 27., 31.],
         [ 3.,  7., 11., 15., 19., 23., 27., 31.],
         [ 3.,  7., 11., 15., 19., 23., 27., 31.],
         [ 3.,  7., 11., 15., 19., 23., 27., 31.]],

        [[ 3.,  7., 11., 15., 19., 23., 27., 31.],
         [ 5., 13., 21., 29., 37., 45., 53., 61.],
         [ 5., 13., 21., 29., 37., 45., 53., 61.],
         [ 5., 13., 21., 29., 37., 45., 53., 61.]],

        [[ 5., 13., 21., 29., 37., 45., 53., 61.],
         [ 5., 13., 21., 29., 37., 45., 53., 61.],
         [ 5., 13., 21., 29., 37., 45., 53., 61.],
         [ 5., 13., 21., 29., 37., 45., 53., 61.]]])
x:tensor([[ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.],
        [ 0.,  0.,  7., 12.]])
b:tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [2.],
         [2.],
         [2.]],

        [[2.],
         [2.],
         [2.],
         [2.]]], dtype=torch.float64)

Tensors with torch.no_grad(): x_:False, loss_:False, loss_.grad_fn:None

Detached tensor with .detach(): _x:False, _x.grad_fn:None

In [356]:
x4 = torch.ones(3,4, requires_grad=True)
x1 = x4.clone()
display(x4.requires_grad)
display(x4.storage().data_ptr() == x1.storage().data_ptr())
# so cloning gradient tensor, the cloned one will also be gradient required tensor, but will not have reference to each other

True

False

In [364]:
# Again note that torch.no_grad() and .detach() help to NOT to compute the gradients for tensors with grad enabled
# it is used in cases of fine-tuning pre-trained model, evaluation and inferencing

In [403]:
# Gradient accumulation is basically about using .backward() method several times on the same loss value scalar tensor
# basically if we run .backward() times at first it will show RuntimeError, but in order to avoid it
# and allow to run .backward() more than one time, we need to pass retrain_graph=True as argument to .backward()
# in this way the new calculated gradients will be added to the previous ones in .grad attribute

a = torch.tensor([4.5], requires_grad=True)
y = torch.mul(a,a)
z = torch.exp(y)

# if we want to run .backward() on the same tensor multiple times, then in the first .backward() call 
# we need to pass retain_grap=True
z.backward(retain_graph=True)
print(f"Gradients of Z with respect to A dz/da: {a.grad}") # only leaf tensors gradients are stored in .grad attribute by default

#f = torch.sqrt(z)

z.backward(retain_graph=True)
print(f"Gradients of Z with respect to A df/da: {a.grad}") # only leaf tensors gradients are stored in .grad attribute by default
z.backward()
print(f"Gradients of Z with respect to A df/da: {a.grad}") # only leaf tensors gradients are stored in .grad attribute by default
a.grad.zero_()
print(f"Gradients of Z with respect to A df/da: {a.grad}") # only leaf tensors gradients are stored in .grad attribute by default

Gradients of Z with respect to A dz/da: tensor([5.6067e+09])
Gradients of Z with respect to A df/da: tensor([1.1213e+10])
Gradients of Z with respect to A df/da: tensor([1.6820e+10])
Gradients of Z with respect to A df/da: tensor([0.])

In [404]:
"""
    Basically if we want to run .backward() two times, then in the first .backward() call we need to
    pass retain_graph=True as argument, and so forth
"""

'\n    Basically if we want to run .backward() two times, then in the first .backward() call we need to\n    pass retain_graph=True as argument, and so forth\n'

In [424]:
a = torch.tensor([5.0], requires_grad=True)
y = a * a
z = y * 2
print(a.is_leaf, y.is_leaf, z.is_leaf)
z.backward(gradient=torch.tensor([1.0]),retain_graph=True)
display(a.grad)

# IMPORTANT, we can call .backward() only a single time after passing 
# for the first .backward() retain_graph=True, and if we want to use .backward() the third time for the same tensor
# then pass retain_graph=True for the .backward() above it, meaning after passing retain_graph=True
# we can only call .backward() only one more time
z.backward(retain_graph=True)
display(a.grad)
z.backward(retain_graph=True)
display(a.grad)
z.backward()
display(a.grad)

# Look the gradients are being accumulated, so a new calculated one and the previous existing ones are simply added by default
# if we want to empty .grad attribute of tensor, then use tensor.grad.zero_()
a.grad.zero_()
display(a.grad)

True False False

tensor([20.])

tensor([40.])

tensor([60.])

tensor([80.])

tensor([0.])

In [6]:
x = torch.arange(10, dtype=torch.float32, requires_grad=True).view(2,5)
w = torch.arange(10.0, requires_grad=True).reshape(2,5)
x_ = x.clone()
b = x_.reshape(5,2)
b = b.permute(1,0)
b.requires_grad_(True)
x.retain_grad()
w.retain_grad()
b.retain_grad()
y = w * x + b
z = y**2

z_ones = torch.ones_like(z)

z.backward(gradient=torch.ones(2,5), retain_graph=True)
print(x.grad)
z.backward(gradient=z_ones, retain_graph=True)
print(x.grad)
z.backward(gradient=z_ones, retain_graph=True)
print(x.grad)
z.backward(gradient=z_ones, retain_graph=True)
print(x.grad)
z.backward(gradient=z_ones, retain_graph=True)
print(x.grad)
# gradients are simply being accumulated and added, and we can empty it
x.grad.zero_()
print(x.grad)
z.backward(gradient=z_ones, retain_graph=True)
print(x.grad)
z.backward(gradient=z_ones)
print(x.grad)

# after tensor.grad.zero_() the gradients stored in .grad attribute of a given leaf tensor are emptied, 
# and then we can start adding again

tensor([[   0.,   58.,   38.,  168.,  208.],
        [ 368.,  498.,  898., 1184., 1800.]])
tensor([[   0.,  116.,   76.,  336.,  416.],
        [ 736.,  996., 1796., 2368., 3600.]])
tensor([[   0.,  174.,  114.,  504.,  624.],
        [1104., 1494., 2694., 3552., 5400.]])
tensor([[   0.,  232.,  152.,  672.,  832.],
        [1472., 1992., 3592., 4736., 7200.]])
tensor([[   0.,  290.,  190.,  840., 1040.],
        [1840., 2490., 4490., 5920., 9000.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[   0.,   58.,   38.,  168.,  208.],
        [ 368.,  498.,  898., 1184., 1800.]])
tensor([[   0.,  116.,   76.,  336.,  416.],
        [ 736.,  996., 1796., 2368., 3600.]])

In [46]:
x = torch.arange(40.0, requires_grad=True).view(2,5,4)
w = torch.randn(5,4, requires_grad=True)
b = torch.ones(1,5,1,requires_grad=True)

truth = torch.randn(2,5,4)
y = w * x + b
y.retain_grad()
x.retain_grad()
loss = torch.abs(truth - y)
loss_ones = torch.ones_like(loss)
print(f"Gradients after forward pass: x={x.grad}, w={w.grad}, b={b.grad}, y={y.grad}")
loss.backward(gradient=loss_ones, retain_graph=True)
print(f"Is leaf: x={x.is_leaf}, w={w.is_leaf}, b={b.is_leaf}, y={y.is_leaf}")
print(f"Gradient after FIRST backward pass:\nx={x.grad},\nw={w.grad},\nb={b.grad}\n")
loss.backward(gradient=loss_ones, retain_graph=True)
print(f"Gradient after SECOND backward pass:\nx={x.grad},\nw={w.grad},\nb={b.grad}\n")
loss.backward(gradient=loss_ones, retain_graph=True)
print(f"Gradient after THIRD backward pass:\nx={x.grad},\nw={w.grad},\nb={b.grad}\n")
# Gradients are being accumulated, in their corresponding .grad attribute
# but we can manually empty each of them
x.grad.zero_()
w.grad.zero_()
b.grad.zero_()
print("Gradients after manually empting them\n",x.grad, w.grad, b.grad)

loss.backward(gradient=loss_ones)
print(f"\nGradient after GRAD.ZERO_() backward pass:\nx={x.grad},\nw={w.grad},\nb={b.grad}\n")
print(f"Gradients for non-leaf/intermediate tensors: y={y.grad_fn}")

Gradients after forward pass: x=None, w=None, b=None, y=None
Is leaf: x=False, w=True, b=True, y=False
Gradient after FIRST backward pass:
x=tensor([[[-2.1362,  0.0395,  1.4157, -0.0429],
         [ 0.8641,  0.4581,  0.3930, -0.1724],
         [ 0.8493,  0.6583,  1.8618,  0.6285],
         [ 0.5152,  0.9438,  0.3897,  1.8575],
         [ 0.3382,  1.2126,  1.5895,  1.2673]],

        [[ 2.1362, -0.0395,  1.4157, -0.0429],
         [ 0.8641,  0.4581,  0.3930,  0.1724],
         [ 0.8493,  0.6583,  1.8618,  0.6285],
         [ 0.5152,  0.9438,  0.3897,  1.8575],
         [ 0.3382,  1.2126,  1.5895,  1.2673]]]),
w=tensor([[-20.,  20.,  24.,  26.],
        [ 28., -30.,  32., -20.],
        [ 36., -38., -40.,  42.],
        [-44., -46.,  48., -50.],
        [ 52., -54.,  56., -58.]]),
b=tensor([[[ 4.],
         [ 2.],
         [ 0.],
         [-4.],
         [ 0.]]])

Gradient after SECOND backward pass:
x=tensor([[[-4.2725,  0.0791,  2.8315, -0.0858],
         [ 1.7283,  0.9161,  0.7860, -0.3449],
         [ 1.6986,  1.3166,  3.7236,  1.2569],
         [ 1.0304,  1.8876,  0.7794,  3.7149],
         [ 0.6765,  2.4252,  3.1790,  2.5346]],

        [[ 4.2725, -0.0791,  2.8315, -0.0858],
         [ 1.7283,  0.9161,  0.7860,  0.3449],
         [ 1.6986,  1.3166,  3.7236,  1.2569],
         [ 1.0304,  1.8876,  0.7794,  3.7149],
         [ 0.6765,  2.4252,  3.1790,  2.5346]]]),
w=tensor([[ -40.,   40.,   48.,   52.],
        [  56.,  -60.,   64.,  -40.],
        [  72.,  -76.,  -80.,   84.],
        [ -88.,  -92.,   96., -100.],
        [ 104., -108.,  112., -116.]]),
b=tensor([[[ 8.],
         [ 4.],
         [ 0.],
         [-8.],
         [ 0.]]])

Gradient after THIRD backward pass:
x=tensor([[[-6.4087,  0.1186,  4.2472, -0.1287],
         [ 2.5924,  1.3742,  1.1790, -0.5173],
         [ 2.5479,  1.9748,  5.5854,  1.8854],
         [ 1.5456,  2.8315,  1.1691,  5.5724],
         [ 1.0147,  3.6379,  4.7685,  3.8018]],

        [[ 6.4087, -0.1186,  4.2472, -0.1287],
         [ 2.5924,  1.3742,  1.1790,  0.5173],
         [ 2.5479,  1.9748,  5.5854,  1.8854],
         [ 1.5456,  2.8315,  1.1691,  5.5724],
         [ 1.0147,  3.6379,  4.7685,  3.8018]]]),
w=tensor([[ -60.,   60.,   72.,   78.],
        [  84.,  -90.,   96.,  -60.],
        [ 108., -114., -120.,  126.],
        [-132., -138.,  144., -150.],
        [ 156., -162.,  168., -174.]]),
b=tensor([[[ 12.],
         [  6.],
         [  0.],
         [-12.],
         [  0.]]])

Gradients after manually empting them
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.]]])

Gradient after GRAD.ZERO_() backward pass:
x=tensor([[[-2.1362,  0.0395,  1.4157, -0.0429],
         [ 0.8641,  0.4581,  0.3930, -0.1724],
         [ 0.8493,  0.6583,  1.8618,  0.6285],
         [ 0.5152,  0.9438,  0.3897,  1.8575],
         [ 0.3382,  1.2126,  1.5895,  1.2673]],

        [[ 2.1362, -0.0395,  1.4157, -0.0429],
         [ 0.8641,  0.4581,  0.3930,  0.1724],
         [ 0.8493,  0.6583,  1.8618,  0.6285],
         [ 0.5152,  0.9438,  0.3897,  1.8575],
         [ 0.3382,  1.2126,  1.5895,  1.2673]]]),
w=tensor([[-20.,  20.,  24.,  26.],
        [ 28., -30.,  32., -20.],
        [ 36., -38., -40.,  42.],
        [-44., -46.,  48., -50.],
        [ 52., -54.,  56., -58.]]),
b=tensor([[[ 4.],
         [ 2.],
         [ 0.],
         [-4.],
         [ 0.]]])

Gradients for non-leaf/intermediate tensors: y=<AddBackward0 object at 0x137ef5a30>

In [2]:
# optimizer.zero_grad() is used to empty gradient attributes of all parameters handling by optimizer in the mode
# optimizer.step() updates the weights after calculating loss_fn, gradients
# typically use optimizer.zero_grad() at the top of training loop
# and use optimizer.step() at the last so only after relevant computations are done, then update weights based on gradients

In [3]:
# when we call some_tensor.backward(), the gradients of some_tensor with respect to all the previous
# connected tensors will be computed and stored on the leaf tensors
# meaning any tensors that come after some_tensor and used for operations will not be included
# or computed since in this case we are calling .backward() from the intermediate tensor
# say a -> b -> c -> d -> e -> f
# if we call c.backward() then gradients of C with respect to A and B will be computed and stored in A 
# or B, depending which one is leaf tensor, if both then gradients will be stored in both
# if we call e.backward() then gradients of E with respect to D, C, B and A will be computed and 
# stored in leaf tensors, the same f.backward() will be compute gradients of F with respect to D, E, C, B and A

# gradient attributes are stored only on the leaf tensors by default
# but if we want to retain gradients for intermediate tensors then we use .retain_grad() method
# it will store all the gradients computed before it, and not after it
# because with .retain_grad() we are computing the gradient of intermediate_tensor with respect 
# to all other tensors that comes before it and which are connected
# also note that if we use retain_grad() on the final output
# and then try to access .grad attribute we will simply get a tensor filled with 1.0s
# because a gradient of G with respect to G, meaning to itself, will always be 1

# note when computing the gradient of say Y with respect to X, 
# firstly all the pair-wise node derivatives of all the unique paths connected from Y to X
# will be multiplied, and then those multiplied derivates of all possible paths from Y to X will be summed
# and then resulting value will be an actual and accurate derivate of Y with respect to X
# it is accurate compared to only multipliying derivates of unique paths and summing them over for
# only directly connected nodes coming from leaf node(tensor), because those leaf-nodes
# can have indirect impact on the final loss value as well, even if indirectly connected
# through other intermediate tensors

In [50]:
# leaf tensors
a = torch.rand(4,5, requires_grad=True)
b = torch.rand(4,1, requires_grad=True)
c = torch.rand(1,5, requires_grad=True)
print(a.is_leaf,b.is_leaf,c.is_leaf)

# intermediate tensors, even though gradients are calculated for them, they are not explicitly stored in their .grad attribute
inter_1 = a @ c.T + b
inter_2 = a * c + b
inter_1.retain_grad()
inter_2.retain_grad()
# leaf tensors, but since no gradients required, no derivates will be computed for them with respect to previous tensors
e = torch.arange(180,200).view(4,5)  
f = torch.ones(4,1)

inter_3 = inter_1.T @ f
inter_4 = torch.mul(inter_2, e)

output = inter_3 + inter_4 # predicted values
labels = torch.randn(4,5) # ground truth
# sum of squared errors
loss = (output - labels) ** 2
loss.retain_grad()
# now the gradients of LOSS with respect to every preceding tensors connected to it, directly and indirectly will have computed
# and stored in their corresponding leaf tensors
# leaf tensors will contain gradients that are both directly and indirectly come from the input values
loss.backward(gradient=torch.ones(4,5))
print(f"grad_fn functions involed in intermediate(non-lefa) tensors: \ninter_1={inter_1.grad_fn}, inter_2={inter_2.grad_fn},\
inter_3={inter_3.grad_fn},\ninter_4={inter_4.grad_fn}\n")

# for now we can only access gradients computed for leaf tensors
print(f"Gradients of leaf tensors:\na={a.grad}\nb={b.grad}\nc={c.grad}")
# again, the gradients stored in .grad attribute are simply the sum of all possible paths of multiplied pair-wise derivatives
# which are directly and indirectly connected from output to input
print(f"\nGradients for leaf tensors but without gradients required, no gradients will be calculated for them,\n\
hence nothing will be in their corresponding .grad attribute: e={e.grad}, f={f.grad}")
print(f"\nIf we try to access .grad for non-leaf(intermediate) but gradients required tensors, .grad attribute\n\
will be empty, because by default, only for leaf-tensors gradients are stored.\n")
# if we want to compute the gradients for those intermediate/non-leaf tensors
# we need to use retain_grad() method and it will store gradients of that non-leaf tensor
# and basically derivates of non-leaf tensor with respect to all previous tensors, and not after it.
# autograd does calculate the gradients of those non-leaf tensors, but they are not stored in their .grad attribute
print(f"Gradients of non-leaf tensors now are stored in their .grad attribute:\ninter_1={inter_1.grad}\n\
inter_2={inter_2.grad},\nloss={loss.grad}")

True True True
grad_fn functions involed in intermediate(non-lefa) tensors:
inter_1=<AddBackward0 object at 0x11d227af0>, inter_2=<AddBackward0 object at 0x11d227af0>,inter_3=<MmBackward0 object at 0x11d227af0>,
inter_4=<MulBackward0 object at 0x11d227af0>

Gradients of leaf tensors:
a=tensor([[31687.2227, 41356.3164, 29994.5762, 41956.3008, 22144.4102],
        [50141.6562, 57926.3008, 30274.7070, 51902.4336, 23156.7715],
        [19674.8945, 21032.0840, 20240.4805, 17646.8984,  8854.6533],
        [ 8443.3594, 12747.5840,  4610.7793, 26268.8164,  8273.5068]])
b=tensor([[342821.6875],
        [430090.1562],
        [167753.9375],
        [105263.8125]])
c=tensor([[125020.1406, 107215.4141, 103531.3672, 119119.1875, 193669.6250]])

Gradients for leaf tensors but without gradients required, no gradients will be calculated for them,
hence nothing will be in their corresponding .grad attribute: e=None, f=None

If we try to access .grad for non-leaf(intermediate) but gradients required tensors, .grad attribute
will be empty, because by default, only for leaf-tensors gradients are stored.

Gradients of non-leaf tensors now are stored in their .grad attribute:
inter_1=tensor([[5475.2827],
        [5475.2827],
        [5475.2827],
        [5475.2827]])
inter_2=tensor([[58085.0234, 64910.9609, 69356.3125, 68852.0547, 76142.0547],
        [95102.1406, 93112.1875, 70055.1953, 86472.0469, 79873.3047],
        [33989.9102, 30320.2012, 45021.4297, 25786.9336, 27160.1855],
        [11460.9619, 16220.4238,  6027.8618, 41061.0234, 25018.2617]]),
loss=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [2]:
# note that the loss.grad, are all ones, in fact the gradient of the A with respect to A, is one
# derivate of the value with respect to itself, is always one

In [18]:
def f(x):
    return 3 * x ** 2 - 4 * x

def numerical_lim(f,x,h):
    return (f(x + h) - f(x)) / h

h = 0.1 # step size
for i in range(7):
    print(f'h={h:.7f}, numerical limit ={numerical_lim(f,1,h):.7f}')
    h *= 0.1

h=0.1000000, numerical limit =2.3000000
h=0.0100000, numerical limit =2.0300000
h=0.0010000, numerical limit =2.0030000
h=0.0001000, numerical limit =2.0003000
h=0.0000100, numerical limit =2.0000300
h=0.0000010, numerical limit =2.0000030
h=0.0000001, numerical limit =2.0000003

In [32]:
def f(x):
    return 4 * x ** 2 - 3 * x
    
def numerical_diff(f,x,h):
    return (f(x + h) - f(x))/h

h = 1e-2
for i in range(10):
    print(f"h={h:.10f}, numerical diff={numerical_diff(f,1,h):.10f}")
    h *=0.1

h=0.0100000000, numerical diff=5.0400000000
h=0.0010000000, numerical diff=5.0040000000
h=0.0001000000, numerical diff=5.0004000000
h=0.0000100000, numerical diff=5.0000400000
h=0.0000010000, numerical diff=5.0000040002
h=0.0000001000, numerical diff=5.0000004048
h=0.0000000100, numerical diff=4.9999999696
h=0.0000000010, numerical diff=5.0000004137
h=0.0000000001, numerical diff=5.0000004137
h=0.0000000000, numerical diff=5.0000004137

In [36]:
# Basically when we call .backward() for scalar tensor
# by default the vector v value in Jacobian-gradient product is 1.0 with 0-D dimension
# hence if we are using .backward() on non-scalar tensor
# we must provide the vector v value that matches with the shape of that output tensor
# v vector is simply vector that matches with the output tensor, and has only 1.0 in of all its entries
# simply filled with 1.0s

# torch.nn

In [2]:
!conda config --show channels

channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

In [3]:
!conda config --describe channel_priority

# # channel_priority (ChannelPriority)
# #   Accepts values of 'strict', 'flexible', and 'disabled'. The default
# #   value is 'flexible'. With strict channel priority, packages in lower
# #   priority channels are not considered if a package with the same name
# #   appears in a higher priority channel. With flexible channel priority,
# #   the solver may reach into lower priority channels to fulfill
# #   dependencies, rather than raising an unsatisfiable error. With channel
# #   priority disabled, package version takes precedence, and the
# #   configured priority of channels is used only to break ties. In
# #   previous versions of conda, this parameter was configured as either
# #   True or False. True is now an alias to 'flexible'.
# #
# channel_priority: flexible

FOR ADDING

conda config --add channels conda-forge

In [11]:
# If we do not know what arguments a given can accept, then call that function
# but instead of closing it with (), simply type ? twice
torch.tensor??

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

.. warning::

    When working with tensors prefer using :func:`torch.Tensor.clone`,
    :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
    readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
    ``t.clone().detach()``, and ``torch.tensor(t, requires_grad=True)``
    is equivalent to ``t.clone().detach().requires_grad_(True)``.

.. seealso::

    :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
    :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, infers data type from :attr:`data`.
    device (:class:`torch.device`, optional): the device of the constructed tensor. If None and data is a tensor
        then the device of data is used. If None and data is not a tensor then
        the result tensor is constructed on the current device.
    requires_grad (bool, optional): If autograd should record operations on the
        returned tensor. Default: ``False``.
    pin_memory (bool, optional): If set, returned tensor would be allocated in
        the pinned memory. Works only for CPU tensors. Default: ``False``.


Example::

    >>> torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
    tensor([[ 0.1000,  1.2000],
            [ 2.2000,  3.1000],
            [ 4.9000,  5.2000]])

    >>> torch.tensor([0, 1])  # Type inference on data
    tensor([ 0,  1])

    >>> torch.tensor([[0.11111, 0.222222, 0.3333333]],
    ...              dtype=torch.float64,
    ...              device=torch.device('cuda:0'))  # creates a double tensor on a CUDA device
    tensor([[ 0.1111,  0.2222,  0.3333]], dtype=torch.float64, device='cuda:0')

    >>> torch.tensor(3.14159)  # Create a zero-dimensional (scalar) tensor
    tensor(3.1416)

    >>> torch.tensor([])  # Create an empty tensor (of size (0,))
    tensor([])
Type:      builtin_function_or_method

In [15]:
torch.logical_and??

Docstring:
logical_and(input, other, *, out=None) -> Tensor

Computes the element-wise logical AND of the given input tensors. Zeros are treated as ``False`` and nonzeros are
treated as ``True``.

Args:
    input (Tensor): the input tensor.
    other (Tensor): the tensor to compute AND with

Keyword args:
    out (Tensor, optional): the output tensor.

Example::

    >>> torch.logical_and(torch.tensor([True, False, True]), torch.tensor([True, False, False]))
    tensor([ True, False, False])
    >>> a = torch.tensor([0, 1, 10, 0], dtype=torch.int8)
    >>> b = torch.tensor([4, 0, 1, 0], dtype=torch.int8)
    >>> torch.logical_and(a, b)
    tensor([False, False,  True, False])
    >>> torch.logical_and(a.double(), b.double())
    tensor([False, False,  True, False])
    >>> torch.logical_and(a.double(), b)
    tensor([False, False,  True, False])
    >>> torch.logical_and(a, b, out=torch.empty(4, dtype=torch.bool))
    tensor([False, False,  True, False])
Type:      builtin_function_or_method

In [16]:
torch.autograd??

Type:        module
String form: <module 'torch.autograd' from '/opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/autograd/__init__.py'>
File:        /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/autograd/__init__.py
Source:
# mypy: allow-untyped-defs
"""
``torch.autograd`` provides classes and functions implementing automatic differentiation of arbitrary scalar valued functions.

It requires minimal changes to the existing code - you only need to declare :class:`Tensor` s
for which gradients should be computed with the ``requires_grad=True`` keyword.
As of now, we only support autograd for floating point :class:`Tensor` types (
half, float, double and bfloat16) and complex :class:`Tensor` types (cfloat, cdouble).
"""

import warnings
from typing import cast, List, Optional, Sequence, Tuple, Union

import torch
from torch import _vmap_internals
from torch.overrides import handle_torch_function, has_torch_function, is_tensor_like
from torch.types import _size, _TensorOrTensors, _TensorOrTensorsOrGradEdge

from . import forward_ad, functional, graph
from .anomaly_mode import detect_anomaly, set_detect_anomaly
from .function import Function, NestedIOFunction
from .grad_mode import (
    _force_original_view_tracking,
    _unsafe_preserve_version_counter,
    enable_grad,
    inference_mode,
    no_grad,
    set_grad_enabled,
    set_multithreading_enabled,
)
from .gradcheck import gradcheck, gradgradcheck
from .graph import _engine_run_backward
from .variable import Variable


__all__ = [
    "Variable",
    "Function",
    "backward",
    "grad_mode",
    "NestedIOFunction",
    "detect_anomaly",
    "enable_grad",
    "grad",
    "gradcheck",
    "gradgradcheck",
    "inference_mode",
    "no_grad",
    "set_detect_anomaly",
    "set_grad_enabled",
    "set_multithreading_enabled",
    "variable",
]

_OptionalTensor = Optional[torch.Tensor]
_ShapeorNestedShape = Union[_size, Sequence[_size], torch.Tensor]


def _calculate_shape(
    output: Union[torch.Tensor, graph.GradientEdge],
    grad: torch.Tensor,
    is_grads_batched: bool,
) -> Tuple[_ShapeorNestedShape, _ShapeorNestedShape]:
    # is_same_size ensures that both tensors are either nested or non nested
    # circular import
    from torch.nested._internal.nested_tensor import NestedTensor

    if isinstance(output, graph.GradientEdge):
        # We have already checked that we are not a C++ NestedTensor
        if is_grads_batched:
            raise RuntimeError("Batched grads are not supported with GradientEdge")
        out_metadata = output.node._input_metadata[output.output_nr]
        return torch.Size(out_metadata.shape), grad.shape

    if output.is_nested and not isinstance(output, NestedTensor):
        if is_grads_batched:
            raise RuntimeError("Batched grads are not supported with Nested Tensor.")
        out_shape = output._nested_tensor_size()
        grad_shape = grad._nested_tensor_size()

        return out_shape, grad_shape

    reg_out_shape = output.shape
    reg_grad_shape = grad.shape if not is_grads_batched else grad.shape[1:]
    return reg_out_shape, reg_grad_shape


def _make_grads(
    outputs: Union[Sequence[torch.Tensor], Sequence[graph.GradientEdge]],
    grads: Sequence[_OptionalTensor],
    is_grads_batched: bool,
) -> Tuple[_OptionalTensor, ...]:
    new_grads: List[_OptionalTensor] = []
    for out, grad in zip(outputs, grads):
        out = cast(Union[torch.Tensor, graph.GradientEdge], out)
        out_size = None
        out_device = None

        if isinstance(out, graph.GradientEdge):
            out_metadata = out.node._input_metadata[out.output_nr]
            out_size = torch.Size(out_metadata.shape)
            out_dtype = out_metadata.dtype
            out_device = out_metadata.device
            out_is_nested = out_metadata.is_nested_tensor
            if out_metadata.is_cpp_nested_tensor:
                raise RuntimeError(
                    "C++ NestedTensor are not supported with GradientEdge"
                )
            out_is_cpp_nested = False
        else:
            # circular import
            from torch.nested._internal.nested_tensor import NestedTensor

            assert isinstance(out, torch.Tensor)
            out_dtype = out.dtype
            out_is_nested = out.is_nested
            out_is_cpp_nested = out_is_nested and not isinstance(out, NestedTensor)
            if not out_is_cpp_nested:
                out_size = out.shape

        if isinstance(grad, torch.Tensor):
            from torch.fx.experimental.symbolic_shapes import expect_true, sym_eq

            first_grad = grad if not is_grads_batched else grad[0]

            # TODO: We can remove this conditional once we uniformly use
            # singleton int to represent jagged dimension, so that size() call
            # on nested tensor works.
            if out_is_cpp_nested:
                assert isinstance(out, torch.Tensor)
                shape_matches = torch.is_same_size(out, first_grad)
            else:
                # We need to do a regular size check, without going through
                # the operator, to be able to handle unbacked symints
                # (expect_true ensures we can deal with unbacked)
                assert out_size is not None
                shape_matches = expect_true(sym_eq(out_size, first_grad.size()))

            if not shape_matches:
                out = cast(Union[torch.Tensor, graph.GradientEdge], out)
                out_shape, grad_shape = _calculate_shape(
                    out, first_grad, is_grads_batched
                )
                if is_grads_batched:
                    raise RuntimeError(
                        "If `is_grads_batched=True`, we interpret the first "
                        "dimension of each grad_output as the batch dimension. "
                        "The sizes of the remaining dimensions are expected to match "
                        "the shape of corresponding output, but a mismatch "
                        "was detected: grad_output["
                        + str(grads.index(grad))
                        + "] has a shape of "
                        + str(grad_shape)
                        + " and output["
                        + str(outputs.index(out))
                        + "] has a shape of "
                        + str(out_shape)
                        + ". "
                        "If you only want some tensors in `grad_output` to be considered "
                        "batched, consider using vmap."
                    )
                else:
                    raise RuntimeError(
                        "Mismatch in shape: grad_output["
                        + str(grads.index(grad))
                        + "] has a shape of "
                        + str(grad_shape)
                        + " and output["
                        + str(outputs.index(out))
                        + "] has a shape of "
                        + str(out_shape)
                        + "."
                    )
            if out_dtype.is_complex != grad.dtype.is_complex:
                raise RuntimeError(
                    "For complex Tensors, both grad_output and output"
                    " are required to have the same dtype."
                    " Mismatch in dtype: grad_output["
                    + str(grads.index(grad))
                    + "] has a dtype of "
                    + str(grad.dtype)
                    + " and output["
                    + str(outputs.index(out))
                    + "] has a dtype of "
                    + str(out_dtype)
                    + "."
                )
            new_grads.append(grad)
        elif grad is None:
            if isinstance(out, graph.GradientEdge) or out.requires_grad:  # type: ignore[attr-defined]
                if isinstance(out, graph.GradientEdge):
                    assert out_size is not None
                    out_numel_is_1 = all(o == 1 for o in out_size)
                else:
                    assert isinstance(out, torch.Tensor)
                    out_numel_is_1 = out.numel() == 1
                if not out_numel_is_1:
                    raise RuntimeError(
                        "grad can be implicitly created only for scalar outputs"
                    )
                if not out_dtype.is_floating_point:
                    msg = (
                        "grad can be implicitly created only for real scalar outputs"
                        f" but got {out_dtype}"
                    )
                    raise RuntimeError(msg)
                if isinstance(out, graph.GradientEdge):
                    assert out_size is not None
                    assert out_device is not None
                    new_grads.append(
                        torch.ones(
                            out_size,
                            dtype=out_dtype,
                            device=out_device,
                        )
                    )
                else:
                    assert isinstance(out, torch.Tensor)
                    new_grads.append(
                        torch.ones_like(out, memory_format=torch.preserve_format)
                    )
            else:
                new_grads.append(None)
        else:
            raise TypeError(
                "gradients can be either Tensors or None, but got "
                + type(grad).__name__
            )
    return tuple(new_grads)


def _tensor_or_tensors_to_tuple(
    tensors: Optional[_TensorOrTensors], length: int
) -> Tuple[_OptionalTensor, ...]:
    if tensors is None:
        return (None,) * length
    if isinstance(tensors, torch.Tensor):
        return (tensors,)
    return tuple(tensors)


def backward(
    tensors: _TensorOrTensors,
    grad_tensors: Optional[_TensorOrTensors] = None,
    retain_graph: Optional[bool] = None,
    create_graph: bool = False,
    grad_variables: Optional[_TensorOrTensors] = None,
    inputs: Optional[_TensorOrTensorsOrGradEdge] = None,
) -> None:
    r"""Compute the sum of gradients of given tensors with respect to graph leaves.

    The graph is differentiated using the chain rule. If any of ``tensors``
    are non-scalar (i.e. their data has more than one element) and require
    gradient, then the Jacobian-vector product would be computed, in this
    case the function additionally requires specifying ``grad_tensors``.
    It should be a sequence of matching length, that contains the "vector"
    in the Jacobian-vector product, usually the gradient of the differentiated
    function w.r.t. corresponding tensors (``None`` is an acceptable value for
    all tensors that don't need gradient tensors).

    This function accumulates gradients in the leaves - you might need to zero
    ``.grad`` attributes or set them to ``None`` before calling it.
    See :ref:`Default gradient layouts<default-grad-layouts>`
    for details on the memory layout of accumulated gradients.

    .. note::
        Using this method with ``create_graph=True`` will create a reference cycle
        between the parameter and its gradient which can cause a memory leak.
        We recommend using ``autograd.grad`` when creating the graph to avoid this.
        If you have to use this function, make sure to reset the ``.grad`` fields of your
        parameters to ``None`` after use to break the cycle and avoid the leak.

    .. note::

        If you run any forward ops, create ``grad_tensors``, and/or call ``backward``
        in a user-specified CUDA stream context, see
        :ref:`Stream semantics of backward passes<bwd-cuda-stream-semantics>`.

    .. note::

        When ``inputs`` are provided and a given input is not a leaf,
        the current implementation will call its grad_fn (even though it is not strictly needed to get this gradients).
        It is an implementation detail on which the user should not rely.
        See https://github.com/pytorch/pytorch/pull/60521#issuecomment-867061780 for more details.

    Args:
        tensors (Sequence[Tensor] or Tensor): Tensors of which the derivative will be
            computed.
        grad_tensors (Sequence[Tensor or None] or Tensor, optional): The "vector" in
            the Jacobian-vector product, usually gradients w.r.t. each element of
            corresponding tensors. None values can be specified for scalar Tensors or
            ones that don't require grad. If a None value would be acceptable for all
            grad_tensors, then this argument is optional.
        retain_graph (bool, optional): If ``False``, the graph used to compute the grad
            will be freed. Note that in nearly all cases setting this option to ``True``
            is not needed and often can be worked around in a much more efficient
            way. Defaults to the value of ``create_graph``.
        create_graph (bool, optional): If ``True``, graph of the derivative will
            be constructed, allowing to compute higher order derivative products.
            Defaults to ``False``.
        inputs (Sequence[Tensor] or Tensor or Sequence[GradientEdge], optional): Inputs w.r.t. which the gradient
            be will accumulated into ``.grad``. All other Tensors will be ignored. If
            not provided, the gradient is accumulated into all the leaf Tensors that
            were used to compute the :attr:`tensors`.
    """
    if torch._C._are_functorch_transforms_active():
        raise RuntimeError(
            "backward() called inside a functorch transform. This is not "
            "supported, please use functorch.grad or functorch.vjp instead "
            "or call backward() outside of functorch transforms."
        )

    if grad_variables is not None:
        warnings.warn(
            "`grad_variables` is deprecated. Use `grad_tensors` instead.",
            FutureWarning,
            stacklevel=2,
        )
        if grad_tensors is None:
            grad_tensors = grad_variables
        else:
            raise RuntimeError(
                "`grad_tensors` and `grad_variables` (deprecated) "
                "arguments both passed to `backward()`. Please only "
                "use `grad_tensors`."
            )
    if inputs is not None and len(inputs) == 0:
        raise RuntimeError("`inputs` argument to `backward()` cannot be empty.")

    tensors = (tensors,) if isinstance(tensors, torch.Tensor) else tuple(tensors)
    inputs = (
        (inputs,)
        if isinstance(inputs, (torch.Tensor, graph.GradientEdge))
        else tuple(inputs)
        if inputs is not None
        else ()
    )

    grad_tensors_ = _tensor_or_tensors_to_tuple(grad_tensors, len(tensors))
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
    if retain_graph is None:
        retain_graph = create_graph

    # The reason we repeat the same comment below is that
    # some Python versions print out the first line of a multi-line function
    # calls in the traceback and some print out the last line
    _engine_run_backward(
        tensors,
        grad_tensors_,
        retain_graph,
        create_graph,
        inputs,
        allow_unreachable=True,
        accumulate_grad=True,
    )


def grad(
    outputs: _TensorOrTensorsOrGradEdge,
    inputs: _TensorOrTensorsOrGradEdge,
    grad_outputs: Optional[_TensorOrTensors] = None,
    retain_graph: Optional[bool] = None,
    create_graph: bool = False,
    only_inputs: bool = True,
    allow_unused: Optional[bool] = None,
    is_grads_batched: bool = False,
    materialize_grads: bool = False,
) -> Tuple[torch.Tensor, ...]:
    r"""Compute and return the sum of gradients of outputs with respect to the inputs.

    ``grad_outputs`` should be a sequence of length matching ``output``
    containing the "vector" in vector-Jacobian product, usually the pre-computed
    gradients w.r.t. each of the outputs. If an output doesn't require_grad,
    then the gradient can be ``None``).

    .. note::

        If you run any forward ops, create ``grad_outputs``, and/or call ``grad``
        in a user-specified CUDA stream context, see
        :ref:`Stream semantics of backward passes<bwd-cuda-stream-semantics>`.

    .. note::

        ``only_inputs`` argument is deprecated and is ignored now (defaults to ``True``).
        To accumulate gradient for other parts of the graph, please use
        ``torch.autograd.backward``.

    Args:
        outputs (sequence of Tensor or GradientEdge): outputs of the differentiated function.
        inputs (sequence of Tensor or GradientEdge): Inputs w.r.t. which the gradient will be
            returned (and not accumulated into ``.grad``).
        grad_outputs (sequence of Tensor): The "vector" in the vector-Jacobian product.
            Usually gradients w.r.t. each output. None values can be specified for scalar
            Tensors or ones that don't require grad. If a None value would be acceptable
            for all grad_tensors, then this argument is optional. Default: None.
        retain_graph (bool, optional): If ``False``, the graph used to compute the grad
            will be freed. Note that in nearly all cases setting this option to ``True``
            is not needed and often can be worked around in a much more efficient
            way. Defaults to the value of ``create_graph``.
        create_graph (bool, optional): If ``True``, graph of the derivative will
            be constructed, allowing to compute higher order derivative products.
            Default: ``False``.
        allow_unused (Optional[bool], optional): If ``False``, specifying inputs
            that were not used when computing outputs (and therefore their grad is
            always zero) is an error. Defaults to the value of ``materialize_grads``.
        is_grads_batched (bool, optional): If ``True``, the first dimension of each
            tensor in ``grad_outputs`` will be interpreted as the batch dimension.
            Instead of computing a single vector-Jacobian product, we compute a
            batch of vector-Jacobian products for each "vector" in the batch.
            We use the vmap prototype feature as the backend to vectorize calls
            to the autograd engine so that this computation can be performed in a
            single call. This should lead to performance improvements when compared
            to manually looping and performing backward multiple times. Note that
            due to this feature being experimental, there may be performance
            cliffs. Please use ``torch._C._debug_only_display_vmap_fallback_warnings(True)``
            to show any performance warnings and file an issue on github if warnings exist
            for your use case. Defaults to ``False``.
        materialize_grads (bool, optional): If ``True``, set the gradient for unused inputs
            to zero instead of None. This is useful when computing higher-order derivatives.
            If ``materialize_grads`` is ``True`` and ``allow_unused`` is ``False``, an error
            will be raised. Defaults to ``False``.

    """
    if materialize_grads and allow_unused is False:
        raise ValueError(
            "Expected allow_unused to be True or not passed when materialize_grads=True, "
            "but got: allow_unused=False."
        )
    if allow_unused is None:
        allow_unused = materialize_grads
    if is_tensor_like(outputs) or isinstance(outputs, graph.GradientEdge):
        outputs = cast(
            Union[Sequence[torch.Tensor], Sequence[graph.GradientEdge]], (outputs,)
        )
    else:
        outputs = tuple(outputs)
    if is_tensor_like(inputs) or isinstance(inputs, graph.GradientEdge):
        inputs = cast(_TensorOrTensorsOrGradEdge, (inputs,))
    else:
        inputs = tuple(inputs)
    t_outputs = tuple(i for i in outputs if is_tensor_like(i))
    t_inputs = tuple(i for i in inputs if is_tensor_like(i))
    overridable_args = t_outputs + t_inputs

In [17]:
# So in case if you do not understand what arguments we can pass, call ?? without brackets for a given method

import torch
import torch.nn as nn

class MySimpleNet(nn.Module):
    def __init__(self, attr1, attr2):
        super().__init__(base_class_attr1, base_class_attr2) # no self, since it is using super(), but if using parent class name, then use #self
        # define layers, activation functions and components for data to go throuhg
        # example for layers include convolutional, linear e.g. layers
        self.layer1 = nn.Linear(input_feature=10, output_feature=5)
        # also can define activation functions
        self.activation = nn.ReLU()

        def forward(self, data_input):
            # define the flow of the data through components initilized in __init__
            data_input = self.layer1(data_input)
            data_input = self.activation(data_input)
            return data_input

# create an instance of the class
model = MySimpleNet()
print(model)

In [4]:
import torch
import torch.nn as nn

class CustomModuleWithParameter(nn.Module):
    def __init__(self):
        super().__init__()
    
        # learnable parameter tensor, that has required_grad=True by default
        self.param_weight = nn.Parameter(torch.randn(3,4))
    
        # a simple tensor that does not have required required by default, so will not be recorded 
        # for computing the gradients and included into the computational graph
        self.tensor_weight = torch.ones(6,4)

    def forward(self, x):
        # goes through components
        return torch.dot(x, self.param_weight)

model = CustomModuleWithParameter()

for name, parameters in module.named_parameters():
    print(f"Parameter name: {name}, shape: {parameters.shape}, is gradients required?: {parameters.requires_grad}")

# look a simple tensor is not included as the part of parameters of the model, since it does not have
# gradients required by default

for name in module.parameters():
    print(f"Parameter shape: {name.shape}, is gradients required?: {name.requires_grad}")

Parameter name: param_weight, shape: torch.Size([3, 4]), is gradients required?: True
Parameter shape: torch.Size([3, 4]), is gradients required?: True

In [5]:
import torch
import torch.nn as nn

class ParamNet(nn.Module):
    def __init__(self):
        super().__init__()
        # included into the list of parameters of the module and required gradient by default
        self.weight_param1 = nn.Parameter(torch.rand(3,5))
        self.weight_param2 = nn.Parameter(torch.ones(7,9))
        
        # not included into the list of parameters of the moduel and does not require gradients
        self.tensor_no_param_no_grad = torch.tensor([3,4,5], dtype=torch.float32)
        
        # even with gradients enabled, it will still not be included into the list of model parameters
        self.tensor_no_param_yes_grad = torch.rand(2,3, requires_grad=True)

    def forward(self, data_input):
        # define the data flow going through layers/activation_functions
        return torch.matmul(data_input, self.weight_param)

# create an instance of the model
model = ParamNet()

# now iterate throught all the parameters of the model
for name, param in model.named_parameters():
    print(f"Parameter name: {name}, type: {type(param)}, shape: {param.shape}, is gradient required?: {param.requires_grad}")

# this code also iterates through all the parameters of the model, but does not return the name of the parameters
for param in model.parameters():
   print(f"\nParameter shape: {param.shape}, class type: {type(param)}, is gradients required?: {param.requires_grad}\n{param}\n")

Parameter name: weight_param1, type: <class 'torch.nn.parameter.Parameter'>, shape: torch.Size([3, 5]), is gradient required?: True
Parameter name: weight_param2, type: <class 'torch.nn.parameter.Parameter'>, shape: torch.Size([7, 9]), is gradient required?: True

Parameter shape: torch.Size([3, 5]), class type: <class 'torch.nn.parameter.Parameter'>, is gradients required?: True
Parameter containing:
tensor([[0.6613, 0.7870, 0.2244, 0.7261, 0.3084],
        [0.9800, 0.7766, 0.2283, 0.8950, 0.4856],
        [0.2311, 0.5942, 0.1179, 0.7616, 0.3801]], requires_grad=True)


Parameter shape: torch.Size([7, 9]), class type: <class 'torch.nn.parameter.Parameter'>, is gradients required?: True
Parameter containing:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]], requires_grad=True)

In [68]:
import torch
import torch.nn as nn

# Can we perform operations on variables on two classes torch.Tensor and torch.nn.parameter.Parameter
a = nn.Parameter(torch.rand(3,2))
a_ = a.clone()
b = torch.rand(2,5)
c = a @ b
display(c.shape, c.dtype, type(c), c.device, c.requires_grad, c.grad_fn, a.requires_grad, b.requires_grad, a.grad, b.grad, c.grad)
print(type(a))

e = a + a_
# So Operations of torch.nn.parameter.Parameter results in torch.Tensor regardless
print("The operations of only torch.nn.parameter.Parameter object types, results in object type of ", type(e))
# so if there is operations done with tensors of type torch.Tensor and torch.nn.parameter.Parameter (or shortly torch.nn.Parameter)
# then the resulting tensor will be of type torch.Tensor, at in this case!

/var/folders/1x/9lpkf83945l_89078l86mxm80000gn/T/ipykernel_39748/3864927170.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_951ooclnw1/croot/libtorch_1746637517770/work/build/aten/src/ATen/core/TensorBody.h:494.)
  display(c.shape, c.dtype, type(c), c.device, c.requires_grad, c.grad_fn, a.requires_grad, b.requires_grad, a.grad, b.grad, c.grad)

torch.Size([3, 5])

torch.float32

torch.Tensor

device(type='cpu')

True

True

False

None

None

None

<class 'torch.nn.parameter.Parameter'>
The operations of only torch.nn.parameter.Parameter object types, results in object type of  <class 'torch.Tensor'>

In [77]:
import torch
import torch.nn as nn

class ParamExperimentNet(nn.Module):
    def __init__(self, 
                 weight_param1: torch.nn.parameter.Parameter, 
                 weight_param2: torch.nn.parameter.Parameter, 
                 weight_param3: torch.nn.parameter.Parameter,
                 tn_nograd1: torch.Tensor,
                 tn_nograd2: torch.Tensor):
        super().__init__()
        # torch.nn.parameter.Parameter objects: requires_grad=True by default
        self.weight_param1 = weight_param1
        self.weight_param2 = weight_param2
        self.weight_param3 = weight_param3
        
        # torch.Tensor objects: requires_grad=False by default
        self.tn_nograd1 = tn_nograd1
        self.tn_nograd2 = tn_nograd2

    # forward-pass, compute loss, compute gradients
    def forward(self, data_input: torch.Tensor):
        # define the flow of data through layers/activation_function/components initialized in __init__
        op1 = torch.add(data_input, self.weight_param1)
        op2 = torch.add(self.weight_param2, self.weight_param3)
        op3 = torch.add(self.tn_nograd1, self.tn_nograd2) 
        return op1 + op2 + op3

# create an instance of the ParParamExperimentNet Class and provide 5 positional arguments
x1 = nn.Parameter(torch.rand(4,5))
x2 = nn.Parameter(torch.arange(5.0).view(1,5))
x3 = nn.Parameter(torch.ones(4,1))
k1 = torch.zeros(2,4,1)
k2 = torch.randn(1,4,5)
# these shapes are broadcastable, numbers along each dimensions, either match, 1 or 0.
model_heh = ParamExperimentNet(x1,x2,x3,k1,k2)

# iterate through all the parameters, only objects of type torch.nn.parameter.Parameter (or torch.nn.Parameter)
# will be captured by .named_parameters() and parameters()

# Since there is only tensors of type torch.nn.parameter.Parameter, only those are listed as parameters of the model
# and torch.Tensor object types are not listed, nn.Parameter have requires_grad=True by default and are recorded
# into computational graph
for name, param in model_heh.named_parameters():
    print(f"Parameter name: {name}, shape: {param.shape}, type: {type(param)}, requires_grad={param.requires_grad}")

# Does the same thing as named_parameters(), with a single difference being, it does capture the name 
# of the individual nn.Parameter, also torch.Tensor are not listed here as well
print("")
for param in model_heh.parameters():
    print(f"Parameter shape: {param.shape}, type: {type(param)}, requires_grad={param.requires_grad}")
print("")
forward_pass = model_heh.forward(torch.ones(4,5))
# see the resulting tensor object type is torch.Tensor, even though operations were performed between torch.nn.parameter.Parater
# and torch.Tensor
print(forward_pass.shape, type(forward_pass), forward_pass.requires_grad, forward_pass.is_leaf)

Parameter name: weight_param1, shape: torch.Size([4, 5]), type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True
Parameter name: weight_param2, shape: torch.Size([1, 5]), type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True
Parameter name: weight_param3, shape: torch.Size([4, 1]), type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True

Parameter shape: torch.Size([4, 5]), type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True
Parameter shape: torch.Size([1, 5]), type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True
Parameter shape: torch.Size([4, 1]), type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True

torch.Size([2, 4, 5]) <class 'torch.Tensor'> True False

In [3]:
model_heh.forward??

Signature: model_heh.forward(data_input: torch.Tensor)
Docstring:
Define the computation performed at every call.

Should be overridden by all subclasses.

.. note::
    Although the recipe for forward pass needs to be defined within
    this function, one should call the :class:`Module` instance afterwards
    instead of this since the former takes care of running the
    registered hooks while the latter silently ignores them.
Source:
    def forward(self, data_input: torch.Tensor):
        # define the flow of data through layers/activation_function/components initialized in __init__
        op1 = torch.add(data_input, self.weight_param1)
        op2 = torch.add(self.weight_param2, self.weight_param3)
        op3 = torch.add(self.tn_nograd1, self.tn_nograd2)
        return op1 + op2 + op3
File:      /var/folders/1x/9lpkf83945l_89078l86mxm80000gn/T/ipykernel_40437/2692077383.py
Type:      method

In [6]:
model_heh.state_dict??

Signature: model_heh.state_dict(*args, destination=None, prefix='', keep_vars=False)
Source:
    def state_dict(self, *args, destination=None, prefix="", keep_vars=False):
        r"""Return a dictionary containing references to the whole state of the module.

        Both parameters and persistent buffers (e.g. running averages) are
        included. Keys are corresponding parameter and buffer names.
        Parameters and buffers set to ``None`` are not included.

        .. note::
            The returned object is a shallow copy. It contains references
            to the module's parameters and buffers.

        .. warning::
            Currently ``state_dict()`` also accepts positional arguments for
            ``destination``, ``prefix`` and ``keep_vars`` in order. However,
            this is being deprecated and keyword arguments will be enforced in
            future releases.

        .. warning::
            Please avoid the use of argument ``destination`` as it is not
            designed for end-users.

        Args:
            destination (dict, optional): If provided, the state of module will
                be updated into the dict and the same object is returned.
                Otherwise, an ``OrderedDict`` will be created and returned.
                Default: ``None``.
            prefix (str, optional): a prefix added to parameter and buffer
                names to compose the keys in state_dict. Default: ``''``.
            keep_vars (bool, optional): by default the :class:`~torch.Tensor` s
                returned in the state dict are detached from autograd. If it's
                set to ``True``, detaching will not be performed.
                Default: ``False``.

        Returns:
            dict:
                a dictionary containing a whole state of the module

        Example::

            >>> # xdoctest: +SKIP("undefined vars")
            >>> module.state_dict().keys()
            ['bias', 'weight']

        """
        # TODO: Remove `args` and the parsing logic when BC allows.
        if len(args) > 0:
            # DeprecationWarning is ignored by default
            warnings.warn(
                "Positional args are being deprecated, use kwargs instead. Refer to "
                "https://pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.state_dict"
                " for details.",
                FutureWarning,
                stacklevel=2,
            )
            if destination is None:
                destination = args[0]
            if len(args) > 1 and prefix == "":
                prefix = args[1]
            if len(args) > 2 and keep_vars is False:
                keep_vars = args[2]

        if destination is None:
            destination = OrderedDict()
            destination._metadata = OrderedDict()

        local_metadata = dict(version=self._version)
        if hasattr(destination, "_metadata"):
            destination._metadata[prefix[:-1]] = local_metadata

        for hook in self._state_dict_pre_hooks.values():
            hook(self, prefix, keep_vars)
        self._save_to_state_dict(destination, prefix, keep_vars)
        for name, module in self._modules.items():
            if module is not None:
                module.state_dict(
                    destination=destination,
                    prefix=prefix + name + ".",
                    keep_vars=keep_vars,
                )
        for hook in self._state_dict_hooks.values():
            hook_result = hook(self, destination, prefix, local_metadata)
            if not getattr(hook, "_from_public_api", False):
                if hook_result is not None:
                    destination = hook_result
            else:
                if hook_result is not None:
                    raise RuntimeError("state_dict post-hook must return None")
        return destination
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py
Type:      method

model_heh.load_state_dict??

In [11]:
model_heh.train??

Signature: model_heh.train(mode: bool = True) -> ~T
Source:
    def train(self: T, mode: bool = True) -> T:
        r"""Set the module in training mode.

        This has any effect only on certain modules. See documentations of
        particular modules for details of their behaviors in training/evaluation
        mode, if they are affected, e.g. :class:`Dropout`, :class:`BatchNorm`,
        etc.

        Args:
            mode (bool): whether to set training mode (``True``) or evaluation
                         mode (``False``). Default: ``True``.

        Returns:
            Module: self
        """
        if not isinstance(mode, bool):
            raise ValueError("training mode is expected to be boolean")
        self.training = mode
        for module in self.children():
            module.train(mode)
        return self
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py
Type:      method

In [12]:
model_heh.eval??

Signature: model_heh.eval() -> ~T
Source:
    def eval(self: T) -> T:
        r"""Set the module in evaluation mode.

        This has any effect only on certain modules. See documentations of
        particular modules for details of their behaviors in training/evaluation
        mode, if they are affected, e.g. :class:`Dropout`, :class:`BatchNorm`,
        etc.

        This is equivalent with :meth:`self.train(False) <torch.nn.Module.train>`.

        See :ref:`locally-disable-grad-doc` for a comparison between
        `.eval()` and several similar mechanisms that may be confused with it.

        Returns:
            Module: self
        """
        return self.train(False)
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py
Type:      method

In [13]:
model_heh.modules??

Signature: model_heh.modules() -> Iterator[ForwardRef('Module')]
Source:
    def modules(self) -> Iterator["Module"]:
        r"""Return an iterator over all modules in the network.

        Yields:
            Module: a module in the network

        Note:
            Duplicate modules are returned only once. In the following
            example, ``l`` will be returned only once.

        Example::

            >>> l = nn.Linear(2, 2)
            >>> net = nn.Sequential(l, l)
            >>> for idx, m in enumerate(net.modules()):
            ...     print(idx, '->', m)

            0 -> Sequential(
              (0): Linear(in_features=2, out_features=2, bias=True)
              (1): Linear(in_features=2, out_features=2, bias=True)
            )
            1 -> Linear(in_features=2, out_features=2, bias=True)

        """
        for _, module in self.named_modules():
            yield module
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py
Type:      method

In [15]:
model_heh.children??

Signature: model_heh.children() -> Iterator[ForwardRef('Module')]
Source:
    def children(self) -> Iterator["Module"]:
        r"""Return an iterator over immediate children modules.

        Yields:
            Module: a child module
        """
        for name, module in self.named_children():
            yield module
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/module.py
Type:      method

In [3]:
import torch
import torch.nn as nn

class AgainParamNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.weight1 = nn.Parameter(torch.rand(3,4))
        self.weight2 = nn.Parameter(torch.rand(5,6))
        self.weight3 = torch.rand(9,8)

    def forward(self, data_input):
        return data_input + self.weight3

model = AgainParamNet()

for name, param in model.named_parameters():
    print(f"Parameter name: {name}, type: {type(param)}, requires_grad={param.requires_grad}")

for param in model.parameters():
    print(param)

Parameter name: weight1, type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True
Parameter name: weight2, type: <class 'torch.nn.parameter.Parameter'>, requires_grad=True
Parameter containing:
tensor([[0.8615, 0.3522, 0.1782, 0.1892],
        [0.5046, 0.6216, 0.1529, 0.2444],
        [0.9990, 0.7839, 0.2083, 0.6377]], requires_grad=True)
Parameter containing:
tensor([[0.2053, 0.5451, 0.6087, 0.9635, 0.8662, 0.0589],
        [0.5184, 0.1772, 0.0550, 0.4578, 0.6219, 0.0965],
        [0.7546, 0.7754, 0.9498, 0.5987, 0.0716, 0.8863],
        [0.9625, 0.3226, 0.1820, 0.8026, 0.3104, 0.3272],
        [0.5890, 0.1193, 0.4736, 0.4637, 0.5690, 0.9625]], requires_grad=True)

In [48]:
# torch.nn.parameter.Parameter will still have its required_grad=True
# even inside of context manager "with torch.no_grad(): "
# no_grad() does not effect nn.Parameter

import torch
from torch import nn
from torch import optim

class SimpleNet(nn.Module):
    def __init__(self,):
        super(SimpleNet, self).__init__()
        # Define learnable parameters of the model that will be updated
        self.weight = nn.Parameter(torch.rand(1))

    def forward(self, x):
        return torch.mul(x, self.weight)

model = SimpleNet()
print(f"Initial model parameters: {list(model.parameters())}")

#define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

#sampe input and target
input_tensor = torch.tensor([2.0])
target_tensor = torch.tensor([4.0])

for epoch in range(100):
    optimizer.zero_grad() # avoid gradient accumulation of other batches effecting the updates of parameters
    output = model(input_tensor) # forward pass
    loss = criterion(output, target_tensor) # calculate loss
    loss.backward()
    optimizer.step() # update parameters

    if epoch % 10 == 0:
        print(f"Epoch: {epoch}, Loss: {loss.item()}, weight: {model.weight.item()}")

print(f"Final Model parameters: {list(model.parameters())}")

Initial model parameters: [Parameter containing:
tensor([0.6953], requires_grad=True)]
Epoch: 0, Loss: 6.809258460998535, weight: 0.7996504902839661
Epoch: 10, Loss: 1.284861445426941, weight: 1.4785820245742798
Epoch: 20, Loss: 0.24244500696659088, weight: 1.773501992225647
Epoch: 30, Loss: 0.04574774205684662, weight: 1.9016119241714478
Epoch: 40, Loss: 0.00863232184201479, weight: 1.957261323928833
Epoch: 50, Loss: 0.0016288697952404618, weight: 1.98143470287323
Epoch: 60, Loss: 0.00030735816108062863, weight: 1.9919354915618896
Epoch: 70, Loss: 5.799321661470458e-05, weight: 1.9964969158172607
Epoch: 80, Loss: 1.0943246707029175e-05, weight: 1.9984782934188843
Epoch: 90, Loss: 2.064821728708921e-06, weight: 1.999338984489441
Final Model parameters: [Parameter containing:
tensor([1.9997], requires_grad=True)]

In [57]:
criterion??

Signature:      criterion(*args, **kwargs)
Type:           MSELoss
String form:    MSELoss()
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/loss.py
Source:
class MSELoss(_Loss):
    r"""Creates a criterion that measures the mean squared error (squared L2 norm) between
    each element in the input :math:`x` and target :math:`y`.

    The unreduced (i.e. with :attr:`reduction` set to ``'none'``) loss can be described as:

    .. math::
        \ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
        l_n = \left( x_n - y_n \right)^2,

    where :math:`N` is the batch size. If :attr:`reduction` is not ``'none'``
    (default ``'mean'``), then:

    .. math::
        \ell(x, y) =
        \begin{cases}
            \operatorname{mean}(L), &  \text{if reduction} = \text{`mean';}\\
            \operatorname{sum}(L),  &  \text{if reduction} = \text{`sum'.}
        \end{cases}

    :math:`x` and :math:`y` are tensors of arbitrary shapes with a total
    of :math:`N` elements each.

    The mean operation still operates over all the elements, and divides by :math:`N`.

    The division by :math:`N` can be avoided if one sets ``reduction = 'sum'``.

    Args:
        size_average (bool, optional): Deprecated (see :attr:`reduction`). By default,
            the losses are averaged over each loss element in the batch. Note that for
            some losses, there are multiple elements per sample. If the field :attr:`size_average`
            is set to ``False``, the losses are instead summed for each minibatch. Ignored
            when :attr:`reduce` is ``False``. Default: ``True``
        reduce (bool, optional): Deprecated (see :attr:`reduction`). By default, the
            losses are averaged or summed over observations for each minibatch depending
            on :attr:`size_average`. When :attr:`reduce` is ``False``, returns a loss per
            batch element instead and ignores :attr:`size_average`. Default: ``True``
        reduction (str, optional): Specifies the reduction to apply to the output:
            ``'none'`` | ``'mean'`` | ``'sum'``. ``'none'``: no reduction will be applied,
            ``'mean'``: the sum of the output will be divided by the number of
            elements in the output, ``'sum'``: the output will be summed. Note: :attr:`size_average`
            and :attr:`reduce` are in the process of being deprecated, and in the meantime,
            specifying either of those two args will override :attr:`reduction`. Default: ``'mean'``

    Shape:
        - Input: :math:`(*)`, where :math:`*` means any number of dimensions.
        - Target: :math:`(*)`, same shape as the input.

    Examples::

        >>> loss = nn.MSELoss()
        >>> input = torch.randn(3, 5, requires_grad=True)
        >>> target = torch.randn(3, 5)
        >>> output = loss(input, target)
        >>> output.backward()
    """
    __constants__ = ["reduction"]

    def __init__(self, size_average=None, reduce=None, reduction: str = "mean") -> None:
        super().__init__(size_average, reduce, reduction)

    def forward(self, input: Tensor, target: Tensor) -> Tensor:
        return F.mse_loss(input, target, reduction=self.reduction)
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.

In [4]:
import torch
from torch import nn
from torch import optim

class SimNet(nn.Module):
    def __init__(self):
        super(SimNet, self).__init__()
        self.weight = nn.Parameter(torch.rand(2,3))
        self.bias = nn.Parameter(torch.rand(2,1))

    def forward(self, data: torch.Size([2,3])):
        return data * self.weight + self.bias


modnet = SimNet()
print(f"Initial Model learnable parameters: {list(modnet.named_parameters())}") # or simply .parameters()

# input and target values
input_value = torch.rand(2,3)
target_value = torch.rand(2,3)

# define loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(modnet.parameters(), lr=0.01)

for epoch in range(100):
    # clear all the gradients accumulation before processing a new batch
    optimizer.zero_grad()
    output = modnet(input_value) # forward pass
    loss = criterion(output, target_value) # compute loss
    loss.backward(gradient=torch.tensor(1.0)) # since loss is non-scalar, we need to provide tensor of ones with the same shape as loss
    optimizer.step() # update weights and biases

    if epoch % 10 == 0:
        print(f"\nEpoch: {epoch}, Weight: {modnet.weight.reshape(-1)}, Bias: {modnet.bias.reshape(-1)}, Loss: {loss:.4f}")

Initial Model learnable parameters: [('weight', Parameter containing:
tensor([[0.7893, 0.9549, 0.1121],
        [0.0870, 0.9928, 0.4731]], requires_grad=True)), ('bias', Parameter containing:
tensor([[0.0925],
        [0.0916]], requires_grad=True))]

Epoch: 0, Weight: tensor([0.7883, 0.9553, 0.1137, 0.0868, 0.9924, 0.4732],
       grad_fn=<ViewBackward0>), Bias: tensor([0.0958, 0.0910], grad_fn=<ViewBackward0>), Loss: 0.2101

Epoch: 10, Weight: tensor([0.7779, 0.9595, 0.1294, 0.0853, 0.9889, 0.4740],
       grad_fn=<ViewBackward0>), Bias: tensor([0.1269, 0.0855], grad_fn=<ViewBackward0>), Loss: 0.1960

Epoch: 20, Weight: tensor([0.7669, 0.9635, 0.1443, 0.0838, 0.9856, 0.4749],
       grad_fn=<ViewBackward0>), Bias: tensor([0.1549, 0.0806], grad_fn=<ViewBackward0>), Loss: 0.1840

Epoch: 30, Weight: tensor([0.7555, 0.9672, 0.1586, 0.0825, 0.9825, 0.4759],
       grad_fn=<ViewBackward0>), Bias: tensor([0.1802, 0.0763], grad_fn=<ViewBackward0>), Loss: 0.1737

Epoch: 40, Weight: tensor([0.7437, 0.9709, 0.1721, 0.0813, 0.9796, 0.4769],
       grad_fn=<ViewBackward0>), Bias: tensor([0.2031, 0.0724], grad_fn=<ViewBackward0>), Loss: 0.1648

Epoch: 50, Weight: tensor([0.7316, 0.9743, 0.1851, 0.0801, 0.9768, 0.4780],
       grad_fn=<ViewBackward0>), Bias: tensor([0.2237, 0.0690], grad_fn=<ViewBackward0>), Loss: 0.1570

Epoch: 60, Weight: tensor([0.7193, 0.9776, 0.1976, 0.0790, 0.9742, 0.4791],
       grad_fn=<ViewBackward0>), Bias: tensor([0.2424, 0.0660], grad_fn=<ViewBackward0>), Loss: 0.1501

Epoch: 70, Weight: tensor([0.7067, 0.9808, 0.2095, 0.0779, 0.9717, 0.4802],
       grad_fn=<ViewBackward0>), Bias: tensor([0.2593, 0.0634], grad_fn=<ViewBackward0>), Loss: 0.1439

Epoch: 80, Weight: tensor([0.6940, 0.9838, 0.2210, 0.0769, 0.9693, 0.4814],
       grad_fn=<ViewBackward0>), Bias: tensor([0.2747, 0.0611], grad_fn=<ViewBackward0>), Loss: 0.1383

Epoch: 90, Weight: tensor([0.6811, 0.9867, 0.2321, 0.0759, 0.9670, 0.4826],
       grad_fn=<ViewBackward0>), Bias: tensor([0.2886, 0.0590], grad_fn=<ViewBackward0>), Loss: 0.1332

In [82]:
# So main difference between torch.Tensor and torch.nn.parameter.Parameter is that 
# nn.Parameter wrapped around torch.Tensor makes it explicit that these tensors are learnable parameters
# of the model, and have requires_grad=True by default, and they are included into the list
# of model parameters, in model.parameters(), unlike just torch.Tensor is not included into the
# list of model parameters even with gradients required, and even after that torch.Tensor
# is not involed in the optimization and updating of the weights, but only nn.Parameter are

In [5]:
nn.Linear??

Init signature:
nn.Linear(
    in_features: int,
    out_features: int,
    bias: bool = True,
    device=None,
    dtype=None,
) -> None
Source:
class Linear(Module):
    r"""Applies an affine linear transformation to the incoming data: :math:`y = xA^T + b`.

    This module supports :ref:`TensorFloat32<tf32_on_ampere>`.

    On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.

    Args:
        in_features: size of each input sample
        out_features: size of each output sample
        bias: If set to ``False``, the layer will not learn an additive bias.
            Default: ``True``

    Shape:
        - Input: :math:`(*, H_{in})` where :math:`*` means any number of
          dimensions including none and :math:`H_{in} = \text{in\_features}`.
        - Output: :math:`(*, H_{out})` where all but the last dimension
          are the same shape as the input and :math:`H_{out} = \text{out\_features}`.

    Attributes:
        weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
        bias:   the learnable bias of the module of shape :math:`(\text{out\_features})`.
                If :attr:`bias` is ``True``, the values are initialized from
                :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
                :math:`k = \frac{1}{\text{in\_features}}`

    Examples::

        >>> m = nn.Linear(20, 30)
        >>> input = torch.randn(128, 20)
        >>> output = m(input)
        >>> print(output.size())
        torch.Size([128, 30])
    """

    __constants__ = ["in_features", "out_features"]
    in_features: int
    out_features: int
    weight: Tensor

    def __init__(
        self,
        in_features: int,
        out_features: int,
        bias: bool = True,
        device=None,
        dtype=None,
    ) -> None:
        factory_kwargs = {"device": device, "dtype": dtype}
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(
            torch.empty((out_features, in_features), **factory_kwargs)
        )
        if bias:
            self.bias = Parameter(torch.empty(out_features, **factory_kwargs))
        else:
            self.register_parameter("bias", None)
        self.reset_parameters()

    def reset_parameters(self) -> None:
        # Setting a=sqrt(5) in kaiming_uniform is the same as initializing with
        # uniform(-1/sqrt(in_features), 1/sqrt(in_features)). For details, see
        # https://github.com/pytorch/pytorch/issues/57109
        init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            init.uniform_(self.bias, -bound, bound)

    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)

    def extra_repr(self) -> str:
        return f"in_features={self.in_features}, out_features={self.out_features}, bias={self.bias is not None}"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/linear.py
Type:           type
Subclasses:     NonDynamicallyQuantizableLinear, LazyLinear, Linear, LinearBn1d, Linear

In [25]:
# nn.Linear takes number of columns as input features, because
# each column in matrix corresponds to a unique feature while the rows
# corresponding to individual records of data, as long as number of columns equal to in_features, 
# linear model should work

model = nn.Linear(in_features=30, out_features=10)
data = torch.rand(256, 30) # 256 individual records each with 30 unique features
print(f"Input feature shape: {data.shape}")
output = model(data)
print(f"Ouput feature shape: {output.shape}, dtype: {output.dtype}, type: {type(output)}, requires_grad={output.requires_grad}")
display(output, output.grad_fn, output.is_leaf, output.requires_grad, output.size(), output.shape)

Input feature shape: torch.Size([256, 30])
Ouput feature shape: torch.Size([256, 10]), dtype: torch.float32, type: <class 'torch.Tensor'>, requires_grad=True

tensor([[ 0.0902, -0.2231, -0.0956,  ...,  0.0401, -0.5219,  0.2464],
        [ 0.1397, -0.0361,  0.2733,  ...,  0.0066, -0.7993, -0.0205],
        [-0.0953, -0.1675,  0.1679,  ...,  0.0898, -0.3153, -0.2594],
        ...,
        [ 0.2344, -0.1465,  0.2307,  ..., -0.0650, -0.6518, -0.0357],
        [ 0.2038, -0.2387, -0.0833,  ...,  0.0567, -0.4366,  0.1892],
        [ 0.1586, -0.2073, -0.1245,  ..., -0.1068, -0.5967,  0.0478]],
       grad_fn=<AddmmBackward0>)

False

True

torch.Size([256, 10])

torch.Size([256, 10])

In [2]:
import torch
from torch import nn

class SimpleLinearModel(nn.Module):
    def __init__(self, in_features, out_features):
        super(SimpleLinearModel, self).__init__()
        # define a linear layer
        self.linear_layer = nn.Linear(in_features, out_features)
        # model initilized with in_features and out_features
        print(f"Model initialized with in_features={in_features} and out_features={out_features}")
        print(f"Defined a linear layer {self.linear_layer}")

    def forward(self, data_input):
        # input data shape/size
        print(f"Input data shape: {data_input.size()}") # also can do data_input.shape, no difference with .size()
        output = self.linear_layer(data_input)
        print(f"Input data after linear layer: {output.shape}")
        return output

in_dim = 30
out_dim = 14
linmod = SimpleLinearModel(in_features=in_dim, out_features=out_dim)

# random input data
data = torch.arange(1290, dtype=torch.float32).view(43, 30)

# forward pass
output = linmod(data)
print(f"Model output shape: {output.shape}\n")

# Model parameter
for name, param in linmod.named_parameters():
    print(f"Parameter name: {name}, shape: {param.size()}")

Model initialized with in_features=30 and out_features=14
Defined a linear layer Linear(in_features=30, out_features=14, bias=True)
Input data shape: torch.Size([43, 30])
Input data after linear layer: torch.Size([43, 14])
Model output shape: torch.Size([43, 14])

Parameter name: linear_layer.weight, shape: torch.Size([14, 30])
Parameter name: linear_layer.bias, shape: torch.Size([14])

In [4]:
nn.Linear??

Init signature:
nn.Linear(
    in_features: int,
    out_features: int,
    bias: bool = True,
    device=None,
    dtype=None,
) -> None
Source:
class Linear(Module):
    r"""Applies an affine linear transformation to the incoming data: :math:`y = xA^T + b`.

    This module supports :ref:`TensorFloat32<tf32_on_ampere>`.

    On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.

    Args:
        in_features: size of each input sample
        out_features: size of each output sample
        bias: If set to ``False``, the layer will not learn an additive bias.
            Default: ``True``

    Shape:
        - Input: :math:`(*, H_{in})` where :math:`*` means any number of
          dimensions including none and :math:`H_{in} = \text{in\_features}`.
        - Output: :math:`(*, H_{out})` where all but the last dimension
          are the same shape as the input and :math:`H_{out} = \text{out\_features}`.

    Attributes:
        weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
        bias:   the learnable bias of the module of shape :math:`(\text{out\_features})`.
                If :attr:`bias` is ``True``, the values are initialized from
                :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
                :math:`k = \frac{1}{\text{in\_features}}`

    Examples::

        >>> m = nn.Linear(20, 30)
        >>> input = torch.randn(128, 20)
        >>> output = m(input)
        >>> print(output.size())
        torch.Size([128, 30])
    """

    __constants__ = ["in_features", "out_features"]
    in_features: int
    out_features: int
    weight: Tensor

    def __init__(
        self,
        in_features: int,
        out_features: int,
        bias: bool = True,
        device=None,
        dtype=None,
    ) -> None:
        factory_kwargs = {"device": device, "dtype": dtype}
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(
            torch.empty((out_features, in_features), **factory_kwargs)
        )
        if bias:
            self.bias = Parameter(torch.empty(out_features, **factory_kwargs))
        else:
            self.register_parameter("bias", None)
        self.reset_parameters()

    def reset_parameters(self) -> None:
        # Setting a=sqrt(5) in kaiming_uniform is the same as initializing with
        # uniform(-1/sqrt(in_features), 1/sqrt(in_features)). For details, see
        # https://github.com/pytorch/pytorch/issues/57109
        init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            init.uniform_(self.bias, -bound, bound)

    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)

    def extra_repr(self) -> str:
        return f"in_features={self.in_features}, out_features={self.out_features}, bias={self.bias is not None}"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/linear.py
Type:           type
Subclasses:     NonDynamicallyQuantizableLinear, LazyLinear, Linear, LinearBn1d, Linear

In [26]:
import torch
from torch import nn
from torch import optim

class SimpleLinearModel(nn.Module):
    def __init__(self, in_feature, out_feature):
        super().__init__()
        #define the layer
        self.linear_layer = nn.Linear(in_feature, out_feature)

    def forward(self, data):
        output = self.linear_layer(data)
        return output

# create an instance of the class
inputs = 45
outputs = 12
model = SimpleLinearModel(in_feature=inputs, out_feature=outputs)

# loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# input data
dm = torch.rand(32, 45) # 45 is number of features, while 32 is the number of individual records
output = model(dm) # forward pass

for param in model.parameters():
    print(param)

display(output.requires_grad, output.grad_fn, output.shape, output)

Parameter containing:
tensor([[ 0.0039, -0.0131, -0.0172, -0.0807, -0.0624, -0.1078, -0.0286, -0.1331,
         -0.0718, -0.0279, -0.0602, -0.0578,  0.0239,  0.0658, -0.1053,  0.1004,
         -0.0655,  0.0263,  0.0576,  0.0890, -0.1239, -0.1270, -0.0558, -0.1327,
          0.1340, -0.1274,  0.0080, -0.0992, -0.0706, -0.0779,  0.0381,  0.0431,
         -0.0101, -0.1080,  0.1249, -0.0319, -0.0694,  0.1283,  0.0793, -0.0864,
          0.0463,  0.0050,  0.1030, -0.0348, -0.0298],
        [ 0.0958, -0.0722, -0.0986,  0.1186, -0.1114, -0.1209, -0.0830,  0.0182,
          0.1394,  0.1088, -0.1145, -0.0831,  0.0150, -0.1429, -0.1408,  0.0304,
          0.0432,  0.0073, -0.1487, -0.0418, -0.0709,  0.0682, -0.0925,  0.0834,
          0.0844,  0.0950, -0.0365, -0.1371,  0.1028,  0.0794,  0.0188,  0.0218,
         -0.0943, -0.1338,  0.1062, -0.0656,  0.1050,  0.0091,  0.1473,  0.0441,
          0.0917,  0.0200, -0.0119, -0.0814,  0.0880],
        [-0.0232, -0.1239, -0.1010, -0.0473,  0.1402,  0.1218,  0.0399,  0.1317,
         -0.0831, -0.0938,  0.1248, -0.1472,  0.1482,  0.0516,  0.1442, -0.0528,
          0.1045, -0.1236, -0.0361, -0.0625, -0.0185, -0.0256,  0.1324,  0.0560,
          0.0576, -0.0548,  0.0272,  0.0537, -0.1169, -0.1128,  0.0662,  0.1369,
         -0.0335, -0.0271,  0.0566,  0.0223, -0.1473, -0.0770, -0.1309,  0.0464,
         -0.0725, -0.1103,  0.1383, -0.0427, -0.0743],
        [-0.1055, -0.0067, -0.1101,  0.0891, -0.0012, -0.1157,  0.1014, -0.0868,
          0.0248,  0.0709,  0.0326, -0.0749,  0.1238, -0.0102,  0.0283,  0.0004,
         -0.1078,  0.0232,  0.0670,  0.0944,  0.1296, -0.0425,  0.0044, -0.1350,
          0.1309,  0.0571,  0.0359,  0.0052,  0.0234, -0.0046, -0.0773, -0.0147,
         -0.0997, -0.0127, -0.1013,  0.0672, -0.0738,  0.0392,  0.0951, -0.0988,
         -0.0997, -0.0217, -0.0077, -0.0754,  0.1350],
        [ 0.0988,  0.0861, -0.0470, -0.1101, -0.0946,  0.0629, -0.1422, -0.0655,
         -0.1455, -0.0507, -0.1115,  0.0538,  0.1311, -0.0890, -0.1120, -0.1170,
          0.0814,  0.1031, -0.0609, -0.0571,  0.0094, -0.0423, -0.1043,  0.1366,
         -0.1193,  0.0953, -0.1271,  0.1009, -0.0133,  0.0179, -0.1199,  0.0456,
          0.1271,  0.0163, -0.0627,  0.0331, -0.1455,  0.0501,  0.0593,  0.0940,
          0.0233, -0.1409,  0.1125,  0.0354,  0.1383],
        [-0.0158, -0.0266,  0.0439, -0.1440,  0.1409,  0.1412, -0.1177, -0.0848,
         -0.0718,  0.1297, -0.0684, -0.1081,  0.0979,  0.0411,  0.0561, -0.1136,
         -0.1156,  0.0402, -0.1180,  0.1322, -0.0698,  0.0201,  0.0505,  0.0302,
          0.0154, -0.0312,  0.1237, -0.1292,  0.0784, -0.0795, -0.1120, -0.1140,
         -0.0462,  0.0893, -0.1128,  0.1310,  0.1384, -0.0085,  0.0303,  0.1226,
          0.0148,  0.1437, -0.0114, -0.0521, -0.1322],
        [-0.1359,  0.0895, -0.0936, -0.0449,  0.1160, -0.1329,  0.0796,  0.0837,
         -0.0429, -0.1238,  0.0906, -0.1429, -0.1282, -0.0226, -0.1151, -0.0785,
          0.0887,  0.1479, -0.0141, -0.0579, -0.0625, -0.0894,  0.0324, -0.0116,
         -0.1397, -0.1098, -0.1125, -0.0806,  0.0180,  0.1364,  0.1408,  0.0259,
          0.0595,  0.0594,  0.0205, -0.0217,  0.1395,  0.1205,  0.0573, -0.0501,
         -0.0226,  0.0401,  0.0075,  0.0904, -0.0720],
        [ 0.0693, -0.0151, -0.0521, -0.0894, -0.0849, -0.1385, -0.1132, -0.0248,
          0.1238, -0.0713,  0.0416, -0.1355,  0.0240, -0.1453, -0.0423,  0.0753,
         -0.0193, -0.0177, -0.1412,  0.1045,  0.0433,  0.0208, -0.0869,  0.0882,
          0.0588, -0.0469,  0.0652,  0.0759,  0.0471,  0.0769,  0.0320, -0.0461,
          0.1390,  0.0783,  0.0319,  0.1456, -0.0565, -0.0050,  0.0922,  0.0695,
         -0.0829, -0.0925, -0.0795, -0.0755, -0.0961],
        [-0.0796, -0.1010, -0.1104,  0.0777,  0.1309,  0.0307,  0.0137, -0.1263,
         -0.0787, -0.1238, -0.1249,  0.0847,  0.0701,  0.0474,  0.0041,  0.0476,
          0.1223,  0.1038, -0.1024, -0.0456, -0.0959,  0.1321,  0.0355, -0.0465,
         -0.0472,  0.0446, -0.0174, -0.1358, -0.0819, -0.0256,  0.0849, -0.1282,
          0.0631, -0.0519, -0.0441, -0.1242,  0.1122,  0.1283,  0.0630, -0.0400,
         -0.1207, -0.0815, -0.0606, -0.0589,  0.1041],
        [-0.1343, -0.1135,  0.1062, -0.0520,  0.1455,  0.0166,  0.1330,  0.0592,
          0.0964,  0.0679,  0.0219, -0.0935,  0.0034,  0.0151,  0.1425, -0.1263,
         -0.0336,  0.1254,  0.0544, -0.1347,  0.0343,  0.0862, -0.0027,  0.0092,
          0.0647,  0.1284,  0.0826, -0.0741,  0.0269, -0.0356, -0.1103, -0.0798,
         -0.1428, -0.1267, -0.1086,  0.1145, -0.0336, -0.1314, -0.0624,  0.1439,
         -0.0646, -0.0742, -0.0734, -0.0874, -0.1340],
        [ 0.0217,  0.0902, -0.1267,  0.0030, -0.0777,  0.0922, -0.1134, -0.0126,
         -0.1311,  0.0267,  0.1375, -0.1293, -0.0692, -0.0597,  0.1407,  0.0071,
          0.0629, -0.0879,  0.1095, -0.1441,  0.0185,  0.0624, -0.0838, -0.0998,
         -0.0981,  0.1374,  0.0830, -0.1293, -0.1064,  0.1261,  0.1450,  0.0271,
         -0.1173, -0.1020,  0.0940,  0.0733,  0.0331, -0.0646,  0.0082, -0.0433,
         -0.0646, -0.1400, -0.0595, -0.0362, -0.0780],
        [ 0.0280, -0.0120,  0.0797,  0.0295, -0.1181, -0.1130,  0.1095,  0.0759,
         -0.0455,  0.1380, -0.1094, -0.0194, -0.0162,  0.0140, -0.0376,  0.1013,
          0.1209,  0.1092,  0.1368,  0.0059,  0.0490, -0.0446,  0.0519,  0.0013,
         -0.0639, -0.1020,  0.1314, -0.0041, -0.1112,  0.1153, -0.0684,  0.0188,
         -0.1482,  0.0025,  0.0419,  0.1160,  0.1005,  0.0171,  0.1020, -0.0383,
          0.1201, -0.0807, -0.1017,  0.0980, -0.1456]], requires_grad=True)
Parameter containing:
tensor([ 0.1088, -0.1073, -0.0453,  0.0493, -0.0488, -0.1183,  0.1107,  0.0115,
        -0.1368,  0.0305, -0.0962, -0.0361], requires_grad=True)

True

torch.Size([32, 12])

tensor([[-2.2470e-01, -5.8710e-02, -2.5785e-01,  3.5865e-01, -1.0950e-02,
         -1.9977e-01,  9.3109e-03,  3.0657e-02, -4.3339e-01, -2.5841e-02,
         -6.4272e-01,  1.5443e-01],
        [-3.3919e-01, -1.2645e-01,  8.0899e-02, -1.1143e-01, -3.9810e-01,
         -9.6678e-02, -6.4685e-02, -2.2056e-01, -2.0543e-01, -4.2925e-01,
         -6.0277e-01, -1.5761e-02],
        [-4.9108e-01, -2.3577e-01,  9.6117e-03,  1.2700e-01, -1.7415e-01,
         -3.8185e-01, -2.3065e-01, -3.3726e-01, -6.2643e-01, -2.1114e-01,
         -5.9623e-01,  2.7459e-01],
        [-2.7542e-01, -1.9220e-01, -2.5051e-01, -2.8725e-01, -1.2958e-01,
         -5.5331e-02, -2.4683e-01, -1.7822e-01, -6.0195e-01, -3.8581e-01,
         -8.9296e-01,  4.5097e-02],
        [-3.8682e-01, -2.3957e-01, -1.7267e-01,  1.0346e-01, -2.7054e-01,
          4.0088e-03, -1.3918e-01, -1.3058e-01, -2.8258e-01, -1.6801e-01,
         -6.6350e-01,  8.4326e-02],
        [-2.7883e-01, -1.7829e-01, -2.6589e-01,  4.6228e-02, -3.9745e-01,
         -3.2392e-01,  6.9230e-03, -1.4288e-01, -3.3412e-01, -3.1499e-01,
         -7.5887e-01, -4.6748e-02],
        [-8.0426e-02,  5.7619e-02, -7.6395e-02,  1.2750e-01, -2.6947e-01,
         -1.2938e-01, -6.1483e-02, -3.9099e-02, -3.1632e-01, -2.6064e-01,
         -3.1031e-01,  1.1861e-01],
        [-3.4473e-01, -3.1640e-02,  4.8224e-03,  1.1186e-01, -5.0024e-01,
         -4.1376e-01,  5.0095e-02,  6.1807e-02, -5.4451e-01,  5.5040e-02,
         -2.4346e-01,  3.1529e-01],
        [-2.1262e-01,  6.0683e-02, -1.4706e-01,  7.5436e-02, -1.8727e-01,
         -2.5309e-01,  7.7624e-02, -1.1758e-01, -5.2270e-01, -2.6164e-01,
         -7.1594e-01,  2.3899e-01],
        [-1.2847e-01,  1.6470e-01, -3.6638e-01, -2.0892e-01, -2.2025e-01,
         -1.1279e-01,  1.8024e-01, -5.8911e-02, -1.7691e-01, -1.8017e-01,
         -5.8982e-01,  4.6199e-01],
        [-4.4606e-01, -5.0079e-01,  1.1770e-01, -8.2404e-02, -3.3142e-02,
         -2.2934e-01, -1.7378e-01, -5.3540e-01, -5.7699e-01,  3.5460e-02,
         -4.6668e-01,  1.4637e-01],
        [-5.1985e-01, -7.6914e-02, -1.3741e-01, -1.7172e-01,  8.6210e-02,
          1.5785e-01,  1.1791e-01, -1.5508e-01, -4.7063e-01, -1.6701e-01,
         -1.8834e-01,  1.3570e-01],
        [-4.8153e-01, -1.2962e-01, -2.3262e-01, -1.8152e-02, -5.8150e-02,
          8.9494e-02,  1.2296e-01,  9.0283e-02, -4.7531e-01, -1.1841e-01,
         -4.3422e-01,  4.8526e-01],
        [-4.7092e-01, -2.3329e-01, -5.7897e-02, -9.8882e-02, -3.2665e-01,
         -6.5247e-02,  3.1410e-01,  8.6061e-02, -5.0412e-01, -1.0846e-02,
         -5.5795e-01,  5.9003e-02],
        [-5.7715e-01, -2.4668e-01,  1.9199e-01, -6.3896e-02, -3.9907e-01,
         -5.0746e-02, -4.5770e-02,  1.0522e-01, -5.2899e-01,  1.1100e-02,
         -6.0430e-01,  2.0967e-02],
        [-2.1075e-01, -5.1417e-01,  2.5709e-01, -5.4861e-02, -6.4781e-01,
         -2.2392e-01, -3.0525e-01, -2.4005e-01, -5.6088e-01, -2.6814e-01,
         -5.3344e-01,  2.4113e-01],
        [-3.6347e-01, -1.0628e-01, -1.7134e-02, -2.9396e-01,  2.7949e-02,
         -1.5916e-01,  2.2203e-01, -7.3848e-02,  6.7383e-03, -3.9317e-01,
         -5.2213e-01,  2.2877e-01],
        [-7.1967e-01, -3.1989e-01,  2.3205e-03,  2.4050e-02, -2.3455e-01,
         -2.1050e-01, -2.7413e-02,  1.2166e-01, -5.1925e-01,  1.7080e-01,
         -5.1846e-01, -3.0435e-02],
        [-1.8936e-01,  9.2761e-03, -1.5488e-01, -6.6657e-02, -4.2266e-01,
         -1.9409e-01,  1.0227e-01,  2.4452e-01, -5.1060e-01, -2.8881e-01,
         -2.3043e-01,  5.2368e-01],
        [-3.6121e-01, -1.4379e-01,  1.2871e-01, -1.5966e-01, -3.6859e-01,
         -1.3627e-01,  3.7719e-01,  2.3200e-02, -3.0444e-01, -4.4283e-02,
         -4.2232e-01,  1.5437e-01],
        [-5.4064e-01, -1.7198e-01, -2.9298e-01, -1.9469e-01, -3.4277e-02,
         -3.6144e-01,  1.0888e-01, -2.2686e-02, -8.3253e-01,  1.8430e-02,
         -5.1430e-01,  8.3102e-02],
        [-4.2542e-01, -2.5447e-01,  3.3598e-01,  3.1721e-02, -2.4241e-01,
          1.5187e-01, -1.6827e-01, -2.1106e-01, -4.7370e-02,  1.2178e-01,
         -3.7345e-01, -1.3108e-01],
        [-2.0020e-01, -4.1939e-01,  1.0017e-01, -2.1232e-01, -4.4063e-01,
         -7.4535e-02, -2.3089e-01, -2.5450e-01, -7.5605e-01, -2.1934e-01,
         -4.8380e-01,  3.5132e-01],
        [-2.8992e-01, -3.5108e-01, -2.2816e-01,  2.8755e-02, -1.9082e-01,
         -2.7617e-01, -3.4891e-02, -3.4362e-01, -3.2430e-01, -2.0560e-01,
         -4.0649e-01,  3.2888e-01],
        [-2.4278e-01, -1.9037e-01, -1.2574e-01,  1.1459e-01, -2.0692e-02,
          5.3232e-02, -4.9061e-02, -1.6751e-01, -3.7609e-01, -4.1895e-02,
         -3.8395e-01,  3.1022e-01],
        [-4.3935e-01, -1.2241e-01, -1.9710e-01,  1.3534e-04, -5.7758e-01,
          3.3353e-01,  5.1177e-02,  5.3989e-02, -4.8319e-01,  2.1240e-01,
         -3.3898e-01,  1.5711e-01],
        [-1.7015e-01, -2.2244e-01, -2.5131e-01, -8.7330e-02, -1.5919e-01,
         -2.5986e-01, -9.7492e-03, -7.6852e-02, -2.9884e-01, -2.8189e-01,
         -8.1657e-01,  3.2378e-01],
        [-2.8202e-01,  1.1350e-01, -2.8093e-01,  1.1209e-01, -2.0011e-01,
         -4.6414e-01, -1.7037e-01, -9.3862e-02, -3.4407e-01, -1.2868e-01,
         -5.9693e-01, -8.2874e-02],
        [-3.9762e-01,  1.2845e-01, -8.9404e-02, -2.5966e-01,  9.6970e-02,
          1.3074e-02,  3.3997e-01,  1.6612e-02, -3.1838e-01,  7.7463e-02,
         -1.2011e-01,  2.4934e-01],
        [-5.3602e-01, -3.8510e-01, -1.0240e-01,  7.5908e-03, -1.9656e-01,
         -2.5107e-01, -3.1033e-01, -3.7892e-02, -3.5327e-01, -3.6853e-02,
         -8.3487e-01,  1.1070e-01],
        [-3.7964e-01, -1.3180e-01, -2.8206e-01, -2.1108e-01, -8.3246e-02,
         -1.0480e-01, -2.0995e-01, -3.9266e-01, -6.8251e-01, -4.0382e-01,
         -3.1418e-01,  4.2107e-01],
        [-4.0313e-01, -1.9005e-01,  9.5097e-02,  1.0122e-03,  1.0310e-02,
         -1.4736e-01, -1.4287e-01, -1.6967e-01, -5.2101e-01,  1.1092e-01,
         -1.1826e-01,  4.3184e-03]], grad_fn=<AddmmBackward0>)

In [71]:
import torch
from torch import nn
from torch import optim
import torch.nn.functional as F # Often used for functional APIs like activation functions
import math

class SimpleMultiLayerPerceptron(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        # defining layers
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.activation = nn.ReLU() 
        self.layer2 = nn.Linear(hidden_size, output_size)
        print(f"Model parameters initialized with: {input_size}, {hidden_size}, {output_size}")
        print(f"Layer 1: {self.layer1}")
        print(f"Activation layer: {self.activation}")
        print(f"Layer 2: {self.layer2}")

    def forward(self, data):
        print(f"Forward pass input shape: {data.shape}")
        data = self.layer1(data)
        print(f"Input data after first layer: {data.shape}")
        data = self.activation(data) # or we can also define it as F.relu(data), without having to define nn.ReLU()
        print(f"Input data after activation layer: {data.shape}")
        data = self.layer2(data)
        print(f"Input data after second layer: {data.shape}")
        return data

a = torch.rand(224,224) # image size of 224,224
input_features = a.reshape(-1).clone() # flaten the image into a single row vector
input_features = math.floor(input_features.sum().tolist()) # summed and turned into int, since nn.Linear expects a scalar int value
hidden_layer = 128 # number of hidden layers
output_layer = 10 # spits out 10 classifications

# create an instance of the model class
model = SimpleMultiLayerPerceptron(input_size=input_features, hidden_size=hidden_layer, output_size=output_layer)

# define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# input_data
data_data = torch.randn(28, input_features)
target_data = torch.randn(28, 10) # since after given layers, the resulting shape is (28,10)

for name, param in model.named_parameters():
    print(f"Parameter name: {name}, shape: {param.shape}")

for epoch in range(100):
    optimizer.zero_grad()
    output = model(data_data) # forward pass
    loss = criterion(output, target_data) # outputs a scalar value
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        for name, param in model.named_parameters():         
            print(f"Epoch: {epoch}, parameter name: {name}, shape: {param.shape}, loss: {loss:.4f}")
        break

Model parameters initialized with: 24975, 128, 10
Layer 1: Linear(in_features=24975, out_features=128, bias=True)
Activation layer: ReLU()
Layer 2: Linear(in_features=128, out_features=10, bias=True)
Parameter name: layer1.weight, shape: torch.Size([128, 24975])
Parameter name: layer1.bias, shape: torch.Size([128])
Parameter name: layer2.weight, shape: torch.Size([10, 128])
Parameter name: layer2.bias, shape: torch.Size([10])
Forward pass input shape: torch.Size([28, 24975])
Input data after first layer: torch.Size([28, 128])
Input data after activation layer: torch.Size([28, 128])
Input data after second layer: torch.Size([28, 10])
Epoch: 0, parameter name: layer1.weight, shape: torch.Size([128, 24975]), loss: 0.9810
Epoch: 0, parameter name: layer1.bias, shape: torch.Size([128]), loss: 0.9810
Epoch: 0, parameter name: layer2.weight, shape: torch.Size([10, 128]), loss: 0.9810
Epoch: 0, parameter name: layer2.bias, shape: torch.Size([10]), loss: 0.9810

In [63]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import math
import time

class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleMLP, self).__init__()
        # define layers
        self.layer1 = nn.Linear(input_size, hidden_size)
        #self.activativation = nn.ReLU() # commented out since for this example we will use directly F.relu() in the def forward
        self.layer2 = nn.Linear(hidden_size, output_size)

    # receive input data, and define its flow inside of forward method
    def forward(self, x):
        #op1 = self.layer1(x)
        #op2 = F.relu(op1)
        #op3 = self.layer2(op2)
        #return op3
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        return x

# here we are not defining input and label datas, but we are simply defining the 
# SIZES: input sample size and output sample size
# input referring to the number of unique characteristics, in the case of matrix, refers to the number of rows, not columns
# output defines the total number of classification outputs, such as from given input
# we are trying to classify it into to distinct classes
# again when creating an instance of the model class, we are passing only the input/hidden/output sample sizes
# only sizes when passing an argument to the instance of the class
# we will pass an actual input features when doing forward pass
in_size = 784 # flattened version of 28x28 image
hi_size = 128 # number of hidden layers
ou_size = 10 # aim is to define 10 distinct classes from the given image
model = SimpleMLP(in_size, hi_size, ou_size)

name_ = []
for name, param in model.named_parameters():
    print(f"Parameter name: {name}, shape: {param.shape}, requires_grad={param.requires_grad}")
    name_.append(name)

# define loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

# input data and target label
dum = torch.randn(64,784)
label = torch.randn(64,10) # since for element-wise oprations the dimension must match

# iterate and update parameters
start_time = time.time()
for epoch in range(100):
    optimizer.zero_grad() # to avoid gradient accumulation 
    output = model(dum) # forward pass
    loss = loss_fn(output, label)
    loss.backward() # scalar value
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch: {epoch}, loss: {loss:.5f}, ")
end_time = time.time() - start_time
print(f"{end_time/60:.4f} minutes")
print(f"{end_time:.4f} seconds")

Parameter name: layer1.weight, shape: torch.Size([128, 784]), requires_grad=True
Parameter name: layer1.bias, shape: torch.Size([128]), requires_grad=True
Parameter name: layer2.weight, shape: torch.Size([10, 128]), requires_grad=True
Parameter name: layer2.bias, shape: torch.Size([10]), requires_grad=True
Epoch: 0, loss: 1.08200,
Epoch: 10, loss: 1.07211,
Epoch: 20, loss: 1.06247,
Epoch: 30, loss: 1.05300,
Epoch: 40, loss: 1.04370,
Epoch: 50, loss: 1.03455,
Epoch: 60, loss: 1.02553,
Epoch: 70, loss: 1.01668,
Epoch: 80, loss: 1.00799,
Epoch: 90, loss: 0.99943,
0.0023 minutes
0.1381 seconds

In [59]:
nn.Linear??

Init signature:
nn.Linear(
    in_features: int,
    out_features: int,
    bias: bool = True,
    device=None,
    dtype=None,
) -> None
Source:
class Linear(Module):
    r"""Applies an affine linear transformation to the incoming data: :math:`y = xA^T + b`.

    This module supports :ref:`TensorFloat32<tf32_on_ampere>`.

    On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.

    Args:
        in_features: size of each input sample
        out_features: size of each output sample
        bias: If set to ``False``, the layer will not learn an additive bias.
            Default: ``True``

    Shape:
        - Input: :math:`(*, H_{in})` where :math:`*` means any number of
          dimensions including none and :math:`H_{in} = \text{in\_features}`.
        - Output: :math:`(*, H_{out})` where all but the last dimension
          are the same shape as the input and :math:`H_{out} = \text{out\_features}`.

    Attributes:
        weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
        bias:   the learnable bias of the module of shape :math:`(\text{out\_features})`.
                If :attr:`bias` is ``True``, the values are initialized from
                :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
                :math:`k = \frac{1}{\text{in\_features}}`

    Examples::

        >>> m = nn.Linear(20, 30)
        >>> input = torch.randn(128, 20)
        >>> output = m(input)
        >>> print(output.size())
        torch.Size([128, 30])
    """

    __constants__ = ["in_features", "out_features"]
    in_features: int
    out_features: int
    weight: Tensor

    def __init__(
        self,
        in_features: int,
        out_features: int,
        bias: bool = True,
        device=None,
        dtype=None,
    ) -> None:
        factory_kwargs = {"device": device, "dtype": dtype}
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(
            torch.empty((out_features, in_features), **factory_kwargs)
        )
        if bias:
            self.bias = Parameter(torch.empty(out_features, **factory_kwargs))
        else:
            self.register_parameter("bias", None)
        self.reset_parameters()

    def reset_parameters(self) -> None:
        # Setting a=sqrt(5) in kaiming_uniform is the same as initializing with
        # uniform(-1/sqrt(in_features), 1/sqrt(in_features)). For details, see
        # https://github.com/pytorch/pytorch/issues/57109
        init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            init.uniform_(self.bias, -bound, bound)

    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)

    def extra_repr(self) -> str:
        return f"in_features={self.in_features}, out_features={self.out_features}, bias={self.bias is not None}"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/linear.py
Type:           type
Subclasses:     NonDynamicallyQuantizableLinear, LazyLinear, Linear, LinearBn1d, Linear

In [60]:
time.time??

Docstring:
time() -> floating point number

Return the current time in seconds since the Epoch.
Fractions of a second may be present if the system clock provides them.
Type:      builtin_function_or_method

In [86]:
import torch
from torch import nn
from torch import optim
from torch.nn import functional as F
from time import time

class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.activation = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.layer1(x)
        x = self.activation(x) # x = F.relu(x)
        x = self.layer2(x)
        return x

# we define here the sample size
model = SimpleMLP(input_size=1156, hidden_size=64, output_size=5)

# define loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# define input features and labels
input_feature = torch.randn(89,1156)
target_label = torch.randn(89,5)
start_time = time()
for epoch in range(100000):
    optimizer.zero_grad() # to avoid gradient accumulation
    output = model(input_feature)
    loss = loss_fn(output, target_label)
    loss.backward()
    optimizer.step() # update weights after gradient calculation

    if epoch % 10000 == 0:
        print(f"Epoch: {epoch}, loss: {loss}")
        
    if loss <= 1e-13:
        print(f"Learning stopped with {loss:.6f}.")
        break
        
end_time = time() - start_time
print(f"{end_time:.13f} seconds")

Epoch: 0, loss: 1.1556340456008911
Epoch: 10000, loss: 1.4406993393417666e-12
Epoch: 20000, loss: 4.2720227312262327e-13
Epoch: 30000, loss: 2.315888095443669e-13
Epoch: 40000, loss: 1.5679954079930725e-13
Epoch: 50000, loss: 1.1333288636988098e-13
Learning stopped with 0.000000.
51.1217720508575 seconds

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

class SimpleMLP(nn.Module):
    def __init__(self, ints, hids, outs):
        super(SimpleMLP, self).__init__()
        self.layer1 = nn.Linear(ints, hids)
        self.layer2 = nn.Linear(hids, outs)

    def forward(self, x):
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        return x

modelNet = SimpleMLP(ints=456, hids=256, outs=15)
loss_fn = nn.MSELoss()
optimizer = optim.SGD(modelNet.parameters(), lr=0.001)
data = torch.arange(44688, 89376, dtype=torch.float32).reshape(98,456)
labels = torch.ones(98,15)

for epoch in range(10000):
    optimizer.zero_grad()
    output = modelNet(data)
    loss = loss_fn(output, labels)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print(f"Epoch: {epoch}, loss: {loss.item()}")

Epoch: 0, loss: 123039976.0
Epoch: 1000, loss: 3.6826285920888816e+27
Epoch: 2000, loss: 2.82058066069858e+27
Epoch: 3000, loss: 2.1603244666356866e+27
Epoch: 4000, loss: 1.6546243915813448e+27
Epoch: 5000, loss: 1.2673013528926223e+27
Epoch: 6000, loss: 9.706442826871111e+26
Epoch: 7000, loss: 7.434306446298663e+26
Epoch: 8000, loss: 5.694045775473244e+26
Epoch: 9000, loss: 4.3611515637903016e+26

In [9]:
import torch
from torch import nn

# also called as fully connected layer or dense layer which flatens all entires into a single row or column vector
linear_layer = nn.Linear(in_features=30, out_features=20) # features representing rows
input_feature = torch.randn(54, 30)
output_feature = linear_layer(input_feature)
print(f"input_feature shape: {input_feature.shape}")
print(f"output_feature shape: {output_feature.shape}")
print(f"linear_layer weight: {linear_layer.weight.shape}, bias: {linear_layer.bias.shape}")

input_feature shape: torch.Size([54, 30])
output_feature shape: torch.Size([54, 20])
linear_layer weight: torch.Size([20, 30]), bias: torch.Size([20])

In [14]:
lin = nn.Linear(45, 78) # the first number is the number of input features, second is number of output features
ins = torch.arange(1530.0).view(34,45)
ous = lin(ins)
print(ins.shape, ous.size())
print(lin.weight.shape, lin.bias.shape)

torch.Size([34, 45]) torch.Size([34, 78])
torch.Size([78, 45]) torch.Size([78])

In [23]:
import torch
import torch.nn as nn

linear_layer = nn.Linear(60, 14)
input_feature = torch.randn(45, 60)
output_feature = linear_layer(input_feature)
print(input_feature.shape, output_feature.size())
print(linear_layer.weight.shape, linear_layer.bias.size())
print(linear_layer.weight) # both weight and bias after linear layer, will have gradients required
# nn.Linear flattens given tensor, also called as fully connected layer or dense layer
# this often serves as the final classification or regression layer in complex models of CNN/RNN

torch.Size([45, 60]) torch.Size([45, 14])
torch.Size([14, 60]) torch.Size([14])
Parameter containing:
tensor([[-0.0061,  0.0606, -0.0500,  0.0603,  0.1140, -0.0347, -0.0051, -0.1037,
          0.0037, -0.0633,  0.0330, -0.0456, -0.0558,  0.0357, -0.1094, -0.0602,
          0.0158,  0.1178,  0.0089, -0.0164, -0.0570, -0.0210,  0.0202,  0.0972,
         -0.1023,  0.0030,  0.1271,  0.0175,  0.0117, -0.0627,  0.0944,  0.1082,
         -0.0351,  0.0133,  0.0246, -0.1029,  0.0806, -0.0058, -0.0594,  0.1200,
         -0.1040,  0.0264, -0.0815, -0.0827, -0.0368,  0.0113,  0.0162,  0.0106,
          0.0103, -0.0860,  0.0624,  0.1177,  0.0793,  0.0866,  0.1153, -0.1158,
         -0.0847, -0.0106,  0.0095, -0.1252],
        [-0.0206, -0.1165, -0.0636,  0.0647,  0.1050,  0.0027, -0.0200,  0.0205,
          0.0084, -0.0773,  0.0278,  0.0681,  0.0221, -0.0159,  0.1042, -0.0104,
         -0.0341,  0.0785,  0.0771, -0.0292, -0.0799, -0.0347, -0.1158, -0.1174,
          0.1006, -0.0149,  0.0528,  0.0871,  0.0814,  0.0491, -0.0565,  0.1146,
          0.0450,  0.1285, -0.0049, -0.0152,  0.1030,  0.1200, -0.0584, -0.0107,
          0.0561, -0.0525,  0.1193, -0.0060,  0.0832, -0.1194,  0.1152, -0.0092,
          0.0560, -0.0743, -0.0697,  0.0337,  0.0607,  0.0656, -0.0470,  0.1065,
         -0.0882,  0.0411, -0.0852, -0.0746],
        [ 0.1093, -0.0084,  0.0170,  0.0625,  0.1032,  0.0707, -0.0146, -0.1198,
         -0.0795,  0.0266, -0.0972, -0.0321, -0.0672, -0.0152, -0.0932, -0.0578,
          0.0457, -0.1200,  0.0131, -0.0275,  0.0813,  0.1175,  0.1166,  0.0951,
         -0.0982, -0.0914, -0.1063,  0.0529, -0.0586,  0.0146, -0.1007, -0.0461,
          0.0473, -0.0899,  0.0835, -0.0310,  0.1106, -0.0990, -0.0085,  0.0528,
         -0.0404, -0.0463,  0.0097, -0.1221, -0.0379, -0.0862, -0.0322,  0.0359,
          0.0614, -0.1233, -0.0512, -0.0457, -0.0679, -0.0590, -0.1262, -0.0317,
         -0.0333, -0.0920,  0.0753,  0.0543],
        [-0.0443, -0.0740,  0.0027, -0.0369, -0.0181,  0.0961, -0.0053,  0.0876,
         -0.0709, -0.0069, -0.0413, -0.0633,  0.1018,  0.0802,  0.0158, -0.0286,
          0.1261, -0.0312, -0.0401,  0.0704, -0.0015,  0.0564,  0.0975, -0.0614,
         -0.0009,  0.1197,  0.1157, -0.0051,  0.1098,  0.1122, -0.0963,  0.0133,
         -0.0781, -0.1244, -0.1068,  0.1192, -0.0998, -0.0541, -0.0424, -0.0803,
          0.0883,  0.0628, -0.0042, -0.0113,  0.1010,  0.0895, -0.0411,  0.0065,
         -0.0078,  0.0613,  0.0380, -0.0810, -0.0205, -0.0712,  0.0456, -0.0468,
          0.0692, -0.1037, -0.0176,  0.0596],
        [-0.0027, -0.1182, -0.0729,  0.1086, -0.0044,  0.0275, -0.0621,  0.1190,
         -0.0560, -0.0321,  0.0122,  0.0386,  0.0825,  0.0582,  0.1133,  0.1279,
         -0.1006, -0.0599, -0.0658, -0.0986, -0.0942, -0.0925,  0.0547, -0.0043,
          0.0377, -0.0974, -0.0558,  0.0199, -0.0584, -0.1015, -0.1281,  0.0647,
         -0.0449, -0.0229, -0.0389, -0.0506, -0.0971, -0.0289, -0.0391,  0.0034,
          0.0137, -0.0277,  0.0375, -0.1273, -0.0592, -0.0908,  0.1017,  0.1157,
          0.0264, -0.0421,  0.1089,  0.0274,  0.0138, -0.1050,  0.0135,  0.0050,
          0.0355, -0.0658,  0.0206, -0.0165],
        [-0.0134, -0.1214, -0.0167,  0.0749, -0.1023,  0.0119, -0.0257,  0.1199,
          0.1245,  0.1025,  0.0437,  0.0768, -0.0139,  0.0676, -0.0965, -0.0873,
         -0.0307, -0.0839,  0.0759,  0.0676, -0.0125, -0.0862,  0.0675, -0.1162,
         -0.1084,  0.0160, -0.1079,  0.0544, -0.1088, -0.1020,  0.0969, -0.0411,
         -0.0642,  0.0247,  0.1043,  0.0004, -0.1134,  0.0096, -0.0885, -0.1240,
          0.0684,  0.0540,  0.0421,  0.0893, -0.0625, -0.0775, -0.0032, -0.0336,
         -0.0996, -0.0175, -0.0263,  0.0715, -0.1075,  0.0081, -0.1165,  0.0545,
          0.0678, -0.0575,  0.0744,  0.1222],
        [-0.0523,  0.0970,  0.0675,  0.0133, -0.0510,  0.0083, -0.0916, -0.0082,
          0.0670, -0.0716,  0.0759, -0.1267,  0.1176, -0.1089,  0.0797,  0.0032,
          0.0263, -0.0394,  0.0894,  0.0924,  0.0583,  0.0193,  0.0703,  0.0952,
         -0.0713,  0.0302, -0.0248,  0.0077, -0.1221, -0.0748,  0.0447,  0.0855,
          0.0237,  0.0787, -0.0295, -0.0385,  0.0565,  0.0433,  0.0488, -0.0559,
         -0.1040,  0.0162, -0.0909, -0.0407,  0.1030,  0.0497,  0.0186,  0.1153,
         -0.0151,  0.1144, -0.0978,  0.0116, -0.0754,  0.0480,  0.1205, -0.0461,
          0.0660,  0.0591, -0.0286,  0.0180],
        [-0.0446, -0.0364, -0.0296,  0.0442,  0.0037,  0.0690, -0.0407, -0.0203,
          0.0057, -0.0039,  0.0919,  0.0596, -0.0300,  0.0928, -0.1149,  0.0040,
          0.0769,  0.1144,  0.0260,  0.0152,  0.0358,  0.0945,  0.0654, -0.0848,
         -0.0925, -0.0372, -0.0142, -0.1240, -0.0254, -0.0782, -0.0794,  0.0266,
         -0.0845,  0.0601,  0.1064,  0.1077,  0.0124,  0.1075,  0.0559,  0.0614,
         -0.0027,  0.0963,  0.0935, -0.1268,  0.0164,  0.1113,  0.0551, -0.0772,
         -0.0861, -0.0528, -0.0491,  0.0661,  0.1001, -0.1105,  0.0933, -0.0189,
          0.1094,  0.1161,  0.1241, -0.0576],
        [-0.0914, -0.0411, -0.1202,  0.1048, -0.0316,  0.0674,  0.0944,  0.0022,
         -0.1048, -0.0090,  0.0990,  0.0092, -0.0140,  0.1049,  0.0002,  0.0506,
          0.0163, -0.0031,  0.0229,  0.1095,  0.0746, -0.0357,  0.0189, -0.0304,
         -0.0519,  0.0027,  0.1217, -0.0689,  0.0733, -0.0458,  0.1196, -0.0661,
         -0.0370, -0.0895, -0.0004, -0.0754,  0.0298, -0.0560, -0.0862,  0.0901,
         -0.0190,  0.1248,  0.0513, -0.0550,  0.0159,  0.0973,  0.0095,  0.1264,
         -0.0194,  0.0405, -0.0143, -0.1190,  0.0272, -0.0714,  0.1128, -0.0063,
         -0.0560, -0.0269,  0.1221,  0.0330],
        [-0.0098,  0.1109,  0.0978, -0.0678,  0.0163, -0.0481, -0.1124,  0.0577,
         -0.1011,  0.0842,  0.0528, -0.1141, -0.0782,  0.0204, -0.0632, -0.0876,
         -0.0416,  0.0553, -0.0611, -0.1216, -0.0894,  0.0336, -0.0443,  0.0588,
         -0.0336, -0.0915,  0.0251, -0.1005,  0.1256, -0.0352, -0.0556,  0.0234,
          0.0314,  0.1283,  0.0464,  0.0343, -0.1046, -0.1230, -0.1156,  0.0147,
         -0.0147, -0.0683, -0.0184,  0.0913, -0.0789, -0.1175, -0.0142,  0.0028,
         -0.1199, -0.1070,  0.1284, -0.0154, -0.0939,  0.0186,  0.0336,  0.0414,
         -0.1232,  0.0484, -0.0539, -0.1057],
        [ 0.1150,  0.0164, -0.0559,  0.0764, -0.0819, -0.0736, -0.0857,  0.0419,
         -0.0106,  0.0600,  0.1232,  0.0525, -0.0577, -0.0160,  0.0529,  0.0799,
          0.0388,  0.1000,  0.0704,  0.0766,  0.0520, -0.0953,  0.0312,  0.0072,
          0.1162, -0.0888, -0.0748, -0.0803, -0.1247, -0.1157, -0.0653,  0.1176,
         -0.0459,  0.0862, -0.0459,  0.1187, -0.0939,  0.0525,  0.0784, -0.0581,
         -0.0757, -0.0820, -0.0380,  0.1228, -0.0245, -0.0375, -0.1086, -0.1283,
         -0.0087,  0.0926,  0.0767,  0.0772,  0.0479, -0.0353,  0.1036,  0.0543,
         -0.0505,  0.0562, -0.0033,  0.0321],
        [ 0.0377,  0.0161, -0.0875,  0.1002, -0.0249,  0.1068,  0.0562,  0.1067,
          0.1209,  0.0987, -0.1110, -0.0244,  0.0251,  0.0147, -0.0855,  0.0264,
         -0.1126, -0.0743, -0.0255,  0.1040, -0.0773,  0.1219,  0.0731,  0.0609,
          0.0146, -0.0720,  0.0345, -0.0573,  0.0258,  0.0412,  0.1158,  0.1151,
         -0.0319, -0.0618, -0.0311,  0.0322, -0.1031,  0.0507,  0.0667,  0.1221,
         -0.0213, -0.1051, -0.0827, -0.1058, -0.0838,  0.0037,  0.1210,  0.1012,
         -0.1022, -0.0567, -0.0052,  0.0895,  0.1058,  0.0318,  0.0327, -0.0880,
          0.0164, -0.1095, -0.0004, -0.0221],
        [-0.0609,  0.0839,  0.0023, -0.0344, -0.0147, -0.0222, -0.0292,  0.0126,
         -0.1049,  0.0115,  0.0966, -0.0565, -0.1116, -0.0554,  0.0555, -0.0315,
          0.0929,  0.0997, -0.1037,  0.0665, -0.0224,  0.0189, -0.0399,  0.0765,
         -0.1024, -0.0637, -0.0740, -0.1173, -0.0612,  0.0680, -0.0776, -0.0370,
         -0.0186, -0.0570,  0.0679,  0.0899, -0.0167,  0.0998,  0.1196, -0.0731,
         -0.0422, -0.0241,  0.0920,  0.0274, -0.0336,  0.0961, -0.0526, -0.0814,
          0.0058,  0.0448, -0.0971, -0.1037,  0.1222,  0.1288,  0.1098,  0.1117,
         -0.0327,  0.0917, -0.1205, -0.0437],
        [ 0.0125, -0.0309, -0.1008, -0.0445,  0.1007, -0.0967, -0.1129, -0.1202,
         -0.0796, -0.0573,  0.0338, -0.1002,  0.0759, -0.1167,  0.1147, -0.0508,
         -0.1238, -0.1280, -0.0732,  0.0254,  0.0605,  0.0490,  0.1279,  0.0576,
          0.0861,  0.0133,  0.1107,  0.0559, -0.0289,  0.0260, -0.1082, -0.0318,
          0.0439, -0.0440, -0.1254,  0.0470,  0.0019, -0.0281, -0.0981,  0.1127,
          0.1120,  0.0390,  0.0220,  0.0581,  0.0500,  0.0209, -0.0820, -0.0844,
          0.0252, -0.0498,  0.0774, -0.0342, -0.0335,  0.1090, -0.0147,  0.0762,
         -0.0094, -0.0208,  0.0580,  0.0540]], requires_grad=True)

In [46]:
fc_layer = nn.Linear(in_features=10, out_features=3)
features = torch.randn(5,10)
outputs = fc_layer(features)
print(f"Features: {features.shape}, Outputs: {outputs.size()}")
print(f"Parameters of fc_layer: weight={fc_layer.weight.shape}, bias={fc_layer.bias.shape}")
display(fc_layer.weight, fc_layer.bias)
print(f"Gradients required?: features={features.requires_grad}, outputs={outputs.requires_grad}")
print(f"Gradients required?: weight={fc_layer.weight.requires_grad}, bias={fc_layer.bias.requires_grad}")
print(f"Is leaf: features={features.is_leaf}, outputs={outputs.is_leaf}")
print(f"Grad_fn: features={features.grad_fn}, outputs={outputs.grad_fn}, weight={fc_layer.weight.grad_fn},\
 bias={fc_layer.bias.grad_fn}")

Features: torch.Size([5, 10]), Outputs: torch.Size([5, 3])
Parameters of fc_layer: weight=torch.Size([3, 10]), bias=torch.Size([3])

Parameter containing:
tensor([[-0.0205,  0.0809,  0.1949,  0.2649,  0.3076,  0.0447,  0.2620, -0.2888,
          0.2190, -0.0489],
        [-0.1672,  0.1811,  0.1750, -0.1704,  0.2198, -0.3022, -0.2651,  0.2293,
         -0.1227, -0.0345],
        [ 0.2470,  0.1746, -0.1729,  0.1715,  0.1494,  0.2128, -0.1646,  0.2819,
          0.1728,  0.2751]], requires_grad=True)

Parameter containing:
tensor([-0.1094,  0.2055,  0.1367], requires_grad=True)

Gradients required?: features=False, outputs=True
Gradients required?: weight=True, bias=True
Is leaf: features=True, outputs=False
Grad_fn: features=None, outputs=<AddmmBackward0 object at 0x16b4fd0d0>, weight=None, bias=None

In [60]:
nn.Conv2d?
# there are other variants of Conv1d and Conv3d are also available

Init signature:
nn.Conv2d(
    in_channels: int,
    out_channels: int,
    kernel_size: Union[int, Tuple[int, int]],
    stride: Union[int, Tuple[int, int]] = 1,
    padding: Union[str, int, Tuple[int, int]] = 0,
    dilation: Union[int, Tuple[int, int]] = 1,
    groups: int = 1,
    bias: bool = True,
    padding_mode: str = 'zeros',
    device=None,
    dtype=None,
) -> None
Docstring:
Applies a 2D convolution over an input signal composed of several input
planes.

In the simplest case, the output value of the layer with input size
:math:`(N, C_{\text{in}}, H, W)` and output :math:`(N, C_{\text{out}}, H_{\text{out}}, W_{\text{out}})`
can be precisely described as:

.. math::
    \text{out}(N_i, C_{\text{out}_j}) = \text{bias}(C_{\text{out}_j}) +
    \sum_{k = 0}^{C_{\text{in}} - 1} \text{weight}(C_{\text{out}_j}, k) \star \text{input}(N_i, k)


where :math:`\star` is the valid 2D `cross-correlation`_ operator,
:math:`N` is a batch size, :math:`C` denotes a number of channels,
:math:`H` is a height of input planes in pixels, and :math:`W` is
width in pixels.


This module supports :ref:`TensorFloat32<tf32_on_ampere>`.

On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.

* :attr:`stride` controls the stride for the cross-correlation, a single
  number or a tuple.

* :attr:`padding` controls the amount of padding applied to the input. It
  can be either a string {'valid', 'same'} or an int / a tuple of ints giving the
  amount of implicit padding applied on both sides.

* :attr:`dilation` controls the spacing between the kernel points; also
  known as the à trous algorithm. It is harder to describe, but this `link`_
  has a nice visualization of what :attr:`dilation` does.


* :attr:`groups` controls the connections between inputs and outputs.
  :attr:`in_channels` and :attr:`out_channels` must both be divisible by
  :attr:`groups`. For example,

    * At groups=1, all inputs are convolved to all outputs.
    * At groups=2, the operation becomes equivalent to having two conv
      layers side by side, each seeing half the input channels
      and producing half the output channels, and both subsequently
      concatenated.
    * At groups= :attr:`in_channels`, each input channel is convolved with
      its own set of filters (of size
      :math:`\frac{\text{out\_channels}}{\text{in\_channels}}`).

The parameters :attr:`kernel_size`, :attr:`stride`, :attr:`padding`, :attr:`dilation` can either be:

    - a single ``int`` -- in which case the same value is used for the height and width dimension
    - a ``tuple`` of two ints -- in which case, the first `int` is used for the height dimension,
      and the second `int` for the width dimension

Note:
    When `groups == in_channels` and `out_channels == K * in_channels`,
    where `K` is a positive integer, this operation is also known as a "depthwise convolution".

    In other words, for an input of size :math:`(N, C_{in}, L_{in})`,
    a depthwise convolution with a depthwise multiplier `K` can be performed with the arguments
    :math:`(C_\text{in}=C_\text{in}, C_\text{out}=C_\text{in} \times \text{K}, ..., \text{groups}=C_\text{in})`.

Note:
    In some circumstances when given tensors on a CUDA device and using CuDNN, this operator may select a nondeterministic algorithm to increase performance. If this is undesirable, you can try to make the operation deterministic (potentially at a performance cost) by setting ``torch.backends.cudnn.deterministic = True``. See :doc:`/notes/randomness` for more information.

Note:
    ``padding='valid'`` is the same as no padding. ``padding='same'`` pads
    the input so the output has the shape as the input. However, this mode
    doesn't support any stride values other than 1.

Note:
    This module supports complex data types i.e. ``complex32, complex64, complex128``.

Args:
    in_channels (int): Number of channels in the input image
    out_channels (int): Number of channels produced by the convolution
    kernel_size (int or tuple): Size of the convolving kernel
    stride (int or tuple, optional): Stride of the convolution. Default: 1
    padding (int, tuple or str, optional): Padding added to all four sides of
        the input. Default: 0
    dilation (int or tuple, optional): Spacing between kernel elements. Default: 1
    groups (int, optional): Number of blocked connections from input
        channels to output channels. Default: 1
    bias (bool, optional): If ``True``, adds a learnable bias to the
        output. Default: ``True``
    padding_mode (str, optional): ``'zeros'``, ``'reflect'``,
        ``'replicate'`` or ``'circular'``. Default: ``'zeros'``


Shape:
    - Input: :math:`(N, C_{in}, H_{in}, W_{in})` or :math:`(C_{in}, H_{in}, W_{in})`
    - Output: :math:`(N, C_{out}, H_{out}, W_{out})` or :math:`(C_{out}, H_{out}, W_{out})`, where

      .. math::
          H_{out} = \left\lfloor\frac{H_{in}  + 2 \times \text{padding}[0] - \text{dilation}[0]
                    \times (\text{kernel\_size}[0] - 1) - 1}{\text{stride}[0]} + 1\right\rfloor

      .. math::
          W_{out} = \left\lfloor\frac{W_{in}  + 2 \times \text{padding}[1] - \text{dilation}[1]
                    \times (\text{kernel\_size}[1] - 1) - 1}{\text{stride}[1]} + 1\right\rfloor

Attributes:
    weight (Tensor): the learnable weights of the module of shape
        :math:`(\text{out\_channels}, \frac{\text{in\_channels}}{\text{groups}},`
        :math:`\text{kernel\_size[0]}, \text{kernel\_size[1]})`.
        The values of these weights are sampled from
        :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
        :math:`k = \frac{groups}{C_\text{in} * \prod_{i=0}^{1}\text{kernel\_size}[i]}`
    bias (Tensor):   the learnable bias of the module of shape
        (out_channels). If :attr:`bias` is ``True``,
        then the values of these weights are
        sampled from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
        :math:`k = \frac{groups}{C_\text{in} * \prod_{i=0}^{1}\text{kernel\_size}[i]}`

Examples:

    >>> # With square kernels and equal stride
    >>> m = nn.Conv2d(16, 33, 3, stride=2)
    >>> # non-square kernels and unequal stride and with padding
    >>> m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
    >>> # non-square kernels and unequal stride and with padding and dilation
    >>> m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
    >>> input = torch.randn(20, 16, 50, 100)
    >>> output = m(input)

.. _cross-correlation:
    https://en.wikipedia.org/wiki/Cross-correlation

.. _link:
    https://github.com/vdumoulin/conv_arithmetic/blob/master/README.md
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/conv.py
Type:           type
Subclasses:     LazyConv2d, Conv2d, ConvBn2d, Conv2d

In [87]:
# in_channels, in the case of RGB is 3, since there are Red, Green and Blue color channels
# out_channels, represent the number of outputted feature maps
# meaning we can produce as many output feature maps as we want
# kernel_size is the dimension of filters (kernels), we can either provide a single int
# or tuple, in case of int will be square, such (H,W) where both are equal
# or tuple if the filter(kernel) size is not square
# padding helps to preserve the initial spatial dimensions, but by default is 0,
# so effectively convol_layer with padding=0 will also act as pooling_layer for downsizing the spatial dimensions
convol_layer = nn.Conv2d(in_channels=3, out_channels=15, kernel_size=5,device="mps")

# PyTorch expects channel-first format for images:
# [batch_size, input_channels, height, width]
input_image_batch = torch.randn(25, 3, 32, 32, device="mps")
# batch_size is basically the number of total images being passed as inputs for convol_layer
output_feature_maps = convol_layer(input_image_batch)

print(f"Input image shape: {input_image_batch.shape}")
print(f"Output feature map shape: {output_feature_maps.shape}")
# for input and output image/feature_maps [batch_size, input_color_channels, height, width]
print(f"\nConvoluation layer weight: {convol_layer.weight.shape}")
# [number_of_feature_maps, input_color_channels, kernel_height, kernel_width]
print(f"Convoluation layer weight: {convol_layer.bias.shape}")

Input image shape: torch.Size([25, 3, 32, 32])
Output feature map shape: torch.Size([25, 15, 28, 28])

Convoluation layer weight: torch.Size([15, 3, 5, 5])
Convoluation layer weight: torch.Size([15])

In [113]:
device = torch.device("mps" if torch.backends.mps.is_available else "gpu" if torch.cuda.is_available else "cpu")
convol_layer = nn.Conv2d(in_channels=3, out_channels=30, kernel_size=5, stride=1, padding=2, device=device)
input_image_batches = torch.randn(120, 3, 224, 224, device=device)
output_feature_maps = convol_layer(input_image_batches)
print(f"Input image: {input_image_batches.shape}")
print(f"Output feature maps: {output_feature_maps.size()}")
print(f"\nConvol weight: {convol_layer.weight.shape}\nConvol bias: {convol_layer.bias.shape}")

Input image: torch.Size([120, 3, 224, 224])
Output feature maps: torch.Size([120, 30, 224, 224])

Convol weight: torch.Size([30, 3, 5, 5])
Convol bias: torch.Size([30])

In [120]:
convolutional_layer = nn.Conv2d(in_channels=3, out_channels=120, kernel_size=5, padding=0)
input_image = torch.arange(19660800, dtype=torch.float32).reshape(400, 3, 128, 128)
# [batch_size, input_color_channels, height, width]
output_feature_maps = convolutional_layer(input_image)
# produces features maps where each one is learning specific patterns from the given input images
print(f"Input image shape: {input_image.shape}")
print(f"Output feature maps shape: {output_feature_maps.shape}")
print(f"\nConvol weight shape: {convolutional_layer.weight.shape}")
print(f"Convol bias shape: {convolutional_layer.bias.shape}")

Input image shape: torch.Size([400, 3, 128, 128])
Output feature maps shape: torch.Size([400, 120, 124, 124])

Convol weight shape: torch.Size([120, 3, 5, 5])
Convol bias shape: torch.Size([120])

In [122]:
nn.RNN?

Init signature: nn.RNN(*args, **kwargs)
Docstring:
__init__(input_size,hidden_size,num_layers=1,nonlinearity='tanh',bias=True,batch_first=False,dropout=0.0,bidirectional=False,device=None,dtype=None)

Apply a multi-layer Elman RNN with :math:`\tanh` or :math:`\text{ReLU}`
non-linearity to an input sequence. For each element in the input sequence,
each layer computes the following function:

.. math::
    h_t = \tanh(x_t W_{ih}^T + b_{ih} + h_{t-1}W_{hh}^T + b_{hh})

where :math:`h_t` is the hidden state at time `t`, :math:`x_t` is
the input at time `t`, and :math:`h_{(t-1)}` is the hidden state of the
previous layer at time `t-1` or the initial hidden state at time `0`.
If :attr:`nonlinearity` is ``'relu'``, then :math:`\text{ReLU}` is used instead of :math:`\tanh`.

.. code-block:: python

    # Efficient implementation equivalent to the following with bidirectional=False
    def forward(x, h_0=None):
        if batch_first:
            x = x.transpose(0, 1)
        seq_len, batch_size, _ = x.size()
        if h_0 is None:
            h_0 = torch.zeros(num_layers, batch_size, hidden_size)
        h_t_minus_1 = h_0
        h_t = h_0
        output = []
        for t in range(seq_len):
            for layer in range(num_layers):
                h_t[layer] = torch.tanh(
                    x[t] @ weight_ih[layer].T
                    + bias_ih[layer]
                    + h_t_minus_1[layer] @ weight_hh[layer].T
                    + bias_hh[layer]
                )
            output.append(h_t[-1])
            h_t_minus_1 = h_t
        output = torch.stack(output)
        if batch_first:
            output = output.transpose(0, 1)
        return output, h_t

Args:
    input_size: The number of expected features in the input `x`
    hidden_size: The number of features in the hidden state `h`
    num_layers: Number of recurrent layers. E.g., setting ``num_layers=2``
        would mean stacking two RNNs together to form a `stacked RNN`,
        with the second RNN taking in outputs of the first RNN and
        computing the final results. Default: 1
    nonlinearity: The non-linearity to use. Can be either ``'tanh'`` or ``'relu'``. Default: ``'tanh'``
    bias: If ``False``, then the layer does not use bias weights `b_ih` and `b_hh`.
        Default: ``True``
    batch_first: If ``True``, then the input and output tensors are provided
        as `(batch, seq, feature)` instead of `(seq, batch, feature)`.
        Note that this does not apply to hidden or cell states. See the
        Inputs/Outputs sections below for details.  Default: ``False``
    dropout: If non-zero, introduces a `Dropout` layer on the outputs of each
        RNN layer except the last layer, with dropout probability equal to
        :attr:`dropout`. Default: 0
    bidirectional: If ``True``, becomes a bidirectional RNN. Default: ``False``

Inputs: input, h_0
    * **input**: tensor of shape :math:`(L, H_{in})` for unbatched input,
      :math:`(L, N, H_{in})` when ``batch_first=False`` or
      :math:`(N, L, H_{in})` when ``batch_first=True`` containing the features of
      the input sequence.  The input can also be a packed variable length sequence.
      See :func:`torch.nn.utils.rnn.pack_padded_sequence` or
      :func:`torch.nn.utils.rnn.pack_sequence` for details.
    * **h_0**: tensor of shape :math:`(D * \text{num\_layers}, H_{out})` for unbatched input or
      :math:`(D * \text{num\_layers}, N, H_{out})` containing the initial hidden
      state for the input sequence batch. Defaults to zeros if not provided.

    where:

    .. math::
        \begin{aligned}
            N ={} & \text{batch size} \\
            L ={} & \text{sequence length} \\
            D ={} & 2 \text{ if bidirectional=True otherwise } 1 \\
            H_{in} ={} & \text{input\_size} \\
            H_{out} ={} & \text{hidden\_size}
        \end{aligned}

Outputs: output, h_n
    * **output**: tensor of shape :math:`(L, D * H_{out})` for unbatched input,
      :math:`(L, N, D * H_{out})` when ``batch_first=False`` or
      :math:`(N, L, D * H_{out})` when ``batch_first=True`` containing the output features
      `(h_t)` from the last layer of the RNN, for each `t`. If a
      :class:`torch.nn.utils.rnn.PackedSequence` has been given as the input, the output
      will also be a packed sequence.
    * **h_n**: tensor of shape :math:`(D * \text{num\_layers}, H_{out})` for unbatched input or
      :math:`(D * \text{num\_layers}, N, H_{out})` containing the final hidden state
      for each element in the batch.

Attributes:
    weight_ih_l[k]: the learnable input-hidden weights of the k-th layer,
        of shape `(hidden_size, input_size)` for `k = 0`. Otherwise, the shape is
        `(hidden_size, num_directions * hidden_size)`
    weight_hh_l[k]: the learnable hidden-hidden weights of the k-th layer,
        of shape `(hidden_size, hidden_size)`
    bias_ih_l[k]: the learnable input-hidden bias of the k-th layer,
        of shape `(hidden_size)`
    bias_hh_l[k]: the learnable hidden-hidden bias of the k-th layer,
        of shape `(hidden_size)`

.. note::
    All the weights and biases are initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`
    where :math:`k = \frac{1}{\text{hidden\_size}}`

.. note::
    For bidirectional RNNs, forward and backward are directions 0 and 1 respectively.
    Example of splitting the output layers when ``batch_first=False``:
    ``output.view(seq_len, batch, num_directions, hidden_size)``.

.. note::
    ``batch_first`` argument is ignored for unbatched inputs.

.. include:: ../cudnn_rnn_determinism.rst

.. include:: ../cudnn_persistent_rnn.rst

Examples::

    >>> rnn = nn.RNN(10, 20, 2)
    >>> input = torch.randn(5, 3, 10)
    >>> h0 = torch.randn(2, 3, 20)
    >>> output, hn = rnn(input, h0)
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/rnn.py
Type:           type
Subclasses:

wrap LaTex equation inside of double $$ signs

$$h_t = \tanh(x_t W_{ih}^T + b_{ih} + h_{t-1}W_{hh}^T + b_{hh})$$

In [150]:
from IPython.display import display, Math, Latex
display(Math(r'h_t = \tanh(x_t W_{ih}^T + b_{ih} + h_{t-1}W_{hh}^T + b_{hh})'))

In [163]:
import torch
from torch import nn
recurrent_layer = nn.RNN(input_size=5, hidden_size=30, batch_first=True)

# input sequence (batch_size, sequence_length, input_features_size)
input_sequence_batch = torch.randn(10, 20, 5)

# hidden state (number_of_stacked_layers, batch_size, hidden_size)
# by default the num_layer=1
# if hidden state is not provided by default it will be zero
hidden_state_size = torch.randn(1, 10, 30)

output_sequence, ouput_hidden_state = recurrent_layer(input_sequence_batch, hidden_state_size)

print(f"Input sequence shape: {input_sequence_batch.shape}")
print(f"Initial hidden state shape: {hidden_state_size.shape}")
print(f"\nOutput sequence shape: {output_sequence.shape}")
print(f"Output hidden state shape: {output_sequence.shape}")
print(f"\nRecurrent weight shape: {recurrent_layer.all_weights}")
print(f"Recurrent Layer: {recurrent_layer}")

Input sequence shape: torch.Size([10, 20, 5])
Initial hidden state shape: torch.Size([1, 10, 30])

Output sequence shape: torch.Size([10, 20, 30])
Output hidden state shape: torch.Size([10, 20, 30])

Recurrent weight shape: [[Parameter containing:
tensor([[ 0.0559, -0.1811,  0.1618,  0.0336,  0.0444],
        [-0.1492,  0.1553, -0.1643,  0.0388, -0.1554],
        [ 0.1153, -0.0060, -0.1494, -0.1464, -0.0359],
        [ 0.0321, -0.0835, -0.0366, -0.1035, -0.1246],
        [-0.1563, -0.1467,  0.0580,  0.0204,  0.0921],
        [-0.1378,  0.1149, -0.1678, -0.0393, -0.1366],
        [ 0.0694,  0.1011,  0.1518,  0.0730, -0.1385],
        [ 0.0221,  0.1031, -0.1167, -0.0681,  0.0298],
        [-0.0408, -0.1622, -0.1772, -0.0034, -0.0027],
        [ 0.0559,  0.0495, -0.1254,  0.1144,  0.0998],
        [-0.0197,  0.0708, -0.1566, -0.1436, -0.1746],
        [-0.1671,  0.0665, -0.1535,  0.1005, -0.1689],
        [ 0.0774, -0.1448, -0.0972,  0.0486, -0.0556],
        [-0.0423,  0.0505,  0.1191,  0.1160,  0.1092],
        [ 0.1361,  0.0442, -0.0609, -0.0274, -0.1059],
        [-0.0982, -0.0047, -0.0902, -0.1624, -0.1591],
        [ 0.1027,  0.1151, -0.1350,  0.0134, -0.0487],
        [-0.0605,  0.1125, -0.0408, -0.1571, -0.0385],
        [-0.0655, -0.1495,  0.1747,  0.0778,  0.0034],
        [-0.0234,  0.1142, -0.0844,  0.1531, -0.0063],
        [-0.0590,  0.0776, -0.1232,  0.1490, -0.1767],
        [-0.1394, -0.0632, -0.0862,  0.0690,  0.0173],
        [-0.1786,  0.1449,  0.1610, -0.1427,  0.0879],
        [ 0.1366, -0.0121,  0.0823,  0.0547,  0.0982],
        [-0.0017, -0.0843,  0.1006,  0.1225, -0.1639],
        [ 0.0478, -0.0501,  0.0170, -0.1220,  0.1406],
        [-0.1250, -0.0960,  0.0282, -0.1312,  0.0289],
        [-0.1230,  0.0826,  0.0447,  0.0958, -0.1315],
        [-0.0986,  0.1660, -0.1693,  0.1257,  0.0993],
        [ 0.0375,  0.0488, -0.1796,  0.1102, -0.0553]], requires_grad=True), Parameter containing:
tensor([[-1.3477e-01,  1.3173e-02, -1.6128e-01,  4.0788e-03, -6.1137e-03,
          3.7498e-02,  9.0401e-02,  1.4141e-01, -1.3941e-01,  1.2810e-01,
         -1.0482e-02, -8.4342e-02, -1.7233e-01,  1.7104e-01,  1.2203e-01,
         -1.3649e-01,  9.0246e-02,  1.2405e-02, -1.2423e-01,  6.0979e-03,
         -3.5845e-02,  1.4039e-01, -1.5479e-01, -1.1593e-01,  1.7836e-01,
          7.0399e-02, -8.5286e-02, -1.1668e-01, -1.7429e-02, -1.6364e-01],
        [-6.7484e-02, -1.5027e-01,  9.4564e-03, -6.3510e-02,  1.7834e-01,
         -5.5022e-02,  1.0582e-03,  6.4236e-03, -4.1159e-02, -7.4757e-02,
         -1.1255e-01, -4.4441e-03,  1.0613e-01,  1.6527e-01, -5.7791e-02,
          4.0983e-02, -1.4995e-02, -1.3626e-02, -8.1857e-02, -1.2996e-01,
          1.3075e-01, -9.1349e-02,  1.3672e-02,  2.5696e-02, -1.0948e-01,
         -6.0570e-02, -1.5588e-01, -1.5229e-01, -1.7253e-01, -1.6452e-01],
        [-1.3790e-01,  1.4286e-01,  1.1534e-01, -4.0533e-02, -1.1941e-02,
         -1.7869e-01, -1.6007e-01,  1.3108e-01,  1.4367e-01,  1.7604e-01,
          1.4574e-01, -9.4216e-02, -1.3259e-01, -1.1412e-01, -1.0228e-01,
         -1.3116e-01,  8.6118e-02,  8.1289e-02, -1.4819e-02,  5.2322e-02,
          8.3845e-02,  1.9950e-02,  5.0283e-02, -4.4009e-02,  1.0898e-01,
          1.1731e-01, -1.3077e-01, -2.4453e-02, -1.7707e-01,  1.6689e-01],
        [-8.4730e-02, -1.4871e-01,  1.4510e-01, -6.7641e-02,  1.6769e-01,
          2.0277e-02,  1.1620e-01, -1.2957e-01, -1.1412e-01,  3.3488e-02,
          2.5277e-02,  6.8041e-02,  1.1330e-01,  1.2948e-01, -5.0473e-02,
         -1.5668e-02, -1.6816e-02, -2.1643e-02, -6.1175e-03,  2.3760e-02,
          3.3449e-02,  8.9801e-02,  9.1597e-02, -1.2812e-01, -1.8605e-02,
         -5.9889e-03,  3.9220e-02, -3.0875e-04,  4.9439e-02,  3.9975e-02],
        [ 6.2944e-02, -1.3507e-01,  1.5134e-01,  6.5118e-02, -1.6428e-01,
         -1.3419e-01,  1.1838e-01, -6.4112e-02, -1.6004e-01, -1.1159e-01,
         -1.7730e-01,  8.4240e-04, -8.0427e-02, -1.7483e-01, -1.2379e-01,
         -2.8599e-02, -1.3282e-02, -9.7383e-03, -5.0771e-02,  7.8313e-02,
          2.2885e-02,  4.5378e-02, -1.2064e-01, -4.2937e-02,  1.1489e-01,
         -2.1565e-02,  1.0838e-01, -1.6443e-01,  1.2274e-01,  1.4549e-01],
        [ 1.1233e-01,  4.3514e-04,  2.6700e-02,  8.8440e-03,  7.7037e-02,
          1.6985e-01, -4.6768e-02,  1.1283e-01,  3.0948e-02,  3.9700e-02,
          5.8021e-02, -1.6619e-01, -9.8236e-03,  4.5059e-02, -8.4994e-02,
          1.4820e-01, -4.1144e-04, -1.6645e-02, -1.4075e-01, -3.8314e-02,
         -1.1656e-01, -4.6074e-02,  1.5618e-01, -1.7912e-01, -7.0161e-02,
          2.2807e-02,  6.3532e-02,  9.3767e-02,  1.2292e-01,  9.8913e-02],
        [ 1.4241e-01, -1.4767e-02, -1.8116e-01, -1.3224e-01, -1.8211e-01,
          1.4437e-02,  9.2245e-02, -1.3302e-01,  2.6154e-02,  1.0519e-01,
         -1.1665e-01,  1.2033e-01, -9.8295e-03, -2.3899e-02,  4.2898e-02,
         -5.8318e-02,  1.1467e-01,  6.3764e-02,  4.0420e-02, -8.1303e-02,
         -1.1043e-01,  1.3776e-01, -5.0018e-02, -4.3625e-02,  1.5381e-01,
          1.6155e-01,  1.5624e-01, -1.5593e-01, -8.2886e-02, -3.8461e-02],
        [-5.5385e-02,  6.4601e-02, -1.5785e-01, -4.0144e-02, -7.6199e-02,
         -7.6276e-02,  6.7381e-02,  1.1140e-01, -7.1100e-02, -7.3807e-02,
          1.4087e-01,  1.5384e-02,  9.7202e-02, -6.1639e-02,  9.5748e-02,
          1.6320e-01, -8.2101e-02, -7.1531e-02,  1.0807e-01, -5.1360e-02,
         -1.7476e-01,  1.5484e-01,  1.0099e-01,  2.4405e-02,  4.9403e-02,
          1.4502e-01, -2.0260e-02, -2.5833e-02,  1.8233e-01, -7.3683e-02],
        [-5.9100e-03,  2.0800e-02,  1.1008e-01, -5.6629e-02,  8.1711e-02,
         -3.0830e-02,  1.7668e-01,  9.2222e-02, -4.0636e-02, -1.3971e-01,
         -9.6723e-02, -4.3553e-02, -8.3209e-02,  5.9671e-02,  7.8362e-02,
          4.0895e-03,  5.3687e-02, -7.2357e-02, -1.2625e-01, -5.0123e-02,
          4.9212e-02, -3.9051e-02, -2.9340e-02, -3.0828e-03,  9.4950e-04,
          1.8172e-01,  7.1060e-02,  5.3061e-03, -1.6866e-02,  3.5235e-02],
        [-9.2704e-02,  1.1181e-01,  1.3972e-01, -6.5893e-02, -7.4356e-02,
          1.5300e-01,  1.7493e-01, -2.5955e-02,  3.9737e-02,  3.1417e-02,
          9.5599e-02,  1.2360e-01,  1.7262e-02, -2.6243e-02, -1.5923e-01,
         -7.6565e-02,  1.7744e-01, -6.3857e-02,  1.8057e-01,  1.0064e-01,
         -8.6868e-02, -1.2575e-01,  3.2660e-02,  1.0103e-01, -5.1281e-02,
          1.3621e-01,  1.2891e-01, -6.7874e-02, -1.7842e-01, -1.3911e-01],
        [-1.5095e-01, -9.4439e-02, -7.0565e-02, -9.7491e-02,  6.0879e-02,
          1.1920e-01,  1.4711e-02,  1.4271e-01, -3.0145e-02,  1.4027e-01,
         -1.2350e-02,  4.5327e-02,  2.3458e-02, -8.4128e-02, -1.6302e-01,
         -8.8987e-02, -1.0354e-01,  3.1279e-02, -1.3499e-01,  2.3109e-02,
         -1.0106e-01, -1.5587e-01, -9.1892e-03, -1.4545e-01, -3.1085e-02,
         -3.1087e-02, -3.8444e-02,  3.0455e-02, -1.6159e-01, -7.8351e-02],
        [ 1.3683e-02,  6.4668e-02, -3.2008e-02,  2.4879e-02, -1.5626e-01,
         -7.3294e-02,  1.4522e-02,  2.6897e-02,  1.0665e-01, -4.3729e-02,
          1.1311e-01,  7.1443e-02, -1.7300e-01,  9.9852e-02,  1.6268e-01,
         -1.7543e-01,  1.1301e-02, -2.0900e-02,  1.2984e-01, -1.0751e-01,
         -1.4885e-01,  1.2474e-01,  2.3454e-02,  1.1231e-01, -1.3454e-01,
          8.3063e-02,  1.1513e-02, -1.2581e-01,  7.9343e-02, -2.9278e-02],
        [ 1.7314e-01,  1.2880e-01, -8.0499e-02, -9.1659e-02, -1.6082e-01,
         -2.3725e-02,  1.1546e-01,  2.8211e-02,  1.2912e-01,  3.6311e-02,
          1.0493e-01, -1.3510e-01,  1.3919e-01,  2.7522e-02,  1.6474e-01,
         -1.0776e-01,  1.1964e-01, -5.7590e-03, -8.6757e-02,  1.0267e-01,
          1.5738e-01,  7.0708e-02,  1.4907e-01, -1.6775e-01, -4.1055e-02,
         -1.4005e-01,  9.1479e-02,  4.5741e-02, -1.7497e-01, -1.1410e-01],
        [-1.5577e-01,  1.1980e-01, -3.0086e-02, -4.4977e-02,  4.6699e-02,
         -4.3095e-02,  4.1695e-02,  6.0539e-02,  3.9652e-02, -1.3631e-01,
          1.6723e-01, -1.6337e-01,  7.2477e-02, -6.4668e-02,  1.3461e-01,
          1.7918e-01, -1.2654e-02,  1.3457e-01, -4.3346e-02, -1.0450e-01,
          1.3932e-01,  9.4193e-02, -3.5845e-02,  1.3202e-01,  3.8523e-02,
          1.6903e-01, -7.6562e-02, -1.7980e-01,  8.8202e-02,  1.6678e-01],
        [ 1.1702e-01, -4.2846e-02,  1.2267e-01,  1.4520e-01,  8.5521e-02,
          4.9810e-02,  5.6040e-02,  7.8934e-02, -1.7980e-01, -8.8354e-02,
          1.4782e-01,  6.6380e-02,  1.2209e-01,  4.5145e-02, -1.7719e-01,
          1.3301e-01, -2.0991e-02, -2.7672e-02, -2.6176e-02,  3.2579e-03,
         -1.1404e-01,  1.6755e-01,  3.5863e-03,  1.2760e-01, -2.3995e-02,
          3.1302e-02,  1.7325e-01,  1.7747e-01,  1.7741e-01,  1.6085e-01],
        [ 1.2985e-01,  1.1278e-01, -1.6856e-01,  7.0462e-02,  1.4934e-01,
         -1.1024e-01, -8.5544e-02,  1.4131e-01,  1.6511e-01,  1.5262e-01,
         -7.4293e-02,  1.6380e-02, -1.4550e-01, -1.4898e-03, -4.2082e-02,
          4.5683e-02, -1.0717e-01,  4.7374e-02,  1.7051e-01,  1.2599e-01,
         -1.0857e-01,  1.7588e-01,  9.5941e-02,  1.2628e-01,  2.2427e-02,
          2.2373e-02,  9.8640e-02,  9.9985e-02, -1.4112e-01,  1.1134e-01],
        [ 2.5120e-03,  1.1711e-01, -5.2932e-02, -1.7829e-01, -1.6363e-01,
         -2.0225e-02, -1.6589e-01,  1.6076e-01, -3.2161e-02,  1.3968e-03,
         -1.7835e-01,  1.5895e-01,  1.2345e-01,  8.5072e-02, -4.0995e-02,
          1.0639e-01, -9.1993e-03, -7.6380e-02,  1.5917e-01, -1.5169e-01,
         -1.3213e-01, -8.7680e-03, -1.4483e-01, -1.3146e-01, -4.1812e-02,
          8.6344e-02,  1.2863e-01, -1.3229e-01,  1.7661e-01, -3.0590e-02],
        [-2.3694e-02,  9.0722e-02, -7.6584e-02, -8.2682e-02, -1.2409e-01,
          8.3951e-02, -1.1953e-01,  1.6203e-01, -1.2320e-01, -1.7112e-01,
          4.6388e-02, -1.3657e-01,  8.9139e-02, -1.4705e-01, -2.0509e-03,
         -9.2494e-02, -1.3517e-01, -8.0431e-02, -2.0859e-02,  1.4764e-01,
         -1.6111e-01,  4.0591e-02,  8.8602e-02, -3.5177e-02, -1.3919e-01,
         -1.0062e-01, -1.7320e-01,  1.0842e-01,  6.1237e-02, -1.7129e-01],
        [-9.1654e-02,  9.8565e-02,  9.2534e-02,  7.1912e-02, -1.1436e-01,
          7.7538e-03,  4.3539e-02, -8.4914e-03, -9.1625e-02,  9.7964e-02,
          1.1717e-01,  1.7412e-01,  2.7275e-02, -1.7961e-01,  1.7788e-01,
         -1.6326e-01, -6.5020e-02,  1.7675e-01, -1.4636e-01,  1.1381e-01,
         -8.8920e-02,  1.3415e-01, -1.1589e-02,  1.4892e-01,  1.3328e-01,
         -1.2308e-01,  1.7596e-01, -1.7540e-01, -4.6927e-02,  1.5864e-01],
        [ 5.6741e-02,  1.1649e-01, -1.0116e-01, -1.5320e-01,  6.9236e-02,
          1.1257e-01,  8.9233e-02,  1.4059e-01, -6.7763e-02, -4.6138e-02,
         -1.4722e-01,  6.1349e-02, -1.6063e-01, -1.6093e-01, -4.1833e-02,
          1.2317e-01, -1.4285e-01,  1.2258e-01,  1.5853e-01,  1.8722e-02,
         -5.0869e-02, -1.2553e-01, -1.6597e-01,  1.6796e-01,  1.3861e-01,
          1.1941e-01,  3.0213e-03,  7.4501e-02,  6.4022e-03, -3.5857e-02],
        [ 1.1325e-02,  1.1729e-01, -4.7580e-02,  4.0109e-02,  1.5686e-01,
         -4.2100e-02, -8.7043e-02, -4.0700e-02,  1.6609e-01, -1.5538e-01,
          1.8657e-02, -3.2926e-02, -1.4436e-01, -1.4575e-01, -1.8212e-01,
         -7.8261e-02,  4.4258e-02, -1.3183e-01,  1.3473e-01, -1.5922e-01,
          6.2503e-02,  1.7870e-01, -3.3873e-02, -1.0318e-01, -6.5716e-02,
         -1.1230e-01,  1.4010e-01,  7.1017e-02,  8.9827e-02, -1.4217e-01],
        [-1.4412e-02, -2.3294e-02, -1.1223e-01, -4.6860e-02,  1.7741e-01,
         -1.2855e-01,  1.7038e-01,  4.4613e-02,  1.4715e-01, -5.2256e-02,
         -1.2923e-01,  5.1647e-02, -1.2635e-01, -1.5599e-01, -1.7095e-01,
         -4.3590e-02,  1.2261e-01, -2.4683e-02,  4.2221e-02,  1.5476e-02,
         -1.5173e-02, -1.9246e-02,  1.3678e-01,  1.5444e-02,  2.4448e-02,
          4.2087e-02,  1.8979e-02,  1.6306e-01,  4.8123e-02, -1.0975e-01],
        [-1.2526e-01,  1.7899e-01,  1.5525e-01,  7.8120e-02, -1.2900e-01,
         -1.4981e-01, -1.7238e-01, -4.2387e-02,  5.1881e-02,  5.9347e-02,
         -8.4818e-02,  7.2727e-02,  1.0549e-01, -1.2287e-01, -1.7363e-01,
          7.8582e-02,  1.6468e-02,  1.7560e-01,  1.1040e-01, -8.7847e-02,
          2.4843e-02,  4.5390e-02,  1.5911e-01, -1.7253e-01,  1.6225e-01,
          6.8698e-02, -1.4121e-01,  1.7759e-01, -8.6545e-02, -1.7376e-01],
        [ 4.6336e-02, -1.0700e-01, -8.8045e-03,  5.9895e-02, -1.8251e-01,
         -1.0286e-01, -7.1275e-02,  3.3830e-02, -1.6007e-01,  7.1714e-02,
          1.0900e-01, -7.7794e-02, -1.0568e-01,  1.1603e-02, -9.5582e-02,
          1.0889e-01,  1.2411e-01,  8.4712e-02,  1.2342e-01, -2.8958e-02,
          1.8505e-02,  6.8055e-02, -1.7130e-01,  6.9382e-02,  2.5620e-02,
          1.4072e-01, -1.3130e-01, -1.7325e-01, -4.6819e-02, -1.6139e-01],
        [ 8.2402e-02, -1.8210e-04, -2.5068e-02, -1.1522e-01, -1.2032e-01,
         -3.9532e-02,  5.9135e-02, -1.1905e-01,  6.0734e-02,  1.4882e-02,
          1.2609e-01,  6.1895e-02, -1.0724e-01,  8.9293e-02, -1.8234e-01,
          2.6348e-02,  1.8972e-02,  1.1243e-01, -4.1303e-03, -1.0850e-01,
         -5.4476e-02,  1.8302e-02,  9.6375e-02,  1.5214e-02, -1.0081e-01,
         -1.6892e-01,  1.3496e-01, -2.6088e-02,  1.5087e-01,  1.0870e-01],
        [ 5.7144e-02, -1.8254e-01, -2.7743e-02, -4.1717e-03, -1.7723e-01,
          1.3254e-02,  4.6689e-02,  1.6046e-01,  1.5645e-01, -4.9762e-02,
         -1.7831e-01, -2.7223e-02,  9.6307e-02, -3.0270e-02, -1.8725e-02,
          9.4008e-02,  1.6262e-01,  1.1755e-01,  8.7020e-03,  5.3473e-02,
          8.7290e-02, -8.0174e-02,  1.3806e-01, -3.0290e-02,  5.9816e-02,
         -1.0475e-01,  7.3104e-02,  3.8910e-03,  1.8035e-01,  3.0502e-02],
        [ 9.6794e-02,  1.6466e-01, -1.4663e-01,  3.8264e-02,  1.5523e-01,
         -7.5854e-02, -1.2186e-01,  1.5941e-01, -1.3198e-01,  4.6833e-02,
         -1.5685e-01,  6.3171e-02,  5.9239e-02,  2.6822e-02,  1.2148e-01,
          1.2312e-02, -1.1286e-01, -1.1384e-01, -1.4231e-01, -3.5505e-02,
          1.2869e-01, -1.0044e-01, -1.0139e-01, -3.8590e-02,  1.6865e-01,
         -7.4531e-02,  1.6258e-01, -1.4820e-01, -1.4209e-01, -1.3482e-01],
        [-6.7313e-02,  1.3159e-01,  4.3238e-02, -7.7024e-02,  1.6915e-01,
         -1.7639e-01,  2.7287e-02, -1.3977e-01,  5.2537e-02,  5.7004e-02,
         -3.2756e-02, -1.6748e-01, -1.3529e-01, -7.2046e-02,  1.7526e-01,
         -2.9652e-02, -1.6710e-01,  6.4203e-02, -3.0574e-02,  2.5079e-03,
         -8.4411e-02,  5.9659e-02,  2.3005e-02, -1.1088e-01, -1.3016e-01,
         -1.4678e-01,  1.2316e-01,  3.4563e-02, -1.2137e-01,  2.7435e-02],
        [ 1.5590e-01, -8.1316e-02, -1.0818e-01,  1.3802e-01, -1.2071e-01,
         -6.7972e-03, -4.5015e-02,  8.3319e-02,  1.4283e-01, -3.6768e-02,
          1.4968e-01, -3.3383e-02,  1.6113e-01, -1.5296e-01, -1.1766e-01,
          1.2644e-01, -4.1551e-02,  5.4904e-02,  8.9869e-02, -1.0211e-01,
         -1.2211e-01, -4.5257e-02, -1.0441e-02,  1.3402e-01, -4.3495e-02,
          9.2934e-02,  6.6902e-02,  1.3747e-02,  1.2528e-01, -6.3020e-02],
        [ 7.3841e-03, -1.0425e-01,  9.2544e-02,  1.7353e-01, -1.7317e-01,
         -1.2477e-01,  4.6930e-02,  1.0769e-01, -4.8509e-02,  5.5807e-03,
          6.0844e-02, -5.6657e-02,  1.5515e-01, -8.0719e-02, -1.6431e-01,
         -1.0651e-01,  8.4291e-03, -1.2581e-01, -1.3300e-01, -9.4521e-02,
          1.6328e-01,  5.1570e-02, -1.5957e-01,  2.1058e-02, -1.0976e-01,
          1.7341e-01, -1.2207e-02,  8.8322e-02, -6.3167e-02,  1.2534e-01]],
       requires_grad=True), Parameter containing:
tensor([ 0.1021, -0.0003, -0.0311, -0.1823,  0.0036,  0.0280, -0.1812,  0.1007,
        -0.1443, -0.0031, -0.1538, -0.0228, -0.0776, -0.1543,  0.0707,  0.0592,
        -0.1192,  0.0272,  0.1209,  0.0277,  0.1453,  0.0030,  0.0870, -0.0655,
        -0.1544, -0.1018,  0.0774,  0.1036, -0.0203,  0.1455],
       requires_grad=True), Parameter containing:
tensor([ 0.0271, -0.0751, -0.0253, -0.0002,  0.1440, -0.0898,  0.1653, -0.1747,
        -0.1653, -0.1640,  0.0875, -0.1683,  0.0351, -0.1601, -0.1275,  0.0068,
         0.0096, -0.1219,  0.0736, -0.1526,  0.0078, -0.0552, -0.1475,  0.1038,
        -0.0714, -0.0255, -0.0886, -0.0939,  0.1074, -0.0945],
       requires_grad=True)]]
Recurrent Layer: RNN(5, 30, batch_first=True)

In [168]:
nn.Linear?

Init signature:
nn.Linear(
    in_features: int,
    out_features: int,
    bias: bool = True,
    device=None,
    dtype=None,
) -> None
Docstring:
Applies an affine linear transformation to the incoming data: :math:`y = xA^T + b`.

This module supports :ref:`TensorFloat32<tf32_on_ampere>`.

On certain ROCm devices, when using float16 inputs this module will use :ref:`different precision<fp16_on_mi200>` for backward.

Args:
    in_features: size of each input sample
    out_features: size of each output sample
    bias: If set to ``False``, the layer will not learn an additive bias.
        Default: ``True``

Shape:
    - Input: :math:`(*, H_{in})` where :math:`*` means any number of
      dimensions including none and :math:`H_{in} = \text{in\_features}`.
    - Output: :math:`(*, H_{out})` where all but the last dimension
      are the same shape as the input and :math:`H_{out} = \text{out\_features}`.

Attributes:
    weight: the learnable weights of the module of shape
        :math:`(\text{out\_features}, \text{in\_features})`. The values are
        initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
        :math:`k = \frac{1}{\text{in\_features}}`
    bias:   the learnable bias of the module of shape :math:`(\text{out\_features})`.
            If :attr:`bias` is ``True``, the values are initialized from
            :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
            :math:`k = \frac{1}{\text{in\_features}}`

Examples::

    >>> m = nn.Linear(20, 30)
    >>> input = torch.randn(128, 20)
    >>> output = m(input)
    >>> print(output.size())
    torch.Size([128, 30])
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/linear.py
Type:           type
Subclasses:     NonDynamicallyQuantizableLinear, LazyLinear, Linear, LinearBn1d, Linear

In [187]:
from IPython.display import display, Math, Latex
display(Math(r'y = xW^T + b'))

In [188]:
recurrent_layer = nn.RNN(input_size=15, hidden_size=50, batch_first=True, device="mps")

# [batch_size, sequence_length, input_feature_size]
input_sequence = torch.randn(120, 60, 15, device="mps")
# [num_layers, batch_size, hidden_size]
initial_hidden_state = torch.randn(1, 120, 50, device="mps")

output_sequence, final_hidden_state = recurrent_layer(input_sequence, initial_hidden_state)

print(f"Input sequence shape: {input_sequence.shape}")
print(f"Initial hidden state shape: {initial_hidden_state.shape}")
print(f"\nOutput sequence shape: {output_sequence.shape}")
print(f"Final hidden state shape: {final_hidden_state.shape}")

Input sequence shape: torch.Size([120, 60, 15])
Initial hidden state shape: torch.Size([1, 120, 50])

Output sequence shape: torch.Size([120, 60, 50])
Final hidden state shape: torch.Size([1, 120, 50])

In [189]:
rnn_layer = nn.RNN(input_size=78, hidden_size=243, batch_first=True)
# [batch_size, sequence_length, input_featuer_size]
input_sequence = torch.randn(400, 123, 78)
# [num_layer, batch_size, hidden_size]
initial_hidden_state = torch.randn(1, 400, 243)

output_sequence, final_hidden_state = rnn_layer(input_sequence, initial_hidden_state)

print(f"Input sequence shape: {input_sequence.shape}")
print(f"Initial hidden state shape: {initial_hidden_state.shape}")
print(f"\nOutput sequence shape: {output_sequence.shape}")
print(f"Final hidden state shape: {final_hidden_state.shape}")

Input sequence shape: torch.Size([400, 123, 78])
Initial hidden state shape: torch.Size([1, 400, 243])

Output sequence shape: torch.Size([400, 123, 243])
Final hidden state shape: torch.Size([1, 400, 243])

In [195]:
device = torch.device("mps" if torch.backends.mps.is_available else "cuda" if torch.cuda.is_available else "cpu")
recurrent_layer = nn.RNN(input_size=32, hidden_size=98, batch_first=True, device=device)

# [batch_size, sequence_length, input_feature_size]
input_sequence = torch.rand(456, 103, 32, device=device)

# [num_layer, batch_size, hidden_size]
initial_hidden_state = torch.randn(1, 456, 98, device=device)

output_sequence, final_hidden_state = recurrent_layer(input_sequence, initial_hidden_state)

print(f"Input sequence shape: {input_sequence.shape}")
print(f"Initial hidden state shape: {initial_hidden_state.shape}")
print(f"\nOutput sequence shape: {output_sequence.shape}")
print(f"Final hidden state shape: {final_hidden_state.shape}")

Input sequence shape: torch.Size([456, 103, 32])
Initial hidden state shape: torch.Size([1, 456, 98])

Output sequence shape: torch.Size([456, 103, 98])
Final hidden state shape: torch.Size([1, 456, 98])

In [199]:
# activation(non-linear) function
import torch.nn.functional as F
F.relu??

Signature: F.relu(input: torch.Tensor, inplace: bool = False) -> torch.Tensor
Source:
def relu(input: Tensor, inplace: bool = False) -> Tensor:  # noqa: D400,D402
    r"""relu(input, inplace=False) -> Tensor

    Applies the rectified linear unit function element-wise. See
    :class:`~torch.nn.ReLU` for more details.
    """
    if has_torch_function_unary(input):
        return handle_torch_function(relu, (input,), input, inplace=inplace)
    if inplace:
        result = torch.relu_(input)
    else:
        result = torch.relu(input)
    return result
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/functional.py
Type:      function

In [200]:
nn.ReLU??

Init signature: nn.ReLU(inplace: bool = False)
Source:
class ReLU(Module):
    r"""Applies the rectified linear unit function element-wise.

    :math:`\text{ReLU}(x) = (x)^+ = \max(0, x)`

    Args:
        inplace: can optionally do the operation in-place. Default: ``False``

    Shape:
        - Input: :math:`(*)`, where :math:`*` means any number of dimensions.
        - Output: :math:`(*)`, same shape as the input.

    .. image:: ../scripts/activation_images/ReLU.png

    Examples::

        >>> m = nn.ReLU()
        >>> input = torch.randn(2)
        >>> output = m(input)


      An implementation of CReLU - https://arxiv.org/abs/1603.05201

        >>> m = nn.ReLU()
        >>> input = torch.randn(2).unsqueeze(0)
        >>> output = torch.cat((m(input), m(-input)))
    """

    __constants__ = ["inplace"]
    inplace: bool

    def __init__(self, inplace: bool = False):
        super().__init__()
        self.inplace = inplace

    def forward(self, input: Tensor) -> Tensor:
        return F.relu(input, inplace=self.inplace)

    def extra_repr(self) -> str:
        inplace_str = "inplace=True" if self.inplace else ""
        return inplace_str
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/activation.py
Type:           type
Subclasses:     ReLU6

$$\text{ReLU}(x) = (x)^+ = \max(0, x)$$

In [214]:
from IPython.display import display, Math, Latex
display(Math(r'\text{ReLU}(x) = (x)^+ = \max(0, x)'))

In [330]:
import torch
from torch import nn
from IPython.display import display, Math, Latex
from torch.nn import functional as F

relu = nn.ReLU()
a = torch.tensor([-10])
out = relu(a)
print(f"Input: {a}")
print(f"After ReLU: {out}\n")
# simple any negatives values are changed to 0, while positives values stay as they are

display(Math(r'\text{LeakyReLU}(x) = \max(0, x) + \text{negative\_slope} * \min(0, x)'))
m = nn.LeakyReLU()
inputs = torch.tensor(-4)
output = m(inputs.double())
print(output)

class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        # defining layers, expects 456 input_feature_size, and outputs it into 233 dimensions
        self.fc1 = nn.Linear(456, 233)
        self.relu_layer = nn.ReLU()
        self.fc2 = nn.Linear(233, 30)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu_layer(x) # or F.relu(x)
        x = self.fc2(x)
        return x

model = SimpleNet()
# batch size of 45 and number of features are 456, dimensions only specificed at this point
data = torch.arange(456*45, dtype=torch.float32).view(45,456)
output = model(data) # forward pass
print(f"\nInput feature shape: {data.shape}")
print(f"Output feature shape: {output.shape}")

Input: tensor([-10])
After ReLU: tensor([0])

tensor(-0.0400, dtype=torch.float64)

Input feature shape: torch.Size([45, 456])
Output feature shape: torch.Size([45, 30])

In [153]:
import torch
from torch import nn

class SimpleNett(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.fc1 = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.relu_layer = nn.ReLU()
        self.fc2 = nn.Linear(in_features=hidden_size, out_features=output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu_layer(x)
        x = self.fc2(x)
        return x

model = SimpleNett(input_size=678, hidden_size=99, output_size=10)
data = torch.randn(101, 678)
output = model(data)
print(f"Simplnet here: {SimpleNett}")
print(f"Input shape: {data.shape}")
print(f"Output shape: {output.shape}")
for name, param in model.named_parameters():
    print(f"\n{name}\n{param}")

Simplnet here: <class '__main__.SimpleNett'>
Input shape: torch.Size([101, 678])
Output shape: torch.Size([101, 10])

fc1.weight
Parameter containing:
tensor([[ 0.0019,  0.0027, -0.0225,  ...,  0.0321, -0.0231,  0.0119],
        [ 0.0206,  0.0009,  0.0196,  ..., -0.0176,  0.0227, -0.0317],
        [ 0.0295,  0.0151, -0.0250,  ..., -0.0037, -0.0282,  0.0188],
        ...,
        [ 0.0181,  0.0057, -0.0311,  ..., -0.0270, -0.0292, -0.0313],
        [-0.0020, -0.0078,  0.0020,  ..., -0.0127,  0.0217, -0.0142],
        [-0.0274, -0.0236,  0.0315,  ..., -0.0353, -0.0285,  0.0055]],
       requires_grad=True)

fc1.bias
Parameter containing:
tensor([-0.0059,  0.0095,  0.0254,  0.0094,  0.0174,  0.0240, -0.0250,  0.0104,
         0.0306, -0.0013,  0.0266,  0.0342,  0.0234, -0.0381, -0.0038, -0.0235,
        -0.0313,  0.0297, -0.0225,  0.0318, -0.0125,  0.0376,  0.0013,  0.0094,
         0.0350, -0.0180, -0.0234,  0.0136,  0.0367, -0.0055,  0.0210, -0.0281,
        -0.0132, -0.0231, -0.0024,  0.0218,  0.0217, -0.0139, -0.0379, -0.0321,
        -0.0373,  0.0165, -0.0009,  0.0084,  0.0371, -0.0083, -0.0028,  0.0049,
         0.0058,  0.0230, -0.0253,  0.0241, -0.0249,  0.0366,  0.0288, -0.0003,
        -0.0251,  0.0155, -0.0374,  0.0255, -0.0283,  0.0117,  0.0120,  0.0319,
         0.0164, -0.0046,  0.0286,  0.0229, -0.0022, -0.0085, -0.0247, -0.0042,
         0.0247,  0.0362, -0.0366, -0.0263,  0.0195,  0.0263, -0.0254, -0.0173,
        -0.0115, -0.0158,  0.0030, -0.0237,  0.0294, -0.0042,  0.0038, -0.0269,
         0.0215,  0.0140,  0.0290, -0.0160, -0.0025,  0.0291,  0.0344,  0.0005,
         0.0072,  0.0341, -0.0257], requires_grad=True)

fc2.weight
Parameter containing:
tensor([[ 0.0722, -0.0969,  0.0266,  0.0814, -0.0382, -0.0410, -0.0334,  0.0551,
          0.0304, -0.0171,  0.0260, -0.0617,  0.0401,  0.0021,  0.0297, -0.0951,
         -0.0809, -0.0900, -0.0704,  0.0195, -0.0319, -0.0098,  0.0966, -0.0921,
          0.0786,  0.0671,  0.0423, -0.0017, -0.0753,  0.0535, -0.0356, -0.0396,
         -0.0749, -0.0737, -0.0602, -0.0033, -0.0392,  0.0165, -0.0198,  0.0021,
         -0.0489,  0.0660, -0.0065,  0.0263,  0.0007, -0.0804,  0.0313,  0.0168,
          0.0173, -0.0930, -0.0636,  0.0534,  0.0756, -0.0910, -0.0374, -0.0618,
          0.0434,  0.0651, -0.0818, -0.0823,  0.0451,  0.0889,  0.0058,  0.0201,
         -0.0325,  0.0341, -0.0475, -0.0158,  0.0757,  0.0128,  0.0651, -0.0797,
         -0.0963,  0.0417,  0.0112,  0.0995,  0.0163,  0.0592,  0.0723, -0.0284,
         -0.0621, -0.0396, -0.0382, -0.0542, -0.0193, -0.0722,  0.0562, -0.0821,
         -0.0505,  0.0702, -0.0391,  0.1003,  0.0852, -0.0481,  0.0001,  0.0513,
          0.0336,  0.0863,  0.0580],
        [-0.0840, -0.0974, -0.0955, -0.0180, -0.0967, -0.0765, -0.0212,  0.0591,
         -0.0170,  0.0641, -0.0652,  0.0722,  0.0967, -0.0767,  0.0153,  0.0232,
          0.0729,  0.0694, -0.0671,  0.0089,  0.0370, -0.0296,  0.0325,  0.0221,
         -0.0061, -0.0643, -0.0470,  0.0187,  0.0726,  0.0095, -0.0259, -0.0216,
         -0.0050,  0.0194,  0.0756,  0.0476, -0.0689,  0.0124,  0.0139, -0.1000,
          0.0565,  0.0452,  0.0539, -0.0493,  0.0996, -0.0810,  0.0434, -0.0089,
         -0.0032, -0.0782,  0.0264, -0.0014, -0.0980, -0.0329, -0.0805, -0.0690,
          0.0224,  0.0383,  0.0235, -0.0094,  0.0362,  0.0388,  0.0368, -0.0173,
         -0.0038,  0.0503, -0.0734,  0.0408, -0.0357, -0.0958,  0.0095,  0.0256,
          0.0679,  0.0131, -0.0217,  0.0517, -0.0954,  0.0521, -0.0205, -0.0290,
          0.0535, -0.0595, -0.0718,  0.0556,  0.0863,  0.0084, -0.0806,  0.0489,
          0.0630, -0.0796, -0.0443,  0.0653, -0.0570,  0.0119, -0.0890, -0.0785,
          0.0765,  0.0837, -0.0904],
        [ 0.0368, -0.0902, -0.0920,  0.0250, -0.0533, -0.0832,  0.0716,  0.0098,
          0.0108,  0.0648, -0.1003, -0.0541, -0.0232,  0.0986,  0.0272, -0.0917,
         -0.0591,  0.0179,  0.0354, -0.0317, -0.0986,  0.0549, -0.0978, -0.0656,
          0.0827, -0.0850,  0.0384,  0.0264, -0.0252, -0.0317,  0.0182,  0.0508,
         -0.0031, -0.0694, -0.0356, -0.0995, -0.0265,  0.0233,  0.0583,  0.0091,
          0.0698, -0.0022, -0.0675,  0.0683, -0.0167, -0.0671,  0.0055,  0.0047,
         -0.0922,  0.0756, -0.0530, -0.0610, -0.0485,  0.0569, -0.0787,  0.0519,
          0.1000,  0.0185,  0.0398,  0.0436,  0.0223,  0.0156, -0.0998, -0.0049,
          0.0951,  0.0951,  0.0923,  0.0453,  0.0272,  0.0285, -0.0420, -0.0318,
         -0.0674,  0.0386,  0.0055,  0.0263, -0.0333,  0.0520, -0.0716,  0.0886,
          0.0332,  0.0362, -0.0691,  0.0006,  0.0498, -0.0897, -0.0231,  0.0764,
         -0.0056,  0.0397,  0.0601, -0.0866,  0.0544,  0.0683,  0.0441, -0.0631,
         -0.0979,  0.0692, -0.0040],
        [ 0.0910, -0.0584,  0.0721,  0.0337,  0.0577,  0.0935, -0.0591, -0.0998,
          0.0408,  0.0777, -0.0712, -0.0984, -0.0198,  0.0147,  0.0944, -0.0516,
         -0.0690,  0.0606,  0.0409,  0.0935,  0.0509, -0.0972, -0.0566,  0.0331,
          0.0612, -0.0550,  0.0575,  0.0352, -0.0600, -0.0599,  0.0458,  0.0860,
         -0.0368, -0.0390,  0.0087,  0.0715, -0.0404, -0.0518, -0.0017,  0.0474,
         -0.0805,  0.0597,  0.0371,  0.0832, -0.0792, -0.0582,  0.0608, -0.0340,
          0.0329,  0.0449, -0.0217, -0.0210,  0.0580,  0.0386, -0.0145, -0.0471,
          0.0720,  0.0097, -0.0522, -0.0845, -0.0162, -0.0694, -0.0343,  0.0796,
         -0.0102, -0.0036,  0.0914,  0.0434,  0.0290, -0.0327, -0.0869,  0.0743,
          0.0453,  0.0693,  0.0842, -0.0105, -0.0060,  0.0422, -0.0382, -0.0740,
          0.0317,  0.0713, -0.0505, -0.0402,  0.0684,  0.0846, -0.0191, -0.0054,
          0.0516,  0.0533,  0.0917, -0.0756,  0.0108, -0.0700, -0.0982, -0.0219,
          0.0138,  0.0457, -0.0691],
        [ 0.0329, -0.0645, -0.0103, -0.0408,  0.0250, -0.0469, -0.0543,  0.0501,
          0.0646, -0.0179, -0.0286, -0.0613,  0.0875,  0.0933, -0.0338, -0.0713,
          0.0422,  0.0236,  0.0970, -0.0936,  0.0517, -0.0184,  0.0740, -0.0027,
         -0.0072,  0.0906, -0.0326, -0.0231, -0.0481,  0.0329, -0.0577,  0.0696,
         -0.0725,  0.0171,  0.0104,  0.0810,  0.0615, -0.0363, -0.0674,  0.0859,
          0.0578,  0.0698,  0.0464,  0.0763,  0.0296,  0.0525,  0.0453,  0.0032,
          0.0719, -0.0836, -0.0668, -0.0032,  0.0273,  0.0611, -0.0407, -0.1002,
         -0.0769,  0.0406, -0.0153,  0.0582,  0.0521,  0.0369,  0.0088,  0.0041,
         -0.0355, -0.0262, -0.0061,  0.0282, -0.0786,  0.0490,  0.0946, -0.0517,
         -0.0467,  0.0898, -0.0313,  0.0443, -0.0913, -0.0417, -0.0688, -0.0803,
          0.0218,  0.0260,  0.0920, -0.0524, -0.0146, -0.0724, -0.0299,  0.0671,
          0.0489, -0.0838,  0.0795, -0.0454, -0.0165,  0.0760, -0.0070, -0.0059,
         -0.0823,  0.0473, -0.0471],
        [ 0.0514,  0.0915,  0.0128,  0.0504, -0.0252, -0.0278,  0.0999,  0.0310,
          0.0943, -0.0579,  0.0710,  0.0138,  0.0201, -0.0250, -0.0177,  0.0186,
          0.0213, -0.0941,  0.0548,  0.0858, -0.0975, -0.0045,  0.0133,  0.0102,
         -0.0257,  0.0174, -0.0695, -0.0687,  0.0374, -0.0433, -0.0008, -0.0058,
         -0.0681, -0.0847, -0.0866,  0.0021, -0.0810,  0.0513, -0.0336,  0.0712,
          0.0292, -0.0778, -0.0398,  0.0660,  0.0969,  0.0534, -0.0600, -0.0398,
         -0.0867, -0.0874,  0.0751, -0.0892, -0.0952,  0.0510,  0.0336,  0.0803,
          0.0649, -0.0571,  0.0721, -0.0219, -0.0378,  0.0547, -0.0483, -0.1005,
          0.0153,  0.0509,  0.0311,  0.0517, -0.0367, -0.0447,  0.0522, -0.0203,
          0.0144,  0.0209, -0.0425, -0.0334, -0.0988, -0.0675, -0.0644, -0.0702,
         -0.0974,  0.0858,  0.0038,  0.0200,  0.0735,  0.0427, -0.0123,  0.0463,
         -0.0228,  0.0150,  0.0907,  0.0722,  0.0618, -0.0611,  0.0004,  0.0466,
         -0.0010,  0.0049,  0.0820],
        [-0.1003,  0.0724, -0.0583, -0.0686,  0.0202, -0.0396,  0.0332, -0.0348,
          0.0104, -0.0481,  0.0136,  0.0488,  0.0767, -0.0084, -0.0910,  0.0201,
          0.0188, -0.0289,  0.0354,  0.0065,  0.0486, -0.0963, -0.0392, -0.0674,
         -0.0152,  0.0911,  0.0575, -0.0554, -0.0359,  0.0042, -0.0301, -0.0940,
         -0.0750,  0.0688,  0.0827,  0.0298, -0.0924,  0.0574, -0.0029, -0.0840,
         -0.0664, -0.0535,  0.0750, -0.0767, -0.0669,  0.0185,  0.0472, -0.0951,
          0.0374,  0.0295,  0.0716,  0.0579,  0.0465, -0.0824,  0.0987, -0.0857,
          0.0500,  0.0865,  0.0449,  0.0157, -0.0131, -0.0375, -0.0097,  0.0997,
          0.0108, -0.0402, -0.0241,  0.0859,  0.0618,  0.0082,  0.0239,  0.0170,
          0.0104, -0.0341, -0.0675, -0.0120,  0.0912,  0.0783,  0.0384, -0.0993,
          0.0781, -0.0488, -0.0220, -0.0882,  0.0792,  0.0907,  0.0622, -0.0771,
          0.0474,  0.0566,  0.0652, -0.0781,  0.0890, -0.0738,  0.0342, -0.0918,
          0.0383, -0.0493, -0.0572],
        [ 0.0299, -0.0675, -0.0229, -0.0008, -0.0184, -0.0047,  0.0765,  0.0229,
          0.0708, -0.0735,  0.0328, -0.0595, -0.0305, -0.0092,  0.0902, -0.0695,
          0.0218, -0.0637,  0.0327,  0.0957,  0.0620,  0.0700, -0.0878, -0.0632,
          0.0783, -0.0145, -0.0077, -0.0812, -0.0896,  0.0644, -0.0993,  0.0056,
         -0.0672, -0.0534,  0.0743, -0.0861, -0.0496, -0.0842, -0.0650,  0.1003,
          0.0983, -0.0685, -0.0804,  0.0284, -0.0550,  0.0258,  0.0323,  0.0860,
          0.0305, -0.0618, -0.0474, -0.0514, -0.0991, -0.0888, -0.0107,  0.0264,
         -0.0018, -0.0143, -0.0971,  0.0311,  0.0874, -0.0879,  0.0108, -0.0926,
          0.0642,  0.0781,  0.0106, -0.0502, -0.0475,  0.0040,  0.0710,  0.0312,
          0.0026, -0.0985, -0.0467, -0.0735,  0.0045,  0.0028, -0.0726, -0.0421,
         -0.0940,  0.0451,  0.0559, -0.0831, -0.0864, -0.0363,  0.0879,  0.0718,
         -0.0932,  0.0028,  0.0085,  0.0346,  0.0757,  0.0285,  0.0981, -0.0531,
          0.0824, -0.0578,  0.0924],
        [-0.0584, -0.0218, -0.0404, -0.0525,  0.0481,  0.0281,  0.0231, -0.0282,
          0.0260,  0.0060,  0.0457,  0.0049, -0.0274, -0.0491, -0.0564,  0.0116,
         -0.0203, -0.0357,  0.0137, -0.0977,  0.1000, -0.0280,  0.0435,  0.0369,
         -0.0926, -0.0058, -0.0676,  0.0590,  0.0762, -0.0011,  0.0307, -0.0390,
         -0.0809,  0.0845, -0.0240,  0.0730,  0.0777,  0.0685,  0.0181,  0.0236,
          0.0567,  0.0858, -0.0525,  0.0933, -0.0656, -0.0018, -0.0724, -0.0334,
         -0.0105, -0.0091, -0.0875, -0.0785,  0.0389, -0.0028,  0.0261,  0.0452,
         -0.0424, -0.0661,  0.0507,  0.0736,  0.0803,  0.0264,  0.0092,  0.0121,
         -0.0560, -0.0963,  0.0253, -0.0437,  0.0986, -0.0876,  0.0892, -0.0746,
         -0.0182, -0.0654,  0.0459,  0.0577,  0.0660, -0.1004,  0.0503,  0.0362,
         -0.0458,  0.0493, -0.0048, -0.0600,  0.0032, -0.0931,  0.0297, -0.0781,
          0.0597,  0.0578,  0.0745, -0.0156,  0.0995,  0.0317,  0.0838,  0.0436,
          0.0980,  0.0659,  0.0434],
        [ 0.0377, -0.0440, -0.0828,  0.0892, -0.0532,  0.0972, -0.0224,  0.0297,
         -0.0346,  0.0897,  0.0576,  0.0473, -0.0151, -0.0024,  0.0901, -0.0447,
         -0.0040,  0.0816, -0.0640, -0.0382,  0.0032, -0.0789,  0.0431, -0.0942,
         -0.0280,  0.0860,  0.0133, -0.0673,  0.0529,  0.0088,  0.0927, -0.0999,
          0.0087,  0.0950, -0.0891, -0.0729,  0.0315,  0.0797, -0.0973, -0.0183,
         -0.0698, -0.0844,  0.0364, -0.0390,  0.0561,  0.0424,  0.0046,  0.0832,
         -0.0328,  0.0423,  0.0206, -0.0193,  0.0703,  0.0625, -0.0325,  0.0178,
          0.0911,  0.0230, -0.0331,  0.0732,  0.0688, -0.0737,  0.0454, -0.0087,
         -0.0379, -0.0031, -0.0867, -0.0454, -0.0439,  0.0892, -0.0156, -0.0649,
          0.0456,  0.0309, -0.0969,  0.0979,  0.0582,  0.0471,  0.0192,  0.0754,
          0.0476,  0.0536, -0.0570,  0.0574, -0.0742,  0.0819,  0.0101,  0.0497,
          0.0775, -0.0086, -0.0933, -0.0266, -0.0168, -0.0892, -0.0122,  0.0118,
         -0.0989,  0.0245,  0.0288]], requires_grad=True)

fc2.bias
Parameter containing:
tensor([ 0.0654,  0.0162, -0.0876, -0.0603,  0.0969,  0.0436,  0.0457, -0.0872,
        -0.0752,  0.0104], requires_grad=True)

In [31]:
nn.Sigmoid??

Init signature: nn.Sigmoid(*args, **kwargs) -> None
Source:
class Sigmoid(Module):
    r"""Applies the Sigmoid function element-wise.

    .. math::
        \text{Sigmoid}(x) = \sigma(x) = \frac{1}{1 + \exp(-x)}


    Shape:
        - Input: :math:`(*)`, where :math:`*` means any number of dimensions.
        - Output: :math:`(*)`, same shape as the input.

    .. image:: ../scripts/activation_images/Sigmoid.png

    Examples::

        >>> m = nn.Sigmoid()
        >>> input = torch.randn(2)
        >>> output = m(input)
    """

    def forward(self, input: Tensor) -> Tensor:
        return torch.sigmoid(input)
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/activation.py
Type:           type
Subclasses:     Sigmoid

$$\text{Sigmoid}(x) = \sigma(x) = \frac{1}{1 + \exp(-x)}$$

In [50]:
sigmoid_fn = nn.Sigmoid()
a = torch.randn(4,5)
out = sigmoid_fn(a)
print(out)

tensor([[0.8413, 0.2666, 0.2209, 0.4478, 0.2555],
        [0.3689, 0.5505, 0.6077, 0.3919, 0.6345],
        [0.8020, 0.8913, 0.8339, 0.1325, 0.5005],
        [0.6600, 0.3008, 0.6081, 0.3239, 0.4794]])

In [83]:
sig = nn.Sigmoid()
x = torch.arange(1,11, dtype=torch.float32).view(2,-1)
out = sig(x)
print(out)

tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])

In [105]:
sig = nn.Softmax()
x = torch.arange(100,200).reshape(10,-1)
out = sig(x.double())
print(out)

tensor([[7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01],
        [7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
         3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01]], dtype=torch.float64)

In [135]:
tanh_fn = nn.Tanh()
a = torch.randn(5,3)
out = tanh_fn(a)
print(a, out)

tensor([[-1.2553, -1.3892, -0.3123],
        [ 1.0924, -0.1668, -0.4186],
        [ 0.5846,  0.6687,  0.1507],
        [-0.5314, -0.2875,  0.4560],
        [ 1.2602,  1.0357, -0.1451]]) tensor([[-0.8498, -0.8830, -0.3025],
        [ 0.7977, -0.1653, -0.3957],
        [ 0.5260,  0.5842,  0.1495],
        [-0.4864, -0.2798,  0.4268],
        [ 0.8511,  0.7762, -0.1441]])

In [151]:
tanh = nn.Tanh()
data = torch.randn(4,5)
output = tanh(data)
display(data, output)

tensor([[-0.8751,  0.4436,  0.2700,  0.6443,  1.4003],
        [ 0.3759, -0.3399, -0.2924,  0.6470,  1.0304],
        [-1.6272, -1.5808,  0.1687,  1.2274, -0.2017],
        [-0.2560,  0.9555, -1.1243,  1.6118,  0.4275]])

tensor([[-0.7040,  0.4166,  0.2636,  0.5678,  0.8854],
        [ 0.3592, -0.3274, -0.2844,  0.5696,  0.7741],
        [-0.9257, -0.9187,  0.1671,  0.8418, -0.1990],
        [-0.2505,  0.7423, -0.8091,  0.9234,  0.4032]])

In [161]:
import torch
from torch import nn
from collections import OrderedDict
from torch.nn import functional as F

input_size = 567
hidden_size = 128
output_size = 10

model = nn.Sequential(
    nn.Linear(input_size, hidden_size),
    nn.ReLU(),
    nn.Linear(hidden_size, output_size)
)
# the problem is that weights and biases and each layers can be accessed with int indexes, which can be 
# hard for debugging, better assign names for each layers with OrderedDict
data = torch.randn(45, 567)
output = model(data)
print(f"Input: {data.shape}")
print(f"Output: {output.shape}")
for name, param in model.named_parameters():
    print(name, param.shape)

Input: torch.Size([45, 567])
Output: torch.Size([45, 10])
0.weight torch.Size([128, 567])
0.bias torch.Size([128])
2.weight torch.Size([10, 128])
2.bias torch.Size([10])

In [162]:
OrderedDict??

Init signature: OrderedDict(self, /, *args, **kwargs)
Source:
class OrderedDict(dict):
    'Dictionary that remembers insertion order'
    # An inherited dict maps keys to values.
    # The inherited dict provides __getitem__, __len__, __contains__, and get.
    # The remaining methods are order-aware.
    # Big-O running times for all methods are the same as regular dictionaries.

    # The internal self.__map dict maps keys to links in a doubly linked list.
    # The circular doubly linked list starts and ends with a sentinel element.
    # The sentinel element never gets deleted (this simplifies the algorithm).
    # The sentinel is in self.__hardroot with a weakref proxy in self.__root.
    # The prev links are weakref proxies (to prevent circular references).
    # Individual links are kept alive by the hard reference in self.__map.
    # Those hard references disappear when a key is deleted from an OrderedDict.

    def __init__(self, other=(), /, **kwds):
        '''Initialize an ordered dictionary.  The signature is the same as
        regular dictionaries.  Keyword argument order is preserved.
        '''
        try:
            self.__root
        except AttributeError:
            self.__hardroot = _Link()
            self.__root = root = _proxy(self.__hardroot)
            root.prev = root.next = root
            self.__map = {}
        self.__update(other, **kwds)

    def __setitem__(self, key, value,
                    dict_setitem=dict.__setitem__, proxy=_proxy, Link=_Link):
        'od.__setitem__(i, y) <==> od[i]=y'
        # Setting a new item creates a new link at the end of the linked list,
        # and the inherited dictionary is updated with the new key/value pair.
        if key not in self:
            self.__map[key] = link = Link()
            root = self.__root
            last = root.prev
            link.prev, link.next, link.key = last, root, key
            last.next = link
            root.prev = proxy(link)
        dict_setitem(self, key, value)

    def __delitem__(self, key, dict_delitem=dict.__delitem__):
        'od.__delitem__(y) <==> del od[y]'
        # Deleting an existing item uses self.__map to find the link which gets
        # removed by updating the links in the predecessor and successor nodes.
        dict_delitem(self, key)
        link = self.__map.pop(key)
        link_prev = link.prev
        link_next = link.next
        link_prev.next = link_next
        link_next.prev = link_prev
        link.prev = None
        link.next = None

    def __iter__(self):
        'od.__iter__() <==> iter(od)'
        # Traverse the linked list in order.
        root = self.__root
        curr = root.next
        while curr is not root:
            yield curr.key
            curr = curr.next

    def __reversed__(self):
        'od.__reversed__() <==> reversed(od)'
        # Traverse the linked list in reverse order.
        root = self.__root
        curr = root.prev
        while curr is not root:
            yield curr.key
            curr = curr.prev

    def clear(self):
        'od.clear() -> None.  Remove all items from od.'
        root = self.__root
        root.prev = root.next = root
        self.__map.clear()
        dict.clear(self)

    def popitem(self, last=True):
        '''Remove and return a (key, value) pair from the dictionary.

        Pairs are returned in LIFO order if last is true or FIFO order if false.
        '''
        if not self:
            raise KeyError('dictionary is empty')
        root = self.__root
        if last:
            link = root.prev
            link_prev = link.prev
            link_prev.next = root
            root.prev = link_prev
        else:
            link = root.next
            link_next = link.next
            root.next = link_next
            link_next.prev = root
        key = link.key
        del self.__map[key]
        value = dict.pop(self, key)
        return key, value

    def move_to_end(self, key, last=True):
        '''Move an existing element to the end (or beginning if last is false).

        Raise KeyError if the element does not exist.
        '''
        link = self.__map[key]
        link_prev = link.prev
        link_next = link.next
        soft_link = link_next.prev
        link_prev.next = link_next
        link_next.prev = link_prev
        root = self.__root
        if last:
            last = root.prev
            link.prev = last
            link.next = root
            root.prev = soft_link
            last.next = link
        else:
            first = root.next
            link.prev = root
            link.next = first
            first.prev = soft_link
            root.next = link

    def __sizeof__(self):
        sizeof = _sys.getsizeof
        n = len(self) + 1                       # number of links including root
        size = sizeof(self.__dict__)            # instance dictionary
        size += sizeof(self.__map) * 2          # internal dict and inherited dict
        size += sizeof(self.__hardroot) * n     # link objects
        size += sizeof(self.__root) * n         # proxy objects
        return size

    update = __update = _collections_abc.MutableMapping.update

    def keys(self):
        "D.keys() -> a set-like object providing a view on D's keys"
        return _OrderedDictKeysView(self)

    def items(self):
        "D.items() -> a set-like object providing a view on D's items"
        return _OrderedDictItemsView(self)

    def values(self):
        "D.values() -> an object providing a view on D's values"
        return _OrderedDictValuesView(self)

    __ne__ = _collections_abc.MutableMapping.__ne__

    __marker = object()

    def pop(self, key, default=__marker):
        '''od.pop(k[,d]) -> v, remove specified key and return the corresponding
        value.  If key is not found, d is returned if given, otherwise KeyError
        is raised.

        '''
        if key in self:
            result = self[key]
            del self[key]
            return result
        if default is self.__marker:
            raise KeyError(key)
        return default

    def setdefault(self, key, default=None):
        '''Insert key with a value of default if key is not in the dictionary.

        Return the value for key if key is in the dictionary, else default.
        '''
        if key in self:
            return self[key]
        self[key] = default
        return default

    @_recursive_repr()
    def __repr__(self):
        'od.__repr__() <==> repr(od)'
        if not self:
            return '%s()' % (self.__class__.__name__,)
        return '%s(%r)' % (self.__class__.__name__, list(self.items()))

    def __reduce__(self):
        'Return state information for pickling'
        inst_dict = vars(self).copy()
        for k in vars(OrderedDict()):
            inst_dict.pop(k, None)
        return self.__class__, (), inst_dict or None, None, iter(self.items())

    def copy(self):
        'od.copy() -> a shallow copy of od'
        return self.__class__(self)

    @classmethod
    def fromkeys(cls, iterable, value=None):
        '''Create a new ordered dictionary with keys from iterable and values set to value.
        '''
        self = cls()
        for key in iterable:
            self[key] = value
        return self

    def __eq__(self, other):
        '''od.__eq__(y) <==> od==y.  Comparison to another OD is order-sensitive
        while comparison to a regular mapping is order-insensitive.

        '''
        if isinstance(other, OrderedDict):
            return dict.__eq__(self, other) and all(map(_eq, self, other))
        return dict.__eq__(self, other)

    def __ior__(self, other):
        self.update(other)
        return self

    def __or__(self, other):
        if not isinstance(other, dict):
            return NotImplemented
        new = self.__class__(self)
        new.update(other)
        return new

    def __ror__(self, other):
        if not isinstance(other, dict):
            return NotImplemented
        new = self.__class__(other)
        new.update(self)
        return new
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/collections/__init__.py
Type:           type
Subclasses:

In [170]:
from collections import OrderedDict

input_size = 782
hidden_size = 64
output_size= 13

model_v2 = nn.Sequential(OrderedDict([
    ('fc1', nn.Linear(input_size, hidden_size)),
    ('relu', nn.ReLU()),
    ('fc2', nn.Linear(hidden_size, output_size))
]))
# OrderedDict from python collections, we can access given layers and corresponding weights and biases
# without indexes but rather with intuitive names
data = torch.randn(56, input_size)
output = model_v2(data)
print(f"Model parameters shape: {model_v2.fc1.weight.shape}, {model_v2.fc2.bias.shape}")

Model parameters shape: torch.Size([64, 782]), torch.Size([13])

In [184]:
import torch
from torch import nn
from collections import OrderedDict

# unlike nn.Module where when defining the layers/activation functions in the constructor
# assigning as the attributes of the model, the order did not matter, because we were specifying the order
# inside of the forward function, but for models where output of one function directly goes to the 
# input of another, without having any skips or changing directions, then we can use
# nn.Sequential without having to define forward function
# we simply pass as arguments the submodules (layers/activation functions), and their order matters
# we are both defining the layers and how the data will flow through the layers, sequentially
# one after another

model_v4 = nn.Sequential(OrderedDict([
    ("layer1", nn.Linear(600, 300)),
    ("relu", nn.ReLU()),
    ("layer2", nn.Linear(300, 10))
]))

data = torch.randn(56, 600)
output =  model_v4(data)
print(f"Model parameters: {model_v4.layer1}, {model_v4.relu}\n,{model_v4.layer2}")
display(model_v4.layer1.weight, model_v4.layer1.weight.shape, model_v4.layer1.bias, model_v4.layer1.bias.shape)
display(model_v4.relu, model_v4.layer2, model_v4.layer2.weight, model_v4.layer2.weight.shape)
display(model_v4.layer2.bias, model_v4.layer2.bias.shape)

Model parameters: Linear(in_features=600, out_features=300, bias=True), ReLU()
,Linear(in_features=300, out_features=10, bias=True)

Parameter containing:
tensor([[-0.0175,  0.0137, -0.0230,  ...,  0.0202, -0.0355, -0.0203],
        [-0.0282,  0.0266, -0.0140,  ...,  0.0200, -0.0021,  0.0129],
        [ 0.0206, -0.0360, -0.0055,  ...,  0.0149,  0.0388,  0.0267],
        ...,
        [-0.0320,  0.0116,  0.0202,  ..., -0.0082,  0.0236, -0.0013],
        [ 0.0399, -0.0038,  0.0194,  ..., -0.0357,  0.0204,  0.0200],
        [ 0.0293, -0.0382,  0.0241,  ..., -0.0038,  0.0085,  0.0268]],
       requires_grad=True)

torch.Size([300, 600])

Parameter containing:
tensor([ 0.0407,  0.0016,  0.0061,  0.0033,  0.0151, -0.0386,  0.0227,  0.0004,
        -0.0276, -0.0212, -0.0076, -0.0070, -0.0091, -0.0305,  0.0292, -0.0238,
         0.0175, -0.0004,  0.0272, -0.0396,  0.0341, -0.0369,  0.0021, -0.0032,
         0.0231,  0.0405,  0.0187,  0.0010, -0.0161,  0.0270,  0.0404,  0.0300,
         0.0334, -0.0144,  0.0341, -0.0218, -0.0230, -0.0213, -0.0049,  0.0231,
         0.0051,  0.0066,  0.0106,  0.0304,  0.0389,  0.0275, -0.0275,  0.0369,
         0.0250,  0.0208,  0.0209,  0.0171,  0.0242,  0.0399,  0.0315, -0.0403,
        -0.0076,  0.0277,  0.0279, -0.0378,  0.0012,  0.0350,  0.0200, -0.0236,
        -0.0115,  0.0201, -0.0264,  0.0037,  0.0399, -0.0333, -0.0042,  0.0247,
        -0.0237, -0.0106,  0.0349,  0.0341,  0.0198, -0.0122, -0.0057,  0.0101,
        -0.0169,  0.0056,  0.0339, -0.0279,  0.0330, -0.0162,  0.0041, -0.0198,
        -0.0162,  0.0022, -0.0197,  0.0035,  0.0359,  0.0387, -0.0316,  0.0015,
        -0.0108, -0.0310, -0.0124, -0.0287, -0.0165,  0.0084,  0.0295,  0.0182,
        -0.0283,  0.0050,  0.0315,  0.0034, -0.0372, -0.0106, -0.0358, -0.0178,
        -0.0181,  0.0141,  0.0154,  0.0193,  0.0400,  0.0236,  0.0084,  0.0239,
        -0.0288,  0.0217, -0.0093, -0.0369,  0.0090,  0.0295, -0.0270, -0.0022,
         0.0081, -0.0254,  0.0139, -0.0248, -0.0399, -0.0199,  0.0296, -0.0103,
        -0.0364, -0.0372, -0.0057, -0.0138,  0.0400, -0.0243, -0.0178,  0.0176,
        -0.0160,  0.0324, -0.0136,  0.0269,  0.0125, -0.0105,  0.0055,  0.0146,
         0.0116, -0.0133, -0.0121,  0.0242,  0.0137, -0.0132,  0.0156,  0.0231,
        -0.0137, -0.0391, -0.0209, -0.0099,  0.0188, -0.0284,  0.0339, -0.0363,
        -0.0033, -0.0378, -0.0028,  0.0222, -0.0281, -0.0247, -0.0082, -0.0181,
        -0.0321, -0.0400, -0.0138,  0.0396,  0.0171, -0.0058, -0.0221,  0.0316,
         0.0181,  0.0199,  0.0388, -0.0148,  0.0329, -0.0370, -0.0203,  0.0176,
         0.0313, -0.0099,  0.0193, -0.0201,  0.0281,  0.0172, -0.0113,  0.0287,
         0.0158, -0.0326,  0.0394,  0.0301, -0.0087,  0.0131, -0.0085,  0.0158,
        -0.0300, -0.0260,  0.0065,  0.0042, -0.0278, -0.0056,  0.0310, -0.0200,
        -0.0273, -0.0316, -0.0162,  0.0159,  0.0143, -0.0074,  0.0155, -0.0158,
        -0.0081,  0.0233,  0.0394,  0.0131, -0.0211, -0.0364, -0.0019, -0.0322,
        -0.0034, -0.0084, -0.0254,  0.0036,  0.0300,  0.0396, -0.0096,  0.0013,
        -0.0194,  0.0220, -0.0121, -0.0030,  0.0338, -0.0069, -0.0319,  0.0075,
         0.0385, -0.0407, -0.0003, -0.0210,  0.0331,  0.0168,  0.0028,  0.0388,
        -0.0402, -0.0014, -0.0379,  0.0358, -0.0203,  0.0326,  0.0352,  0.0040,
        -0.0290,  0.0177,  0.0047,  0.0096,  0.0019, -0.0040,  0.0254,  0.0234,
         0.0128,  0.0173, -0.0034,  0.0155,  0.0165, -0.0047,  0.0265, -0.0012,
        -0.0405,  0.0026,  0.0055, -0.0360,  0.0245,  0.0343, -0.0069, -0.0096,
        -0.0288, -0.0094,  0.0154, -0.0285, -0.0307, -0.0105,  0.0299, -0.0180,
        -0.0298,  0.0225,  0.0349,  0.0072], requires_grad=True)

torch.Size([300])

ReLU()

Linear(in_features=300, out_features=10, bias=True)

Parameter containing:
tensor([[ 0.0412,  0.0139, -0.0110,  ...,  0.0027, -0.0018,  0.0428],
        [ 0.0538,  0.0253, -0.0577,  ..., -0.0107, -0.0512, -0.0273],
        [ 0.0269,  0.0497,  0.0056,  ..., -0.0018,  0.0068, -0.0007],
        ...,
        [ 0.0564,  0.0095, -0.0552,  ...,  0.0101, -0.0048,  0.0051],
        [-0.0217,  0.0099,  0.0156,  ..., -0.0221,  0.0190,  0.0185],
        [ 0.0248, -0.0280, -0.0562,  ..., -0.0362,  0.0295, -0.0189]],
       requires_grad=True)

torch.Size([10, 300])

Parameter containing:
tensor([ 0.0325,  0.0295, -0.0543,  0.0170,  0.0010,  0.0235, -0.0474,  0.0253,
         0.0096,  0.0366], requires_grad=True)

torch.Size([10])

In [2]:
import torch
from torch import nn
from collections import OrderedDict

# one of the applications of the nn.Sequential is creating a reusable blocks of code
# for data to go through given functions defined in nn.Sequential in the sequential order
# without skipping or branching, and reuse this block of code inside of the more complex
# model inside of custom nn.Module structure

# Also used for feed-forward networks, where output of one functions directly goes to the
# input of the following functions, without skipping or branching and the order is important
# nn.Sequential has a linear nature, meaning functions are defined one next to the other
# in the linear fashion and must go through each of them sequentially or linearly
# Also, this nn.Sequential only assumed that there is a single input and a single output
# meaning more than one input tensor will not fit here

model = nn.Sequential(OrderedDict([
    ("fc1", nn.Linear(748, 345)),
    ("relu", nn.ReLU()),
    ("fc2", nn.Linear(345, 12))
]))
data = torch.randn(34,748)
output = model(data)
display(model.fc1.weight.shape, model.fc1.bias.shape, model.relu, model.fc2.weight.shape, model.fc2.bias.shape)

torch.Size([345, 748])

torch.Size([345])

ReLU()

torch.Size([12, 345])

torch.Size([12])

In [188]:
# nn.Sequential layers and containing weights and biases can be accessed with indexing
# but this approach is not practical, therefore it is better to assign names
# for each layer with OrderedDict, then we can get respective weights and biases on need

$$\ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
        l_n = \left( x_n - y_n \right)^2$$

In [65]:
import torch
from torch import nn

loss_fn = nn.MSELoss() # or also referred as L2Loss

predictions = torch.randn(3,4, requires_grad=True)
labels = torch.randn(3,4)

loss = loss_fn(predictions, labels)
print(f"Loss value: {loss.item()}")

Loss value: 2.819516181945801

$$\ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
    l_n = \left| x_n - y_n \right|$$

In [60]:
# Also there is Mean Absolute Error, also known as L1Loss
loss_fn = nn.L1Loss()

prediction = torch.rand(3,5, requires_grad=True)
target = torch.rand(3,5)
loss = loss_fn(prediction, target)
print(f"Loss value: {loss.item()}")

Loss value: 0.38298141956329346

In [3]:
# Mean Squared Error (L1Loss) and Mean Absolute Error (L2Loss), are mostly used
# for regression tasks where the objective is to output a continuous value
# for Classification tasks we use classification loss such as Cross Entropy Loss

criterion_L1 = nn.MSELoss()
criterion_L2 = nn.L1Loss()

outputs = nn.Parameter(torch.randn(4,5, requires_grad=True))
labels = torch.randn(4,5)
l2_loss = criterion_L2(outputs, labels)
l1_loss = criterion_L1(outputs, labels)
print(f"MSELoss(L2 loss): {l1_loss.item()}, L1Loss: {l2_loss.item()}")

MSELoss(L2 loss): 1.6080474853515625, L1Loss: 0.9996082186698914

In [4]:
# Mean Squared Error penilizes errors more harshly by giving much higher losses compared to Mean Absolute Error
# hence MSELoss is very sensitive to outliers, while L1Loss is not so much
# MSELoss will try to move a line closer to outlier data point even if it means to shift away from the 
# most of the data points, while L1Loss will generally stay where the most of the data points are
# and only sligthly move towards outlier, but not as much as L2loss
# again MSE and MAE are used for regression tasks where we want to predict a continuous value

# Cross Entropy Loss is for multi-class classifications where in each sample out of all classess
# there is only one correct class, and it cannot belong to several classes at the same time
# For sign language, in our case there are 100 classes and each signed word can belong to only a single
# class word, even though it is true that one sign can mean two or more different things
# based on context, for simplicity we can relax this assumption, and say that each signed word
# belongs to only a single class word

$$\ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
          l_n = - w_{y_n} \log \frac{\exp(x_{n,y_n})}{\sum_{c=1}^C \exp(x_{n,c})}
          \cdot \mathbb{1}\{y_n \not= \text{ignore\_index}\}$$

In [33]:
cross_loss = nn.CrossEntropyLoss()
output = torch.randn(3,5, requires_grad=True)
target = torch.tensor([1,4,2])
loss = cross_loss(output, target)
print(f"Cross Entropy Loss (Multi-class) classification loss: {loss.item()}")

Cross Entropy Loss (Multi-class) classification loss: 1.587830662727356

In [41]:
categorical_loss = nn.CrossEntropyLoss()
output = torch.randn(5, 10, requires_grad=True)
label = torch.arange(5)
loss = categorical_loss(output, label)
print(f"Categorical CrossEntropyLoss: {loss.item()}")

Categorical CrossEntropyLoss: 2.5165951251983643

In [53]:
categorical_loss = nn.CrossEntropyLoss()
# batch size of 7(rows), and 10(columns) input features
output = torch.randn(7, 10, requires_grad=True)
label = torch.tensor([1,0,5,6,5,8,9])
loss = categorical_loss(output, label)
print(f"Categorical Cross Entropy Loss: {loss.item()}")

Categorical Cross Entropy Loss: 2.789682388305664

In [54]:
# the total number of values in the label/target output must match
# with the batch size, and the number of classes must range between 0-(C-1) 
# where C is the total number of classes
# nn.CrossEntropyLoss() is for multi-class classification where 
# each object/data_point belongs to only a single class out of N-classes
# if each data_point/object can belong to more than one class at the same time
# then use Binary Cross Entropy Loss
# for CrossEntropyLoss since there are many classes, we assign integer values

In [70]:
categorical_cross_loss = nn.CrossEntropyLoss()
output = torch.randn(5,10, requires_grad=True)
# the number of values inside of the target label, must match the batch size
# and the individual number values can range between 0-(C-1)
label = torch.tensor([4,1,1,3,7])
loss = categorical_cross_loss(output, label)
print(f"Categorical Loss: {loss.item()}")

Categorical Loss: 3.179534912109375

In [2]:
# nn.BCELoss expects the model outputs to be already probabilites
# meaning before passing outputs to nn.BCELoss, we have to apply sigmoid function
# to squeeze the output ranges from 0 to 1, and then pass these outputs to nn.BCELoss
# however, for nn.BCEWithLogitsLoss, the sigmoid is done automatically
# meaning we can pass the raw model outputs(logits) to the nn.BCEWithLogitsLoss()
# and it will provide loss, and one more thing, the target labels
# individual value range must be either 0 or 1, and nothing more
# because a given data points either belongs to certain class, as 1 if ti does or not which is defined as 0
# and the shape of target labels must be the same as the model outputs

bce_loss = nn.BCELoss()
output = torch.randn(3,4, requires_grad=True)
output = torch.sigmoid(output) # squeezes output in the range of 0 and 1
target_label = torch.tensor([[1.0,1.0,0.0,1.0],[1.0,1.0,0.0,0.0],[1.0,1.0,1.0,0.0]])
loss = bce_loss(output, target_label)
print(f"Binary Cross Entropy Loss: {loss.item()}")

Binary Cross Entropy Loss: 0.7762537002563477

In [15]:
# BCELoss expects the output to be in probability format in the range of 0-1
# hence need to use Sigmoid in order to squeeze the output into range of 0-1
binary_loss = nn.BCELoss()

output = torch.randn(3,4, requires_grad=True)
output = torch.sigmoid(output)
label = torch.tensor([[1,0,0,1],[1,0,1,1],[0,1,1,0]], dtype=torch.float32)

loss = binary_loss(output, label)
print(f"Binary Cross Entropy Loss: {loss}")

Binary Cross Entropy Loss: 0.8383407592773438

In [20]:
# nn.BCEWithLogitsLoss() automatically applies sigmoid function
# to the raw output(logits) of the model, so no need to use sigmoid explicitly
binary_loss = nn.BCEWithLogitsLoss()

output = torch.randn(4,5, requires_grad=True)
label = torch.ones(4,5)

loss = binary_loss(output, label)
print(f"Binary Cross Entropy Loss with Logits: {loss.item()}")

Binary Cross Entropy Loss with Logits: 0.5449265241622925

In [21]:
nn.BCEWithLogitsLoss??

Init signature:
nn.BCEWithLogitsLoss(
    weight: Optional[torch.Tensor] = None,
    size_average=None,
    reduce=None,
    reduction: str = 'mean',
    pos_weight: Optional[torch.Tensor] = None,
) -> None
Source:
class BCEWithLogitsLoss(_Loss):
    r"""This loss combines a `Sigmoid` layer and the `BCELoss` in one single
    class. This version is more numerically stable than using a plain `Sigmoid`
    followed by a `BCELoss` as, by combining the operations into one layer,
    we take advantage of the log-sum-exp trick for numerical stability.

    The unreduced (i.e. with :attr:`reduction` set to ``'none'``) loss can be described as:

    .. math::
        \ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
        l_n = - w_n \left[ y_n \cdot \log \sigma(x_n)
        + (1 - y_n) \cdot \log (1 - \sigma(x_n)) \right],

    where :math:`N` is the batch size. If :attr:`reduction` is not ``'none'``
    (default ``'mean'``), then

    .. math::
        \ell(x, y) = \begin{cases}
            \operatorname{mean}(L), & \text{if reduction} = \text{`mean';}\\
            \operatorname{sum}(L),  & \text{if reduction} = \text{`sum'.}
        \end{cases}

    This is used for measuring the error of a reconstruction in for example
    an auto-encoder. Note that the targets `t[i]` should be numbers
    between 0 and 1.

    It's possible to trade off recall and precision by adding weights to positive examples.
    In the case of multi-label classification the loss can be described as:

    .. math::
        \ell_c(x, y) = L_c = \{l_{1,c},\dots,l_{N,c}\}^\top, \quad
        l_{n,c} = - w_{n,c} \left[ p_c y_{n,c} \cdot \log \sigma(x_{n,c})
        + (1 - y_{n,c}) \cdot \log (1 - \sigma(x_{n,c})) \right],

    where :math:`c` is the class number (:math:`c > 1` for multi-label binary classification,
    :math:`c = 1` for single-label binary classification),
    :math:`n` is the number of the sample in the batch and
    :math:`p_c` is the weight of the positive answer for the class :math:`c`.

    :math:`p_c > 1` increases the recall, :math:`p_c < 1` increases the precision.

    For example, if a dataset contains 100 positive and 300 negative examples of a single class,
    then ``pos_weight`` for the class should be equal to :math:`\frac{300}{100}=3`.
    The loss would act as if the dataset contains :math:`3\times 100=300` positive examples.

    Examples::

        >>> target = torch.ones([10, 64], dtype=torch.float32)  # 64 classes, batch size = 10
        >>> output = torch.full([10, 64], 1.5)  # A prediction (logit)
        >>> pos_weight = torch.ones([64])  # All weights are equal to 1
        >>> criterion = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)
        >>> criterion(output, target)  # -log(sigmoid(1.5))
        tensor(0.20...)

    In the above example, the ``pos_weight`` tensor's elements correspond to the 64 distinct classes
    in a multi-label binary classification scenario. Each element in ``pos_weight`` is designed to adjust the
    loss function based on the imbalance between negative and positive samples for the respective class.
    This approach is useful in datasets with varying levels of class imbalance, ensuring that the loss
    calculation accurately accounts for the distribution in each class.

    Args:
        weight (Tensor, optional): a manual rescaling weight given to the loss
            of each batch element. If given, has to be a Tensor of size `nbatch`.
        size_average (bool, optional): Deprecated (see :attr:`reduction`). By default,
            the losses are averaged over each loss element in the batch. Note that for
            some losses, there are multiple elements per sample. If the field :attr:`size_average`
            is set to ``False``, the losses are instead summed for each minibatch. Ignored
            when :attr:`reduce` is ``False``. Default: ``True``
        reduce (bool, optional): Deprecated (see :attr:`reduction`). By default, the
            losses are averaged or summed over observations for each minibatch depending
            on :attr:`size_average`. When :attr:`reduce` is ``False``, returns a loss per
            batch element instead and ignores :attr:`size_average`. Default: ``True``
        reduction (str, optional): Specifies the reduction to apply to the output:
            ``'none'`` | ``'mean'`` | ``'sum'``. ``'none'``: no reduction will be applied,
            ``'mean'``: the sum of the output will be divided by the number of
            elements in the output, ``'sum'``: the output will be summed. Note: :attr:`size_average`
            and :attr:`reduce` are in the process of being deprecated, and in the meantime,
            specifying either of those two args will override :attr:`reduction`. Default: ``'mean'``
        pos_weight (Tensor, optional): a weight of positive examples to be broadcasted with target.
            Must be a tensor with equal size along the class dimension to the number of classes.
            Pay close attention to PyTorch's broadcasting semantics in order to achieve the desired
            operations. For a target of size [B, C, H, W] (where B is batch size) pos_weight of
            size [B, C, H, W] will apply different pos_weights to each element of the batch or
            [C, H, W] the same pos_weights across the batch. To apply the same positive weight
            along all spacial dimensions for a 2D multi-class target [C, H, W] use: [C, 1, 1].
            Default: ``None``

    Shape:
        - Input: :math:`(*)`, where :math:`*` means any number of dimensions.
        - Target: :math:`(*)`, same shape as the input.
        - Output: scalar. If :attr:`reduction` is ``'none'``, then :math:`(*)`, same
          shape as input.

     Examples::

        >>> loss = nn.BCEWithLogitsLoss()
        >>> input = torch.randn(3, requires_grad=True)
        >>> target = torch.empty(3).random_(2)
        >>> output = loss(input, target)
        >>> output.backward()
    """

    def __init__(
        self,
        weight: Optional[Tensor] = None,
        size_average=None,
        reduce=None,
        reduction: str = "mean",
        pos_weight: Optional[Tensor] = None,
    ) -> None:
        super().__init__(size_average, reduce, reduction)
        self.register_buffer("weight", weight)
        self.register_buffer("pos_weight", pos_weight)
        self.weight: Optional[Tensor]
        self.pos_weight: Optional[Tensor]

    def forward(self, input: Tensor, target: Tensor) -> Tensor:
        return F.binary_cross_entropy_with_logits(
            input,
            target,
            self.weight,
            pos_weight=self.pos_weight,
            reduction=self.reduction,
        )
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/nn/modules/loss.py
Type:           type
Subclasses:

In [53]:
# The target label must have the same shape as the output of the mode
# nn.BCELoss() requires the output to be in the range of 0-1, hence use torch.sigmoid before passing
# output to BCELoss()
# nn.BCEWithLogitsLoss() applies sigmoid automatically to the raw output logits
binary_loss = nn.BCEWithLogitsLoss()

output = torch.randn(4,6, requires_grad=True)
# the target label must be either 0 or 1
label = torch.zeros(4,6)

loss = binary_loss(output, label)
print(f"Binary Cross Entropy Loss: {loss.item()}")

Binary Cross Entropy Loss: 1.0016568899154663

In [54]:
from torch import optim

optim.SGD??

Init signature:
optim.SGD(
    params,
    lr: Union[float, torch.Tensor] = 0.001,
    momentum: float = 0,
    dampening: float = 0,
    weight_decay: float = 0,
    nesterov=False,
    *,
    maximize: bool = False,
    foreach: Optional[bool] = None,
    differentiable: bool = False,
    fused: Optional[bool] = None,
)
Docstring:
Implements stochastic gradient descent (optionally with momentum).

.. math::
   \begin{aligned}
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{input}      : \gamma \text{ (lr)}, \: \theta_0 \text{ (params)}, \: f(\theta)
            \text{ (objective)}, \: \lambda \text{ (weight decay)},                          \\
        &\hspace{13mm} \:\mu \text{ (momentum)}, \:\tau \text{ (dampening)},
        \:\textit{ nesterov,}\:\textit{ maximize}                                     \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{for} \: t=1 \: \textbf{to} \: \ldots \: \textbf{do}                         \\
        &\hspace{5mm}g_t           \leftarrow   \nabla_{\theta} f_t (\theta_{t-1})           \\
        &\hspace{5mm}\textbf{if} \: \lambda \neq 0                                           \\
        &\hspace{10mm} g_t \leftarrow g_t + \lambda  \theta_{t-1}                            \\
        &\hspace{5mm}\textbf{if} \: \mu \neq 0                                               \\
        &\hspace{10mm}\textbf{if} \: t > 1                                                   \\
        &\hspace{15mm} \textbf{b}_t \leftarrow \mu \textbf{b}_{t-1} + (1-\tau) g_t           \\
        &\hspace{10mm}\textbf{else}                                                          \\
        &\hspace{15mm} \textbf{b}_t \leftarrow g_t                                           \\
        &\hspace{10mm}\textbf{if} \: \textit{nesterov}                                       \\
        &\hspace{15mm} g_t \leftarrow g_{t} + \mu \textbf{b}_t                             \\
        &\hspace{10mm}\textbf{else}                                                   \\[-1.ex]
        &\hspace{15mm} g_t  \leftarrow  \textbf{b}_t                                         \\
        &\hspace{5mm}\textbf{if} \: \textit{maximize}                                          \\
        &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} + \gamma g_t                   \\[-1.ex]
        &\hspace{5mm}\textbf{else}                                                    \\[-1.ex]
        &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} - \gamma g_t                   \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
        &\bf{return} \:  \theta_t                                                     \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
   \end{aligned}

Nesterov momentum is based on the formula from
`On the importance of initialization and momentum in deep learning`__.

Args:
    params (iterable): iterable of parameters to optimize or dicts defining
        parameter groups
    lr (float, Tensor, optional): learning rate (default: 1e-3)
    momentum (float, optional): momentum factor (default: 0)
    weight_decay (float, optional): weight decay (L2 penalty) (default: 0)
    dampening (float, optional): dampening for momentum (default: 0)
    nesterov (bool, optional): enables Nesterov momentum (default: False)
    maximize (bool, optional): maximize the objective with respect to the
        params, instead of minimizing (default: False)
    foreach (bool, optional): whether foreach implementation of optimizer
        is used. If unspecified by the user (so foreach is None), we will try to use
        foreach over the for-loop implementation on CUDA, since it is usually
        significantly more performant. Note that the foreach implementation uses
        ~ sizeof(params) more peak memory than the for-loop version due to the intermediates
        being a tensorlist vs just one tensor. If memory is prohibitive, batch fewer
        parameters through the optimizer at a time or switch this flag to False (default: None)
    differentiable (bool, optional): whether autograd should
        occur through the optimizer step in training. Otherwise, the step()
        function runs in a torch.no_grad() context. Setting to True can impair
        performance, so leave it False if you don't intend to run autograd
        through this instance (default: False)
    fused (bool, optional): whether the fused implementation is used.
        Currently, `torch.float64`, `torch.float32`, `torch.float16`, and `torch.bfloat16`
        are supported. (default: None)

.. note:: The foreach and fused implementations are typically faster than the for-loop,
          single-tensor implementation, with fused being theoretically fastest with both
          vertical and horizontal fusion. As such, if the user has not specified either
          flag (i.e., when foreach = fused = None), we will attempt defaulting to the foreach
          implementation when the tensors are all on CUDA. Why not fused? Since the fused
          implementation is relatively new, we want to give it sufficient bake-in time.
          To specify fused, pass True for fused. To force running the for-loop
          implementation, pass False for either foreach or fused.


Example:
    >>> # xdoctest: +SKIP
    >>> optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
    >>> optimizer.zero_grad()
    >>> loss_fn(model(input), target).backward()
    >>> optimizer.step()

__ http://www.cs.toronto.edu/%7Ehinton/absps/momentum.pdf

.. note::
    The implementation of SGD with Momentum/Nesterov subtly differs from
    Sutskever et al. and implementations in some other frameworks.

    Considering the specific case of Momentum, the update can be written as

    .. math::
        \begin{aligned}
            v_{t+1} & = \mu * v_{t} + g_{t+1}, \\
            p_{t+1} & = p_{t} - \text{lr} * v_{t+1},
        \end{aligned}

    where :math:`p`, :math:`g`, :math:`v` and :math:`\mu` denote the
    parameters, gradient, velocity, and momentum respectively.

    This is in contrast to Sutskever et al. and
    other frameworks which employ an update of the form

    .. math::
        \begin{aligned}
            v_{t+1} & = \mu * v_{t} + \text{lr} * g_{t+1}, \\
            p_{t+1} & = p_{t} - v_{t+1}.
        \end{aligned}

    The Nesterov version is analogously modified.

    Moreover, the initial value of the momentum buffer is set to the
    gradient value at the first step. This is in contrast to some other
    frameworks that initialize it to all zeros.
Source:
class SGD(Optimizer):  # noqa: D101
    def __init__(
        self,
        params,
        lr: Union[float, Tensor] = 1e-3,
        momentum: float = 0,
        dampening: float = 0,
        weight_decay: float = 0,
        nesterov=False,
        *,
        maximize: bool = False,
        foreach: Optional[bool] = None,
        differentiable: bool = False,
        fused: Optional[bool] = None,
    ):  # noqa: D107
        if isinstance(lr, Tensor) and lr.numel() != 1:
            raise ValueError("Tensor lr must be 1-element")
        if lr < 0.0:
            raise ValueError(f"Invalid learning rate: {lr}")
        if momentum < 0.0:
            raise ValueError(f"Invalid momentum value: {momentum}")
        if weight_decay < 0.0:
            raise ValueError(f"Invalid weight_decay value: {weight_decay}")

        defaults = dict(
            lr=lr,
            momentum=momentum,
            dampening=dampening,
            weight_decay=weight_decay,
            nesterov=nesterov,
            maximize=maximize,
            foreach=foreach,
            differentiable=differentiable,
            fused=fused,
        )
        if nesterov and (momentum <= 0 or dampening != 0):
            raise ValueError("Nesterov momentum requires a momentum and zero dampening")
        super().__init__(params, defaults)

        if fused:
            self._step_supports_amp_scaling = True
            self._need_device_dtype_check_for_fused = True
            if differentiable:
                raise RuntimeError("`fused` does not support `differentiable`")
            if foreach:
                raise RuntimeError("`fused` and `foreach` cannot be `True` together.")

    def __setstate__(self, state):  # noqa: D105
        super().__setstate__(state)
        for group in self.param_groups:
            group.setdefault("nesterov", False)
            group.setdefault("maximize", False)
            group.setdefault("foreach", None)
            group.setdefault("differentiable", False)
            group.setdefault("fused", False)

    def _init_group(self, group, params, grads, momentum_buffer_list):
        has_sparse_grad = False

        for p in group["params"]:
            if p.grad is not None:
                if group["fused"] and getattr(
                    self, "_need_device_dtype_check_for_fused", True
                ):
                    _device_dtype_check_for_fused(p)
                    self._need_device_dtype_check_for_fused = False
                params.append(p)
                grads.append(p.grad)
                if p.grad.is_sparse:
                    has_sparse_grad = True

                if group["momentum"] != 0:
                    state = self.state[p]
                    momentum_buffer_list.append(state.get("momentum_buffer"))

        return has_sparse_grad

    @_use_grad_for_differentiable
    def step(self, closure=None):
        """Perform a single optimization step.

        Args:
            closure (Callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            params: List[Tensor] = []
            grads: List[Tensor] = []
            momentum_buffer_list: List[Optional[Tensor]] = []

            has_sparse_grad = self._init_group(
                group, params, grads, momentum_buffer_list
            )

            sgd(
                params,
                grads,
                momentum_buffer_list,
                weight_decay=group["weight_decay"],
                momentum=group["momentum"],
                lr=group["lr"],
                dampening=group["dampening"],
                nesterov=group["nesterov"],
                maximize=group["maximize"],
                has_sparse_grad=has_sparse_grad,
                foreach=group["foreach"],
                fused=group["fused"],
                grad_scale=getattr(self, "grad_scale", None),
                found_inf=getattr(self, "found_inf", None),
            )

            if group["momentum"] != 0:
                # update momentum_buffers in state
                for p, momentum_buffer in zip(params, momentum_buffer_list):
                    state = self.state[p]
                    state["momentum_buffer"] = momentum_buffer

        return loss
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/optim/sgd.py
Type:           type
Subclasses:

In [11]:
from torch import optim

optimizer = optim.SGD(model.parameters(), lr=0.01)
optimizer = optim.Adam(model.parameters(), lr=0.001)

# They are the variant of gradient descent
# they update the actual weights and biases based on the calculated gradients/derivatives
# of the loss with respect to all parameters(weights, biases)

In [12]:
optim.SGD?

Init signature:
optim.SGD(
    params,
    lr: Union[float, torch.Tensor] = 0.001,
    momentum: float = 0,
    dampening: float = 0,
    weight_decay: float = 0,
    nesterov=False,
    *,
    maximize: bool = False,
    foreach: Optional[bool] = None,
    differentiable: bool = False,
    fused: Optional[bool] = None,
)
Docstring:
Implements stochastic gradient descent (optionally with momentum).

.. math::
   \begin{aligned}
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{input}      : \gamma \text{ (lr)}, \: \theta_0 \text{ (params)}, \: f(\theta)
            \text{ (objective)}, \: \lambda \text{ (weight decay)},                          \\
        &\hspace{13mm} \:\mu \text{ (momentum)}, \:\tau \text{ (dampening)},
        \:\textit{ nesterov,}\:\textit{ maximize}                                     \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{for} \: t=1 \: \textbf{to} \: \ldots \: \textbf{do}                         \\
        &\hspace{5mm}g_t           \leftarrow   \nabla_{\theta} f_t (\theta_{t-1})           \\
        &\hspace{5mm}\textbf{if} \: \lambda \neq 0                                           \\
        &\hspace{10mm} g_t \leftarrow g_t + \lambda  \theta_{t-1}                            \\
        &\hspace{5mm}\textbf{if} \: \mu \neq 0                                               \\
        &\hspace{10mm}\textbf{if} \: t > 1                                                   \\
        &\hspace{15mm} \textbf{b}_t \leftarrow \mu \textbf{b}_{t-1} + (1-\tau) g_t           \\
        &\hspace{10mm}\textbf{else}                                                          \\
        &\hspace{15mm} \textbf{b}_t \leftarrow g_t                                           \\
        &\hspace{10mm}\textbf{if} \: \textit{nesterov}                                       \\
        &\hspace{15mm} g_t \leftarrow g_{t} + \mu \textbf{b}_t                             \\
        &\hspace{10mm}\textbf{else}                                                   \\[-1.ex]
        &\hspace{15mm} g_t  \leftarrow  \textbf{b}_t                                         \\
        &\hspace{5mm}\textbf{if} \: \textit{maximize}                                          \\
        &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} + \gamma g_t                   \\[-1.ex]
        &\hspace{5mm}\textbf{else}                                                    \\[-1.ex]
        &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} - \gamma g_t                   \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
        &\bf{return} \:  \theta_t                                                     \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
   \end{aligned}

Nesterov momentum is based on the formula from
`On the importance of initialization and momentum in deep learning`__.

Args:
    params (iterable): iterable of parameters to optimize or dicts defining
        parameter groups
    lr (float, Tensor, optional): learning rate (default: 1e-3)
    momentum (float, optional): momentum factor (default: 0)
    weight_decay (float, optional): weight decay (L2 penalty) (default: 0)
    dampening (float, optional): dampening for momentum (default: 0)
    nesterov (bool, optional): enables Nesterov momentum (default: False)
    maximize (bool, optional): maximize the objective with respect to the
        params, instead of minimizing (default: False)
    foreach (bool, optional): whether foreach implementation of optimizer
        is used. If unspecified by the user (so foreach is None), we will try to use
        foreach over the for-loop implementation on CUDA, since it is usually
        significantly more performant. Note that the foreach implementation uses
        ~ sizeof(params) more peak memory than the for-loop version due to the intermediates
        being a tensorlist vs just one tensor. If memory is prohibitive, batch fewer
        parameters through the optimizer at a time or switch this flag to False (default: None)
    differentiable (bool, optional): whether autograd should
        occur through the optimizer step in training. Otherwise, the step()
        function runs in a torch.no_grad() context. Setting to True can impair
        performance, so leave it False if you don't intend to run autograd
        through this instance (default: False)
    fused (bool, optional): whether the fused implementation is used.
        Currently, `torch.float64`, `torch.float32`, `torch.float16`, and `torch.bfloat16`
        are supported. (default: None)

.. note:: The foreach and fused implementations are typically faster than the for-loop,
          single-tensor implementation, with fused being theoretically fastest with both
          vertical and horizontal fusion. As such, if the user has not specified either
          flag (i.e., when foreach = fused = None), we will attempt defaulting to the foreach
          implementation when the tensors are all on CUDA. Why not fused? Since the fused
          implementation is relatively new, we want to give it sufficient bake-in time.
          To specify fused, pass True for fused. To force running the for-loop
          implementation, pass False for either foreach or fused.


Example:
    >>> # xdoctest: +SKIP
    >>> optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
    >>> optimizer.zero_grad()
    >>> loss_fn(model(input), target).backward()
    >>> optimizer.step()

__ http://www.cs.toronto.edu/%7Ehinton/absps/momentum.pdf

.. note::
    The implementation of SGD with Momentum/Nesterov subtly differs from
    Sutskever et al. and implementations in some other frameworks.

    Considering the specific case of Momentum, the update can be written as

    .. math::
        \begin{aligned}
            v_{t+1} & = \mu * v_{t} + g_{t+1}, \\
            p_{t+1} & = p_{t} - \text{lr} * v_{t+1},
        \end{aligned}

    where :math:`p`, :math:`g`, :math:`v` and :math:`\mu` denote the
    parameters, gradient, velocity, and momentum respectively.

    This is in contrast to Sutskever et al. and
    other frameworks which employ an update of the form

    .. math::
        \begin{aligned}
            v_{t+1} & = \mu * v_{t} + \text{lr} * g_{t+1}, \\
            p_{t+1} & = p_{t} - v_{t+1}.
        \end{aligned}

    The Nesterov version is analogously modified.

    Moreover, the initial value of the momentum buffer is set to the
    gradient value at the first step. This is in contrast to some other
    frameworks that initialize it to all zeros.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/optim/sgd.py
Type:           type
Subclasses:

In [14]:
optim.Adam?

Init signature:
optim.Adam(
    params: Union[Iterable[torch.Tensor], Iterable[Dict[str, Any]]],
    lr: Union[float, torch.Tensor] = 0.001,
    betas: Tuple[float, float] = (0.9, 0.999),
    eps: float = 1e-08,
    weight_decay: float = 0,
    amsgrad: bool = False,
    *,
    foreach: Optional[bool] = None,
    maximize: bool = False,
    capturable: bool = False,
    differentiable: bool = False,
    fused: Optional[bool] = None,
)
Docstring:
Implements Adam algorithm.

.. math::
   \begin{aligned}
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{input}      : \gamma \text{ (lr)}, \beta_1, \beta_2
            \text{ (betas)},\theta_0 \text{ (params)},f(\theta) \text{ (objective)}          \\
        &\hspace{13mm}      \lambda \text{ (weight decay)},  \: \textit{amsgrad},
            \:\textit{maximize}                                                              \\
        &\textbf{initialize} :  m_0 \leftarrow 0 \text{ ( first moment)},
            v_0\leftarrow 0 \text{ (second moment)},\: \widehat{v_0}^{max}\leftarrow 0\\[-1.ex]
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{for} \: t=1 \: \textbf{to} \: \ldots \: \textbf{do}                         \\

        &\hspace{5mm}\textbf{if} \: \textit{maximize}:                                       \\
        &\hspace{10mm}g_t           \leftarrow   -\nabla_{\theta} f_t (\theta_{t-1})         \\
        &\hspace{5mm}\textbf{else}                                                           \\
        &\hspace{10mm}g_t           \leftarrow   \nabla_{\theta} f_t (\theta_{t-1})          \\
        &\hspace{5mm}\textbf{if} \: \lambda \neq 0                                           \\
        &\hspace{10mm} g_t \leftarrow g_t + \lambda  \theta_{t-1}                            \\
        &\hspace{5mm}m_t           \leftarrow   \beta_1 m_{t-1} + (1 - \beta_1) g_t          \\
        &\hspace{5mm}v_t           \leftarrow   \beta_2 v_{t-1} + (1-\beta_2) g^2_t          \\
        &\hspace{5mm}\widehat{m_t} \leftarrow   m_t/\big(1-\beta_1^t \big)                   \\
        &\hspace{5mm}\widehat{v_t} \leftarrow   v_t/\big(1-\beta_2^t \big)                   \\
        &\hspace{5mm}\textbf{if} \: amsgrad                                                  \\
        &\hspace{10mm}\widehat{v_t}^{max} \leftarrow \mathrm{max}(\widehat{v_t}^{max},
            \widehat{v_t})                                                                   \\
        &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} - \gamma \widehat{m_t}/
            \big(\sqrt{\widehat{v_t}^{max}} + \epsilon \big)                                 \\
        &\hspace{5mm}\textbf{else}                                                           \\
        &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} - \gamma \widehat{m_t}/
            \big(\sqrt{\widehat{v_t}} + \epsilon \big)                                       \\
        &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
        &\bf{return} \:  \theta_t                                                     \\[-1.ex]
        &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
   \end{aligned}

For further details regarding the algorithm we refer to `Adam: A Method for Stochastic Optimization`_.

Args:
    params (iterable): iterable of parameters to optimize or dicts defining
        parameter groups
    lr (float, Tensor, optional): learning rate (default: 1e-3). A tensor LR
        is not yet supported for all our implementations. Please use a float
        LR if you are not also specifying fused=True or capturable=True.
    betas (Tuple[float, float], optional): coefficients used for computing
        running averages of gradient and its square (default: (0.9, 0.999))
    eps (float, optional): term added to the denominator to improve
        numerical stability (default: 1e-8)
    weight_decay (float, optional): weight decay (L2 penalty) (default: 0)
    amsgrad (bool, optional): whether to use the AMSGrad variant of this
        algorithm from the paper `On the Convergence of Adam and Beyond`_
        (default: False)
    foreach (bool, optional): whether foreach implementation of optimizer
        is used. If unspecified by the user (so foreach is None), we will try to use
        foreach over the for-loop implementation on CUDA, since it is usually
        significantly more performant. Note that the foreach implementation uses
        ~ sizeof(params) more peak memory than the for-loop version due to the intermediates
        being a tensorlist vs just one tensor. If memory is prohibitive, batch fewer
        parameters through the optimizer at a time or switch this flag to False (default: None)
    maximize (bool, optional): maximize the objective with respect to the
        params, instead of minimizing (default: False)
    capturable (bool, optional): whether this instance is safe to
        capture in a CUDA graph. Passing True can impair ungraphed performance,
        so if you don't intend to graph capture this instance, leave it False
        (default: False)
    differentiable (bool, optional): whether autograd should
        occur through the optimizer step in training. Otherwise, the step()
        function runs in a torch.no_grad() context. Setting to True can impair
        performance, so leave it False if you don't intend to run autograd
        through this instance (default: False)
    fused (bool, optional): whether the fused implementation is used.
        Currently, `torch.float64`, `torch.float32`, `torch.float16`, and `torch.bfloat16`
        are supported. (default: None)

.. note:: The foreach and fused implementations are typically faster than the for-loop,
          single-tensor implementation, with fused being theoretically fastest with both
          vertical and horizontal fusion. As such, if the user has not specified either
          flag (i.e., when foreach = fused = None), we will attempt defaulting to the foreach
          implementation when the tensors are all on CUDA. Why not fused? Since the fused
          implementation is relatively new, we want to give it sufficient bake-in time.
          To specify fused, pass True for fused. To force running the for-loop
          implementation, pass False for either foreach or fused.
.. Note::
    A prototype implementation of Adam and AdamW for MPS supports `torch.float32` and `torch.float16`.
.. _Adam\: A Method for Stochastic Optimization:
    https://arxiv.org/abs/1412.6980
.. _On the Convergence of Adam and Beyond:
    https://openreview.net/forum?id=ryQu7f-RZ
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/optim/adam.py
Type:           type
Subclasses:

In [22]:
a = torch.randint(0,100, (5,4)).float()
print(a)

tensor([[ 1., 12., 47., 35.],
        [49., 11., 62., 26.],
        [89.,  3., 69., 35.],
        [56., 64., 15., 51.],
        [62., 33., 46., 53.]])

In [43]:
b = torch.randint(6,16, (3,4)).float()
print(b)

tensor([[11., 10., 10.,  6.],
        [11.,  8., 11.,  7.],
        [15., 10.,  7.,  7.]])

In [61]:
import torch
from torch import nn
from torch import optim

class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNet, self).__init__() # initilizes parent class
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        return x

model = SimpleNet(400, 235, 13)

data = torch.randint(100,400, (56, 400)).float() # the lowest number is 100, and highest is 400, and shape is (56,400)
# will output only integers between these range
label = torch.randint(0,1,(56,13)).float()

optimizer = optim.SGD(model.parameters(), lr=0.001)
loss_fn = nn.BCELoss() # expects output to be in range 0-1, while BCEWithLogitsLoss() converts it automatically

for epoch in range(1000):
    optimizer.zero_grad()
    output = model(data)
    loss = loss_fn(output, label)
    loss.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print(f"Epoch: {epoch}, Loss: {loss.item()}")

Epoch: 0, Loss: 48.84001159667969
Epoch: 100, Loss: 8.658561512220331e-08
Epoch: 200, Loss: 8.269275042493973e-08
Epoch: 300, Loss: 7.920038314068734e-08
Epoch: 400, Loss: 7.601553164704455e-08
Epoch: 500, Loss: 7.309704130875616e-08
Epoch: 600, Loss: 7.042604011076037e-08
Epoch: 700, Loss: 6.797645113465478e-08
Epoch: 800, Loss: 6.571800525989602e-08
Epoch: 900, Loss: 6.363453053381818e-08

In [62]:
import os

os.path.join??

Signature: os.path.join(a, *p)
Source:
def join(a, *p):
    """Join two or more pathname components, inserting '/' as needed.
    If any component is an absolute path, all previous path components
    will be discarded.  An empty last part will result in a path that
    ends with a separator."""
    a = os.fspath(a)
    sep = _get_sep(a)
    path = a
    try:
        if not p:
            path[:0] + sep  #23780: Ensure compatible data type even if p is null.
        for b in map(os.fspath, p):
            if b.startswith(sep):
                path = b
            elif not path or path.endswith(sep):
                path += b
            else:
                path += sep + b
    except (TypeError, AttributeError, BytesWarning):
        genericpath._check_arg_types('join', a, *p)
        raise
    return path
File:      /opt/anaconda3/envs/pytorch_env/lib/python3.9/posixpath.py
Type:      function

# Data Handling

In [3]:
import numpy as np

a = np.random.randint(5,10,size=10)
print(a)
b = np.random.randn(2,5)
print(b)

features = np.random.rand(100,10)
labels = np.random.randint(0,5,size=100)
display(features.shape, labels.shape, labels)
assert len(features) == len(labels), "shape no MATCH!" # used for debugging and returns AssertionError if statement is False
display(features.shape, labels.shape, labels)

[9 9 6 7 6 9 6 8 9 5]
[[ 0.27489797  0.79296663 -1.53291725  1.449387    1.31492947]
 [-1.28704841 -1.3266105  -0.67658688 -0.38525619 -1.35918974]]

(100, 10)

(100,)

array([2, 3, 2, 3, 1, 1, 4, 0, 0, 3, 0, 2, 0, 2, 1, 3, 3, 3, 2, 2, 4, 2,
       4, 0, 1, 0, 0, 2, 1, 4, 2, 3, 4, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 4,
       2, 4, 0, 1, 4, 4, 3, 3, 2, 3, 3, 4, 0, 4, 3, 4, 4, 1, 1, 0, 1, 3,
       1, 3, 4, 1, 0, 3, 0, 1, 1, 2, 4, 2, 3, 2, 2, 4, 3, 2, 3, 3, 0, 2,
       2, 3, 3, 3, 3, 1, 2, 4, 4, 1, 3, 0])

(100, 10)

(100,)

array([2, 3, 2, 3, 1, 1, 4, 0, 0, 3, 0, 2, 0, 2, 1, 3, 3, 3, 2, 2, 4, 2,
       4, 0, 1, 0, 0, 2, 1, 4, 2, 3, 4, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 4,
       2, 4, 0, 1, 4, 4, 3, 3, 2, 3, 3, 4, 0, 4, 3, 4, 4, 1, 1, 0, 1, 3,
       1, 3, 4, 1, 0, 3, 0, 1, 1, 2, 4, 2, 3, 2, 2, 4, 3, 2, 3, 3, 0, 2,
       2, 3, 3, 3, 3, 1, 2, 4, 4, 1, 3, 0])

In [110]:
import torch
from torch.utils.data import Dataset
import numpy as np

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        assert len(features) == len(labels)
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(features) # given that both features and labels size must be equal, returning one's size is enough

    def __getitem__(self, idx):
        # get a single data from the sample by index
        feature = self.features[idx]
        label = self.labels[idx]

        # we can take as input list or numpy ndarrays, but we must convert them to tensors and return
        # features and labels as tuple
        sample = (torch.tensor(feature, dtype=torch.float32), torch.tensor(label, dtype=torch.int64))
        return sample

batch_size = 100
input_size = 10
features_data = np.random.rand(batch_size, input_size) # 100 by 10
labels_data = np.random.randint(5,10, size=batch_size)
# look 10 features, corresponding to having only one label
# that is why the shape of labels is (100) basically a row vector, not a matrix
# again even with millions of features, it would have only one single corresponding label

my_dataset = CustomDataset(features_data, labels_data)
print(f"My dataset size: {len(my_dataset)}\n")

first_sample = my_dataset[0]
first_feature, first_label = first_sample

print(f"First sample size: {first_sample}")
print(f"First feature size: {first_feature.shape}")
print(f"First label size: {first_label.shape}")

My dataset size: 100

First sample size: (tensor([0.8712, 0.6464, 0.4607, 0.8589, 0.3803, 0.7976, 0.2634, 0.7944, 0.8359,
        0.8287]), tensor(8))
First feature size: torch.Size([10])
First label size: torch.Size([])

In [125]:
import torch
from torch.utils.data import Dataset
import numpy as np

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        assert len(features) == len(labels) # if AssertionError pops up then we will know that it is because of this
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        # for a given index, provide both feature and label of that given index from the sample
        feature = self.features[idx]
        label = self.labels[idx]

        # we have to convert to tensor and return as a tuple of feature and label for given index
        sample = (torch.tensor(feature, dtype=torch.float32), torch.tensor(label, dtype=torch.float32))
        return sample

features_d = np.random.randn(400, 50) # bath size 400, and number of features is 50
labels_d = np.random.randn(400)

# remember, dataset returns a tuple containing feature and label
custom_dataset = CustomDataset(features_d, labels_d)
print(f"Custom dataset size: {len(custom_dataset)}")

feature_1, label_1 = custom_dataset[0]
print(f"First feature shape: {feature_1.shape}")
print(f"First label shape: {label_1.shape}")

for idx, sample in enumerate(custom_dataset):
    print(idx, sample)

Custom dataset size: 400
First feature shape: torch.Size([50])
First label shape: torch.Size([])
0 (tensor([-0.7775,  0.5033,  0.0716,  0.8516,  1.5418, -0.6231, -0.4957,  0.6414,
         0.2658,  0.9195,  0.9075, -2.5162,  1.5511,  0.4663, -0.4269,  0.7292,
         1.2050, -0.8770,  0.5460,  0.5613,  1.1625, -0.1521, -1.1106, -0.4349,
         0.6739,  0.3471,  0.0924, -0.5720, -0.6781, -0.2323,  0.5186, -0.0785,
         0.4389,  0.5458, -1.0737,  0.1319,  0.2427, -2.0302,  0.3010,  1.4198,
         0.9126,  0.2522, -0.5937,  0.5791,  0.0549, -0.2832, -0.5893,  0.1626,
        -0.4605, -0.7168]), tensor(0.8611))
1 (tensor([ 0.4048,  0.5614,  0.5157,  0.3312, -1.2971,  2.5868, -1.7598, -1.3626,
         2.2573, -0.6847, -0.0719,  0.2926,  0.9393,  0.4447,  0.3880, -0.6699,
         0.9073,  0.3172,  1.6562, -0.1892,  1.0904,  1.0268, -2.0419,  0.3942,
        -0.3816, -0.2055,  0.0864, -0.7578, -0.2828, -1.7723,  0.9638,  0.4744,
         0.0063, -1.8630,  0.6693,  0.8392, -1.8720, -0.4328,  0.1536,  0.2718,
         0.0993,  1.8358,  1.2997, -0.7713, -0.5897, -0.1442,  0.8967,  0.3159,
         0.4610,  0.6774]), tensor(-0.3684))
2 (tensor([ 0.6554, -0.5343, -0.2160,  0.1127, -2.7444, -0.5822,  0.5239, -0.1169,
        -0.8149, -0.5733, -0.7724, -2.1639, -1.0650,  0.9439, -1.0936,  0.0376,
        -2.2878,  1.1727,  0.6842, -0.3523, -0.5888, -0.7631, -0.4862, -0.7970,
         0.9985, -1.4760, -1.6868, -0.3246,  0.2095,  1.4261, -0.0674,  1.1716,
         1.7208, -1.3565, -1.9348,  0.2439,  1.5904,  0.2639,  0.9322, -0.0560,
         1.8999, -1.2881, -1.0574, -0.1889, -0.7320,  0.9590, -0.4101, -1.2343,
         0.0151,  1.6122]), tensor(0.5791))
3 (tensor([ 0.8470,  0.7564, -1.3723,  1.1578, -0.1833, -0.4073, -0.2285,  1.5302,
         1.4852, -0.1309,  2.6718, -1.2098,  0.2397, -0.2003, -0.0225, -0.9569,
         1.3725,  0.3727, -0.5481,  0.3650, -0.3803, -0.1453,  0.2377,  0.1662,
         0.1898,  0.9751, -0.1129,  0.7896,  1.1857, -0.5796,  0.2614, -1.5297,
        -0.1002,  0.0266, -0.5608,  0.1862,  1.4596, -0.8166,  0.0450,  1.4380,
        -0.7876,  0.5475,  0.2736, -0.5153,  1.1840,  0.3570, -0.6699,  0.1641,
         0.4951,  0.8274]), tensor(0.0761))
4 (tensor([ 0.4778, -2.0269, -0.7009, -0.1071,  0.8798,  1.6640, -1.3533, -0.2369,
         0.1004,  1.5148,  1.1353,  1.2554, -0.4621,  0.5075,  0.0736, -0.1463,
        -1.7361,  1.9002, -1.2790, -1.7323,  0.3282,  0.0438,  0.9773, -0.1156,
         0.8034,  0.5453,  0.3408, -0.6095,  0.7332, -0.3736, -0.3474,  2.2309,
        -0.5247,  0.7493,  1.3289, -0.1140, -0.5080, -1.0279,  0.4489,  1.4846,
        -0.1883,  1.3371, -0.2630,  0.1181, -0.6973,  0.4302,  1.8205, -1.2556,
         0.5664, -2.3714]), tensor(-1.2268))
5 (tensor([ 0.5237,  0.2326,  0.2373,  1.0069, -1.4628, -0.5323,  0.6091,  0.0445,
         1.0735,  1.1585,  0.0538,  0.1212, -0.0483,  0.4474,  2.7299, -0.8295,
         0.3270,  0.4382, -0.8599, -0.3861,  1.6497,  0.2042, -0.8274,  0.1052,
        -0.4523, -0.7817,  0.4374,  0.9947, -0.4532, -1.9556, -0.4407,  0.1813,
        -0.9485,  0.9002,  0.7396, -0.8827,  0.4887,  1.8374,  0.1024, -0.3917,
         1.0298, -0.7022, -0.4581, -0.3947, -0.0117, -0.0680,  2.1055,  1.5875,
        -0.5179, -0.4156]), tensor(1.6498))
6 (tensor([-3.5413e-01,  5.1486e-01, -4.5585e-04, -3.6150e-01, -2.2126e-01,
        -6.9744e-01, -4.5659e-01, -1.1820e+00, -8.5669e-01, -4.8311e-02,
         1.1984e+00, -1.8375e-01,  4.9473e-02,  7.5670e-01, -1.5513e+00,
         5.9122e-01,  1.0853e-01,  1.2711e+00,  1.8585e-01, -3.8046e-01,
        -4.2381e-01,  8.1628e-01,  3.2174e-01, -1.9527e+00, -2.6591e-01,
         1.7750e+00,  2.4824e+00, -2.3772e+00, -9.9807e-01, -1.2004e+00,
        -1.4562e-01, -5.1487e-01,  5.2502e-01, -1.2500e+00,  3.6354e-01,
         1.7534e-01, -1.0430e+00,  5.2265e-01, -1.0959e+00, -1.9389e+00,
        -4.7339e-01,  1.6049e-01, -1.6261e+00,  5.5790e-01, -2.2795e-01,
        -1.4466e-01,  2.3424e-01,  6.0393e-03, -2.4852e-01, -6.2064e-01]), tensor(0.9250))
7 (tensor([-0.5436, -0.1030, -1.7888, -0.7563,  0.7349, -2.3117,  0.9223,  0.8815,
         0.0924,  0.4566,  1.3737, -0.6434,  2.1679, -0.4031,  1.2907, -0.5818,
         1.0630, -0.4269, -0.0371, -1.1382, -0.9469, -0.8841, -0.2420,  1.1955,
        -1.7812, -1.4735, -0.4005,  0.7983,  0.3212,  1.0766, -1.0805, -0.3067,
        -1.1855,  0.6177,  0.0555, -0.6798, -1.9066, -0.6722, -0.3675,  0.8195,
         2.2824, -0.4348,  0.7867, -1.0728,  0.9589, -0.7046,  0.1672, -0.4980,
         0.3967, -0.0176]), tensor(0.8283))
8 (tensor([ 1.6752e+00,  1.7339e+00, -1.9348e-01, -9.3308e-01,  2.9282e+00,
        -1.5881e+00, -7.7621e-01, -7.7057e-01, -8.4421e-01, -1.6122e+00,
        -7.7985e-01, -6.2433e-01, -6.5280e-01, -1.0439e+00, -6.2428e-01,
         1.3904e-01,  2.3276e-01,  1.2484e+00, -5.7858e-01, -1.5546e+00,
        -1.4855e+00,  7.0819e-01, -1.3364e+00, -2.7206e+00, -2.9245e-01,
         5.5480e-01,  3.2149e-01,  9.8577e-02, -5.4571e-01, -2.5238e-01,
        -1.0537e-01,  2.0315e-03, -1.4704e+00, -8.2740e-01,  7.1435e-02,
         8.7356e-01,  5.2631e-01, -1.1953e+00,  1.2629e+00,  6.3280e-01,
        -2.0269e+00, -3.7135e-01, -3.0620e-01,  1.9071e-01,  1.3650e+00,
         1.6064e+00,  6.5840e-01, -7.2142e-01, -9.1314e-02,  9.7349e-01]), tensor(0.1414))
9 (tensor([ 0.3217, -0.6589,  0.1075,  0.3421,  0.3636, -0.4320, -0.7441,  0.1016,
         0.1903,  0.4320,  0.5677, -0.8510,  1.7505,  0.2019,  0.9104,  1.3649,
        -0.7836, -1.8003, -1.1361,  1.0169,  1.8513,  0.4437,  1.3510,  0.8660,
         1.0885, -0.8050,  0.1445,  0.2594,  0.7955, -0.1557, -0.7941, -0.5990,
         0.4003, -1.8003, -0.2438,  1.2403, -1.2106,  0.8064, -0.4656,  0.6447,
        -0.8896, -1.4112,  0.0944, -0.2193,  0.4092, -1.0336, -2.3452, -0.2208,
         0.9268, -1.1148]), tensor(-0.4116))
10 (tensor([ 0.8641,  0.6505,  0.0130,  1.5670, -0.0858,  0.6885, -0.6207, -0.3053,
        -1.2978, -1.9474, -1.0141,  0.7088,  0.5005,  0.4183, -1.1316, -1.0554,
         0.1623, -0.3183,  0.7956,  0.2365, -0.5675, -1.8538,  0.3249, -0.0472,
        -0.1737,  0.4980, -0.8579, -0.2319, -1.8524,  0.5128, -0.3011, -1.2215,
         0.5951, -0.0226,  0.6737,  0.5703, -0.3993,  1.3279,  0.0594, -0.4778,
        -0.7075,  0.4748,  0.0646,  0.4641,  0.2408,  0.0846, -1.2747,  0.2579,
         0.9899, -0.4115]), tensor(1.8882))
11 (tensor([-0.7352,  0.2075, -1.5257, -0.9103, -0.2432,  0.8423, -0.8690, -1.1986,
        -0.7628, -0.4187,  0.3530,  0.2843,  0.2094, -1.1497, -0.9738, -1.4586,
        -1.7334, -1.9717,  0.5930, -1.6313, -0.2293,  0.8544,  0.6787, -1.1172,
         0.3564, -0.6359,  0.6523, -0.6523, -0.3638, -0.7666, -0.3888,  1.7501,
         1.0933,  0.5910, -0.4547,  0.4947,  1.6130,  0.3717,  1.5124, -0.5602,
         0.5502,  0.6047, -0.3962,  0.5278,  0.2887,  1.1294, -0.6041,  0.0485,
        -1.5179, -1.3599]), tensor(2.1051))
12 (tensor([ 0.1529, -1.5189, -1.7629, -0.7626,  1.3561,  0.1558, -1.1867,  1.6221,
         2.2404,  1.1559, -0.3113, -0.0887,  0.9535,  0.5789, -1.8187,  0.0712,
         0.0660,  0.3975,  1.5141,  1.3546,  1.9459, -1.0268, -0.2839, -0.1668,
         1.0086,  0.9753,  0.8587, -0.7324, -0.4970, -0.1487,  0.9572,  1.4759,
        -0.4443,  0.8231,  0.0182,  0.6665,  0.7519,  2.0584, -0.8042,  0.9029,
        -0.6888, -0.2374, -1.2233,  1.5011,  1.6631, -0.3052,  1.1273, -0.1037,
         0.3011,  0.1165]), tensor(1.2133))
13 (tensor([ 0.3443,  0.2889, -1.0506,  0.9788, -0.0250, -0.7742, -0.5202,  1.0850,
         1.5502,  0.6069, -0.6868,  0.9455, -0.7598,  0.3400,  0.1806,  0.4820,
         0.7814,  0.3017, -0.9621,  0.1335,  0.5603, -0.0422, -0.5542, -0.3012,
        -0.7929,  0.1228,  0.4563,  1.1992,  0.7208, -0.8760, -0.9533,  1.3201,
        -1.2581, -0.9686, -0.8513,  0.1920, -1.9081, -1.4903, -0.0186,  0.1671,
         0.8303,  0.5863, -0.4891,  0.3393,  0.2925,  0.7360, -0.5277, -1.2571,
         1.1306,  0.3872]), tensor(-1.1346))
14 (tensor([-3.1670e-01,  1.9009e+00, -1.2588e+00, -6.8982e-01, -5.6711e-01,
         4.8033e-01,  3.8767e-04,  7.9481e-02,  9.9583e-03, -9.7047e-01,
        -9.0199e-01, -4.2390e-01,  8.8505e-01,  3.2893e-01,  1.5703e+00,
         9.0163e-01,  1.6686e+00,  1.3505e+00,  4.2867e-01,  2.1528e-01,
         7.9762e-01, -1.0531e+00,  1.2503e-02, -2.4476e-01, -1.5874e+00,
        -1.6267e+00, -5.2753e-01, -1.3116e-01, -1.4694e-01, -4.0322e-01,
        -1.8967e+00,  1.8507e+00,  9.0398e-01, -7.9621e-01,  1.8018e+00,
         3.4995e-01,  1.8795e+00,  1.4608e+00, -8.4617e-01,  4.9442e-01,
        -1.2588e+00, -1.8175e-01,  7.6520e-02, -1.1345e+00,  3.7246e-01,
         3.6262e-01, -2.1574e-01,  3.4264e-01,  1.7277e+00,  4.2783e-01]), tensor(-0.2800))
15 (tensor([ 0.9270, -0.3173,  0.5559, -1.5572, -1.1451,  1.3656, -0.7693,  0.5527,
         1.3434,  1.2855, -0.9935, -0.9399, -0.7849,  0.5832,  0.5438,  0.6207,
        -1.8989,  1.2452,  0.5888, -0.1675, -1.2456,  1.5149,  0.3017, -1.6758,
         0.9676, -0.3317, -1.5333, -1.0065,  1.8587, -0.1058,  0.1998,  0.6931,
        -0.4969, -0.1900, -0.9315, -0.0584, -1.2011, -0.8017, -2.2788,  0.8627,
         0.6084,  0.3179,  0.6915, -0.4041, -0.3275,  0.0243, -1.3306, -0.3514,
        -0.4183,  0.6752]), tensor(0.0929))
16 (tensor([ 0.6638, -1.3501,  1.0376,  1.9746, -0.6894,  0.5750,  2.3020,  0.3134,
        -0.0052, -1.5195, -0.9553,  0.4289,  0.5904, -2.5704,  0.3933,  0.0709,
        -0.1061, -0.4161, -1.4365, -1.6662, -0.2234, -0.9859,  0.4889, -0.5477,
         0.6940, -0.7504, -0.8980,  0.4275,  1.7579,  0.5108,  0.2501,  0.1375,
         0.8469, -0.6645, -2.1016,  1.2681, -0.2055, -0.1261, -1.7156,  0.0822,
        -1.0915,  0.8536,  0.9099,  1.7045,  0.9300, -0.5900,  0.0674,  0.3248,
        -0.4421, -0.7444]), tensor(-0.1710))
17 (tensor([-0.4893, -1.2816, -0.7054,  2.4446, -0.4903,  0.2778, -0.5239, -0.2534,
         1.9610, -0.8345,  0.2042, -1.2705, -0.1583,  0.3514,  2.2560, -0.7222,
        -0.8418,  0.9859,  0.9145, -1.3477, -0.2529, -0.3782, -0.1742, -2.8392,
        -0.9643, -0.8930,  0.5358, -0.0942,  0.9676,  0.3099,  1.1377,  0.6851,
        -0.3669, -0.6844, -1.6612, -1.4355, -0.4857,  1.2742, -0.5263,  1.0411,
         0.9037, -0.2147, -0.3653,  0.9229,  0.4219, -0.1505,  0.8524, -0.3829,
         0.0795,  0.7256]), tensor(-1.1913))
18 (tensor([ 0.4808, -0.2262,  0.2634, -0.4521, -0.1911,  0.5174,  1.3808,  1.5946,
        -1.2288, -0.9908, -0.4258,  0.9725, -0.2357, -0.6161,  1.3435, -1.5377,
         0.9886, -1.1670,  1.8294, -0.0473, -1.9094, -0.5160, -0.0458,  0.9859,
        -0.0436,  2.3072, -0.7725, -0.6840,  0.7815, -0.9112, -0.2017,  0.7165,
         1.2673, -0.7953,  0.2214,  0.5534, -0.4693, -1.3524, -1.4689,  0.3871,
        -0.4769, -0.2498,  0.5328, -0.6114,  0.2838, -0.6257,  0.7172, -0.3570,
        -2.1793, -0.4248]), tensor(0.4891))
19 (tensor([-1.2009, -0.7341, -0.6396,  1.1816,  0.9039,  0.3002, -1.9283, -0.1485,
        -0.2667,  0.6865,  0.1086,  1.7385, -0.6315, -0.3621,  0.5458,  1.4818,
        -0.9634,  0.4763, -0.0421, -0.8859,  1.1760, -0.2499,  0.1785,  1.7524,
         0.3104, -0.9732, -0.7000, -0.4157,  0.0212, -0.7212, -2.1824, -0.5508,
         0.7900, -0.7766, -0.9241,  1.6263, -0.0709, -0.4158,  1.9315,  1.4126,
         0.0578, -0.4271,  1.1169, -0.5396,  1.0148, -1.2821, -0.5079, -0.6703,
        -0.4351,  1.7858]), tensor(0.3119))
20 (tensor([ 0.2352, -1.4671,  1.2110,  0.6899,  0.9003, -1.7359, -0.2935,  0.8976,
        -0.8119, -1.1678, -0.9856,  0.1233,  0.3188,  1.6038,  0.0042, -1.3961,
         0.6651, -1.1412,  0.3655, -0.0119,  0.2815,  0.7420, -1.6728, -0.5830,
        -0.4478, -0.0809,  0.6607,  0.2424,  0.7618,  0.5827,  1.1418,  0.1526,
         0.0698,  1.0241,  0.0252,  0.9831,  0.7872,  0.4923,  0.3199, -0.6891,
        -0.2070,  1.4081, -0.8908,  1.7798, -0.0611,  0.7844,  0.6415,  0.0714,
         0.8273,  1.0179]), tensor(0.5376))
21 (tensor([ 0.4215,  0.5825,  1.2126,  0.7533, -0.9459, -1.5262, -0.4011, -0.6819,
        -0.1529,  0.1217, -0.5233,  0.2704,  1.4035, -0.3525, -1.8712, -0.1278,
         1.0030, -0.4376,  1.3965, -1.2929,  0.8241, -0.5153, -1.2130,  1.0933,
         1.3260,  1.0882,  0.7067,  0.2583, -0.4671, -1.0141,  1.5175,  2.0624,
         1.2150,  0.7070,  0.3829,  0.0044, -0.1250, -0.0537, -0.0211,  0.1088,
        -0.4216,  1.4196,  0.1199, -2.0427,  1.5266,  0.3492,  1.0689, -0.4233,
         0.1905,  1.6154]), tensor(-0.6549))
22 (tensor([ 0.6925, -0.8485, -0.0052,  1.3518,  0.3342, -1.2939, -0.8561,  0.1623,
         0.7430,  0.8254,  0.1801, -0.3535, -1.0348,  1.0225, -0.7539,  0.2712,
        -0.8838, -1.8990, -0.5486, -1.1889,  0.2986,  0.9762,  1.6189, -1.1532,
        -1.9336,  0.9451,  0.7550, -0.0290, -2.4142, -0.4750, -0.1695,  1.1664,
        -2.0346, -0.3616, -1.5971,  1.2594,  0.8105, -1.9113, -0.8754, -1.1441,
         0.3097, -0.0444,  0.5231,  0.3724,  0.2788,  0.7450, -0.1458,  0.6554,
         0.9671,  0.1771]), tensor(0.3022))
23 (tensor([-0.8366, -1.1414,  0.0742, -0.0166, -0.0579,  1.9524,  1.2500,  0.1034,
        -0.2114,  0.0304,  0.7830, -1.1708,  0.3343, -1.0453,  0.3921, -1.3427,
        -0.0064,  0.7915, -0.9102,  0.8311, -1.4156,  0.4980, -1.1421, -2.0911,
        -0.9126,  0.4954,  1.3089, -0.2039,  0.3390, -0.7078,  1.0558, -0.7249,
        -1.0121, -0.5069,  0.1149, -1.6554, -0.5236,  0.2678, -1.9123, -1.4082,
         1.8873,  0.4020, -1.8589,  0.3328,  0.2677,  0.1616, -0.3972, -0.5990,
        -0.4324, -0.0376]), tensor(0.7524))
24 (tensor([-1.6326e+00,  6.3392e-01, -2.5113e-02, -1.2764e-01, -4.8834e-04,
         5.6160e-01, -1.6171e-01, -8.1799e-01, -1.2566e+00, -7.6069e-01,
        -1.2182e+00, -1.0086e+00,  2.9756e-01, -1.4148e+00, -6.0030e-02,
         1.0832e+00,  1.5671e-01, -6.5075e-01, -1.8521e-01,  8.0019e-01,
         8.9840e-01, -2.8465e-01,  1.7260e+00,  5.9442e-01, -7.3943e-02,
         4.1477e-01,  7.6624e-01,  3.1916e-01, -5.4316e-01, -3.9288e-01,
         3.4435e-01, -9.4022e-01, -9.3152e-01, -5.6487e-01, -3.3107e-01,
        -4.3763e-01, -6.9575e-01,  1.2969e+00,  3.7026e-01, -1.6315e+00,
         1.5478e-02,  7.5482e-01,  1.4009e+00,  1.0324e+00,  8.6329e-01,
         7.1699e-01,  1.1705e+00,  3.1463e-03, -3.3896e-01, -1.9108e+00]), tensor(0.0805))
25 (tensor([ 0.5589, -0.6717,  0.5337,  0.6912, -1.0768, -0.8296,  0.0138, -0.0277,
        -0.7058,  2.5740,  0.9508,  0.8012,  1.9028,  0.5267,  1.2224, -0.0694,
        -0.0177, -1.4278,  0.1694,  1.2285, -0.3965, -0.5911, -0.9035,  0.0134,
         0.1622, -0.2186,  0.5604, -0.1201, -1.1580, -2.1910,  1.9191,  0.6892,
        -0.9044, -1.4537,  0.4705,  0.2632,  0.4659, -0.3997, -0.3507, -0.2447,
         0.3791,  0.2276,  0.3243, -1.0913,  1.2353, -0.9337,  0.7907,  1.5181,
         0.8764, -0.3690]), tensor(0.3414))
26 (tensor([-0.9289,  0.9454, -0.3993, -0.1191, -0.2746,  1.5976,  0.1450, -1.1232,
        -1.3041, -2.0199, -0.6307,  0.2643,  0.9090,  0.4805,  0.0309,  0.0488,
         2.5021,  1.7589, -0.6690,  1.4282,  0.9211, -0.7051, -1.8321, -0.3032,
         1.1146, -1.0381,  0.6191,  1.5878, -1.4394, -1.3303, -0.8653, -0.2750,
         0.1764, -0.2614,  0.1101,  0.3599, -0.4754, -1.1611, -1.3704, -0.8584,
        -1.0149,  0.6522, -0.5607,  1.9198,  0.8346,  0.8708,  0.4126,  1.0031,
        -0.5372,  0.3529]), tensor(-1.0295))
27 (tensor([-1.4771,  0.6380,  1.4781, -0.4953, -1.8184, -1.3611,  0.9162, -1.5902,
         0.7083, -0.0553,  1.8759, -0.4390,  2.0874,  1.9055,  0.5501, -2.0845,
        -0.3146, -0.4795,  0.6060, -1.5478, -0.9843,  1.4838,  0.0887,  0.8261,
         0.6286,  1.0137,  0.4379,  0.1873, -0.5060,  0.8634, -0.5319, -1.4105,
        -0.6424,  0.3982,  0.4311, -1.7496,  1.0771,  1.2679,  2.0134,  1.0846,
         1.6953, -0.7824,  1.2834, -3.0288, -1.6187,  0.8220, -2.9398,  1.5275,
        -1.8195,  0.2817]), tensor(-1.4958))
28 (tensor([ 0.3848, -1.1984, -1.3815,  0.9589,  0.8572, -0.1658, -0.3349, -3.0327,
         1.5770,  0.9671, -0.2819,  0.0101, -0.1392,  0.9017,  1.0163, -0.6143,
        -0.1904,  0.0646,  0.1276, -0.0995,  0.9226, -2.4155,  0.0994,  1.5492,
        -0.1376, -0.4842,  0.0708,  1.6696, -0.4670,  1.0283,  3.4451,  0.5905,
         0.4191,  0.7982, -0.9614,  0.8774,  0.2918,  0.3804, -0.7798, -1.8338,
         0.1918,  0.3927,  0.7676,  0.8524, -1.0990, -1.2412,  1.0169,  1.4509,
        -1.4226, -0.7459]), tensor(0.6344))
29 (tensor([-0.7202,  1.8012, -0.0461,  1.1995, -0.2701, -0.9141, -0.4169,  0.0139,
        -0.2167, -0.6066, -0.3937, -0.8701, -1.3094,  0.9160, -1.8679, -1.2706,
         0.2680,  0.2337,  1.3833,  0.8771,  1.5890, -1.6171, -1.2509,  0.0369,
         0.2262, -0.4196, -0.2524, -1.1793, -0.9022, -0.1499, -1.0336, -0.2991,
         0.8186, -0.6762,  0.5931,  1.8393,  0.1515, -0.8838,  0.3537,  0.3453,
         0.8964, -0.3372,  0.5551,  1.2881,  1.0005, -0.3352,  0.1810, -0.7825,
        -0.2564, -1.3149]), tensor(-0.6032))
30 (tensor([ 1.5847,  0.9046,  0.7784, -0.8724,  1.2926,  0.7465, -0.8103, -1.6426,
        -0.3962,  0.1919, -0.6261,  0.0542, -0.6233,  0.7042, -1.5133, -0.5479,
        -0.1831, -1.1746, -0.6859, -0.0230, -1.1728,  0.6097, -0.3886, -1.4184,
         2.0315, -0.7135, -0.6052,  0.4211,  0.1988, -0.7659, -1.4682, -0.2069,
         0.8967,  0.5983,  1.2814,  0.5094,  0.2466, -0.5688,  0.5540, -0.5815,
         0.9597,  0.7563, -1.2360,  0.3704,  1.4491,  0.0552,  1.5614, -0.6567,
         0.2474, -0.6549]), tensor(-1.2322))
31 (tensor([-2.0429, -1.4310, -0.4685,  1.1466, -0.7100, -1.2251, -0.5754, -0.3335,
        -1.5457, -1.8403,  0.1852,  0.0649,  0.5224,  0.3520, -0.4971,  0.3619,
         1.4902,  0.6437, -0.6272, -0.5976,  1.6802, -1.7553, -2.2052, -0.9316,
        -1.5958, -0.7500, -0.4454,  0.2092,  0.8561, -0.8041,  0.7816,  1.1246,
        -0.1611,  0.2057,  0.5374, -0.0202, -1.5884,  1.1724, -1.4266,  1.1353,
        -0.6943, -0.0351, -0.5256,  0.3621,  0.3715, -0.4456, -0.6108,  1.3993,
        -1.7908,  1.3391]), tensor(-0.1171))
32 (tensor([ 0.8277, -0.2468,  0.4287,  1.3178,  1.1173,  1.6226,  0.5609,  0.2470,
         0.7622,  0.3805,  0.1906, -0.4632, -0.3234,  0.0646, -0.8750, -0.6785,
        -0.8082,  0.4915,  0.6289,  1.9462, -1.8072, -1.5330,  0.0494, -1.6378,
         1.1104,  2.0842, -0.7341, -0.9650,  0.2205,  1.7225, -0.5344,  0.8980,
         0.1543, -0.7044,  0.4300,  0.8427,  0.5735, -0.5057, -1.3372, -1.4199,
        -0.0258,  0.1588,  0.7969,  2.0820, -1.7956, -0.8331, -0.0810, -1.6574,
         0.3029, -0.6828]), tensor(-0.0925))
33 (tensor([ 0.1316,  0.8828,  2.3716,  1.3657, -0.8769, -0.4082,  1.0424,  0.0846,
        -0.7640, -1.1197, -0.1442,  1.1927,  1.0759, -0.8921,  0.2909,  0.0600,
         0.7217,  1.1106, -1.2056, -0.1339, -1.5661,  0.1323, -0.6139, -1.2070,
         0.4039,  0.7197,  0.5103, -0.3287,  1.1251,  2.0511, -1.3275,  0.1736,
         2.2562, -1.4218, -0.0195,  1.6237,  0.0527, -1.0041, -1.4567, -0.6438,
        -0.1531,  0.5900, -0.0400,  1.3498,  0.9623,  0.5869, -0.0451, -0.9605,
         0.5098, -0.7251]), tensor(1.0013))
34 (tensor([-2.3039,  0.9010, -0.0781,  0.6494,  0.4783,  1.0264,  0.2563, -0.2033,
        -1.4216,  1.2351, -0.3587,  0.1097,  0.2302, -1.0760,  0.5671,  0.0051,
        -0.7006, -0.9541, -0.9150,  0.4825,  0.3008,  0.6804,  0.2151, -1.4517,
        -0.2512,  0.5774, -0.4398,  1.2559, -0.8377, -0.5057, -0.0964, -0.2688,
        -1.1498,  0.2655, -0.9110, -0.2970,  0.2975, -2.1882, -0.5197, -0.1009,
        -1.8645,  1.0825,  0.4835, -0.3007, -0.3265,  1.8257,  1.3774, -1.8916,
         1.0854,  0.3820]), tensor(0.8166))
35 (tensor([-1.1839e+00, -1.9201e+00,  9.1198e-01, -3.8948e-01, -2.9011e-01,
         1.5626e-03,  1.5110e+00, -2.4430e+00, -8.5081e-01,  2.0243e+00,
         7.7819e-01, -1.7324e-01,  8.9873e-01, -4.0972e-01, -4.6577e-01,
        -6.6344e-01,  2.5955e-01, -1.0143e+00,  1.3144e+00, -7.5200e-01,
         9.0483e-01,  3.2069e-01, -5.4661e-01, -1.3610e-01, -9.1107e-02,
        -8.7882e-01,  4.2959e-01,  1.5616e+00,  1.1145e+00,  6.1924e-01,
        -2.1178e-01,  1.3618e+00,  1.3352e+00,  5.1688e-01, -6.2998e-01,

In [20]:
import torch
from torch.utils.data import Dataset
import numpy as np

class CustomData(Dataset):
    def __init__(self, features, labels):
        assert len(features) == len(labels)
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        feature = self.features[idx]
        label = self.labels[idx]
        sample = (torch.tensor(feature, dtype=torch.float32), torch.tensor(label, dtype=torch.float32))
        return sample

inputs = np.random.randint(100,500, size=(560, 43))
labels = np.random.randn(560)

datac = CustomData(inputs, labels)
print(f"Dataset size: {len(datac)}")

input_1, label_1 = datac[0]
print(f"First feature:\n{input_1}\nFirst label: {label_1}")

Dataset size: 560
First feature:
tensor([154., 209., 209., 347., 190., 495., 379., 248., 218., 352., 301., 177.,
        370., 485., 423., 270., 499., 306., 115., 467., 325., 221., 205., 474.,
        308., 102., 298., 332., 455., 466., 199., 357., 178., 310., 306., 315.,
        222., 271., 490., 235., 356., 442., 480.])
First label: 0.6686887145042419

In [2]:
a = torch.nn.parameter.Parameter(torch.tensor(2.0))
print(isinstance(a, torch.nn.parameter.Parameter))
print(isinstance(a, torch.Tensor))

True
True

In [4]:
import torchvision
from torchvision import transforms

# transforms functions, converts PIL image format into PyTorch Tensors
# torchvision datasets usually have images in PIL image format
transformation = transforms.Compose([transforms.ToTensor()])

# Loading train/test dataset
# root defines the root directory where dataset will be saved
# download specifies whether given dataset will be dowloaded
# train=True specifiecs whether it is training set
# transform= specifies if we want to convert PIL image format into PyTorch Tensors

training_dataset = torchvision.datasets.CIFAR10(
                                                root="./dataset_CIFAR10",
                                                train=True,
                                                download=True,
                                                transform=transformation
                                                )

testing_dataset = torchvision.datasets.CIFAR10(
    root="./dataset_CIFAR10",
    train=False,
    transform=transformation,
    download=True
)

# Note that any time you run this code, it will firstly look whether a given dataset
# is present in the root directory, and if not then it will download
# if already present then it will not download the dataset again, avoiding duplication
print(f"\nCIFAR10 training dataset size: {len(training_dataset)}")
print(f"CIFAR10 testing dataset size: {len(testing_dataset)}")

image, label = training_dataset[0] # remember Dataset Class returns a tuple of data point and corresponding label
print(f"\nFirst Image size: {image.size()}")
print(f"First Label size: {label}")

Files already downloaded and verified
Files already downloaded and verified

CIFAR10 training dataset size: 50000
CIFAR10 testing dataset size: 10000

First Image size: torch.Size([3, 32, 32])
First Label size: 6

In [20]:
import torchvision
from torchvision import transforms

# convert PIL images format into PyTorch Tensors
transformation = transforms.Compose([transforms.ToTensor()])

training_set = torchvision.datasets.MNIST(
    root="./data_MNIST",
    train=True,
    transform=transformation,
    download=True
)

testing_set = torchvision.datasets.MNIST(
    root="./data_MNIST",
    train=False,
    transform=transformation,
    download=True
)
# Subsequent runs, will not download the same dataset again,
# it will first check whether a given dataset is present at the root dir
# if and only if not present, then downloads it

print(f"\nMNIST training set size: {len(training_set)}")
print(f"MNIST testing set size: {len(testing_set)}")

# remember that dataset class returns the tuple of data point and respective label
image, label = training_set[0]
print(f"\nFirst image size: {image.shape}")
print(f"First label: {label}")

MNIST training set size: 60000
MNIST testing set size: 10000

First image size: torch.Size([1, 28, 28])
First label: 5

In [23]:
transforms.ToTensor??

Init signature: transforms.ToTensor() -> None
Source:
class ToTensor:
    """Convert a PIL Image or ndarray to tensor and scale the values accordingly.

    This transform does not support torchscript.

    Converts a PIL Image or numpy.ndarray (H x W x C) in the range
    [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]
    if the PIL Image belongs to one of the modes (L, LA, P, I, F, RGB, YCbCr, RGBA, CMYK, 1)
    or if the numpy.ndarray has dtype = np.uint8

    In the other cases, tensors are returned without scaling.

    .. note::
        Because the input image is scaled to [0.0, 1.0], this transformation should not be used when
        transforming target image masks. See the `references`_ for implementing the transforms for image masks.

    .. _references: https://github.com/pytorch/vision/tree/main/references/segmentation
    """

    def __init__(self) -> None:
        _log_api_usage_once(self)

    def __call__(self, pic):
        """
        Args:
            pic (PIL Image or numpy.ndarray): Image to be converted to tensor.

        Returns:
            Tensor: Converted image.
        """
        return F.to_tensor(pic)

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}()"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [24]:
transforms.CenterCrop??

Init signature: transforms.CenterCrop(size)
Source:
class CenterCrop(torch.nn.Module):
    """Crops the given image at the center.
    If the image is torch Tensor, it is expected
    to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions.
    If image size is smaller than output size along any edge, image is padded with 0 and then center cropped.

    Args:
        size (sequence or int): Desired output size of the crop. If size is an
            int instead of sequence like (h, w), a square crop (size, size) is
            made. If provided a sequence of length 1, it will be interpreted as (size[0], size[0]).
    """

    def __init__(self, size):
        super().__init__()
        _log_api_usage_once(self)
        self.size = _setup_size(size, error_msg="Please provide only two dimensions (h, w) for size.")

    def forward(self, img):
        """
        Args:
            img (PIL Image or Tensor): Image to be cropped.

        Returns:
            PIL Image or Tensor: Cropped image.
        """
        return F.center_crop(img, self.size)

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(size={self.size})"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [25]:
transforms.Resize??

Init signature:
transforms.Resize(
    size,
    interpolation=<InterpolationMode.BILINEAR: 'bilinear'>,
    max_size=None,
    antialias=True,
)
Source:
class Resize(torch.nn.Module):
    """Resize the input image to the given size.
    If the image is torch Tensor, it is expected
    to have [..., H, W] shape, where ... means a maximum of two leading dimensions

    Args:
        size (sequence or int): Desired output size. If size is a sequence like
            (h, w), output size will be matched to this. If size is an int,
            smaller edge of the image will be matched to this number.
            i.e, if height > width, then image will be rescaled to
            (size * height / width, size).

            .. note::
                In torchscript mode size as single int is not supported, use a sequence of length 1: ``[size, ]``.
        interpolation (InterpolationMode): Desired interpolation enum defined by
            :class:`torchvision.transforms.InterpolationMode`. Default is ``InterpolationMode.BILINEAR``.
            If input is Tensor, only ``InterpolationMode.NEAREST``, ``InterpolationMode.NEAREST_EXACT``,
            ``InterpolationMode.BILINEAR`` and ``InterpolationMode.BICUBIC`` are supported.
            The corresponding Pillow integer constants, e.g. ``PIL.Image.BILINEAR`` are accepted as well.
        max_size (int, optional): The maximum allowed for the longer edge of
            the resized image. If the longer edge of the image is greater
            than ``max_size`` after being resized according to ``size``,
            ``size`` will be overruled so that the longer edge is equal to
            ``max_size``.
            As a result, the smaller edge may be shorter than ``size``. This
            is only supported if ``size`` is an int (or a sequence of length
            1 in torchscript mode).
        antialias (bool, optional): Whether to apply antialiasing.
            It only affects **tensors** with bilinear or bicubic modes and it is
            ignored otherwise: on PIL images, antialiasing is always applied on
            bilinear or bicubic modes; on other modes (for PIL images and
            tensors), antialiasing makes no sense and this parameter is ignored.
            Possible values are:

            - ``True`` (default): will apply antialiasing for bilinear or bicubic modes.
              Other mode aren't affected. This is probably what you want to use.
            - ``False``: will not apply antialiasing for tensors on any mode. PIL
              images are still antialiased on bilinear or bicubic modes, because
              PIL doesn't support no antialias.
            - ``None``: equivalent to ``False`` for tensors and ``True`` for
              PIL images. This value exists for legacy reasons and you probably
              don't want to use it unless you really know what you are doing.

            The default value changed from ``None`` to ``True`` in
            v0.17, for the PIL and Tensor backends to be consistent.
    """

    def __init__(self, size, interpolation=InterpolationMode.BILINEAR, max_size=None, antialias=True):
        super().__init__()
        _log_api_usage_once(self)
        if not isinstance(size, (int, Sequence)):
            raise TypeError(f"Size should be int or sequence. Got {type(size)}")
        if isinstance(size, Sequence) and len(size) not in (1, 2):
            raise ValueError("If size is a sequence, it should have 1 or 2 values")
        self.size = size
        self.max_size = max_size

        if isinstance(interpolation, int):
            interpolation = _interpolation_modes_from_int(interpolation)

        self.interpolation = interpolation
        self.antialias = antialias

    def forward(self, img):
        """
        Args:
            img (PIL Image or Tensor): Image to be scaled.

        Returns:
            PIL Image or Tensor: Rescaled image.
        """
        return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)

    def __repr__(self) -> str:
        detail = f"(size={self.size}, interpolation={self.interpolation.value}, max_size={self.max_size}, antialias={self.antialias})"
        return f"{self.__class__.__name__}{detail}"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [26]:
transforms.Normalize??

Init signature: transforms.Normalize(mean, std, inplace=False)
Source:
class Normalize(torch.nn.Module):
    """Normalize a tensor image with mean and standard deviation.
    This transform does not support PIL Image.
    Given mean: ``(mean[1],...,mean[n])`` and std: ``(std[1],..,std[n])`` for ``n``
    channels, this transform will normalize each channel of the input
    ``torch.*Tensor`` i.e.,
    ``output[channel] = (input[channel] - mean[channel]) / std[channel]``

    .. note::
        This transform acts out of place, i.e., it does not mutate the input tensor.

    Args:
        mean (sequence): Sequence of means for each channel.
        std (sequence): Sequence of standard deviations for each channel.
        inplace(bool,optional): Bool to make this operation in-place.

    """

    def __init__(self, mean, std, inplace=False):
        super().__init__()
        _log_api_usage_once(self)
        self.mean = mean
        self.std = std
        self.inplace = inplace

    def forward(self, tensor: Tensor) -> Tensor:
        """
        Args:
            tensor (Tensor): Tensor image to be normalized.

        Returns:
            Tensor: Normalized Tensor image.
        """
        return F.normalize(tensor, self.mean, self.std, self.inplace)

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(mean={self.mean}, std={self.std})"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [27]:
transforms.Compose??

Init signature: transforms.Compose(transforms)
Source:
class Compose:
    """Composes several transforms together. This transform does not support torchscript.
    Please, see the note below.

    Args:
        transforms (list of ``Transform`` objects): list of transforms to compose.

    Example:
        >>> transforms.Compose([
        >>>     transforms.CenterCrop(10),
        >>>     transforms.PILToTensor(),
        >>>     transforms.ConvertImageDtype(torch.float),
        >>> ])

    .. note::
        In order to script the transformations, please use ``torch.nn.Sequential`` as below.

        >>> transforms = torch.nn.Sequential(
        >>>     transforms.CenterCrop(10),
        >>>     transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
        >>> )
        >>> scripted_transforms = torch.jit.script(transforms)

        Make sure to use only scriptable transformations, i.e. that work with ``torch.Tensor``, does not require
        `lambda` functions or ``PIL.Image``.

    """

    def __init__(self, transforms):
        if not torch.jit.is_scripting() and not torch.jit.is_tracing():
            _log_api_usage_once(self)
        self.transforms = transforms

    def __call__(self, img):
        for t in self.transforms:
            img = t(img)
        return img

    def __repr__(self) -> str:
        format_string = self.__class__.__name__ + "("
        for t in self.transforms:
            format_string += "\n"
            format_string += f"    {t}"
        format_string += "\n)"
        return format_string
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [28]:
transforms.RandomHorizontalFlip??

Init signature: transforms.RandomHorizontalFlip(p=0.5)
Source:
class RandomHorizontalFlip(torch.nn.Module):
    """Horizontally flip the given image randomly with a given probability.
    If the image is torch Tensor, it is expected
    to have [..., H, W] shape, where ... means an arbitrary number of leading
    dimensions

    Args:
        p (float): probability of the image being flipped. Default value is 0.5
    """

    def __init__(self, p=0.5):
        super().__init__()
        _log_api_usage_once(self)
        self.p = p

    def forward(self, img):
        """
        Args:
            img (PIL Image or Tensor): Image to be flipped.

        Returns:
            PIL Image or Tensor: Randomly flipped image.
        """
        if torch.rand(1) < self.p:
            return F.hflip(img)
        return img

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(p={self.p})"
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [30]:
transforms.ColorJitter?

Init signature:
transforms.ColorJitter(
    brightness: Union[float, Tuple[float, float]] = 0,
    contrast: Union[float, Tuple[float, float]] = 0,
    saturation: Union[float, Tuple[float, float]] = 0,
    hue: Union[float, Tuple[float, float]] = 0,
) -> None
Docstring:
Randomly change the brightness, contrast, saturation and hue of an image.
If the image is torch Tensor, it is expected
to have [..., 1 or 3, H, W] shape, where ... means an arbitrary number of leading dimensions.
If img is PIL Image, mode "1", "I", "F" and modes with transparency (alpha channel) are not supported.

Args:
    brightness (float or tuple of float (min, max)): How much to jitter brightness.
        brightness_factor is chosen uniformly from [max(0, 1 - brightness), 1 + brightness]
        or the given [min, max]. Should be non negative numbers.
    contrast (float or tuple of float (min, max)): How much to jitter contrast.
        contrast_factor is chosen uniformly from [max(0, 1 - contrast), 1 + contrast]
        or the given [min, max]. Should be non-negative numbers.
    saturation (float or tuple of float (min, max)): How much to jitter saturation.
        saturation_factor is chosen uniformly from [max(0, 1 - saturation), 1 + saturation]
        or the given [min, max]. Should be non negative numbers.
    hue (float or tuple of float (min, max)): How much to jitter hue.
        hue_factor is chosen uniformly from [-hue, hue] or the given [min, max].
        Should have 0<= hue <= 0.5 or -0.5 <= min <= max <= 0.5.
        To jitter hue, the pixel values of the input image has to be non-negative for conversion to HSV space;
        thus it does not work if you normalize your image to an interval with negative values,
        or use an interpolation that generates negative values before using this function.
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [31]:
transforms.RandomResizedCrop?

Init signature:
transforms.RandomResizedCrop(
    size,
    scale=(0.08, 1.0),
    ratio=(0.75, 1.3333333333333333),
    interpolation=<InterpolationMode.BILINEAR: 'bilinear'>,
    antialias: Optional[bool] = True,
)
Docstring:
Crop a random portion of image and resize it to a given size.

If the image is torch Tensor, it is expected
to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions

A crop of the original image is made: the crop has a random area (H * W)
and a random aspect ratio. This crop is finally resized to the given
size. This is popularly used to train the Inception networks.

Args:
    size (int or sequence): expected output size of the crop, for each edge. If size is an
        int instead of sequence like (h, w), a square output size ``(size, size)`` is
        made. If provided a sequence of length 1, it will be interpreted as (size[0], size[0]).

        .. note::
            In torchscript mode size as single int is not supported, use a sequence of length 1: ``[size, ]``.
    scale (tuple of float): Specifies the lower and upper bounds for the random area of the crop,
        before resizing. The scale is defined with respect to the area of the original image.
    ratio (tuple of float): lower and upper bounds for the random aspect ratio of the crop, before
        resizing.
    interpolation (InterpolationMode): Desired interpolation enum defined by
        :class:`torchvision.transforms.InterpolationMode`. Default is ``InterpolationMode.BILINEAR``.
        If input is Tensor, only ``InterpolationMode.NEAREST``, ``InterpolationMode.NEAREST_EXACT``,
        ``InterpolationMode.BILINEAR`` and ``InterpolationMode.BICUBIC`` are supported.
        The corresponding Pillow integer constants, e.g. ``PIL.Image.BILINEAR`` are accepted as well.
    antialias (bool, optional): Whether to apply antialiasing.
        It only affects **tensors** with bilinear or bicubic modes and it is
        ignored otherwise: on PIL images, antialiasing is always applied on
        bilinear or bicubic modes; on other modes (for PIL images and
        tensors), antialiasing makes no sense and this parameter is ignored.
        Possible values are:

        - ``True`` (default): will apply antialiasing for bilinear or bicubic modes.
          Other mode aren't affected. This is probably what you want to use.
        - ``False``: will not apply antialiasing for tensors on any mode. PIL
          images are still antialiased on bilinear or bicubic modes, because
          PIL doesn't support no antialias.
        - ``None``: equivalent to ``False`` for tensors and ``True`` for
          PIL images. This value exists for legacy reasons and you probably
          don't want to use it unless you really know what you are doing.

        The default value changed from ``None`` to ``True`` in
        v0.17, for the PIL and Tensor backends to be consistent.
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [32]:
transforms.RandomRotation?

Init signature:
transforms.RandomRotation(
    degrees,
    interpolation=<InterpolationMode.NEAREST: 'nearest'>,
    expand=False,
    center=None,
    fill=0,
)
Docstring:
Rotate the image by angle.
If the image is torch Tensor, it is expected
to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions.

Args:
    degrees (sequence or number): Range of degrees to select from.
        If degrees is a number instead of sequence like (min, max), the range of degrees
        will be (-degrees, +degrees).
    interpolation (InterpolationMode): Desired interpolation enum defined by
        :class:`torchvision.transforms.InterpolationMode`. Default is ``InterpolationMode.NEAREST``.
        If input is Tensor, only ``InterpolationMode.NEAREST``, ``InterpolationMode.BILINEAR`` are supported.
        The corresponding Pillow integer constants, e.g. ``PIL.Image.BILINEAR`` are accepted as well.
    expand (bool, optional): Optional expansion flag.
        If true, expands the output to make it large enough to hold the entire rotated image.
        If false or omitted, make the output image the same size as the input image.
        Note that the expand flag assumes rotation around the center and no translation.
    center (sequence, optional): Optional center of rotation, (x, y). Origin is the upper left corner.
        Default is the center of the image.
    fill (sequence or number): Pixel fill value for the area outside the rotated
        image. Default is ``0``. If given a number, the value is used for all bands respectively.

.. _filters: https://pillow.readthedocs.io/en/latest/handbook/concepts.html#filters
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [7]:
from torchvision import transforms
import torchvision

# Remember, that any data preprocessing is applied for all data splits train/val/test
# However, data augmentation is only applied to training split, to avoid overfitting and achieve better generalization
train_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomCrop(244),
    transforms.RandomHorizontalFlip(), # data augmentation
    transforms.ToTensor(),
    transforms.Normalize(mean=[2.0,3.9,4.2], std = [1.2,1.4,1.6])
])

test_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomCrop(244),
    transforms.ToTensor(), # Converts PIL image format or Numpy Arrays to PyTorch Tensors
    transforms.Normalize(mean=[2.0,3.9,4.2], std=[1.2,1.4,1.6])
])

print(train_transform)
print(test_transform)

train_set = torchvision.datasets.MNIST(
    root = "./data_MNIST",
    train=True,
    download=True,
    transform=train_transform
)
test_set = torchvision.datasets.MNIST(
    root = "./data_MNIST",
    train=False,
    download=True,
    transform=test_transform
)

Compose(
    Resize(size=256, interpolation=bilinear, max_size=None, antialias=True)
    RandomCrop(size=(244, 244), padding=None)
    RandomHorizontalFlip(p=0.5)
    ToTensor()
    Normalize(mean=[2.0, 3.9, 4.2], std=[1.2, 1.4, 1.6])
)
Compose(
    Resize(size=256, interpolation=bilinear, max_size=None, antialias=True)
    RandomCrop(size=(244, 244), padding=None)
    ToTensor()
    Normalize(mean=[2.0, 3.9, 4.2], std=[1.2, 1.4, 1.6])
)

In [14]:
from pathlib import Path
from torchvision.datasets import ImageFolder
from torchvision import transforms

train_transform = transforms.Compose([
    transforms.Resize(255),
    transforms.RandomCrop(144),
    transforms.RandomHorizontalFlip(), # data augmentation
    transforms.AutoAugment(), # data augmentation
    transforms.Normalize(mean=[1.2,3.4,4.5], std=[1.4,5.6,7.8])
])

# No data augmentation is applied here
test_transform = transforms.Compose([
    transforms.Resize(255),
    transforms.RandomCrop(144),
    transforms.Normalize(mean=[1.2,3.4,4.5], std=[1.4,5.6,7.8])
])

train_set_path = Path("./data_MNIST")
test_set_path = Path("./data_MNIST")

train_set = ImageFolder(
    root = train_set_path,
    transform=train_transform
)

test_set = ImageFolder(
    root=test_set_path,
    transform=test_transform
)

sample_image, sample_label = train_set[0] # returns a tuple of data and label

FileNotFoundError: Found no valid file for the classes MNIST. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

In [16]:
from torch.utils.data import Dataset
from PIL import Image

class CustomDataset(Dataset):
    def __init__(self, image_paths, label_paths, transform=None): # by default no transformation is applied
        self.image_paths = image_paths
        self.label_paths =  label_paths
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        label = self.label_paths[idx]

        image = Image.open(image_path).convert("RGB") # load the image and convert to RGB 
        # apply preprocessing steps before returning the image and label
        if self.transform:
            image = self.transform(image)

        return tuple(image, label)

custom_train_dataset = CustomDataset(train_path, train_label, transform=train_transform)
custom_test_dataste = CustomDataset(test_path, test_label, transform=test_transform)

NameError: name 'train_path' is not defined

In [ ]:
from torchvision.datasets import ImageFolder
from pathlib import Path
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image

train_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.ToTensor(),
    transforms.RandomVerticalFlip()
])

test_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.ToTensor()
])

train_path = Path("path/to/training/set")
test_path = Path("path/to/testing/set")

train_set = ImageFolder(root=train_path, transform=train_transform)
test_set = ImageFolder(root=test_path, transform=test_transform)

class CustomDataset(Dataset):
    def __init__(self, image_path, label_path, transform=None):
        self.image_path = image_path
        self.label_path = label_path
        self.transform = transform

    def __len__(self):
        return len(self.image_path)

    def __getitem__(self, idx):
        image_path = self.image_path[idx]
        label = self.label_path[idx]

        # preprocessing is applied AFTER capturing individual data points and BEFORE returning it as a tuple
        image = Image.open(image_path).convert("RGB")
        if self.transform:
            image = self.transform(image)

        # after preprocessing is applied, now we can return the organized, normalized dataset
        return tuple(image, label)

custom_train_dataset = CustomDataset(train_path, train_label, transform=train_transform)
custom_test_dataset = CustomDataset(test_path, test_label, transform=test_transform)

In [22]:
from torchvision.datasets import ImageFolder
from pathlib import Path
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image

train_path = Path("path/to/train/set")
test_path = Path("path/to/test/set")

# remember any data preprocessing is applied to all data splits train/val/test
# but data augmentation is applied only to training set
train_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomCrop(244),
    transforms.RandomHorizontalFlip(p=0.6) # data augmentation
])

test_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomCrop(244)
])

train_set = ImageFolder(root=train_path, transform=train_transform)
test_set = ImageFolder(root=test_path, transform=test_transform)

class CustomDataset(Dataset):
    def __init__(self, image_path, label_path, transform=None):
        self.image_path = image_path
        self.label_path = label_path
        self.transform = transform

    def __len__(self):
        return len(self.image_path)

    def __getitem__(self, idx):
        image_path = self.image_path[idx]
        label = self.label_path[idx]

         # before returning, we need to apply transformations here
        image = Image.open(image_path).convert("RGB")
        if self.transform:
            image = self.transform(image)

        return tuple(torch.tensor(image), torch.tensor(label))

custom_train_dataset = CustomDataset(train_path, train_label, transform=train_transform)
custom_test_dataset = CustomDataset(test_path, test_label, transform=test_transform)

Init signature: Path(*args, **kwargs)
Source:
class Path(PurePath):
    """PurePath subclass that can make system calls.

    Path represents a filesystem path but unlike PurePath, also offers
    methods to do system calls on path objects. Depending on your system,
    instantiating a Path will return either a PosixPath or a WindowsPath
    object. You can also instantiate a PosixPath or WindowsPath directly,
    but cannot instantiate a WindowsPath on a POSIX system or vice versa.
    """
    __slots__ = (
        '_accessor',
    )

    def __new__(cls, *args, **kwargs):
        if cls is Path:
            cls = WindowsPath if os.name == 'nt' else PosixPath
        self = cls._from_parts(args, init=False)
        if not self._flavour.is_supported:
            raise NotImplementedError("cannot instantiate %r on your system"
                                      % (cls.__name__,))
        self._init()
        return self

    def _init(self,
              # Private non-constructor arguments
              template=None,
              ):
        if template is not None:
            self._accessor = template._accessor
        else:
            self._accessor = _normal_accessor

    def _make_child_relpath(self, part):
        # This is an optimization used for dir walking.  `part` must be
        # a single part relative to this path.
        parts = self._parts + [part]
        return self._from_parsed_parts(self._drv, self._root, parts)

    def __enter__(self):
        return self

    def __exit__(self, t, v, tb):
        # https://bugs.python.org/issue39682
        # In previous versions of pathlib, this method marked this path as
        # closed; subsequent attempts to perform I/O would raise an IOError.
        # This functionality was never documented, and had the effect of
        # making Path objects mutable, contrary to PEP 428. In Python 3.9 the
        # _closed attribute was removed, and this method made a no-op.
        # This method and __enter__()/__exit__() should be deprecated and
        # removed in the future.
        pass

    def _opener(self, name, flags, mode=0o666):
        # A stub for the opener argument to built-in open()
        return self._accessor.open(self, flags, mode)

    def _raw_open(self, flags, mode=0o777):
        """
        Open the file pointed by this path and return a file descriptor,
        as os.open() does.
        """
        return self._accessor.open(self, flags, mode)

    # Public API

    @classmethod
    def cwd(cls):
        """Return a new path pointing to the current working directory
        (as returned by os.getcwd()).
        """
        return cls(os.getcwd())

    @classmethod
    def home(cls):
        """Return a new path pointing to the user's home directory (as
        returned by os.path.expanduser('~')).
        """
        return cls(cls()._flavour.gethomedir(None))

    def samefile(self, other_path):
        """Return whether other_path is the same or not as this file
        (as returned by os.path.samefile()).
        """
        st = self.stat()
        try:
            other_st = other_path.stat()
        except AttributeError:
            other_st = self._accessor.stat(other_path)
        return os.path.samestat(st, other_st)

    def iterdir(self):
        """Iterate over the files in this directory.  Does not yield any
        result for the special paths '.' and '..'.
        """
        for name in self._accessor.listdir(self):
            if name in {'.', '..'}:
                # Yielding a path object for these makes little sense
                continue
            yield self._make_child_relpath(name)

    def glob(self, pattern):
        """Iterate over this subtree and yield all existing files (of any
        kind, including directories) matching the given relative pattern.
        """
        sys.audit("pathlib.Path.glob", self, pattern)
        if not pattern:
            raise ValueError("Unacceptable pattern: {!r}".format(pattern))
        drv, root, pattern_parts = self._flavour.parse_parts((pattern,))
        if drv or root:
            raise NotImplementedError("Non-relative patterns are unsupported")
        selector = _make_selector(tuple(pattern_parts), self._flavour)
        for p in selector.select_from(self):
            yield p

    def rglob(self, pattern):
        """Recursively yield all existing files (of any kind, including
        directories) matching the given relative pattern, anywhere in
        this subtree.
        """
        sys.audit("pathlib.Path.rglob", self, pattern)
        drv, root, pattern_parts = self._flavour.parse_parts((pattern,))
        if drv or root:
            raise NotImplementedError("Non-relative patterns are unsupported")
        selector = _make_selector(("**",) + tuple(pattern_parts), self._flavour)
        for p in selector.select_from(self):
            yield p

    def absolute(self):
        """Return an absolute version of this path.  This function works
        even if the path doesn't point to anything.

        No normalization is done, i.e. all '.' and '..' will be kept along.
        Use resolve() to get the canonical path to a file.
        """
        # XXX untested yet!
        if self.is_absolute():
            return self
        # FIXME this must defer to the specific flavour (and, under Windows,
        # use nt._getfullpathname())
        obj = self._from_parts([os.getcwd()] + self._parts, init=False)
        obj._init(template=self)
        return obj

    def resolve(self, strict=False):
        """
        Make the path absolute, resolving all symlinks on the way and also
        normalizing it (for example turning slashes into backslashes under
        Windows).
        """

        def check_eloop(e):
            winerror = getattr(e, 'winerror', 0)
            if e.errno == ELOOP or winerror == _WINERROR_CANT_RESOLVE_FILENAME:
                raise RuntimeError("Symlink loop from %r" % e.filename)

        try:
            s = self._accessor.realpath(self, strict=strict)
        except OSError as e:
            check_eloop(e)
            raise
        p = self._from_parts((s,))

        # In non-strict mode, realpath() doesn't raise on symlink loops.
        # Ensure we get an exception by calling stat()
        if not strict:
            try:
                p.stat()
            except OSError as e:
                check_eloop(e)
        return p

    def stat(self):
        """
        Return the result of the stat() system call on this path, like
        os.stat() does.
        """
        return self._accessor.stat(self)

    def owner(self):
        """
        Return the login name of the file owner.
        """
        return self._accessor.owner(self)

    def group(self):
        """
        Return the group name of the file gid.
        """
        return self._accessor.group(self)

    def open(self, mode='r', buffering=-1, encoding=None,
             errors=None, newline=None):
        """
        Open the file pointed by this path and return a file object, as
        the built-in open() function does.
        """
        return io.open(self, mode, buffering, encoding, errors, newline,
                       opener=self._opener)

    def read_bytes(self):
        """
        Open the file in bytes mode, read it, and close the file.
        """
        with self.open(mode='rb') as f:
            return f.read()

    def read_text(self, encoding=None, errors=None):
        """
        Open the file in text mode, read it, and close the file.
        """
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
            return f.read()

    def write_bytes(self, data):
        """
        Open the file in bytes mode, write to it, and close the file.
        """
        # type-check for the buffer interface before truncating the file
        view = memoryview(data)
        with self.open(mode='wb') as f:
            return f.write(view)

    def write_text(self, data, encoding=None, errors=None):
        """
        Open the file in text mode, write to it, and close the file.
        """
        if not isinstance(data, str):
            raise TypeError('data must be str, not %s' %
                            data.__class__.__name__)
        with self.open(mode='w', encoding=encoding, errors=errors) as f:
            return f.write(data)

    def readlink(self):
        """
        Return the path to which the symbolic link points.
        """
        path = self._accessor.readlink(self)
        obj = self._from_parts((path,), init=False)
        obj._init(template=self)
        return obj

    def touch(self, mode=0o666, exist_ok=True):
        """
        Create this file with the given access mode, if it doesn't exist.
        """
        if exist_ok:
            # First try to bump modification time
            # Implementation note: GNU touch uses the UTIME_NOW option of
            # the utimensat() / futimens() functions.
            try:
                self._accessor.utime(self, None)
            except OSError:
                # Avoid exception chaining
                pass
            else:
                return
        flags = os.O_CREAT | os.O_WRONLY
        if not exist_ok:
            flags |= os.O_EXCL
        fd = self._raw_open(flags, mode)
        os.close(fd)

    def mkdir(self, mode=0o777, parents=False, exist_ok=False):
        """
        Create a new directory at this given path.
        """
        try:
            self._accessor.mkdir(self, mode)
        except FileNotFoundError:
            if not parents or self.parent == self:
                raise
            self.parent.mkdir(parents=True, exist_ok=True)
            self.mkdir(mode, parents=False, exist_ok=exist_ok)
        except OSError:
            # Cannot rely on checking for EEXIST, since the operating system
            # could give priority to other errors like EACCES or EROFS
            if not exist_ok or not self.is_dir():
                raise

    def chmod(self, mode):
        """
        Change the permissions of the path, like os.chmod().
        """
        self._accessor.chmod(self, mode)

    def lchmod(self, mode):
        """
        Like chmod(), except if the path points to a symlink, the symlink's
        permissions are changed, rather than its target's.
        """
        self._accessor.lchmod(self, mode)

    def unlink(self, missing_ok=False):
        """
        Remove this file or link.
        If the path is a directory, use rmdir() instead.
        """
        try:
            self._accessor.unlink(self)
        except FileNotFoundError:
            if not missing_ok:
                raise

    def rmdir(self):
        """
        Remove this directory.  The directory must be empty.
        """
        self._accessor.rmdir(self)

    def lstat(self):
        """
        Like stat(), except if the path points to a symlink, the symlink's
        status information is returned, rather than its target's.
        """
        return self._accessor.lstat(self)

    def rename(self, target):
        """
        Rename this path to the target path.

        The target path may be absolute or relative. Relative paths are
        interpreted relative to the current working directory, *not* the
        directory of the Path object.

        Returns the new Path instance pointing to the target path.
        """
        self._accessor.rename(self, target)
        return self.__class__(target)

    def replace(self, target):
        """
        Rename this path to the target path, overwriting if that path exists.

        The target path may be absolute or relative. Relative paths are
        interpreted relative to the current working directory, *not* the
        directory of the Path object.

        Returns the new Path instance pointing to the target path.
        """
        self._accessor.replace(self, target)
        return self.__class__(target)

    def symlink_to(self, target, target_is_directory=False):
        """
        Make this path a symlink pointing to the target path.
        Note the order of arguments (link, target) is the reverse of os.symlink.
        """
        self._accessor.symlink(target, self, target_is_directory)

    def link_to(self, target):
        """
        Make the target path a hard link pointing to this path.

        Note this function does not make this path a hard link to *target*,
        despite the implication of the function and argument names. The order
        of arguments (target, link) is the reverse of Path.symlink_to, but
        matches that of os.link.

        """
        self._accessor.link_to(self, target)

    # Convenience functions for querying the stat results

    def exists(self):
        """
        Whether this path exists.
        """
        try:
            self.stat()
        except OSError as e:
            if not _ignore_error(e):
                raise
            return False
        except ValueError:
            # Non-encodable path
            return False
        return True

    def is_dir(self):
        """
        Whether this path is a directory.
        """
        try:
            return S_ISDIR(self.stat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist or is a broken symlink
            # (see http://web.archive.org/web/20200623061726/https://bitbucket.org/pitrou/pathlib/issues/12/ )
            return False
        except ValueError:
            # Non-encodable path
            return False

    def is_file(self):
        """
        Whether this path is a regular file (also True for symlinks pointing
        to regular files).
        """
        try:
            return S_ISREG(self.stat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist or is a broken symlink
            # (see http://web.archive.org/web/20200623061726/https://bitbucket.org/pitrou/pathlib/issues/12/ )
            return False
        except ValueError:
            # Non-encodable path
            return False

    def is_mount(self):
        """
        Check if this path is a POSIX mount point
        """
        # Need to exist and be a dir
        if not self.exists() or not self.is_dir():
            return False

        try:
            parent_dev = self.parent.stat().st_dev
        except OSError:
            return False

        dev = self.stat().st_dev
        if dev != parent_dev:
            return True
        ino = self.stat().st_ino
        parent_ino = self.parent.stat().st_ino
        return ino == parent_ino

    def is_symlink(self):
        """
        Whether this path is a symbolic link.
        """
        try:
            return S_ISLNK(self.lstat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist
            return False
        except ValueError:
            # Non-encodable path
            return False

    def is_block_device(self):
        """
        Whether this path is a block device.
        """
        try:
            return S_ISBLK(self.stat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist or is a broken symlink
            # (see http://web.archive.org/web/20200623061726/https://bitbucket.org/pitrou/pathlib/issues/12/ )
            return False
        except ValueError:
            # Non-encodable path
            return False

    def is_char_device(self):
        """
        Whether this path is a character device.
        """
        try:
            return S_ISCHR(self.stat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist or is a broken symlink
            # (see http://web.archive.org/web/20200623061726/https://bitbucket.org/pitrou/pathlib/issues/12/ )
            return False
        except ValueError:
            # Non-encodable path
            return False

    def is_fifo(self):
        """
        Whether this path is a FIFO.
        """
        try:
            return S_ISFIFO(self.stat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist or is a broken symlink
            # (see http://web.archive.org/web/20200623061726/https://bitbucket.org/pitrou/pathlib/issues/12/ )
            return False
        except ValueError:
            # Non-encodable path
            return False

    def is_socket(self):
        """
        Whether this path is a socket.
        """
        try:
            return S_ISSOCK(self.stat().st_mode)
        except OSError as e:
            if not _ignore_error(e):
                raise
            # Path doesn't exist or is a broken symlink
            # (see http://web.archive.org/web/20200623061726/https://bitbucket.org/pitrou/pathlib/issues/12/ )
            return False
        except ValueError:
            # Non-encodable path
            return False

    def expanduser(self):
        """ Return a new path with expanded ~ and ~user constructs
        (as returned by os.path.expanduser)
        """
        if (not (self._drv or self._root) and
            self._parts and self._parts[0][:1] == '~'):
            homedir = self._flavour.gethomedir(self._parts[0][1:])
            return self._from_parts([homedir] + self._parts[1:])

        return self
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/pathlib.py
Type:           type
Subclasses:     PosixPath, WindowsPath

In [2]:
from pathlib import Path
p = Path("/")
for subdir in p.iterdir():
    if subdir.is_dir():
        print(subdir)

/home
/usr
/.resolve
/bin
/sbin
/etc
/var
/Library
/System
/private
/.vol
/Users
/Applications
/opt
/dev
/Volumes
/.nofollow
/tmp
/cores

In [5]:
from torchvision.datasets import ImageFolder
ImageFolder??

Init signature:
ImageFolder(
    root: Union[str, pathlib.Path],
    transform: Optional[Callable] = None,
    target_transform: Optional[Callable] = None,
    loader: Callable[[str], Any] = <function default_loader at 0x13ffc7ee0>,
    is_valid_file: Optional[Callable[[str], bool]] = None,
    allow_empty: bool = False,
)
Source:
class ImageFolder(DatasetFolder):
    """A generic data loader where the images are arranged in this way by default: ::

        root/dog/xxx.png
        root/dog/xxy.png
        root/dog/[...]/xxz.png

        root/cat/123.png
        root/cat/nsdf3.png
        root/cat/[...]/asd932_.png

    This class inherits from :class:`~torchvision.datasets.DatasetFolder` so
    the same methods can be overridden to customize the dataset.

    Args:
        root (str or ``pathlib.Path``): Root directory path.
        transform (callable, optional): A function/transform that takes in a PIL image
            and returns a transformed version. E.g, ``transforms.RandomCrop``
        target_transform (callable, optional): A function/transform that takes in the
            target and transforms it.
        loader (callable, optional): A function to load an image given its path.
        is_valid_file (callable, optional): A function that takes path of an Image file
            and check if the file is a valid file (used to check of corrupt files)
        allow_empty(bool, optional): If True, empty folders are considered to be valid classes.
            An error is raised on empty folders if False (default).

     Attributes:
        classes (list): List of the class names sorted alphabetically.
        class_to_idx (dict): Dict with items (class_name, class_index).
        imgs (list): List of (image path, class_index) tuples
    """

    def __init__(
        self,
        root: Union[str, Path],
        transform: Optional[Callable] = None,
        target_transform: Optional[Callable] = None,
        loader: Callable[[str], Any] = default_loader,
        is_valid_file: Optional[Callable[[str], bool]] = None,
        allow_empty: bool = False,
    ):
        super().__init__(
            root,
            loader,
            IMG_EXTENSIONS if is_valid_file is None else None,
            transform=transform,
            target_transform=target_transform,
            is_valid_file=is_valid_file,
            allow_empty=allow_empty,
        )
        self.imgs = self.samples
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/datasets/folder.py
Type:           type
Subclasses:     Country211, EuroSAT, ImageNet

In [16]:
import torch
from torch.utils.data import DataLoader, Dataset

class CustomDataset(Dataset):
    def __init__(self, num_samples=200, transform=None): # set default as 200 if not provided
        self.num_samples = num_samples
        self.features = torch.randn(num_samples, 10) #  features
        self.labels = torch.randint(0,2,(num_samples,))
        self.transform = transform

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

# create an instance of the Dataset Class
dataset_inst = CustomDataset(num_samples=150)

# now create an instance of the DataLoader class
train_loader = DataLoader(dataset=dataset_inst, batch_size=32, shuffle=True)

print(f"Dataset size: {len(dataset_inst)}")
print(f"DataLoader batch size: {train_loader.batch_size}")

for epoch in range(1):
    print(f"Epoch:{epoch+1}")
    for i, batch in enumerate(train_loader):
        feature, label = batch
        print(f"Batch: {i+1}, Feature:{feature.shape}, Label: {label.shape}")

# Notice that while each batch have the same batch-size, this is not always the case for the last batch
# because total number of samples is not always perfectly divisible by the batch-size
# when this is the case, the last batch will have the remaining samples that will not necessarily have the same batch-size
# If out intention is to keep the uniform distribution of batch-size for each batch, then we can set
# drop_last argument in DataLoader as True which will get rid of the last batch containing the leftover
# sample size which is not equal to the actual batch-size, but if it is equal then the last
# batch will not be dropped, in our case last batch has a size of 22 samples, while the rest 32.

Dataset size: 150
DataLoader batch size: 32
Epoch:1
Batch: 1, Feature:torch.Size([32, 10]), Label: torch.Size([32])
Batch: 2, Feature:torch.Size([32, 10]), Label: torch.Size([32])
Batch: 3, Feature:torch.Size([32, 10]), Label: torch.Size([32])
Batch: 4, Feature:torch.Size([32, 10]), Label: torch.Size([32])
Batch: 5, Feature:torch.Size([22, 10]), Label: torch.Size([22])

In [15]:
print(torch.randint(0,2,(100,))) # row vector

tensor([1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0])

In [9]:
import torch
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, num_samples=0, transform=None): # by default set to 0 and None
        self.num_samples = num_samples
        self.transform = transform
        self.features = torch.arange(num_samples*25).view(num_samples, 25) # 25 features
        self.labels = torch.randint(0,5,(num_samples,)) # a row vector

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

custom_dataset = CustomDataset(num_samples=245)
data_loader = DataLoader(dataset=custom_dataset, batch_size=16, shuffle=True, drop_last=True, num_workers=0)

print(f"Dataset size: {len(custom_dataset)}")
print(f"Batch size: {data_loader.batch_size}\n")

for epoch in range(1):
    print(f"Epoch={epoch+1}")
    for i, batch in enumerate(data_loader):
        feature, label = batch # each batch returns a tuple of feature and label
        print(f"Batch:{i+1}, feature shape:{feature.size()}, label shape:{label.shape}")

# total number of samples divided by the batch size, and the resulting number if the number of iterations

Dataset size: 245
Batch size: 16

Epoch=1
Batch:1, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:2, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:3, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:4, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:5, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:6, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:7, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:8, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:9, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:10, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:11, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:12, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:13, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:14, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])
Batch:15, feature shape:torch.Size([16, 25]), label shape:torch.Size([16])

In [2]:
import torch
from torch.utils.data import Dataset, DataLoader

class CustomData(Dataset):
    def __init__(self, samples_size=0, transform=None):
        self.samples_size = samples_size
        self.transform = transform
        self.features = torch.arange(samples_size*13).reshape(samples_size, 13) # 13 features
        self.labels = torch.randint(0,5,(samples_size,))

    def __len__(self):
        return self.samples_size

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

# create instance of the Dataset and DataLoader classes
custom = CustomData(samples_size=256)
# shuffle=True, shuffles the indicies of the data points for each epoch
# hence avoiding overfitting for model to learn the sequences of the example samples
loader = DataLoader(dataset=custom, batch_size=36, shuffle=True, drop_last=False, num_workers=0, pin_memory=True)
# DataLoader provides an iterable interface/abstraction of Dataset Class

print(f"Dataset size: {len(custom)}")
print(f"Loader batch size: {loader.batch_size}\n")

# now iterate through the epoch
for epoch in range(10):
    print("="*20, epoch+1, "="*20)
    for i, batch in enumerate(loader):
        # each batch represent either tuple or list of tuples 
        # in each tuple, there is feature and label
        feature, label = batch
        print(f"Batch:{i+1}, Feature shape: {feature.shape}, Label shape: {label.size()}")
    print()

Dataset size: 256
Loader batch size: 36

==================== 1 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 2 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 3 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 4 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 5 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 6 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 7 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 8 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 9 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

==================== 10 ====================
Batch:1, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:2, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:3, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:4, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:5, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:6, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:7, Feature shape: torch.Size([36, 13]), Label shape: torch.Size([36])
Batch:8, Feature shape: torch.Size([4, 13]), Label shape: torch.Size([4])

In [27]:
DataLoader?

Init signature:
DataLoader(
    dataset: torch.utils.data.dataset.Dataset[+_T_co],
    batch_size: Optional[int] = 1,
    shuffle: Optional[bool] = None,
    sampler: Union[torch.utils.data.sampler.Sampler, Iterable, NoneType] = None,
    batch_sampler: Union[torch.utils.data.sampler.Sampler[List], Iterable[List], NoneType] = None,
    num_workers: int = 0,
    collate_fn: Optional[Callable[[List[~_T]], Any]] = None,
    pin_memory: bool = False,
    drop_last: bool = False,
    timeout: float = 0,
    worker_init_fn: Optional[Callable[[int], NoneType]] = None,
    multiprocessing_context=None,
    generator=None,
    *,
    prefetch_factor: Optional[int] = None,
    persistent_workers: bool = False,
    pin_memory_device: str = '',
)
Docstring:
Data loader combines a dataset and a sampler, and provides an iterable over the given dataset.

The :class:`~torch.utils.data.DataLoader` supports both map-style and
iterable-style datasets with single- or multi-process loading, customizing
loading order and optional automatic batching (collation) and memory pinning.

See :py:mod:`torch.utils.data` documentation page for more details.

Args:
    dataset (Dataset): dataset from which to load the data.
    batch_size (int, optional): how many samples per batch to load
        (default: ``1``).
    shuffle (bool, optional): set to ``True`` to have the data reshuffled
        at every epoch (default: ``False``).
    sampler (Sampler or Iterable, optional): defines the strategy to draw
        samples from the dataset. Can be any ``Iterable`` with ``__len__``
        implemented. If specified, :attr:`shuffle` must not be specified.
    batch_sampler (Sampler or Iterable, optional): like :attr:`sampler`, but
        returns a batch of indices at a time. Mutually exclusive with
        :attr:`batch_size`, :attr:`shuffle`, :attr:`sampler`,
        and :attr:`drop_last`.
    num_workers (int, optional): how many subprocesses to use for data
        loading. ``0`` means that the data will be loaded in the main process.
        (default: ``0``)
    collate_fn (Callable, optional): merges a list of samples to form a
        mini-batch of Tensor(s).  Used when using batched loading from a
        map-style dataset.
    pin_memory (bool, optional): If ``True``, the data loader will copy Tensors
        into device/CUDA pinned memory before returning them.  If your data elements
        are a custom type, or your :attr:`collate_fn` returns a batch that is a custom type,
        see the example below.
    drop_last (bool, optional): set to ``True`` to drop the last incomplete batch,
        if the dataset size is not divisible by the batch size. If ``False`` and
        the size of dataset is not divisible by the batch size, then the last batch
        will be smaller. (default: ``False``)
    timeout (numeric, optional): if positive, the timeout value for collecting a batch
        from workers. Should always be non-negative. (default: ``0``)
    worker_init_fn (Callable, optional): If not ``None``, this will be called on each
        worker subprocess with the worker id (an int in ``[0, num_workers - 1]``) as
        input, after seeding and before data loading. (default: ``None``)
    multiprocessing_context (str or multiprocessing.context.BaseContext, optional): If
        ``None``, the default `multiprocessing context`_ of your operating system will
        be used. (default: ``None``)
    generator (torch.Generator, optional): If not ``None``, this RNG will be used
        by RandomSampler to generate random indexes and multiprocessing to generate
        ``base_seed`` for workers. (default: ``None``)
    prefetch_factor (int, optional, keyword-only arg): Number of batches loaded
        in advance by each worker. ``2`` means there will be a total of
        2 * num_workers batches prefetched across all workers. (default value depends
        on the set value for num_workers. If value of num_workers=0 default is ``None``.
        Otherwise, if value of ``num_workers > 0`` default is ``2``).
    persistent_workers (bool, optional): If ``True``, the data loader will not shut down
        the worker processes after a dataset has been consumed once. This allows to
        maintain the workers `Dataset` instances alive. (default: ``False``)
    pin_memory_device (str, optional): the device to :attr:`pin_memory` to if ``pin_memory`` is
        ``True``.


.. warning:: If the ``spawn`` start method is used, :attr:`worker_init_fn`
             cannot be an unpicklable object, e.g., a lambda function. See
             :ref:`multiprocessing-best-practices` on more details related
             to multiprocessing in PyTorch.

.. warning:: ``len(dataloader)`` heuristic is based on the length of the sampler used.
             When :attr:`dataset` is an :class:`~torch.utils.data.IterableDataset`,
             it instead returns an estimate based on ``len(dataset) / batch_size``, with proper
             rounding depending on :attr:`drop_last`, regardless of multi-process loading
             configurations. This represents the best guess PyTorch can make because PyTorch
             trusts user :attr:`dataset` code in correctly handling multi-process
             loading to avoid duplicate data.

             However, if sharding results in multiple workers having incomplete last batches,
             this estimate can still be inaccurate, because (1) an otherwise complete batch can
             be broken into multiple ones and (2) more than one batch worth of samples can be
             dropped when :attr:`drop_last` is set. Unfortunately, PyTorch can not detect such
             cases in general.

             See `Dataset Types`_ for more details on these two types of datasets and how
             :class:`~torch.utils.data.IterableDataset` interacts with
             `Multi-process data loading`_.

.. warning:: See :ref:`reproducibility`, and :ref:`dataloader-workers-random-seed`, and
             :ref:`data-loading-randomness` notes for random seed related questions.

.. _multiprocessing context:
    https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py
Type:           type
Subclasses:

In [5]:
from torchvision import transforms
transforms.Normalize?

Init signature: transforms.Normalize(mean, std, inplace=False)
Docstring:
Normalize a tensor image with mean and standard deviation.
This transform does not support PIL Image.
Given mean: ``(mean[1],...,mean[n])`` and std: ``(std[1],..,std[n])`` for ``n``
channels, this transform will normalize each channel of the input
``torch.*Tensor`` i.e.,
``output[channel] = (input[channel] - mean[channel]) / std[channel]``

.. note::
    This transform acts out of place, i.e., it does not mutate the input tensor.

Args:
    mean (sequence): Sequence of means for each channel.
    std (sequence): Sequence of standard deviations for each channel.
    inplace(bool,optional): Bool to make this operation in-place.
Init docstring: Initialize internal Module state, shared by both nn.Module and ScriptModule.
File:           /opt/anaconda3/envs/pytorch_env/lib/python3.9/site-packages/torchvision/transforms/transforms.py
Type:           type
Subclasses:

In [41]:
a = torch.randint(0,3,(4,5))
print(a)
print(torch.bincount(a.view(-1))) # bincount counts the number of items per each class
# it can only accept a flattened row vector

tensor([[2, 2, 0, 2, 2],
        [1, 2, 1, 1, 2],
        [0, 1, 2, 0, 0],
        [2, 0, 2, 2, 2]])
tensor([ 5,  4, 11])

In [90]:
import numpy as np

b = torch.randint(0,3,(5,5))
c = np.random.randint(0,2,(5,5))
display(b,c)

b,c = b.reshape(-1), c.reshape(-1)
class_b_count = torch.bincount(b)
class_c_count = torch.bincount(torch.tensor(c))
display(class_b_count, class_c_count)

tensor([[0, 1, 2, 1, 0],
        [1, 2, 2, 1, 2],
        [0, 1, 0, 1, 1],
        [1, 2, 1, 0, 2],
        [1, 2, 1, 2, 2]])

array([[0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1]])

tensor([ 5, 11,  9])

tensor([11, 14])

In [30]:
import torch
import numpy as np

a = torch.randint(0,2,(5,5))
b = np.random.randint(0,3,(5,5))

a_ = torch.randint(0,2, (5,))
b_ = np.random.randint(0,3,(5,))

display(a,b,a_,b_)

# torch.bincount() shows the total number of each unique class
a, b, a_, b_ = a.reshape(-1), b.reshape(-1), a_.reshape(-1), b_.reshape(-1)
count_a = torch.bincount(a)
count_a_ = torch.bincount(a_)
count_b = torch.bincount(torch.tensor(b))
count_b_ = torch.bincount(torch.tensor(b_))
display(count_a,count_a_,count_b, count_b_)

tensor([[0, 0, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 1, 1, 1],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 0]])

array([[2, 0, 0, 1, 2],
       [1, 1, 1, 1, 1],
       [2, 0, 1, 0, 0],
       [1, 2, 0, 1, 1],
       [2, 2, 0, 2, 2]])

tensor([0, 1, 0, 0, 1])

array([2, 1, 1, 1, 2])

tensor([13, 12])

tensor([3, 2])

tensor([ 7, 10,  8])

tensor([0, 3, 2])

In [45]:
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import transforms

num_samples = 130
num_features = 15

features = torch.randn(num_samples, num_features) # 15 features and 130 example samples
labels = torch.randint(0,2,(num_samples,)) # size (100) or (100,), in both cases it has a single bracket, hence flattened row vector

class SyntheticDataset(Dataset):
    def __init__(self, features, labels, transform=None):
        # number of samples for features and labels must be equal
        assert features.shape[0] == labels.shape[0] #[0] represents the number of samples while [1] is for number of features
        self.features = features
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return self.features.shape[0] # or self.labels.shape[0], they both equal or at least must be equal

    def __getitem__(self, idx):
        feature_sample = self.features[idx]
        label_sample = self.labels[idx]

        sample = {"feature": feature_sample, "label": label_sample}
        
        if self.transform:
            sample = self.transform(sample)
            
        # implicitly Python treats returning a sequence of values separated by comma as tuples
        return sample["feature"], sample["label"]


feature_mean = features.mean(dim=0)
feature_std = features.std(dim=0)

# In order to avoid division by zero, we replace all 0 to 1
feature_std[feature_std==0] = 1.0

# we are defining a transformation 
class ToTensorType(object):
    # Converts Features to FloatTensor and labels to LongTensor
    def __call__(self, sample):
        feature, label = sample["feature"], sample["label"]
        return {"feature": feature.float(), "label": label.long()}

class NormalizedFeatureVector(object):
    def __init__(self, mean, std):
        self.mean = mean
        self.std = std

    def __call__(self, sample):
        feature, label = sample["feature"], sample["label"]
        normalized_feature = (feature - self.mean) / self.std
        return {"feature": normalized_feature, "label": label}

data_transform = transforms.Compose([
    ToTensorType(),
    NormalizedFeatureVector(mean=feature_mean, std=feature_std)
])


custom_dataset = SyntheticDataset(features, labels, transform=data_transform)

feature, label = custom_dataset[3]
print(f"Sample feature shape: {feature.shape}") 
print(f"Sample label shape: {label.shape}, {label.item()}")
print(f"Dataset length: {len(custom_dataset)}\n")

# look since we are capturing individual data point, its preceding sample number is 1
# and virtually it is the same as not including it all, so shape will represent the number of features
# a single label represents a scalar number, that is why its shape is empty, scalar numbers are 0-Dimensional
# while features shape shows 15, which means 15 numbers arranged in the sequence order just like row vector but with single brackets
# scalar numbers always have the 0-Dimensional shape, so empty shape does not represent an empty value for the label

# DataLoader provides an iterable interface for the Dataset 
loader = DataLoader(dataset=custom_dataset, batch_size=16, shuffle=True, num_workers=0, drop_last=False, pin_memory=True)

feature, label = next(iter(loader))
print(f"Feature shape:{feature.shape}, Label shape:{label.size()}")

# for epoch in range(5):
#     print("="*20, epoch+1, "="*20)
#     for i, batch in enumerate(loader):
#         feature, label = batch
#         print(f"Batch={batch+1}, Feature shape:{feature.shape}, Label shape:{label.size()}")

Sample feature shape: torch.Size([15])
Sample label shape: torch.Size([]), 0
Dataset length: 130

Feature shape:torch.Size([16, 15]), Label shape:torch.Size([16])

# Training Loop

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
a = torch.randn(3,4, device=device)
print(a.device)
a = a.to("cpu")
print(a.device)

mps:0
cpu

In [28]:
!conda list | grep -E "matplotlib"

matplotlib                3.9.4                    pypi_0    pypi
matplotlib-inline         0.1.7            py39hca03da5_0

In [17]:
# First define packages and basic configurations: imports and hyperparameters
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

learning_rate = 0.01 # how much of a step does each gradient take to update weights and biases
num_epoch = 100 # how many times should the model see the entire datasets
batch_size = 16 # how many individual examples of entire dataset will the model process at a time before updating the weights and biases

device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(f"Current device: {device}")

Current device: mps

In [18]:
# the actual equation at the end should look like this y = 2*X + 1 + (noise)
# where weight=2 and bias=1, input features=X, noise is a small number added

true_weight = torch.tensor([[2]], dtype=torch.float32)
true_bias = torch.tensor([1], dtype=torch.float32)

# creating a training set
X_train = torch.randn(100,1) * 5 # 100 examples with 1 feature
y_train = true_weight * X_train + true_bias + torch.randn(100,1) * 0.5 # Adding small noise

# creating a separate validation set
X_val = torch.randn(20,1) * 5
y_val = true_weight * X_val + true_bias + torch.randn(20,1) * 0.5

# Creating dataset
train_dataset = TensorDataset(X_train, y_train)
val_dataset = TensorDataset(X_val, y_val)

print(len(train_dataset))
print(len(val_dataset)) 

# Create an iterable interface for the dataset
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True) # only for training the shuffle is True
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False) 
# to keep consistent metrics comparison Shuffle is set to False

100
20

In [19]:
# now define a model, loss function and optimizer, and make sure to move the model to a desired device (CPU or GPU)
# a single layer for this example is enough
model = nn.Linear(1,1)

# now move the model to the desired device
model = model.to(device)
# below checks in what device, parameters reside
print(next(model.parameters()).device)

# define the loss function, since it is regressions problem MSE or MAE will do
loss_fn = nn.MSELoss()

# define how the computed gradients will be used to update weights and biases, provide parameters and learning rate
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

# now simply iterate throught the model parameters
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Name: {name}, Parameters: {param.data.squeeze()}, Device:{param.data.device}")

mps:0
Name: weight, Parameters: 0.8020482063293457, Device:mps:0
Name: bias, Parameters: -0.05859243869781494, Device:mps:0

In [20]:
for param in model.parameters():
    print(param.data.device)

mps:0
mps:0

In [21]:
print(next(model.parameters()).data.device)

mps:0

In [22]:
for param in model.parameters():
    print(param.data.squeeze()) # squeeze produces only the actual numerical values of the weights and biases
    # while .device produces the exact device where the parameters reside

tensor(0.8020, device='mps:0')
tensor(-0.0586, device='mps:0')

In [23]:
print("weight device:", model.weight.device)
print("bias device:", model.bias.device)

weight device: mps:0
bias device: mps:0

In [24]:
import time
start_time = time.time()
for epoch in range(num_epoch):
    # set the model to training mode, because some layers behave differently during training and validation modes
    model.train()
    running_loss = 0.0
    num_batch = 0.0
    for idx, (feature, label) in enumerate(train_loader):
        # move input features and target labels to the same device where model parameters reside
        feature = feature.to(device)
        label = label.to(device)

        # now when features/labels and weights/biases are on the same device we can start without RuntimeError
        # run forward pass in order to build up the computational graph and record sequences of operations leading to the final value
        # implicitly passing features into model() activates forward method of the model
        outputs = model(feature)

        # now calculate the loss, of predicted labels against the ground truth labels, the output is a scalar value
        # repeseting the average loss of all the parameters
        # the loss is calculated only for the current batch and not the entire dataset
        loss = loss_fn(outputs, label)

        # before calculating gradients make sure to clear out .grad attribute as to avoid gradient accumulation
        # zero_grad() must be called before or after the loss.backward()
        optimizer.zero_grad()

        # now calculate the gradients, here is the intensive work is done
        loss.backward()

        # now after gradients are calculated, they are stored in .grad attribute of leaf weights/biases with requires_grad=True
        # and we need to use them to update the weights and biases for the current batch
        optimizer.step()

        # calculate the total loss and total number of batches
        running_loss += loss.item() # since it is a scalar value
        num_batch += 1
        # now we can exit the inner batch loop

    average_loss = running_loss / num_batch
    if (epoch+1) % 10 == 0:
        print(f"Epoch: {epoch+1}/{num_epoch}, Loss: {average_loss:.4f}")

# after the two inner loops are finished, the below code will be executed to check speed
end_time = time.time() - start_time
print(f"{end_time:.3f} milli-seconds")

# note that MPS does not support float64 version of tensors
# on MPS 0.766 milli-seconds and 0.129 milli-seconds on CPU, Looks like CPU runs faster than MPS

Epoch: 10/100, Loss: 0.2947
Epoch: 20/100, Loss: 0.2474
Epoch: 30/100, Loss: 0.2299
Epoch: 40/100, Loss: 0.2413
Epoch: 50/100, Loss: 0.2278
Epoch: 60/100, Loss: 0.2352
Epoch: 70/100, Loss: 0.2587
Epoch: 80/100, Loss: 0.2212
Epoch: 90/100, Loss: 0.2251
Epoch: 100/100, Loss: 0.2060
0.776 milli-seconds

In [31]:
# now we do the validation

# since some layers behave different for training and validation sets
# we must explicitly state that we are right now in the validation mode in order to avoid unexpected behaviors of those layers
model.eval()
val_loss = 0.0
num_batch = 0.0

# with no_grad() we make sure that gradients are not computed even if we accidentally call .backward() inside of validation set
with torch.no_grad():
    for feature, label in val_loader:
        # move input features and labels to the same device as the model parameters were defined
        feature = feature.to(device)
        label = label.to(device)

        # make the forward pass
        outputs = model(feature)

        # compute the loss
        loss = loss_fn(outputs, label)

        # that is it pretty much, and no .backward() and no .step() are used since we are not updating the weights/biases
        # we are only checking the accuracy
        val_loss += loss.item() # retuns a scalar loss value 0-Dimensional
        num_batch += 1

average_loss = val_loss / num_batch
print(f"Average validation loss: {average_loss:.4f}")

for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Name: {name}, Parameters: {param.data.squeeze():.4f}")

Average validation loss: 0.4323
Name: weight, Parameters: 1.9747
Name: bias, Parameters: 0.9868

In [35]:
# Saving model checkpoints

# save in .pth extension
path = "checkpoints.pth"
checkpoints = {
    "learning_rate": learning_rate,
    "model_state_dict": model.state_dict(),
    "optimizer_state_dict": optimizer.state_dict()
}
torch.save(checkpoints, path)

In [49]:
# In order to load the checkpoints we must first create an instance of the model and then call load_state_dict()
# because this function will not recreate an object itself

model = nn.Linear(1,1).to(device)

checkpoints_load = torch.load("checkpoints.pth", weights_only=True, map_location="mps") # we can define where to load if needed

model.load_state_dict(checkpoints_load["model_state_dict"])

# set to evaluation mode, and for this mode we do not need to load the optimizer.load_state_dict()
model.eval()

with torch.no_grad():
    sample_input = torch.tensor([[20.0]])
    # move to the same device as model
    sample_input = sample_input.to(device)
    prediction = model(sample_input)
    print(f"Prediction for input=10: {prediction}") # pretty close to 41

# y = 2*x + 1 , if X=20 then prediction should be close to 41

Prediction for input=10: tensor([[40.4800]], device='mps:0')

In [15]:
for param in model.parameters():
    print(param.grad)

# as of now grad attributes are empty
optimizer.step() # cannot do any updates of the parameters since it does not have gradients
# which tell the sensitivity of the loss value to a small/unit change in the weights/biases

tensor([[-4.3435]], device='mps:0')
tensor([-0.6435], device='mps:0')

In [4]:
# Source - https://stackoverflow.com/questions/76898415/cpu-computation-faster-than-mps-on-pytorch-tensors
# Posted by Kadir
# Retrieved 05/11/2025, License - CC-BY-SA 4.0

import time
import torch

device = "mps"

torch.manual_seed(1234)
TENSOR_A_CPU = torch.rand(50, 50)
TENSOR_B_CPU = torch.rand(50, 50)

torch.manual_seed(1234)
TENSOR_A_MPS = torch.rand(50, 50).to(device)
TENSOR_B_MPS = torch.rand(50, 50).to(device)

start_time = time.time()
torch.matmul(TENSOR_A_CPU, TENSOR_B_CPU)
print("CPU : --- %s seconds ---" % (time.time() - start_time))
cpu_time = time.time() - start_time

start_time = time.time()
torch.matmul(TENSOR_A_MPS, TENSOR_B_MPS)
print("MPS : --- %s seconds ---" % (time.time() - start_time))
mps_time = time.time() - start_time

speed = mps_time / cpu_time
percentage = (1 - (cpu_time/mps_time)) * 100
print(f"CPU performs {speed:.4f} times faster compared to MPS on small operations.")
print(f"CPU performs {percentage:.4f}% faster compared to MPS on small operations.")

CPU : --- 0.00013518333435058594 seconds ---
MPS : --- 0.000560760498046875 seconds ---
CPU performs 2.0913 times faster compared to MPS on small operations.
CPU performs 52.1822% faster compared to MPS on small operations.

In [5]:
# Source - https://stackoverflow.com/questions/76898415/cpu-computation-faster-than-mps-on-pytorch-tensors
# Posted by Kadir
# Retrieved 05/11/2025, License - CC-BY-SA 4.0

import time
import torch

device = "mps"

torch.manual_seed(1234)
TENSOR_A_CPU = torch.rand(5000, 5000)
TENSOR_B_CPU = torch.rand(5000, 5000)

torch.manual_seed(1234)
TENSOR_A_MPS = torch.rand(5000, 5000).to(device)
TENSOR_B_MPS = torch.rand(5000, 5000).to(device)

# Warm-up
for _ in range(100):
    torch.matmul(torch.rand(500,500).to(device), torch.rand(500,500).to(device))
    
start_time = time.time()
torch.matmul(TENSOR_A_CPU, TENSOR_B_CPU)
print("CPU : --- %s seconds ---" % (time.time() - start_time))
cpu_time = time.time() - start_time

start_time = time.time()
torch.matmul(TENSOR_A_MPS, TENSOR_B_MPS)
print("MPS : --- %s seconds ---" % (time.time() - start_time))
mps_time = time.time() - start_time

speed = cpu_time / mps_time
percentage = (1 - (mps_time/cpu_time)) * 100
print(f"MPS performs {speed:.4f} times faster compared to CPU on very complex operations.")
print(f"MPS performs {percentage:.4f}% faster compared to CPU on very complex operations.")

# NOW as the complexity of the model increases, the MPS starts to perform much, much faster compared to CPU on Mac
# as of now MPS performs 1168 times faster than CPU, in the subsequent runs MPS performs 3217 times faster than CPU
# from Percentage perspective MPS performs 99.96% faster compared to CPU on Mac M2 as of now

CPU : --- 0.7261269092559814 seconds ---
MPS : --- 0.00047779083251953125 seconds ---
MPS performs 1435.6715 times faster compared to CPU on very complex operations.
MPS performs 99.9303% faster compared to CPU on very complex operations.

In [90]:
# Training Loop

# setup of imports and hyperparameters
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader, Dataset

learning_rate = 0.001
num_epoch = 1000
batch_size = 16 

device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

In [94]:
# define the ground truth weights and biases and create synthetic dataset
# y = 5*X+3 + (noise)
true_weight = torch.tensor([[5.0]]) # by default it is float32, and keep it that way since MPS cannot work with float64
true_bias = torch.tensor([3.0])

# create input features and labels for training set
X_train = torch.randn(250, 1) # 250 examples with 1 feature
y_train = true_weight * X_train + true_bias + torch.randn(250,1) * 0.513

# create input features and labels for validation set
X_val = torch.randn(50, 1) # 50 examples with 1 feature
y_val = true_weight * X_val + true_bias + torch.randn(50,1) * 0.634

# we can either use TensorDataset or Dataset as a wrapper for our train/val dataset
class Simpledata(Dataset):
    def __init__(self, features, labels):
        assert features.shape[0] == labels.shape[0] # must have the same number of examples/batches
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

train_dataset = Simpledata(X_train, y_train)
val_dataset = Simpledata(X_val, y_val)

# now wrap around DataLoader for batching and shuffling
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False) # because we want to keep consistent metrics comparison

In [95]:
# Now we can define model, optimizer and loss(criterion, objective, cost) function

model = nn.Linear(in_features=1, out_features=1)# weights and biases are randomly initiliazed in the model
# move model to the given device for faster computations
model = model.to(device)

criterion = nn.MSELoss()

optimizer = optim.SGD(model.parameters(), lr=learning_rate)

for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Name:{name}, Parameters:{param.data.squeeze():.5f}, Device:{param.data.device}")

Name:weight, Parameters:-0.22189, Device:mps:0
Name:bias, Parameters:-0.12961, Device:mps:0

In [98]:
import time

start_time = time.time()
for epoch in range(num_epoch):
    # set the mode to training
    model.train()
    running_loss = 0.0
    num_batch = 0.0

    for idx, batch in enumerate(train_loader):
        # empty gradients from the previous batch to avoid gradient accumulation
        optimizer.zero_grad()
        
        # unpack the current batch
        feature, label = batch
        # move them to the same device as model parameters
        feature = feature.to(device)
        label = label.to(device)
        
        outputs = model(feature)
        
        loss = criterion(outputs, label) # loss is computed only for the current batch

        loss.backward()

        optimizer.step() # now using gradients update weights and biases for the current batch

        running_loss += loss
        num_batch += 1

    average_loss = running_loss / num_batch
    if (epoch+1) % 20 == 0:
        print(f"Epoch:{epoch+1}/{num_epoch}, Average Loss for the current batch: {average_loss:.4f}")

end_time = time.time() - start_time
print(f"Finished in {end_time:.4f} seconds.")

Epoch:20/1000, Average Loss for the current batch: 0.2853
Epoch:40/1000, Average Loss for the current batch: 0.2771
Epoch:60/1000, Average Loss for the current batch: 0.2872
Epoch:80/1000, Average Loss for the current batch: 0.2754
Epoch:100/1000, Average Loss for the current batch: 0.2784
Epoch:120/1000, Average Loss for the current batch: 0.2804
Epoch:140/1000, Average Loss for the current batch: 0.2831
Epoch:160/1000, Average Loss for the current batch: 0.2879
Epoch:180/1000, Average Loss for the current batch: 0.2760
Epoch:200/1000, Average Loss for the current batch: 0.2747
Epoch:220/1000, Average Loss for the current batch: 0.2773
Epoch:240/1000, Average Loss for the current batch: 0.2776
Epoch:260/1000, Average Loss for the current batch: 0.2815
Epoch:280/1000, Average Loss for the current batch: 0.2772
Epoch:300/1000, Average Loss for the current batch: 0.2790
Epoch:320/1000, Average Loss for the current batch: 0.2765
Epoch:340/1000, Average Loss for the current batch: 0.2808
Epoch:360/1000, Average Loss for the current batch: 0.2806
Epoch:380/1000, Average Loss for the current batch: 0.2838
Epoch:400/1000, Average Loss for the current batch: 0.2842
Epoch:420/1000, Average Loss for the current batch: 0.2780
Epoch:440/1000, Average Loss for the current batch: 0.2816
Epoch:460/1000, Average Loss for the current batch: 0.2796
Epoch:480/1000, Average Loss for the current batch: 0.2800
Epoch:500/1000, Average Loss for the current batch: 0.2809
Epoch:520/1000, Average Loss for the current batch: 0.2756
Epoch:540/1000, Average Loss for the current batch: 0.2811
Epoch:560/1000, Average Loss for the current batch: 0.2821
Epoch:580/1000, Average Loss for the current batch: 0.2819
Epoch:600/1000, Average Loss for the current batch: 0.2782
Epoch:620/1000, Average Loss for the current batch: 0.2840
Epoch:640/1000, Average Loss for the current batch: 0.2763
Epoch:660/1000, Average Loss for the current batch: 0.2858
Epoch:680/1000, Average Loss for the current batch: 0.2775
Epoch:700/1000, Average Loss for the current batch: 0.2783
Epoch:720/1000, Average Loss for the current batch: 0.2809
Epoch:740/1000, Average Loss for the current batch: 0.2768
Epoch:760/1000, Average Loss for the current batch: 0.2822
Epoch:780/1000, Average Loss for the current batch: 0.2795
Epoch:800/1000, Average Loss for the current batch: 0.2782
Epoch:820/1000, Average Loss for the current batch: 0.2794
Epoch:840/1000, Average Loss for the current batch: 0.2800
Epoch:860/1000, Average Loss for the current batch: 0.2818
Epoch:880/1000, Average Loss for the current batch: 0.2883
Epoch:900/1000, Average Loss for the current batch: 0.2793
Epoch:920/1000, Average Loss for the current batch: 0.2828
Epoch:940/1000, Average Loss for the current batch: 0.2750
Epoch:960/1000, Average Loss for the current batch: 0.2812
Epoch:980/1000, Average Loss for the current batch: 0.2782
Epoch:1000/1000, Average Loss for the current batch: 0.2827
Finished in 11.7245 seconds.

In [107]:
# now performs the validation on the validation set
# since some layers behave differently in training and validation mode set mode to eval
model.eval()
val_loss = 0.0
num_batch = 0.0

with torch.no_grad(): # even if we accidentally call .backward() then no gradients will be computed, hence much faster performance
    for feature, label in val_loader:
        feature = feature.to(device)
        label = label.to(device)

        outputs = model(feature)
        loss = criterion(outputs, label) # predicted vs ground truth
        # that is it
        val_loss += loss
        num_batch += 1

average_loss = val_loss / num_batch
print(f"Validation loss: {average_loss:.4f}")

for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Name: {name}, Calculated Gradients in .grad attribute: {param.grad.squeeze()}")

Validation loss: 0.5019
Name: weight, Calculated Gradients in .grad attribute: -1.1735316514968872
Name: bias, Calculated Gradients in .grad attribute: 0.6433367133140564

In [119]:
# saving checkpoints

checkpoints = {
    "learning_rate": learning_rate,
    "batch_size": batch_size,
    "model_state_dict": model.state_dict(), # contains model parameters (weights and biases)
    "optimizer_state_dict": optimizer.state_dict() # contains details related to Optimization algorithms
}

torch.save(checkpoints, "checkpoints1.pth") # define what you want to save and where 
# note that since we performed operations on MPS, so if we try to load checkpoints
# with torch.load then it will try to load them into MPS, but if device is not available then will throw error
# if we do not have that device then we can use map_location and set the "cpu" if needed

print(model.state_dict())
print(optimizer.state_dict())

OrderedDict([('weight', tensor([[5.0208]], device='mps:0')), ('bias', tensor([2.9789], device='mps:0'))])
{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}

In [133]:
# loading the checkpoints, but first we must create an instance of the model itself
# because load_state_dict() will not recreate an instance/object of the model

model = nn.Linear(1,1).to(device) #must be in the same device

checkpoints = torch.load("checkpoints1.pth", weights_only=True)
# it is just a dictionary
print(checkpoints)

model.load_state_dict(checkpoints["model_state_dict"])
optimizer.load_state_dict(checkpoints["optimizer_state_dict"])
# since we are now using it for evaluation and not continuining training, then we do not need to load optimizer, 
# but the sake of example it is included here

# again some layers behave differently in training and validation modes so set explicitly to .eval during validation
model.eval()

# y = 5*X + 3, with X=15 then prediction should 78
with torch.no_grad():
    inputs = torch.tensor([[15.0]])
    inputs = inputs.to(device)
    pred = model(inputs)
    print(f"\nPrediction on input= 15.0, Result:{pred}") # pretty close to 78

{'learning_rate': 0.001, 'batch_size': 16, 'model_state_dict': OrderedDict([('weight', tensor([[5.0208]], device='mps:0')), ('bias', tensor([2.9789], device='mps:0'))]), 'optimizer_state_dict': {'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}}

Prediction on input= 15.0, Result:tensor([[78.2916]], device='mps:0')

In [1]:
import pandas as pd

In [2]:
DEFAULT_SIGNS = [
    'uy', 'maktab', "ko'cha", 'eshik', 'stol', 'stul', 'karavot', 'mashina', 'poezd',
    'metro', 'kema', "ko'prik", "yomg'ir", 'qor', 'shamol', 'qish', 'bahor', 'kun',
    'iltimos', 'assalomu_alaykum', 'kechirasiz', 'yaxshi', 'tez', 'birga', 'katta',
    'kichik', 'yangi', 'mehribon', 'ovqat_tayyorlash', 'yozish', 'yordam_berish', "o'ynash", 'sayr_qilish',
    'qidirish', "yo'qotish", 'jismoniy_tarbiya', 'turish', 'ketish', 'olib_kelish', 'ochish',
    'yopish', "yorug'", "qorong'i", 'toza', 'televizor', "to'la", "bo'sh", 'oxiri',
    'boshlanishi', 'kech', 'tez_orada', 'restoran', 'zavod', 'cherkov', 'bozor', 'shokolad',
    'mehmonxona', 'kitob', "qog'oz", 'parda', 'kiyim', 'oyoq_kiyim', 'paypoq', "qo'lqop",
    'bosh_kiyim', 'bank_kartasi', 'non', 'likopcha', 'muzlatkich', 'internet', 'musiqa',
    'javob', 'yer', "o't", 'tosh', 'it', 'mushuk', 'sigir', 'ot', "qo'y",
    "cho'chqa", 'kartoshka', 'sabzi', 'karam', 'pomidor', 'bodring', 'sarimsoq', "qo'ziqorin",
    "sariyog'", 'stakan', 'futbol', "o'qiyman", "o'simlik_yog'i", 'sovun', 'yostiq',
    'quyon', 'tozalayman', 'topaman', 'kir', 'ryukzak'
]

In [3]:
top_100_words = ['дом', 'школа', 'улица', 'дверь', 'стол', 'стул', 'кровать', 'машина', 'поезд', 
                 'метро', 'корабль', 'мост', 'дождь', 'снег', 'ветер', 'зима', 'весна', 'день', 
                 'пожалуйста', 'здравствуйте', 'извините', 'нормально', 'быстро', 'вместе', 'большой', 
                 'маленький', 'новый', 'добрый', 'готовить', 'писать', 'помогать', 'играть', 'гулять', 
                 'искать', 'терять', 'физкультура', 'вставать', 'уходить', 'приносить', 'открывать', 
                 'закрывать', 'светлый', 'тёмный', 'чистый', 'телевизор', 'полный', 'пустой', 'конец', 
                 'начало', 'поздно', 'скоро', 'ресторан', 'завод', 'церковь', 'базар', 'шоколад', 
                 'гостиница', 'книга', 'бумага', 'занавеска', 'одежда', 'обувь', 'носки', 'перчатки', 
                 'шапка', 'банковская_карта', 'хлеб', 'тарелка', 'холодильник', 'интернет', 'музыка', 
                 'ответ', 'земля', 'трава', 'камень', 'собака', 'кошка', 'корова', 'лошадь', 'овца', 
                 'свинья', 'картошка', 'морковь', 'капуста', 'помидор', 'огурец', 'чеснок', 'грибы', 
                 'сливочное_масло', 'стакан', 'футбол', 'читаю', 'подсолнечное_масло', 'мыло', 'подушка', 
                 'кролик', 'убираю', 'нахожу', 'грязный', 'рюкзак']

In [5]:
mat= []
for uzb_idx, uzb_word in enumerate(DEFAULT_SIGNS, start=1):
    for rus_idx, rus_word in enumerate(top_100_words, start=1):
        if uzb_idx == rus_idx:
            print(f"{uzb_idx}. {uzb_word} ({rus_word})");\
            mat.append(f"{uzb_idx}. {uzb_word} ({rus_word})")

1. uy (дом)
2. maktab (школа)
3. ko'cha (улица)
4. eshik (дверь)
5. stol (стол)
6. stul (стул)
7. karavot (кровать)
8. mashina (машина)
9. poezd (поезд)
10. metro (метро)
11. kema (корабль)
12. ko'prik (мост)
13. yomg'ir (дождь)
14. qor (снег)
15. shamol (ветер)
16. qish (зима)
17. bahor (весна)
18. kun (день)
19. iltimos (пожалуйста)
20. assalomu_alaykum (здравствуйте)
21. kechirasiz (извините)
22. yaxshi (нормально)
23. tez (быстро)
24. birga (вместе)
25. katta (большой)
26. kichik (маленький)
27. yangi (новый)
28. mehribon (добрый)
29. ovqat_tayyorlash (готовить)
30. yozish (писать)
31. yordam_berish (помогать)
32. o'ynash (играть)
33. sayr_qilish (гулять)
34. qidirish (искать)
35. yo'qotish (терять)
36. jismoniy_tarbiya (физкультура)
37. turish (вставать)
38. ketish (уходить)
39. olib_kelish (приносить)
40. ochish (открывать)
41. yopish (закрывать)
42. yorug' (светлый)
43. qorong'i (тёмный)
44. toza (чистый)
45. televizor (телевизор)
46. to'la (полный)
47. bo'sh (пустой)
48. oxiri (конец)
49. boshlanishi (начало)
50. kech (поздно)
51. tez_orada (скоро)
52. restoran (ресторан)
53. zavod (завод)
54. cherkov (церковь)
55. bozor (базар)
56. shokolad (шоколад)
57. mehmonxona (гостиница)
58. kitob (книга)
59. qog'oz (бумага)
60. parda (занавеска)
61. kiyim (одежда)
62. oyoq_kiyim (обувь)
63. paypoq (носки)
64. qo'lqop (перчатки)
65. bosh_kiyim (шапка)
66. bank_kartasi (банковская_карта)
67. non (хлеб)
68. likopcha (тарелка)
69. muzlatkich (холодильник)
70. internet (интернет)
71. musiqa (музыка)
72. javob (ответ)
73. yer (земля)
74. o't (трава)
75. tosh (камень)
76. it (собака)
77. mushuk (кошка)
78. sigir (корова)
79. ot (лошадь)
80. qo'y (овца)
81. cho'chqa (свинья)
82. kartoshka (картошка)
83. sabzi (морковь)
84. karam (капуста)
85. pomidor (помидор)
86. bodring (огурец)
87. sarimsoq (чеснок)
88. qo'ziqorin (грибы)
89. sariyog' (сливочное_масло)
90. stakan (стакан)
91. futbol (футбол)
92. o'qiyman (читаю)
93. o'simlik_yog'i (подсолнечное_масло)
94. sovun (мыло)
95. yostiq (подушка)
96. quyon (кролик)
97. tozalayman (убираю)
98. topaman (нахожу)
99. kir (грязный)
100. ryukzak (рюкзак)

In [7]:
for word in mat:
    print(word)

1. uy (дом)
2. maktab (школа)
3. ko'cha (улица)
4. eshik (дверь)
5. stol (стол)
6. stul (стул)
7. karavot (кровать)
8. mashina (машина)
9. poezd (поезд)
10. metro (метро)
11. kema (корабль)
12. ko'prik (мост)
13. yomg'ir (дождь)
14. qor (снег)
15. shamol (ветер)
16. qish (зима)
17. bahor (весна)
18. kun (день)
19. iltimos (пожалуйста)
20. assalomu_alaykum (здравствуйте)
21. kechirasiz (извините)
22. yaxshi (нормально)
23. tez (быстро)
24. birga (вместе)
25. katta (большой)
26. kichik (маленький)
27. yangi (новый)
28. mehribon (добрый)
29. ovqat_tayyorlash (готовить)
30. yozish (писать)
31. yordam_berish (помогать)
32. o'ynash (играть)
33. sayr_qilish (гулять)
34. qidirish (искать)
35. yo'qotish (терять)
36. jismoniy_tarbiya (физкультура)
37. turish (вставать)
38. ketish (уходить)
39. olib_kelish (приносить)
40. ochish (открывать)
41. yopish (закрывать)
42. yorug' (светлый)
43. qorong'i (тёмный)
44. toza (чистый)
45. televizor (телевизор)
46. to'la (полный)
47. bo'sh (пустой)
48. oxiri (конец)
49. boshlanishi (начало)
50. kech (поздно)
51. tez_orada (скоро)
52. restoran (ресторан)
53. zavod (завод)
54. cherkov (церковь)
55. bozor (базар)
56. shokolad (шоколад)
57. mehmonxona (гостиница)
58. kitob (книга)
59. qog'oz (бумага)
60. parda (занавеска)
61. kiyim (одежда)
62. oyoq_kiyim (обувь)
63. paypoq (носки)
64. qo'lqop (перчатки)
65. bosh_kiyim (шапка)
66. bank_kartasi (банковская_карта)
67. non (хлеб)
68. likopcha (тарелка)
69. muzlatkich (холодильник)
70. internet (интернет)
71. musiqa (музыка)
72. javob (ответ)
73. yer (земля)
74. o't (трава)
75. tosh (камень)
76. it (собака)
77. mushuk (кошка)
78. sigir (корова)
79. ot (лошадь)
80. qo'y (овца)
81. cho'chqa (свинья)
82. kartoshka (картошка)
83. sabzi (морковь)
84. karam (капуста)
85. pomidor (помидор)
86. bodring (огурец)
87. sarimsoq (чеснок)
88. qo'ziqorin (грибы)
89. sariyog' (сливочное_масло)
90. stakan (стакан)
91. futbol (футбол)
92. o'qiyman (читаю)
93. o'simlik_yog'i (подсолнечное_масло)
94. sovun (мыло)
95. yostiq (подушка)
96. quyon (кролик)
97. tozalayman (убираю)
98. topaman (нахожу)
99. kir (грязный)
100. ryukzak (рюкзак)

In [15]:
empty_column = [k*0*"" for k in range(1,101)]
empty_column

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [9]:
pd.DataFrame??

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Source:
class DataFrame(NDFrame, OpsMixin):
    """
    Two-dimensional, size-mutable, potentially heterogeneous tabular data.

    Data structure also contains labeled axes (rows and columns).
    Arithmetic operations align on both row and column labels. Can be
    thought of as a dict-like container for Series objects. The primary
    pandas data structure.

    Parameters
    ----------
    data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
        Dict can contain Series, arrays, constants, dataclass or list-like objects. If
        data is a dict, column order follows insertion-order. If a dict contains Series
        which have an index defined, it is aligned by its index. This alignment also
        occurs if data is a Series or a DataFrame itself. Alignment is done on
        Series/DataFrame inputs.

        If data is a list of dicts, column order follows insertion-order.

    index : Index or array-like
        Index to use for resulting frame. Will default to RangeIndex if
        no indexing information part of input data and no index provided.
    columns : Index or array-like
        Column labels to use for resulting frame when data does not have them,
        defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
        will perform column selection instead.
    dtype : dtype, default None
        Data type to force. Only a single dtype is allowed. If None, infer.
    copy : bool or None, default None
        Copy data from inputs.
        For dict data, the default of None behaves like ``copy=True``.  For DataFrame
        or 2d ndarray input, the default of None behaves like ``copy=False``.
        If data is a dict containing one or more Series (possibly of different dtypes),
        ``copy=False`` will ensure that these inputs are not copied.

        .. versionchanged:: 1.3.0

    See Also
    --------
    DataFrame.from_records : Constructor from tuples, also record arrays.
    DataFrame.from_dict : From dicts of Series, arrays, or dicts.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_table : Read general delimited file into DataFrame.
    read_clipboard : Read text from clipboard into DataFrame.

    Notes
    -----
    Please reference the :ref:`User Guide <basics.dataframe>` for more information.

    Examples
    --------
    Constructing DataFrame from a dictionary.

    >>> d = {'col1': [1, 2], 'col2': [3, 4]}
    >>> df = pd.DataFrame(data=d)
    >>> df
       col1  col2
    0     1     3
    1     2     4

    Notice that the inferred dtype is int64.

    >>> df.dtypes
    col1    int64
    col2    int64
    dtype: object

    To enforce a single dtype:

    >>> df = pd.DataFrame(data=d, dtype=np.int8)
    >>> df.dtypes
    col1    int8
    col2    int8
    dtype: object

    Constructing DataFrame from a dictionary including Series:

    >>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
    >>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
       col1  col2
    0     0   NaN
    1     1   NaN
    2     2   2.0
    3     3   3.0

    Constructing DataFrame from numpy ndarray:

    >>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    ...                    columns=['a', 'b', 'c'])
    >>> df2
       a  b  c
    0  1  2  3
    1  4  5  6
    2  7  8  9

    Constructing DataFrame from a numpy ndarray that has labeled columns:

    >>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
    ...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
    >>> df3 = pd.DataFrame(data, columns=['c', 'a'])
    ...
    >>> df3
       c  a
    0  3  1
    1  6  4
    2  9  7

    Constructing DataFrame from dataclass:

    >>> from dataclasses import make_dataclass
    >>> Point = make_dataclass("Point", [("x", int), ("y", int)])
    >>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
       x  y
    0  0  0
    1  0  3
    2  2  3

    Constructing DataFrame from Series/DataFrame:

    >>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
    >>> df = pd.DataFrame(data=ser, index=["a", "c"])
    >>> df
       0
    a  1
    c  3

    >>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
    >>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
    >>> df2
       x
    a  1
    c  3
    """

    _internal_names_set = {"columns", "index"} | NDFrame._internal_names_set
    _typ = "dataframe"
    _HANDLED_TYPES = (Series, Index, ExtensionArray, np.ndarray)
    _accessors: set[str] = {"sparse"}
    _hidden_attrs: frozenset[str] = NDFrame._hidden_attrs | frozenset([])
    _mgr: BlockManager | ArrayManager

    # similar to __array_priority__, positions DataFrame before Series, Index,
    #  and ExtensionArray.  Should NOT be overridden by subclasses.
    __pandas_priority__ = 4000

    @property
    def _constructor(self) -> Callable[..., DataFrame]:
        return DataFrame

    def _constructor_from_mgr(self, mgr, axes) -> DataFrame:
        df = DataFrame._from_mgr(mgr, axes=axes)

        if type(self) is DataFrame:
            # This would also work `if self._constructor is DataFrame`, but
            #  this check is slightly faster, benefiting the most-common case.
            return df

        elif type(self).__name__ == "GeoDataFrame":
            # Shim until geopandas can override their _constructor_from_mgr
            #  bc they have different behavior for Managers than for DataFrames
            return self._constructor(mgr)

        # We assume that the subclass __init__ knows how to handle a
        #  pd.DataFrame object.
        return self._constructor(df)

    _constructor_sliced: Callable[..., Series] = Series

    def _constructor_sliced_from_mgr(self, mgr, axes) -> Series:
        ser = Series._from_mgr(mgr, axes)
        ser._name = None  # caller is responsible for setting real name

        if type(self) is DataFrame:
            # This would also work `if self._constructor_sliced is Series`, but
            #  this check is slightly faster, benefiting the most-common case.
            return ser

        # We assume that the subclass __init__ knows how to handle a
        #  pd.Series object.
        return self._constructor_sliced(ser)

    # ----------------------------------------------------------------------
    # Constructors

    def __init__(
        self,
        data=None,
        index: Axes | None = None,
        columns: Axes | None = None,
        dtype: Dtype | None = None,
        copy: bool | None = None,
    ) -> None:
        allow_mgr = False
        if dtype is not None:
            dtype = self._validate_dtype(dtype)

        if isinstance(data, DataFrame):
            data = data._mgr
            allow_mgr = True
            if not copy:
                # if not copying data, ensure to still return a shallow copy
                # to avoid the result sharing the same Manager
                data = data.copy(deep=False)

        if isinstance(data, (BlockManager, ArrayManager)):
            if not allow_mgr:
                # GH#52419
                warnings.warn(
                    f"Passing a {type(data).__name__} to {type(self).__name__} "
                    "is deprecated and will raise in a future version. "
                    "Use public APIs instead.",
                    DeprecationWarning,
                    stacklevel=1,  # bump to 2 once pyarrow 15.0 is released with fix
                )

            if using_copy_on_write():
                data = data.copy(deep=False)
            # first check if a Manager is passed without any other arguments
            # -> use fastpath (without checking Manager type)
            if index is None and columns is None and dtype is None and not copy:
                # GH#33357 fastpath
                NDFrame.__init__(self, data)
                return

        manager = _get_option("mode.data_manager", silent=True)

        is_pandas_object = isinstance(data, (Series, Index, ExtensionArray))
        data_dtype = getattr(data, "dtype", None)
        original_dtype = dtype

        # GH47215
        if isinstance(index, set):
            raise ValueError("index cannot be a set")
        if isinstance(columns, set):
            raise ValueError("columns cannot be a set")

        if copy is None:
            if isinstance(data, dict):
                # retain pre-GH#38939 default behavior
                copy = True
            elif (
                manager == "array"
                and isinstance(data, (np.ndarray, ExtensionArray))
                and data.ndim == 2
            ):
                # INFO(ArrayManager) by default copy the 2D input array to get
                # contiguous 1D arrays
                copy = True
            elif using_copy_on_write() and not isinstance(
                data, (Index, DataFrame, Series)
            ):
                copy = True
            else:
                copy = False

        if data is None:
            index = index if index is not None else default_index(0)
            columns = columns if columns is not None else default_index(0)
            dtype = dtype if dtype is not None else pandas_dtype(object)
            data = []

        if isinstance(data, (BlockManager, ArrayManager)):
            mgr = self._init_mgr(
                data, axes={"index": index, "columns": columns}, dtype=dtype, copy=copy
            )

        elif isinstance(data, dict):
            # GH#38939 de facto copy defaults to False only in non-dict cases
            mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
        elif isinstance(data, ma.MaskedArray):
            from numpy.ma import mrecords

            # masked recarray
            if isinstance(data, mrecords.MaskedRecords):
                raise TypeError(
                    "MaskedRecords are not supported. Pass "
                    "{name: data[name] for name in data.dtype.names} "
                    "instead"
                )

            # a masked array
            data = sanitize_masked_array(data)
            mgr = ndarray_to_mgr(
                data,
                index,
                columns,
                dtype=dtype,
                copy=copy,
                typ=manager,
            )

        elif isinstance(data, (np.ndarray, Series, Index, ExtensionArray)):
            if data.dtype.names:
                # i.e. numpy structured array
                data = cast(np.ndarray, data)
                mgr = rec_array_to_mgr(
                    data,
                    index,
                    columns,
                    dtype,
                    copy,
                    typ=manager,
                )
            elif getattr(data, "name", None) is not None:
                # i.e. Series/Index with non-None name
                _copy = copy if using_copy_on_write() else True
                mgr = dict_to_mgr(
                    # error: Item "ndarray" of "Union[ndarray, Series, Index]" has no
                    # attribute "name"
                    {data.name: data},  # type: ignore[union-attr]
                    index,
                    columns,
                    dtype=dtype,
                    typ=manager,
                    copy=_copy,
                )
            else:
                mgr = ndarray_to_mgr(
                    data,
                    index,
                    columns,
                    dtype=dtype,
                    copy=copy,
                    typ=manager,
                )

        # For data is list-like, or Iterable (will consume into list)
        elif is_list_like(data):
            if not isinstance(data, abc.Sequence):
                if hasattr(data, "__array__"):
                    # GH#44616 big perf improvement for e.g. pytorch tensor
                    data = np.asarray(data)
                else:
                    data = list(data)
            if len(data) > 0:
                if is_dataclass(data[0]):
                    data = dataclasses_to_dicts(data)
                if not isinstance(data, np.ndarray) and treat_as_nested(data):
                    # exclude ndarray as we may have cast it a few lines above
                    if columns is not None:
                        columns = ensure_index(columns)
                    arrays, columns, index = nested_data_to_arrays(
                        # error: Argument 3 to "nested_data_to_arrays" has incompatible
                        # type "Optional[Collection[Any]]"; expected "Optional[Index]"
                        data,
                        columns,
                        index,  # type: ignore[arg-type]
                        dtype,
                    )
                    mgr = arrays_to_mgr(
                        arrays,
                        columns,
                        index,
                        dtype=dtype,
                        typ=manager,
                    )
                else:
                    mgr = ndarray_to_mgr(
                        data,
                        index,
                        columns,
                        dtype=dtype,
                        copy=copy,
                        typ=manager,
                    )
            else:
                mgr = dict_to_mgr(
                    {},
                    index,
                    columns if columns is not None else default_index(0),
                    dtype=dtype,
                    typ=manager,
                )
        # For data is scalar
        else:
            if index is None or columns is None:
                raise ValueError("DataFrame constructor not properly called!")

            index = ensure_index(index)
            columns = ensure_index(columns)

            if not dtype:
                dtype, _ = infer_dtype_from_scalar(data)

            # For data is a scalar extension dtype
            if isinstance(dtype, ExtensionDtype):
                # TODO(EA2D): special case not needed with 2D EAs

                values = [
                    construct_1d_arraylike_from_scalar(data, len(index), dtype)
                    for _ in range(len(columns))
                ]
                mgr = arrays_to_mgr(values, columns, index, dtype=None, typ=manager)
            else:
                arr2d = construct_2d_arraylike_from_scalar(
                    data,
                    len(index),
                    len(columns),
                    dtype,
                    copy,
                )

                mgr = ndarray_to_mgr(
                    arr2d,
                    index,
                    columns,
                    dtype=arr2d.dtype,
                    copy=False,
                    typ=manager,
                )

        # ensure correct Manager type according to settings
        mgr = mgr_to_mgr(mgr, typ=manager)

        NDFrame.__init__(self, mgr)

        if original_dtype is None and is_pandas_object and data_dtype == np.object_:
            if self.dtypes.iloc[0] != data_dtype:
                warnings.warn(
                    "Dtype inference on a pandas object "
                    "(Series, Index, ExtensionArray) is deprecated. The DataFrame "
                    "constructor will keep the original dtype in the future. "
                    "Call `infer_objects` on the result to get the old "
                    "behavior.",
                    FutureWarning,
                    stacklevel=2,
                )

    # ----------------------------------------------------------------------

    def __dataframe__(
        self, nan_as_null: bool = False, allow_copy: bool = True
    ) -> DataFrameXchg:
        """
        Return the dataframe interchange object implementing the interchange protocol.

        Parameters
        ----------
        nan_as_null : bool, default False
            `nan_as_null` is DEPRECATED and has no effect. Please avoid using
            it; it will be removed in a future release.
        allow_copy : bool, default True
            Whether to allow memory copying when exporting. If set to False
            it would cause non-zero-copy exports to fail.

        Returns
        -------
        DataFrame interchange object
            The object which consuming library can use to ingress the dataframe.

        Notes
        -----
        Details on the interchange protocol:
        https://data-apis.org/dataframe-protocol/latest/index.html

        Examples
        --------
        >>> df_not_necessarily_pandas = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
        >>> interchange_object = df_not_necessarily_pandas.__dataframe__()
        >>> interchange_object.column_names()
        Index(['A', 'B'], dtype='object')
        >>> df_pandas = (pd.api.interchange.from_dataframe
        ...              (interchange_object.select_columns_by_name(['A'])))
        >>> df_pandas
             A
        0    1
        1    2

        These methods (``column_names``, ``select_columns_by_name``) should work
        for any dataframe library which implements the interchange protocol.
        """

        from pandas.core.interchange.dataframe import PandasDataFrameXchg

        return PandasDataFrameXchg(self, allow_copy=allow_copy)

    def __dataframe_consortium_standard__(
        self, *, api_version: str | None = None
    ) -> Any:
        """
        Provide entry point to the Consortium DataFrame Standard API.

        This is developed and maintained outside of pandas.
        Please report any issues to https://github.com/data-apis/dataframe-api-compat.
        """
        dataframe_api_compat = import_optional_dependency("dataframe_api_compat")
        convert_to_standard_compliant_dataframe = (
            dataframe_api_compat.pandas_standard.convert_to_standard_compliant_dataframe
        )
        return convert_to_standard_compliant_dataframe(self, api_version=api_version)

    def __arrow_c_stream__(self, requested_schema=None):
        """
        Export the pandas DataFrame as an Arrow C stream PyCapsule.

        This relies on pyarrow to convert the pandas DataFrame to the Arrow
        format (and follows the default behaviour of ``pyarrow.Table.from_pandas``
        in its handling of the index, i.e. store the index as a column except
        for RangeIndex).
        This conversion is not necessarily zero-copy.

        Parameters
        ----------
        requested_schema : PyCapsule, default None
            The schema to which the dataframe should be casted, passed as a
            PyCapsule containing a C ArrowSchema representation of the
            requested schema.

        Returns
        -------
        PyCapsule
        """
        pa = import_optional_dependency("pyarrow", min_version="14.0.0")
        if requested_schema is not None:
            requested_schema = pa.Schema._import_from_c_capsule(requested_schema)
        table = pa.Table.from_pandas(self, schema=requested_schema)
        return table.__arrow_c_stream__()

    # ----------------------------------------------------------------------

    @property
    def axes(self) -> list[Index]:
        """
        Return a list representing the axes of the DataFrame.

        It has the row axis labels and column axis labels as the only members.
        They are returned in that order.

        Examples
        --------
        >>> df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
        >>> df.axes
        [RangeIndex(start=0, stop=2, step=1), Index(['col1', 'col2'],
        dtype='object')]
        """
        return [self.index, self.columns]

    @property
    def shape(self) -> tuple[int, int]:
        """
        Return a tuple representing the dimensionality of the DataFrame.

        See Also
        --------

In [52]:


df = pd.DataFrame({"So'zlar": mat, "Signer02": empty_column, "Signer03": empty_column, "Signer04": empty_column, "Signer05": empty_column\
                  , "Signer06": empty_column, "Signer07": empty_column, "Signer08": empty_column, "Signer09": empty_column, \
                   "Signer10": empty_column
                  })

#df = df.set_index("So'zlar")

In [53]:
df

,So'zlar,Signer02,Signer03,Signer04,Signer05,Signer06,Signer07,Signer08,Signer09,Signer10
0,1. uy (дом),,,,,,,,,
1,2. maktab (школа),,,,,,,,,
2,3. ko'cha (улица),,,,,,,,,
3,4. eshik (дверь),,,,,,,,,
4,5. stol (стол),,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...
95,96. quyon (кролик),,,,,,,,,
96,97. tozalayman (убираю),,,,,,,,,
97,98. topaman (нахожу),,,,,,,,,
98,99. kir (грязный),,,,,,,,,
99,100. ryukzak (рюкзак),,,,,,,,,

In [54]:
df.to_excel("output.xlsx", engine='xlsxwriter')

In [47]:
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9